### ISSUE TITLE
Unexpected empty result when selecting ad_group.id from feed_item

### ISSUE THREAD

**Issue by sabrinafontanella** [googleads/google-ads-python#100]
I am noticing a strange behavior with the table `feed_item`. 
I created some ads that are using an ad customizer in my test account and if I try to execute the following query:

```python
In [78]:         query = f""" 
    ...:             SELECT 
    ...:                  feed_item.id, 
    ...:                  feed_item.attribute_values 
    ...:             FROM feed_item  
    ...:         """ 
    ...:
    ...:         ga_service = client.get_service('GoogleAdsService')
    ...:         results = ga_service.search(customer_id, query=query, page_size=100) 
    ...:  
    ...:         for row in results: 
    ...:             print(row)
```

I obtain some values as output:
```
feed_item {
  resource_name: "customers/2740564982/feedItems/94104567~69224194280"
  id {
    value: 69224194280
  }
  attribute_values {
    feed_attribute_id {
      value: 1
    }
    string_value {
      value: "Moodstreet"
    }
  }
}


feed_item {
  resource_name: "customers/2740564982/feedItems/94104567~69224194295"
  id {
    value: 69224194295
  }
  attribute_values {
    feed_attribute_id {
      value: 1
    }
    string_value {
      value: "Qtie"
    }
  }
}
.....other feed_item....
```

Using the `Interactive Google Ads Query Builder` I built this query (I added `ad_group.id)`:

```python
In [78]:         query = f""" 
    ...:             SELECT 
    ...:                  feed_item.id, 
    ...:                  feed_item.attribute_values, 
    ...:                  ad_group.id 
    ...:             FROM feed_item  
    ...:         """ 
    ...:  
    ...:         results = ga_service.search(customer_id, query=query, page_size=100) 
    ...:  
    ...:         for row in results: 
    ...:             print(row) 
    ...:                                                                                                                                                                                                    

In [79]:               
```

But the result, as you can see, is empty.
I found this strange, I would expect the same result as above with the field `ad_group.id`. Do you have an idea why this is happening?

I am using the `google-ads` version `2.0.0`.

Thanks for the help.

**Comment by BenRKarl** [comment]
Hi @sabrinafontanella thanks for the question! Can I clarify, you're getting empty results from the Python library, not the query builder, right? Just when `ad_group.id` is added to the select clause?

**Comment by sabrinafontanella** [comment]
Hi @BenRKarl, I am getting empty results from the Python library (version ` 2.0.0`) and only when I am adding `ad_group.id` to the select clause.

**Comment by sabrinafontanella** [comment]
@BenRKarl do you know if there is any update about this issue?

**Comment by BenRKarl** [comment]
Hi @sabrinafontanella apologies for the delayed response! Have you tried this query on a non-test account? What I believe is happening is that when you select both resources at the same time the overlapping data must have traffic information, and since these Ad Groups are in a test account they are never trafficked. I can verify this on my own production account to see that I can select all feed_items on their own, but when I add ad_group I only get data related to Ad Groups that have been trafficked.

**Comment by wihl** [comment]
Closing as obsolete
