### ISSUE TITLE
Make first-time authentication easier

### ISSUE THREAD

**Issue by devchas** [googleads/google-ads-python#101]
I think it would be helpful to add a link to the [Configuration file setup](https://github.com/googleads/google-ads-python#configuration-file-setup) section of the README of the [OAuth Installed Application Flow](https://github.com/googleads/google-ads-python/wiki/OAuth-Installed-Application-Flow) rather than links to the Auth guide/samples. With the wiki, it's much easier and quicker to get started than following the existing links.

**Comment by BenRKarl** [comment]
@devchas want to submit a PR? :smiley:
