### ISSUE TITLE
Please run this script with UTF-8 encoding to avoid errors.

### ISSUE THREAD

**Issue by SarKrogh** [googleads/google-ads-python#102]
Hello, 

I've recently started to discover Adwords APIs.
After finally reaching the last step "Make your first API call", I get the following error :
"Your default encoding, cp1252, is not UTF-8. Please run this script with UTF-8 encoding to avoid errors." Yet, when I check the default encoding on my system, it says it's UTF-8. 

<img width="700" alt="UTF8" src="https://user-images.githubusercontent.com/50401511/57363374-a8534b00-7189-11e9-9c5a-8e41c618ba6e.PNG">

I've read many issues related to this error. I tried to find other ways to run the scripts to avoid this error. What would you suggest me to do ? 

Thank you for your help,
Sarine

**Comment by j-walker23** [comment]
@SarKrogh I don't know the answer to your question. But i figured i'd give you a heads up that you're in the wrong Github package. Your example is from the old python api package at https://github.com/googleads/googleads-python-lib.

This current one targets the new Google Ads API. While the one you referenced targets the old AdWords API.

**Comment by SarKrogh** [comment]
Oh thank you for the heads up ! I actually found a solution to actually run my scripts :)

**Comment by Trapster** [comment]
@SarKrogh, Looking into the same issue. Could you please share the solution you mentioned above?

**Comment by SarKrogh** [comment]
@Trapster just add the snippet below at the beginning of your scripts and your problem should be fixed 
[To get around the UTF-8 error.txt](https://github.com/googleads/google-ads-python/files/3236452/To.get.around.the.UTF-8.error.txt)

**Comment by Nightfurrysimba0228** [comment]
I got the same error, Can you help me?
