### ISSUE TITLE
GoogleAds doesn't return data and get stuck on a Keywords performance report

### ISSUE THREAD

**Issue by Alonreznik** [googleads/google-ads-python#105]
Hi There.
Recently, we're encountering a bug in our Google Ads python library, when trying to receive data of Keywords Performace response. The Google library just waiting over than 50 minutes to get data back and stuck the process.

Our report is:

```
{'reportName': 'KEYWORDS_PERFORMANCE_REPORT', 
 'selector': {
   'fields': ['Account', 'Currency', 'Activeviewviewableimpressions', 'Adgroupid', 'Adgroup', 'Adgroupstate', 'Network', 'Campaign', 'Campaignid', 'Clicks', 'Keyword', 'Keywordid', 'Impressions', 'Trackingtemplate', 'Day', 'Device', 'Customerid', 'Views', 'View-Throughconv.', 'Clientname', 'Conversions', 'Totalconv.Value', 'Cost', 'Bidstrategyid', 'Verticalid'], 
  'dateRange': {'max': '20190509', 'min': '20190507'}
}, 
   'reportType': 'KEYWORDS_PERFORMANCE_REPORT', 
    'dateRangeType': 'CUSTOM_DATE', '
downloadFormat': 'TSV'} 
```

Is there any way to run the reports using pagination, or see what can we do in these cases, when a report runs a very long time? 
How can we make these run to be quicker?

Thanks

Alon

**Comment by BenRKarl** [comment]
@Alonreznik thanks for the question. Would you please re-submit this issue on the AdWords API client library [repository](https://github.com/googleads/googleads-python-lib)? This repository is for the Google Ads API client library. Thank you!

**Comment by Alonreznik** [comment]
Hi Ben,
Already made.

Thanks
