### ISSUE TITLE
Getting headers with `field_mask` on response object

### ISSUE THREAD

**Issue by rubberviscous** [googleads/google-ads-python#106]
This is a followup to this [issue](https://github.com/googleads/google-ads-python/issues/91). @BenRKarl mentioned that I can fetch all the selected fields by looking at the `field_mask` on the response object. 

However I couldn't find any documentation on this and I'm a little lost on how to do it. Given this reference implementation here: https://github.com/googleads/google-ads-python/blob/master/examples/reporting/get_hotel_ads_performance.py#L49, how would one fetch the fields using field_mask?

I tried `row.field_mask` but got `AttributeError`.

**Comment by BenRKarl** [comment]
@rubberviscous Apologies but I think I meant `update_mask`, the value of which is a field mask.

**Comment by rubberviscous** [comment]
@BenRKarl, is `update_mask` a method or property of the `GoogleAdsRow` object? I tried accessing it  but get `AttributeError: update_mask`.

**Comment by BenRKarl** [comment]
@rubberviscous sorry I think I gave incorrect information. Here are the fields on a [SearchGoogleAdsResponse](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v1.services#searchgoogleadsresponse) object. You'll want to look for the `field_mask` field on the response object, not the rows.
