### ISSUE TITLE
customer_id delivered as INT64 but in search queries expected as string. Why?

### ISSUE THREAD

**Issue by mbaader** [googleads/google-ads-python#109]
Hi, 

the [customer.id](https://developers.google.com/google-ads/api/docs/fields/customer#customerid) has the Data Type INT64.

But when I try to make a search request with a customer_id as an integer, I get the following error:

`    results = ga_service.search(customer_id, query=query, page_size=PAGE_SIZE)
  File "....local/lib/python3.6/site-packages/google/ads/google_ads/v1/services/google_ads_service_client.py", line 220, in search
    validate_only=validate_only,
TypeError: 123456789 has type int, but expected one of: bytes, unicode
`
Looking into the code of google_ads_service_client.py this seems to be intended:

`    def search(self,
               customer_id,
               query,
               page_size=None,
               validate_only=None,
               retry=google.api_core.gapic_v1.method.DEFAULT,
               timeout=google.api_core.gapic_v1.method.DEFAULT,
               metadata=None):
        """
        Returns all rows that match the search query.

        Args:
            customer_id (str): The ID of the customer being queried.
`
But: why?

Regards Mat

**Comment by BenRKarl** [comment]
Hi @mbaader - Thanks for the quesiont. INT64 is the type for the `id` field on the `customer` proto, the string you're required to pass into the search method is interpolated to construct the request URL. Even though they're the same value, say '123456789' they're used for different functions:

```python
query = 'SELECT customer.id FROM customer'
ga_service = client.get_service('GoogleAdsService')
# customer_id is a string/unicode 
results = ga_service.search(customer_id, query=query, page_size=page_size)

for row in results:
    # row.customer.id is an int
```
