### ISSUE TITLE
Querying gclid and conversion_date_time Google Ads API

### ISSUE THREAD

**Issue by BSkedgell** [googleads/google-ads-python#118]
Hello,

I'm trying to query our gclid and conversion_date_time referenced in this documentation:

https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v1.services#gcliddatetimepair

I am unable to figure out the correct syntax nessecary for the query to pull back this data currently. I am able to query for instance campaign id, campaign name, conversions, and view through conversions with this query in Python:

```
df_list = []

query = ('SELECT campaign.id, campaign.name, metrics.conversions, metrics.view_through_conversions, segments.conversion_action_category FROM campaign '
         'WHERE segments.conversion_action_category = "SIGNUP" '
         'ORDER BY campaign.id')

results = ga_service.search(customer_id, query=query, page_size=_DEFAULT_PAGE_SIZE)

try:
  for row in results:
    df_list.append(('%d, %s, %d, %d'
                    % (row.campaign.id.value, row.campaign.name.value,
                       row.metrics.conversions.value, row.metrics.view_through_conversions.value
                      )).split(", "))
except google.ads.google_ads.errors.GoogleAdsException as ex:
    print('Request with ID "%s" failed with status "%s" and includes the '
          'following errors:' % (ex.request_id, ex.error.code().name))
    for error in ex.failure.errors:
        print('\tError with message "%s".' % error.message)
        if error.location:
            for field_path_element in error.location.field_path_elements:
                print('\t\tOn field: %s' % field_path_element.field_name)
```

Would anyone be able to help me adapt this to query the gclid and conversion_date_time or point me in the right direction of a working example or additional documentation on the gclid and conversion_date_time?

**Comment by BSkedgell** [comment]
@BenRKarl is querying gclid and conversion_date_time possible in the Google Ads API?

**Comment by BenRKarl** [comment]
Hi @BSkedgell you can select `gclid` from the [`click_view` resource](https://developers.google.com/google-ads/api/docs/fields/click_view#click_viewgclid). Keep in mind though that not all of the above fields in your query are selectable from `click_view` but here's a basic example that should get you `gclid` and the conversion date:

```
SELECT
  click_view.gclid,
  segments.date
FROM
  click_view
```

The documentation you link to above references the structure of mutation requests made to the [`ConversionAdjustmentUploadService`](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v1.services#conversionadjustmentuploadservice) and those objects aren't always selectable in a Search query. For selecting resources you'll want to use the `API Fields` drop-down in the left-hand sidebar of the [Reference page](https://developers.google.com/google-ads/api/reference/rpc/). 

Hope that helps!
