### ISSUE TITLE
Missing values in `campaign_criterion.listing_scope.dimensions`

### ISSUE THREAD

**Issue by martinvy** [googleads/google-ads-python#121]
Hi. 
I am trying to use [ListingDimensionInfo](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v1.common#google.ads.googleads.v1.common.ListingDimensionInfo) from [CampaignCriterion](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v1.resources#google.ads.googleads.v1.resources.CampaignCriterion), but I was able to retrieve just information about `listing_brand`, all other fields are empty.

I have set following product filter in the Google Ads UI for Display campaign in Settings

![image](https://user-images.githubusercontent.com/9135949/58629270-4dba9400-82dc-11e9-970e-ca254098e035.png)

Then I tried to select the product filter via `GoogleAdsService` with following query

```
SELECT
     campaign_criterion.listing_scope.dimensions
FROM
    campaign_criterion
```

The result contains correct amount of dimensions, but an actual value is available just for `listing_brand`.

```
campaign_criterion {
  listing_scope {
    dimensions {
    }
    dimensions {
      listing_brand {
        value {
          value: "test brand"
        }
      }
    }
    dimensions {
    }
    dimensions {
    }
    dimensions {
    }
  }
}
```

Can you look why the other dimensions values are not being returned? 

Version  `google-ads-2.1.0`.

Thanks :)

**Comment by BenRKarl** [comment]
Hi @martinvy thanks for the question! Apologies for the late reply. Just letting you know that I'm looking into this and will get back to you as soon as possible.

**Comment by BenRKarl** [comment]
Hi @martinvy apologies I wasn't able to find a resolution here. Are you still having this issue? If so please reopen this bug and I'll try to figure out what's happening.
