### ISSUE TITLE
When the "wrong" developer token is used, the lib raises an exception with said token in the error message.

### ISSUE THREAD

**Issue by nickpetzold** [googleads/google-ads-python#126]
Hi guys,

I understand that this might be more an issue of the Google Ads API itself, however I have tried submitting a post on the Google Ads forum and it doesn't seem to have been approved...

We are currently in the process of upgrading a platform from the Adwords API to the Ads API and for those parts of our system which have been upgraded, we are getting the following exception:

```GoogleAdsException: DEVELOPER_TOKEN_PROHIBITED``` 
```message: "Developer token \'<DEVELOPER_TOKEN>\' is not allowed with project \'<PROJECT_ID>\'."```

From inspection of the lib files, it seems you guys are just raising the error message that you are being passed from the API which is to be expected, but it's obviously not good to be having users' developer tokens broadcast like this. Have you got any means to speak the Ads API team to see if this could be fixed? Or at least a quick fix on the lib that at least patches this issue?

Many thanks,
Nick

**Comment by BenRKarl** [comment]
Hey @nickpetzold thank you for bringing this up! We will work on a fix for the client library, and will discuss internally about removing this at the API level.

**Comment by BenRKarl** [comment]
This is fixed, the error from the API is now:

`"Developer token is not allowed with project \'<PROJECT_ID>'."`
