### ISSUE TITLE
Error with campaign.advertising_channel_type

### ISSUE THREAD

**Issue by mateocam** [googleads/google-ads-python#13]
I am using the python client library to connect to Google Ads's API.

```
ga_service = client_service.get_service('GoogleAdsService')
    query = ('SELECT campaign.id, campaign.name, campaign.advertising_channel_type '
            'FROM campaign WHERE date BETWEEN \''+fecha+'\' AND \''+fecha+'\'')

    response = ga_service.search(<client_id>, query=query,page_size=1000)
    result = {}
    result['campanas'] = []

    try:
        for row in response:
            print row
            info = {}
            info['id'] = row.campaign.id.value
            info['name'] = row.campaign.name.value
            info['type'] = row.campaign.advertising_channel_type
```

When I parse the values this is the result I get:

```
{
  "campanas": [
    {
      "id": <campaign_id>, 
      "name": "Lanzamiento SIKU", 
      "type": 2
    }, 
    {
      "id": <campaign_id>, 
      "name": "lvl1 - website traffic", 
      "type": 2
    }, 
    {
      "id": <campaign_id>, 
      "name": "Lvl 2 - display", 
      "type": 3
    }
  ]
}
```

Why am I getting an integer for result["type"] ? When I check the traceback call I can see a string:

```
campaign {
  resource_name: "customers/<customer_id>/campaigns/<campaign_id>"
  id {
    value: 397083380
  }
  name {
    value: "Lanzamiento SIKU"
  }
  advertising_channel_type: SEARCH
}

campaign {
  resource_name: "customers/<customer_id>/campaigns/<campaign_id>"
  id {
    value: 1590766475
  }
  name {
    value: "lvl1 - website traffic"
  }
  advertising_channel_type: SEARCH
}

campaign {
  resource_name: "customers/<customer_id>/campaigns/<campaign_id>"
  id {
    value: 1590784940
  }
  name {
    value: "Lvl 2 - display"
  }
  advertising_channel_type: DISPLAY
}
```

I've searched on the Documentation for the API and found out that it's because the field: advertising_channel_type is of Data Type: Enum. How can I manipulate this object of the Enum class to get the string value? There is no helpful information about this on their Documentation.

You have this documentation where it mentions the Enum class for the field AdvertisingChannelType: https://github.com/googleapis/googleapis/blob/master/google/ads/googleads/v0/enums/advertising_channel_type.proto

but there are missing values for 3 and 4, so it is impossible to map which number corresponds to which advertising channel type:

```
 // Enum describing the various advertising channel types.
  enum AdvertisingChannelType {
    // Not specified.
    UNSPECIFIED = 0;
    // Used for return value only. Represents value unknown in this version.
    UNKNOWN = 1;
    // Search Network. Includes display bundled, and Search+ campaigns.
    SEARCH = 2;
    // Hotel Ads campaigns.
    HOTEL = 5;
  }
}
```

**Comment by BenRKarl** [comment]
Hi @mateocam Apologies for the delayed response. Are you still having this issue?

**Comment by BenRKarl** [comment]
Hi @mateocam just following up here as this issue was also discussed in a separate thread. From a general standpoint I'm hoping to improve the API so that it's easy to access the field names on Enums easily, but in the meantime see this thread for an example on how to get these values by serializing proto messages into dicts using the `MessageToDict` helper: https://github.com/googleads/google-ads-python/issues/83
