### ISSUE TITLE
inversion between InstalledAppFlow and Flow in import

### ISSUE THREAD

**Issue by SENHAJIRHAZI** [googleads/google-ads-python#130]
In the file  google-ads-python/examples/authentication/authenticate_in_web_application.py  

I think 

`from google_auth_oauthlib.flow import InstalledAppFlow`

should be replaced by 

`from google_auth_oauthlib.flow import Flow`

According to this example : 

https://github.com/googleads/google-ads-python/wiki/OAuth-Web-Application-Flow

Thank you

**Comment by BenRKarl** [comment]
@SENHAJIRHAZI thank you for pointing this out, we'll update it as soon as possible.

**Comment by BenRKarl** [comment]
Following up on this - we recently removed the Wiki because it contained redundant information that's already included on our developer site and was confusing to new onboarding users. However we still need to dig into this example to be sure that it's accurate.

**Comment by BenRKarl** [comment]
This is fixed in #425
