### ISSUE TITLE
Problems with initialize a GoogleAdsClient using the credentials stored in google-ads.yaml

### ISSUE THREAD

**Issue by leongrin** [googleads/google-ads-python#141]
I am following this tutorial (https://github.com/googleads/google-ads-python/wiki/OAuth-Installed-Application-Flow), and I did well until item 6.
When I try to initialize a GoogleAdsClient using the credentials stored in google-ads.yaml, I receive some errors, and my IDE shows also a warning message saying "Cannot find reference 'ads' in imported module Google".

I am attaching an image showing the errors in my IDE when I run a code.

Can someone help me fix these issues?

Thank you very much in advance.

![pycharm-google-ads-error](https://user-images.githubusercontent.com/41086608/60112488-430de600-9746-11e9-905d-5448e2022fc0.jpg)

**Comment by akaashhazarika** [comment]
The file path is wrong. Try once by placing the YAML file inside 'google-ads-python' directory.  Or you could work around, by specifying the file path inside load_from_storage method.

**Comment by leongrin** [comment]
I created a clean new project and placed the YAML file on the root, as you suggested. But it's showing the same error, as you can see on the attached image.

![error2](https://user-images.githubusercontent.com/41086608/60132217-74e87200-9771-11e9-80cc-1f29caee16f7.jpg)

I also tried to add a path, but it didn't work.
`google_ads_client = (google.ads.google_ads.client.GoogleAdsClient
                         .load_from_storage('./google-ads.yaml'))`

**Comment by akaashhazarika** [comment]
The file path is wrongly specified.  The current .yaml file is placed under /google-ads/venv/google-ads.yaml. Instead it should be under /google-ads/google-ads.yaml.  

I hope this solves your problem.

**Comment by akaashhazarika** [comment]
Please visit https://developers.google.com/google-ads/api/docs/client-libs/python/oauth-web for more details.

**Comment by wihl** [comment]
Closing issue as obsolete.
