### ISSUE TITLE
Batch processing 

### ISSUE THREAD

**Issue by Cosbgn** [googleads/google-ads-python#142]
Hi, is there an available example for batch processing like in the PHP library here: https://developers.google.com/google-ads/api/docs/batch-processing/flow ?

**Comment by BenRKarl** [comment]
Hi @Cosbgn thanks for the question. We'll reach parity with the PHP example at some point. I marked this issue as a feature request and will keep it open so that we an track progress and link to the PR when it's available.

**Comment by Cosbgn** [comment]
Hi @BenRKarl thanks for the answer, can you just confirm me what's the current situation?

- Batch processing is currently not available in the python library 
or:
- Batch processing is available however is not documented yet

Thank you!

**Comment by BenRKarl** [comment]
@Cosbgn sorry, to be specific, batch processing is available it's just not documented with an example yet.

**Comment by yunstanford** [comment]
@BenRKarl Could you add an example for Batch Processing ? it'd very helpful, Thanks!

**Comment by wihl** [comment]
Batch Processing is not yet generally available. When it becomes generally in 2020, we will provide code samples. Thanks!

**Comment by yunstanford** [comment]
@wihl Thanks for you reply, when you say "Batch Processing is not yet generally available.", does it mean it's not stable to use or just not available ?

**Comment by wihl** [comment]
It is whitelisted to a very small set of external customers at the present time.

**Comment by yunstanford** [comment]
Good to know, then what is the recommended way for large scale update with this new Google API at this moment ? the sync api ?

**Comment by wihl** [comment]
You can use the [GoogleAdsServive.Mutate](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v2.services#googleadsservice) to make up to [5,000](https://developers.google.com/google-ads/api/docs/best-practices/quotas#mutate_requests) operations in a single request. Unlike the AdWords API and the Batch Job Service, all of the operations in this one mutate will be atomic: they will all succeed or all fail (unless you allow [partial failures](https://developers.google.com/google-ads/api/docs/best-practices/partial-failures)).

**Comment by yunstanford** [comment]
@wihl @BenRKarl Any update here regarding Batch Process

**Comment by BenRKarl** [comment]
@yunstanford we added an example for Batch Processing using MutateJobService [here](https://github.com/googleads/google-ads-python/blob/master/examples/campaign_management/add_complete_campaigns_using_mutate_job.py), however the service is still not yet available. I don't have a specific timeline for when it will be released, but when it is I'll update this Issue.

**Comment by mikeengland** [comment]
Hi there. Is the BatchJobService generally available now? For example, to update hotelads bid modifiers/listing group bids?
Thanks!

**Comment by BenRKarl** [comment]
There's a batch jobs example [here](https://github.com/googleads/google-ads-python/blob/master/examples/campaign_management/add_complete_campaigns_using_batch_job.py), closing this for now, please create a new issue if you'd like example of using batch jobs to create other types of entities.
