### ISSUE TITLE
Syntax error when using custom date ranges

### ISSUE THREAD

**Issue by ninjas448** [googleads/google-ads-python#145]
I am trying to use keyword  view to get the metrics list .. I am running the query using custom date ranges. . It is throwing me syntax error. I tried > , between ,all throws same error., kindly help me on this.

'SELECT campaign.id,campaign.name,campaign.start_date,campaign.status,campaign.end_date,metrics.absolute_top_impression_percentage,metrics.active_view_cpm,metrics.active_view_ctr,metrics.active_view_impressions,metrics.active_view_measurability,metrics.active_view_measurable_cost_micros,metrics.active_view_measurable_impressions,metrics.active_view_viewability,metrics.all_conversions,metrics.all_conversions_from_interactions_rate,metrics.all_conversions_from_interactions_value_per_interaction,metrics.all_conversions_value,metrics.all_conversions_value_per_cost,metrics.average_cost,metrics.average_cpc,metrics.average_cpe,metrics.average_cpm,metrics.average_cpv,metrics.average_page_views,metrics.average_position,metrics.average_time_on_site,metrics.bounce_rate,metrics.clicks,metrics.conversions,metrics.conversions_from_interactions_rate,metrics.conversions_value,metrics.cost_micros,metrics.cost_per_all_conversions,metrics.cost_per_conversion,metrics.cost_per_current_model_attributed_conversion,metrics.cross_device_conversions,metrics.ctr,metrics.current_model_attributed_conversions,metrics.current_model_attributed_conversions_value,metrics.engagement_rate,metrics.engagements,metrics.gmail_forwards,metrics.gmail_saves,metrics.gmail_secondary_clicks,metrics.historical_creative_quality_score,metrics.historical_landing_page_quality_score,metrics.historical_quality_score,metrics.historical_search_predicted_ctr,metrics.impressions,metrics.interaction_event_types,metrics.interaction_rate,metrics.interactions,metrics.percent_new_visitors,metrics.search_absolute_top_impression_share,metrics.search_budget_lost_absolute_top_impression_share,metrics.search_budget_lost_top_impression_share,metrics.search_click_share,metrics.search_exact_match_impression_share,metrics.search_impression_share,metrics.search_rank_lost_absolute_top_impression_share,metrics.search_rank_lost_impression_share,metrics.search_rank_lost_top_impression_share,metrics.search_top_impression_share,metrics.top_impression_percentage,metrics.value_per_all_conversions,metrics.value_per_conversion,metrics.value_per_current_model_attributed_conversion,metrics.video_quartile_100_rate,metrics.video_quartile_25_rate,metrics.video_quartile_50_rate,metrics.video_quartile_75_rate,metrics.video_view_rate,metrics.video_views,metrics.view_through_conversions,segments.date FROM keyword_view WHERE segments.date BETWEEN '2019-01-01' AND '2019-01-31' '

**Comment by BenRKarl** [comment]
@ninjas448 I believe it's because the query has improperly balanced single-quotation marks, specifically:

```python
'SELECT ... BETWEEN '2019-01-01' AND '2019-01-31''
```

Should be

```python
'SELECT ... BETWEEN "2019-01-01" AND "2019-01-31"'
```
