### ISSUE TITLE
delegate_account

### ISSUE THREAD

**Issue by jwijffels** [googleads/google-ads-python#146]
Hi,

We would like to use a service account to connect to Google Ads. Where can we find documentation in order to create a delegate account and more details how this works?

thanks,
Jan

**Comment by samg861** [comment]
Provided you've set up correctly as per [the docs](https://developers.google.com/admin-sdk/directory/v1/guides/delegation), authenticating via the library is just a matter of creating the credentials from your service account keyfile, delegating, and then using them to create the google-ads client:

```python
from oauth2client.service_account import ServiceAccountCredentials
from google.ads.google_ads.client import GoogleAdsClient

service_account_keyfile_filepath = '/path/to/keyfile.json'

credentials = ServiceAccountCredentials.from_json_keyfile_name(
    filename=service_account_keyfile_filepath,
    scopes=['https://www.googleapis.com/auth/adwords']
)

# Optionally delegate
credentials = credentials.create_delegated('delegated_user@email.com')

client = GoogleAdsClient(
    credentials=credentials,
    developer_token='my_developer_token'
)

# Don't forget to set login_customer_id at some point
client.login_customer_id = 'my_access_id'

client.get_service('etc')
```

**Comment by jwijffels** [comment]
Thank you for the code. Will try it out!
