### ISSUE TITLE
Incorrect example in proto getters page

### ISSUE THREAD

**Issue by henribru** [googleads/google-ads-python#147]
In https://developers.google.com/google-ads/api/docs/client-libs/python/proto-getters, this is shown as an alternative to `campaign = client.get_type('Campaign')`:
```py
from google.ads.google_ads.v1.proto.resources import campaign_pb2
campaign = campaign_pb2()
```
Runnning this code gives a type error with the message `'module' object is not callable`, which makes sense given that campaign_pb2 actually is a module and not a type. Should it perhaps say this instead?
```py
from google.ads.google_ads.v1.proto.resources.campaign_pb2 import Campaign
campaign = Campaign()
```

**Comment by BenRKarl** [comment]
Hi @henribru thanks for catching this! You're absolutely right. I've submitted a change to the documentation that should be reflected soon.
