### ISSUE TITLE
custom date ranges not working in queries

### ISSUE THREAD

**Issue by apurvis** [googleads/google-ads-python#15]
Using library 0.5.

When I submit this query, everything works fine:
```sql
        SELECT
          date,
          campaign.id,
          metrics.impressions
        FROM campaign
        WHERE date DURING LAST_7_DAYS
          AND metrics.impressions > 0
```

but this query fails with `GoogleAdsException`:
```sql
        SELECT
          date,
          campaign.id,
          metrics.impressions
        FROM campaign
        WHERE date >= '2018-11-03'
          AND date <= '2018-11-10'
          AND metrics.impressions > 0
```

The code executing the queries looks like:
```python
client = (google_ads.client.GoogleAdsClient.load_from_storage())
service = self.client.get_service('GoogleAdsService')
service.search(customer_id, query=query, page_size=1000)
```

[The documentation on custom date ranges](https://developers.google.com/google-ads/api/docs/query/date-ranges) says this is the correct format, and I've seen Google employees suggest [queries that look like this](https://groups.google.com/forum/#!msg/adwords-api/kjHYJ1YNyvg/-P0DdHjNAgAJ) in the forums... so why does this query fail when sent from this library?

my hunch is that maybe the quotes are being encoded incorrectly by this library?

**Comment by wihl** [comment]
You were probably caught in a change of the date specification between beta releases. The [current format](https://developers.google.com/google-ads/api/docs/query/date-ranges) uses `segments.date` instead of `date`.
