### ISSUE TITLE
metrics.average_position is not available in v2 of the api

### ISSUE THREAD

**Issue by srchilukoori** [googleads/google-ads-python#151]
Hi,

metrics.average_position field is not available in the API version 2.
https://developers.google.com/google-ads/api/fields/v1/metrics

Thank you.

**Comment by BenRKarl** [comment]
Hi @srchilukoori thanks for posting the question, and apologies for the confusion! For reference, `metrics.average_position` was removed from the API in `v2` so it's no longer available beyond `v1`. Please reference [this blog post](https://ads-developers.googleblog.com/2018/11/top-metrics-absolute-top-metrics-and.html) for more details on why we're moving away from Average Position and what alternative functionality you can use.
