### ISSUE TITLE
ExtensionFeedItemService not match with document

### ISSUE THREAD

**Issue by huongnvvn** [googleads/google-ads-python#153]
Hi Everyone,

While I use ExtensionFeedItemService to add new Extension. I have some problems as:
1. I can't set any value for variable: targeted_campaign or targeted_ad_group
2. In field promotion_feed_item: I can set value for money_amount_off (discount money), Service response is SUCCESS but I don't see variable money in new promotion extension.  when I set value for variable percent_off as 10 (10%) or 20 (20%) instead of variable money_amount_off , I received an error: "This field has too many decimal places specified".

Can someone help me fix these issues?
Thank you very much in advance.

**Comment by BenRKarl** [comment]
Hi @huongnvvn thanks for reaching out with this question! This appears to be more of an API issue and not an issue related to this library specifically. Would you please post this question to the [support forum](https://groups.google.com/forum/#!forum/adwords-api)? The team there is much better equipped to help. Thank you!
