### ISSUE TITLE
yaml.parser.ParserError: expected '<document start>', but found '<scalar>'

### ISSUE THREAD

**Issue by castnow123** [googleads/google-ads-python#166]
Hi,

I am trying to run get_campaign.py but I am getting this error: 

File "/usr/local/lib/python2.7/dist-packages/yaml/parser.py", line 174, in parse_document_start
    self.peek_token().start_mark)
yaml.parser.ParserError: expected '<document start>', but found '<scalar>'
  in "<string>", line 4, column 1:
    -# recommended OAuth2 flow. For  ... 

Please help.

Thanks

**Comment by stephan9mertel** [comment]
Hi, I get the same error when executing `client = GoogleAdsClient.load_from_storage('./google-ads.yaml')`. I used an online yaml validator to check for errors in my yaml file, but it tells me there are no errors.

**Comment by stephan9mertel** [comment]
@castnow123 I removed all lines starting with `-#` and now it works fine. The parser seems to have a problem with those lines.

**Comment by castnow123** [comment]
Hi Stephen, the downloaded the SDK again and the issue is still there. where is the updated script? is it here: git clone https://github.com/googleads/google-ads-python.git?

**Comment by stephan9mertel** [comment]
Hi @castnow123, please note that I'm not a developer on this project, just a user like you. I tried out some stuff and figuered out that manually removing the lines starting with `-#` from the `google-ads.yaml` file resolves the error.

**Comment by castnow123** [comment]
Thank you Stephan. that error is removed.

**Comment by BenRKarl** [comment]
Hi @castnow123 and @stephan9mertel it appears as though some typos got into that sample file. The lines starting with `-#` should be comments that start with `#` if you remove the `-` chars it should be fine. We'll get that file cleaned up.
