### ISSUE TITLE
cannot create shopping product group tree in one batch. Getting LISTING_GROUP_SUBDIVISION_REQUIRES_OTHERS_CASE error

### ISSUE THREAD

**Issue by Inilien** [googleads/google-ads-python#168]
In my test account's shopping campaign I am trying to create 3 ProductGroups in an empty AdGroup.  
I can successfully create single root level AdGroupCriterion with listing_group type: `UNIT` but when I am trying to create 3 AdGroupCriterions: 1 root and 2 children I am getting errors.  
Here are my `AdGroupCriterionOperation` protobuf messages:  
```
[create {
   resource_name: "customers/5936312994/adGroupCriteria/82410873572~-25"
   status: PAUSED
   ad_group {
     value: "customers/5936312994/adGroups/82410873572"
   }
   listing_group {
     type: SUBDIVISION
   }
 }, create {
   resource_name: "customers/5936312994/adGroupCriteria/82410873572~-27"
   status: ENABLED
   ad_group {
     value: "customers/5936312994/adGroups/82410873572"
   }
   negative {
     value: true
   }
   listing_group {
     type: UNIT
     case_value {
       listing_custom_attribute {
         index: INDEX0
       }
     }
     parent_ad_group_criterion {
       value: "customers/5936312994/adGroupCriteria/82410873572~-25"
     }
   }
 }, create {
   resource_name: "customers/5936312994/adGroupCriteria/82410873572~-26"
   status: ENABLED
   ad_group {
     value: "customers/5936312994/adGroups/82410873572"
   }
   cpc_bid_micros {
     value: 10000000
   }
   listing_group {
     type: UNIT
     case_value {
       listing_custom_attribute {
         value {
           value: "1000-2000"
         }
         index: INDEX0
       }
     }
     parent_ad_group_criterion {
       value: "customers/5936312994/adGroupCriteria/82410873572~-25"
     }
   }
 }]
```
Essentially I got them from my production account.  
When I am trying to call mutate method of `AdGroupCriterionService` I am getting these errors (one per operation):  
```
errors {
  error_code {
    ad_group_criterion_error: LISTING_GROUP_SUBDIVISION_REQUIRES_OTHERS_CASE
  }
  message: "Subdivided listing groups must have an \"others\" case."
  trigger {
    string_value: "ProductPartition{id=TempCriterionId{id=25}, bidSimulatorStatus=null, partitionType=SUBDIVISION, parentCriterionId=null, productGroup=null, productGroupObsoleteStatus=null, caseValue=null, decisionPath=[], salesCountry=null, merchantId=null, hasPromotedSuggestion=null}"
  }
}
errors {
  error_code {
    ad_group_criterion_error: LISTING_GROUP_DOES_NOT_EXIST
  }
  message: "Listing group referenced in the operation was not found in the ad group."
  trigger {
    string_value: "TempCriterionId{id=25}"
  }
  location {
    field_path_elements {
      field_name: "operations"
      index {
      }
    }
    field_path_elements {
      field_name: "create"
    }
    field_path_elements {
      field_name: "listing_group"
    }
    field_path_elements {
      field_name: "parent_ad_group_criterion"
    }
  }
}
errors {
  error_code {
    ad_group_criterion_error: LISTING_GROUP_DOES_NOT_EXIST
  }
  message: "Listing group referenced in the operation was not found in the ad group."
  trigger {
    string_value: "TempCriterionId{id=25}"
  }
  location {
    field_path_elements {
      field_name: "operations"
      index {
        value: 1
      }
    }
    field_path_elements {
      field_name: "create"
    }
    field_path_elements {
      field_name: "listing_group"
    }
    field_path_elements {
      field_name: "parent_ad_group_criterion"
    }
  }
}
```
I am assuming that if root level operation were to succeed then both children would succeed as well. But I cannot figure out how to solve the `LISTING_GROUP_SUBDIVISION_REQUIRES_OTHERS_CASE` error.

I would appreciate any help. Thank you in advance.

**Comment by Inilien** [comment]
the issue was with the order of operations. Turns out Google Ads API is sensitive to it - each operation should be able to complete successfully when they are executed one by one in the provided order, if one of them fails - all other will report as failed too.  
The issue here was resolved in the official Google Ads support channel at Google Groups [here](https://groups.google.com/d/msg/adwords-api/MKoKH8xVn-k/bZ_qudvVBgAJ)

**Comment by saikumarsura-ts** [comment]
Hi Guys,
@Inilien 
I am facing a similar issue 

Subdivisions from all hotels in adGroup
>Trying to create a root node with temporary "-1" negative id as subdivisions.
> Assigning root resource name to child Unit node as the parent resource name.
Also, Suggest a solution on how to subdivide multiple hotels using APIs or postman.
URL:
https://googleads.googleapis.com/v5/customers/1138518998/adGroupCriteria:mutate
Body:
{
    "operations": [
        {
            "create": {
                "resource_name": "customers/1138518998/adGroupCriteria/108695051663~-1",
                "ad_group": "customers/1138518998/adGroups/108695051663",
                "status": "ENABLED",
                "listing_group": {
                    "type": "SUBDIVISION",
                    "case_value": null,
                    "parent_ad_group_criterion": null
                }
            }
        },
        {
            "create": {
                "resource_name": "customers/1138518998/adGroupCriteria/108695051663~-2",
                "ad_group": "customers/1138518998/adGroups/108695051663",
                "percent_cpc_bid_micros": 100000,
                "status": "ENABLED",
                "listing_group": {
                    "type": "UNIT",
                    "case_value": {
                        "hotel_id": {
                            "value": "1007365"
                        }
                    },
                    "parent_ad_group_criterion": "customers/1138518998/adGroupCriteria/108695051663~-1"
                }
            }
        },
        {
            "create": {
                "resource_name": "customers/1138518998/adGroupCriteria/108695051663~-3",
                "ad_group": "customers/1138518998/adGroups/108695051663",
                "percent_cpc_bid_micros": 100000,
                "status": "ENABLED",
                "listing_group": {
                    "type": "SUBDIVISION",
                    "case_value": null,
                    "parent_ad_group_criterion": "customers/1138518998/adGroupCriteria/108695051663~-1"
                }
            }
        }
    ]
}


Thanks in advance.
