### ISSUE TITLE
Transient errors not raising exceptions

### ISSUE THREAD

**Issue by mikeengland** [googleads/google-ads-python#172]
Hi

With the old AdWords API Python module, any kind of concurrent modification or rate errors etc were raised as an exception, even when partial failures was used. This made it very easy to catch the exception and then retry the mutate operation.

From what I can tell in the new module, an exception is not raised, and this error e.g. "Too many requests. Retry in 30 seconds." is just assigned to each operation in the partial failure response.

What do you suggest as a best practice to identify these transient retryable errors? Is it best to just check the response for each operation to see if these errors are present and then retry, or is it possible to make these errors raise an exception so we can rely on the exception bubbling up to the caller where it can be handled?

Thanks!

**Comment by wihl** [comment]
There is a bit of guidance at
https://developers.google.com/google-ads/api/docs/best-practices/error-types

Let us know if more details would be useful.

**Comment by mikeengland** [comment]
Hi @wihl 

When reproducing the error, I have found that for each individual operation submitted, the following error is shown:

error_code {
quota_error: RESOURCE_TEMPORARILY_EXHAUSTED
}
message: "Too many requests. Retry in 30 seconds."
trigger {
string_value: ""
}
location {
field_path_elements {
field_name: "operations"
index {
value: 2653
}
}
}

This works fine for partial failures, but I wondered what the best practices are for actually identifying that a RESOURCE_TEMPORARILY_EXHAUSTED has occurred so that we can wait and resubmit the operations. Is it just a case of checking the first operation for the error code RESOURCE_TEMPORARILY_EXHAUSTED (it seems all submitted operations are assigned this), or is there a better way of identifying it?

I did like the old method of throwing exceptions as it was easy to catch and identify the API errors before deciding to retry.

**Comment by wihl** [comment]
The RESOURCE_TEMPORARILY_EXHAUSTED may not apply to all operations in the request. For example, if you use GoogleAdsService:mutate with a series of regular mutates and then a few large requests to an expensive API like TargetingIdeaService, it is possible that the majority of the mutates will succeed but the TargetIdeaService operations will fail. 

So you have to check which operations triggered the rate limit. See https://developers.google.com/google-ads/api/docs/best-practices/rate-limits and https://developers.google.com/google-ads/api/docs/best-practices/partial-failures
