### ISSUE TITLE
Google Ads API version "v2_1" does not exist.

### ISSUE THREAD

**Issue by Cosbgn** [googleads/google-ads-python#176]
Hello,

I'm trying the latest version of the library (3.2.0) and I get the following error:

```
ValueError: Specified Google Ads API version "v2_1" does not exist. Valid API versions are: "v2", "v1"
```

Do I need to keep the endpoint to `v2` ? I tried but doing that I can't access:
```
accessible_customers = customer_service.list_accessible_customers()
client_customer = accessible_customers.client_customer
```
As `accessible_customers.client_customer` was added in `v2_1`

What's the correct endpoint to use `v2_1`?

**Comment by Cosbgn** [comment]
@BenRKarl Do you know what's the issue here?

**Comment by wihl** [comment]
Use only the major version number, ie "v2".  There is only one minor
version of a major version accessible at one time so 2_1 (or actually 2_2
now) will be picked up automatically.

**Comment by BenRKarl** [comment]
@Cosbgn As @wihl suggested, you only need to provide the major version when retrieving services from a client instance, so for example:

```python
customer_service = client.get_service('CustomerService', version='v2')
```

This will automatically return the most recent minor version for a given major, which is currently `v2_2`
