### ISSUE TITLE
hotel_price_bucket_pb2 mapping issue

### ISSUE THREAD

**Issue by stephan9mertel** [googleads/google-ads-python#180]
In `/google/ads/google_ads/v2/proto/enums/hotel_price_bucket_pb2.py` I found the following mapping

    _descriptor.EnumValueDescriptor(
      name='UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),

    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=1, number=1,
      serialized_options=None,
      type=None),

    _descriptor.EnumValueDescriptor(
      name='LOWEST_TIED', index=2, number=3,
      serialized_options=None,
      type=None),

    _descriptor.EnumValueDescriptor(
      name='NOT_LOWEST', index=3, number=4,
      serialized_options=None,
      type=None),

and noticed that the index is assigned ints from 0 to 3, while the numbers are 0, 1, 3 and 4, with the 2 missing. Is this correct?

**Comment by wihl** [comment]
Yes, this is correct. See the [proto definition](https://github.com/googleapis/googleapis/blob/master/google/ads/googleads/v2/enums/hotel_price_bucket.proto). As in the [protobuf rules for enumeration](https://developers.google.com/protocol-buffers/docs/proto3#enum), there are no issues with skipping numeric values.
