### ISSUE TITLE
Deprecation warning because of google ads package

### ISSUE THREAD

**Issue by stephan9mertel** [googleads/google-ads-python#181]
When executing our system's unit tests we get a bunch full of deprecation warnings like this:
`/google/ads/google_ads/v2/services/enums.py:9744: DeprecationWarning: invalid escape sequence \_`

**Comment by wihl** [comment]
Closing this issue as "cannot reproduce." Feel free to reopen it if you can reproduce it with the latest version of the client library. If so, please specify additional details like platform you are using (e.g. Linux / version, OS X, Windows) and the output from `pip freeze`.

**Comment by stephan9mertel** [comment]
@wihl you're right, with the newest version I can't reproduce the issue anymore. Thanks!
