### ISSUE TITLE
Add query builder

### ISSUE THREAD

**Issue by henribru** [googleads/google-ads-python#182]
The old AdWords API client had a query builder for the optional query language, as seen in this sample: https://developers.google.com/adwords/api/docs/samples/python/basic-operations#get-all-campaigns-using-awql

It would be nice to have something equivalent in this library, especially now that the query language is mandatory.

**Comment by wihl** [comment]
There is an interactive query builder for the Google Ads API. See https://developers.google.com/google-ads/api/docs/query/interactive-gaql-builder

You can also use the [GoogleAdsFieldService](https://developers.google.com/google-ads/api/docs/concepts/field-service) to programmatically build your queries.

**Comment by henribru** [comment]
I realize there is an interactive query builder, but this doesn't fulfill the same role as a programmatic one. The problem is that queries are strings and without a query builder have to be built by string templating and/or concatenation. This makes any abstraction or composability horrible, because you either have to carry around the things you want to put in the query and then build it once at the end (which is basically reimplementing a query builder) or you build it piece by piece, being very diligent about getting things in just the right order
