### ISSUE TITLE
Refresh token

### ISSUE THREAD

**Issue by Mrx8551** [googleads/google-ads-python#187]
I am using your code to configure google ads API. However, I can't generate refresh token by myself. Google support walked me through via this link https://developers.google.com/google-ads/api/docs/oauth/client-library#configure_client_library_with_oauth2_credentials. I still can't find it either. Does anyone do me a favor to get it instantly?

**Comment by wihl** [comment]
No one can generate a refresh token on your behalf as that would be a major security breach. See https://developers.google.com/google-ads/api/docs/client-libs/python/oauth-installed for instructions on generating your refresh token from Python.
