### ISSUE TITLE
ad_group_ad.ad.final_urls throwing list index out of range

### ISSUE THREAD

**Issue by ninjas448** [googleads/google-ads-python#193]
Hi,

am using ad_group_ad.final_urls column in my query which was running fine these days, suddenly its throwing list index error . when I checked the data sent back I could see there is no .value attribute for certain rows. Let me know how to handle it.

ad_group_ad.ad.final_urls.value

Let me know if there is null handling in GAQL

**Comment by wihl** [comment]
@ninjas448 issues posted to this repository should be specific to the Python client library. Your error is general to Google Ads API. Please post your question on the [Google Ads API Forum](https://groups.google.com/forum/#!forum/adwords-api). You'll likely get a faster response there as well.
