### ISSUE TITLE
 "StringValue" does not exist in Google Ads API v2

### ISSUE THREAD

**Issue by ahmed-3li** [googleads/google-ads-python#196]
The get_type() method with a 'StringValue' argument is throwing an error for me in all the code examples

```
def map_locations_to_string_values(client, location_ids):
    gtc_service = client.get_service('GeoTargetConstantService', version='v2')
    locations = []
    for location_id in location_ids:
        location =  client.get_type('StringValue', version='v2')
        location.value = gtc_service.geo_target_constant_path(location_id)
        locations.append(location)
    return locations
```

The error:
`get_type raise ValueError(f'Specified type "{name}" does not exist in Google Ads ' ValueError: Specified type "StringValue" does not exist in Google Ads API v2`

**Comment by wihl** [comment]
@ahmed-3li Thanks for your report. I've confirmed that this is an issue with the V4.1.0 release. I will be releasing a correction shortly.

**Comment by wihl** [comment]
Issue has been corrected.
