### ISSUE TITLE
ExceptionHandling Error

### ISSUE THREAD

**Issue by caleoroco** [googleads/google-ads-python#200]
When producing an exception in the Query, the exception isn't handled correctly 
```
SELECT 
        campaign.id, campaign.status,campaign.advertising_channel_type,ad_group.id, ad_group.status,search_term_view.search_term,search_term_view.status, 
        segments.date, 
        segments.device, 
        segments.search_term_match_type, 
        metrics.impressions, 
        metrics.clicks, 
        metrics.cost_micros, 
        metrics.conversions, 
        metrics.conversions_value 
 FROM  
        search_term_view 
 WHERE  
        metrics.impressions > None 
        AND segments.date BETWEEN '2019-10-05' AND '2020-01-02' 
        LIMIT 10000
```
Error above is `metrics.impressions > None`
Produces the following
```
google_ads_failure = self._get_google_ads_failure(trailing_metadata)
  File "/venv/lib/python3.7/site-packages/google/ads/google_ads/interceptors/exception_interceptor.py", 
line 68, in _get_google_ads_failure
    ga_failure = error_protos.errors_pb2.GoogleAdsFailure()
AttributeError: module 'google.ads.google_ads.v2.proto.errors' has no attribute 'errors_pb2'
```

**Comment by dlauck92** [comment]
Getting the same error. I asked about this question on https://groups.google.com/forum/#!topic/adwords-api/96-aNt9hKlc so hopefully, it gets resolved

**Comment by lucasgomide** [comment]
I got the same error

**Comment by lucasgomide** [comment]
@dlauck92 @caleoroco I think that I solved the issue. I realized that the CustomerId was the MCC. I just changed it to other external account Id and adding the `login_customer_id` config with the MCC account ID.

This works for me.

**Comment by drinkinginthesky** [comment]
hey man, i got the same error, i remove dashes in customer_id, it works

**Comment by razvanbalosin** [comment]
It is about error handling in general, `exception_interceptor` fails to load the `errors_pb2` module and it throws this exception no matter what the internal error was

**Comment by davidcantidio** [comment]
Same problem here.

**Comment by davidcantidio** [comment]
I have solved my problem by doing the following - not sure if all steps are relevant: 

- pip uninstalled googled-ads
- pip3.7 installed google-ads
-  Go to the Oauth Playground, to get a new refresh token. Make sure you are logged as the actual account you are trying to access - in my case a test account. My previous refresh token was generated while I was logged in the production account. I think that was the problem for me.

**Comment by lucasgomide** [comment]
This error still occurring for me when an error on the ad_group_criterion update occurs. I have enabled the debug mode, then I saw the real error. In this case, it was something related to the cpc_micro_bid value. I **had to enable** the debug mode to realize that because `ExceptionInterceptor` is hidden the real error. 

You guys have any ideas about how to fix this module load error? It will hidden real errors in production.

**Comment by wihl** [comment]
It will be addressed in the near future, likely before the next major Google Ads API release.

**Comment by jiulongw** [comment]
For anyone want a quick and dirty fix:

Open this file in your pip installation folder.  For me, it was
`~/miniconda2/envs/py3/lib/python3.7/site-packages/google/ads/google_ads/interceptors/exception_interceptor.py`

Locate following function:
```
    def _get_google_ads_failure(self, trailing_metadata):
        """Gets the Google Ads failure details if they exist.

        Args:
            trailing_metadata: a tuple of metadatum from the service response.

        Returns:
            A GoogleAdsFailure that describes how a GoogleAds API call failed.
            Returns None if either the trailing metadata of the request did not
            return the failure details, or if the GoogleAdsFailure fails to
            parse.
        """
        if trailing_metadata is not None:
            for kv in trailing_metadata:
                if kv[0] == self._failure_key:
                    try:
                        error_protos = import_module(
                            'google.ads.google_ads.%s.proto.errors' %
                                self._api_version)
                        ga_failure = error_protos.errors_pb2.GoogleAdsFailure()
                        ga_failure.ParseFromString(kv[1])
                        return ga_failure
                    except DecodeError:
                        return None

        return None
```

Change first a few lines of code inside `try` block to:
```
                        error_protos = import_module(
                            'google.ads.google_ads.%s.proto.errors.errors_pb2' %
                                self._api_version)
                        ga_failure = error_protos.GoogleAdsFailure()
```

Now it can show real error message.

@wihl if you haven't already done this and if it is a valid fix, I'm happy to send a PR :).

**Comment by lucasgomide** [comment]
👏 👏 👏 👏 👏 👏 👏 👏  @jiulongw

**Comment by Lesikv** [comment]
Hi!
I am still getting this issue. Please help me! 🙏

**Comment by wihl** [comment]
We haven't released this update to Pypi yet - you have to grab it from GitHub (use `pip install -e .` to install from the local repository clone). If you did that, and there is still a problem, can you provide the error?

**Comment by Lesikv** [comment]
Hi! Thank you for quick answer.
I thought that this fix appeared in latest version.

I have changed this file `/site-packages/google/ads/google_ads/interceptors/exception_interceptor.py` as in your pull request and i got another error INVALID_CUSTOMER_ID, but i use this ID in other requests with Adwords Api and it is ok.

**Comment by wihl** [comment]
Did you remove the '-' from the CID, ie. 1234567890, not 123-456-7890? See https://developers.google.com/google-ads/api/docs/migration/format-specs#customer_id_format

**Comment by Lesikv** [comment]
Yes! I had new error 🤦‍♀ 
```
Request with ID "OH1WdoMTodQvElrDm-kepg" failed with status "PERMISSION_DENIED" and includes the following errors:
	Error with message "User doesn't have permission to access customer. Note: If you're accessing a client customer, the manager's customer id must be set in the 'login-customer-id' header. See https://developers.google.com/google-ads/api/docs/concepts/call-structure#login-customer-id".
```
But i have added a new key to config file with login-customer-id

**Comment by wihl** [comment]
lesikv@ Your issues are beyond scope of this particular bug and Python. Could you please make a forum post at https://groups.google.com/g/adwords-api and we can continue to troubleshoot from there? I won't be responding to issues unrelated to this bug here any longer.

**Comment by emilecaron** [comment]
as a simple workaround, having this import at the beginning of my script makes things work:
`from google.ads.google_ads.v2.proto.errors import errors_pb2`
