### ISSUE TITLE
Questions regarding report download segment.date

### ISSUE THREAD

**Issue by yunstanford** [googleads/google-ads-python#204]
1. Does GoogleAds use UTC based date time for reports?
2. Let's say, today is 2020-01-22, and i'd like to download one keyword performance report for 2020-01-21, when does the report become ready (including all data, and metrics.impression, metrics.clicks are accurate) ? Can we download that at 2020-01-22:00:00, at very beginning of 2020-01-22 ?

**Comment by yunstanford** [comment]
Is this still true https://support.google.com/google-ads/answer/2544985?hl=en ?

**Comment by yunstanford** [comment]
^ @wihl

**Comment by wihl** [comment]
> Is this still true https://support.google.com/google-ads/answer/2544985?hl=en ?

Yes, data freshness is the same for the UI and the API. Still investigating the timezones across multiple accounts.

**Comment by wihl** [comment]
The timezone of the returned data is based on the client's timezone setting, not UTC nor the timezone of the login-customer-id. You can retrieve the timezone from the [Customer resource](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v2.resources#google.ads.googleads.v2.resources.Customer) via the CustomerService.
