### ISSUE TITLE
cant add new asset to an exists ad_group_ad

### ISSUE THREAD

**Issue by drinkinginthesky** [googleads/google-ads-python#214]
hi：
When i try to add a new asset to an exists ad_group_ad, an error occured, this is error message:

> {
  error_code {
    request_error: IMMUTABLE_FIELD
  }
  message: "Field \'ad.app_ad.youtube_videos\' cannot be modified by \'UPDATE\' operation."
  location {
    field_path_elements {
      field_name: "operations"
      index {
      }
    }
    field_path_elements {
      field_name: "update"
    }
    field_path_elements {
      field_name: "ad"
    }
    field_path_elements {
      field_name: "app_ad"
    }
    field_path_elements {
      field_name: "youtube_videos"
    }
  }
}

It looks youtube_videos is IMMUTABLE_FIELD? So how can i add new asset to an exists ad_group_ad, the ad_group_ad type is app_ad
thanks

**Comment by drinkinginthesky** [comment]
I use AdService/MutateAds instead of AdGroupAdService/MutateAdGroupAds, it works

**Comment by Rukeith** [comment]
@drinkinginthesky Could you provide sample code?
