### ISSUE TITLE
Mutate gender bid: google.api_core.exceptions.InternalServerError: 500 Internal error encountered.

### ISSUE THREAD

**Issue by ricardocancar** [googleads/google-ads-python#222]
Hi,
this is one operator example to modify the age bid
**operator** example
update {
 resource_name: "customers/customer_id/adGroupCriteria/ad_group_id~503006"
 bid_modifier {
   value: 0.9
 }
}
update_mask {
 paths: "resource_name"
 paths: "bid_modifier"
}

I getting the following error
###  Response

Fault: {
"created": "@1581675413.638711689","description":"Error received from peer ipv4:74.125.193.95:443",
"file": "src/core/lib/surface/call.cc",
"file_line": 1056,
"grpc_message": "Internal error encountered.",
"grpc_status": 13
}

I checked that the ad_group_id exist and is enable the criterion id 503006 is enable also and 
the campaign type is search this code were working before and the error doesn't give me some information 

i just trying to change our bid by age target. 
this is the output that i get when I run this code. 
```agc_service = client.get_service('AdGroupCriterionService', version='v2')
 ad_group_service = client.get_service('AdGroupService', version='v2')
 
operators = []
 for ad_group_id in changes['ad_group_id']:
      for mutation in changes['demographic_adjustments']:
            ad_group_criterion_operation = client.get_type(
                    'AdGroupCriterionOperation')
            # update operation to modify the bid for device
            ad_group_criterion = ad_group_criterion_operation.update
           # Set the campaign path we want to update
            ad_group_criterion.resource_name =\
                 agc_service.ad_group_criteria_path(
                      customer_id, '%s~%s' % (ad_group_id,
                                             mutation['criterion_id']))
            # update the bid for each device
            bid_modifier_value = 1 + mutation['recommended_bid_ajustment']
            ad_group_criterion.bid_modifier.value = bid_modifier_value
            fm = protobuf_helpers.field_mask(None, ad_group_criterion)
            ad_group_criterion_operation.update_mask.CopyFrom(fm)
            operators.append(ad_group_criterion_operation)

ad_group_criterion_response = (
           agc_service.mutate_ad_group_criteria(
                customer_id, operators))



thanks: Ricardo

**Comment by wihl** [comment]
Your code snippet looks fine. You may have found a bug in the server. Please email googleadsapi-support@google.com with private information like your DevToken, customer Id, request id, etc. Mention this GitHub issue as ask them to escalate the case to David Wihl. We can then do a more detailed investigation. Thanks for the bug report!

**Comment by ricardocancar** [comment]
thanks, I sent the information to the email that you provide. But I don't know how to get the request id. from the error. Can you explain me or provide some URL, since I can't find that in the documentation?? sorry and thanks for your help.

**Comment by wihl** [comment]
See [this line](https://github.com/googleads/google-ads-python/blob/ed37e2f298d7cf7ed4f52d5b291f8afea6cc8fe8/examples/campaign_management/update_campaign_criterion_bid_modifier.py#L45) for an example of retrieving the request id.

**Comment by ricardocancar** [comment]
it return a None Request_id

[WARNING]	2020-02-17T16:48:58.960Z Request made: ClientCustomerId: customer_id, Host: googleads.googleapis.com:443, Method: /google.ads.googleads.v2.services.AdGroupCriterionService/MutateAdGroupCriteria, RequestId: None, IsFault: True, FaultMessage: Internal error encountered.

**Comment by ricardocancar** [comment]
Also I have this header:

```Method: /google.ads.googleads.v2.services.AdGroupCriterionService/MutateAdGroupCriteria
Host: googleads.googleapis.com:443
Headers: {
  "developer-token": "token",
  "login-customer-id": "login_id",
  "x-goog-api-client": "gl-python/3.6.9 grpc/1.26.0 gax/1.16.0 gapic/4.0.0",
  "x-goog-request-params": "customer_id=customer"
}

My python version is below than 3.7 and I using google-ads==4.0.0 this may be the problem, but when I downgrade the google ads library, I have the same issue.

**Comment by wihl** [comment]
I don't think it is an issue with Python 3.6 / google-ads=4.0.0. Thanks for the additional information.

**Comment by ricardocancar** [comment]
This is the whole traceback:

Traceback (most recent call last):
  File "/var/task/google/api_core/grpc_helpers.py", line 57, in
error_remapped_callable
    return callable_(*args, **kwargs)
  File "/var/task/grpc/_interceptor.py", line 222, in __call__
    compression=compression)
  File "/var/task/grpc/_interceptor.py", line 257, in _with_call
    return call.result(), call
  File "/var/task/grpc/_channel.py", line 333, in result
    raise self
  File "/var/task/grpc/_interceptor.py", line 248, in continuation
    compression=new_compression)
  File "/var/task/grpc/_interceptor.py", line 272, in with_call
    compression=compression)
  File "/var/task/grpc/_interceptor.py", line 257, in _with_call
    return call.result(), call
  File "/var/task/grpc/_channel.py", line 333, in result
    raise self
  File "/var/task/grpc/_interceptor.py", line 248, in continuation
    compression=new_compression)
  File "/var/task/grpc/_interceptor.py", line 272, in with_call
    compression=compression)
  File "/var/task/grpc/_interceptor.py", line 256, in _with_call
    continuation, client_call_details, request)
  File "/var/task/google/ads/google_ads/interceptors/exception_interceptor.py",
line 139, in intercept_unary_unary
    self._handle_grpc_failure(response)
  File "/var/task/google/ads/google_ads/interceptors/exception_interceptor.py",
line 118, in _handle_grpc_failure
    raise exception
  File "/var/task/grpc/_interceptor.py", line 248, in continuation
    compression=new_compression)
  File "/var/task/grpc/_channel.py", line 835, in with_call
    return _end_unary_response_blocking(state, call, True, None)
  File "/var/task/grpc/_channel.py", line 726, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
    status = StatusCode.INTERNAL
    details = "Internal error encountered."
    debug_error_string =
"{"created":"@1582014045.636110340","description":"Error received from
peer ipv4:74.125.193.95:443","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Internal
error encountered.","grpc_status":13}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 132, in applyer
    changes['changes']['mutater'])
  File "/var/task/mutator.py", line 591, in ad_group_criterion_bid_modifier
    ad_group_criterion_update_bid_modifier(client, customer_id, changes)
  File "/var/task/mutator.py", line 524, in
ad_group_criterion_update_bid_modifier
    customer_id, operators))
  File "/var/task/google/ads/google_ads/v2/services/ad_group_criterion_service_client.py",
line 325, in mutate_ad_group_criteria
    return self._inner_api_calls['mutate_ad_group_criteria'](request,
retry=retry, timeout=timeout, metadata=metadata)
  File "/var/task/google/api_core/gapyouic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/var/task/google/api_core/retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "/var/task/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/var/task/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/var/task/google/api_core/grpc_helpers.py", line 59, in
error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.InternalServerError: 500 Internal error encountered.

if you want me to provide some extra information. you can ask for it
Thanks for the help

**Comment by elviskahoro** [comment]
Hey David (@wihl).

I'm having a similar error response (Internal Error Encountered) but through a call to the KeywordPlanService: client.get_type('KeywordPlanForecastIntervalEnum', version='v3')

The script I'm running is an almost exact copy from: examples/planning/add_keyword_plan.py

Here's the error
  raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.INTERNAL
        details = "Internal error encountered."
        debug_error_string = "{"created":"@1585381494.191782000","description":"Error received from peer ipv4:64.233.185.95:443","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Internal error encountered.","grpc_status":13}"

**Comment by BenRKarl** [comment]
@ricardocancar @elviskahoro thanks for raising this issue. Does this problem occur consistently or is it always reproducible? Can you each share your version of Python, the version of the Google Ads API you're using (i.e `version='v2'` when calling `client.get_service`) and the result of running `pip freeze` so that I can try to reproduce myself?

**Comment by ricardocancar** [comment]
Hi Ben Karl , I solved already this issue.

my environment was python 3.6.9
google-ads==4.0.0
pymongo[tls2, srv]==3.7.2
ikp3db==1.4.1

ok, so the problem is that, we have several google ads account with 2 or
more MCC_ID because we exceed the limit in the UI of 80.000. It seems I can
only do mutation with one mcc not both. If you want I can provide you the
mcc_id. Also I would to have some Error info, if I use the wrong MCC
account to do mutations in one of our customers.
Thanks.

Greetings, Ricardo.

**Comment by elviskahoro** [comment]
I've tried both the MCC for our manager account and the ads account.

keyword_plan_service` = client.get_service('KeywordPlanService', version='v3')
# breaks on this following line
**response = keyword_plan_service.mutate_keyword_plans(customer_id, [operation])**

PIP Freeze (python 3.7.3)
google-ads==5.0.2
google-api-core==1.16.0
google-auth==1.7.1
google-auth-oauthlib==0.4.1
google-pasta==0.1.8
googleapis-common-protos==1.51.0


Same line: 1055 as rivardo
 raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.INTERNAL
        details = "Internal error encountered."
        debug_error_string = "{"created":"@1586014796.743902000","description":"Error received from peer ipv4:172.217.2.42:443","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Internal error encountered.","grpc_status":13}"

**Comment by BenRKarl** [comment]
@elviskahoro That error might indicate that an exception was returned by the API that this library doesn't know how to handle. You can print the error details by printing the raw trailing_metadata by inserting a print statement [like this](https://github.com/googleads/google-ads-python/pull/280/files). Can you try adding this print statement and pasting the trailing metadata here? Be sure to scan the output and remove any credentials, such as your CID or developer token, before pasting.

**Comment by BenRKarl** [comment]
@elviskahoro closing this out, assuming the issue has been resolved by now. Please reopen if that's not the case.
