### ISSUE TITLE
Get country code from api response

### ISSUE THREAD

**Issue by stephan9mertel** [googleads/google-ads-python#227]
We're retrieving the `geo_target_country` segment using the api and expected the value to be a country code, but instead we get a StringValue like `"geoTargetConstants/2170"`.

Is there a way to map this return value to a country code, just like it can be done for instance with the device using `DeviceEnum`?

**Comment by wihl** [comment]
Use the [GeoTargetConstantService](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v2.services#google.ads.googleads.v2.services.GeoTargetConstantService). Pass in the above resource name and you'll get back a [GeoTargetConstant](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v2.resources#google.ads.googleads.v2.resources.GeoTargetConstant) which includes the `country_code`. This [code example](https://github.com/googleads/google-ads-python/blob/master/examples/targeting/get_geo_target_constant_by_names.py) may help.

**Comment by stephan9mertel** [comment]
thanks @wihl. Unfortunately that's not really handy, since we'd have to make an API call for each and every element in a report response. Isn't there a way to obtain all country codes and save them in a local variable in order to be able to do the mapping internally?

**Comment by wihl** [comment]
You can always cache the results instead of hitting the service every time. 

There is also a reference file available at https://developers.google.com/adwords/api/docs/appendix/geotargeting which you have to update regularly.

**Comment by stephan9mertel** [comment]
Many thanks @wihl , this is what I was looking for!
