### ISSUE TITLE
google ads api not getting the list of campaigns

### ISSUE THREAD

**Issue by trabelsirami** [googleads/google-ads-python#234]
Hello everybody i'm having a problems with the googleads api  i have used the right repository and followed the documentation and i have run the get_campains.py file with all the informations in googleads.yaml(developer_token,client_id,client_secret,refresh_token) now it gives me nothing as a result and i don't know what does it mean 
![api_problems](https://user-images.githubusercontent.com/39746414/75672282-ba562b00-5c80-11ea-8916-ff4381c2ff3f.png)
i send it to the googleads api forum 
![yo](https://user-images.githubusercontent.com/39746414/75672349-e07bcb00-5c80-11ea-9910-2d56844b3864.JPG)
the problem is following the documentation the only id i have to use is the client id with this format 
 --> '9585*****098-9kq986vpt01fvlba022484qo348isnj4.apps.googleusercontent.com'they didn't mention anything about the customer client ID the one with this format -->'XXX-XXX-XXXX'
Thank you for replying

**Comment by wihl** [comment]
Please continue this discussion in the forums as it is not specific to Python. All client IDs are in the form of XXX-XXX-XXXX and are attainable from the Ads User Interface http://ads.google.com/
