### ISSUE TITLE
Set policy_validation_parameter.ignorable_policy_topics when updating using AdService

### ISSUE THREAD

**Issue by j-walker23** [googleads/google-ads-python#237]
Hello,

In the Release Notes, it says AdService was added to update existing ads, while keeping metrics.

Is there a way to handle policy findings errors when updating an ads headline to something like the example `'Buy your tickets now!!!!!!!'`.

It works while creating ads using AdGroupAdOperation. But i'm not sure for AdOperation.

**Comment by wihl** [comment]
The [validate_text_ad](https://github.com/googleads/google-ads-python/blob/master/examples/campaign_management/validate_text_ad.py) example should show you how to do this. While it shows creation with AdGroupAdOperation, it should behave the same for [AdOperation](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v3.services#adoperation) updates.

Note that not all ad types are can be updated. See the _mutable_ column in the [list of ad types](https://developers.google.com/google-ads/api/docs/ads/ad-types).

**Comment by j-walker23** [comment]
@wihl  Just an FYI, `policy_validation_parameter` appears to not exist on the underlying proto object for AdOperation only.

<img width="300" alt="Screen Shot 2020-03-05 at 3 00 17 PM" src="https://user-images.githubusercontent.com/2018885/76029636-212e4b00-5ef2-11ea-9581-91633b373b9c.png">

**Comment by j-walker23** [comment]
@wihl The [https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v3.services#adoperation](AdOperation) docs show `policy_validation_parameter` is not an option, for any ad type.

Since the docs are language agnostic, guessing that means editing ads with policy issues is a future feature?

**Comment by wihl** [comment]
Yes, you are correct, this will be a future feature. I'll submit a request for it but can't guarantee when or if it will appear.

**Comment by j-walker23** [comment]
Perfect, thanks so much for your help!

**Comment by wihl** [comment]
internal ref: b/150946495

**Comment by j-walker23** [comment]
@wihl This is only tangentially related, but I figured i'd ask since you are submitting the above.

If we could have `AdOperation` added to [MutateOperation](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v3.services#google.ads.googleads.v3.services.MutateOperation), that would be awesome.

Updating ads with AdOperations are the only time I have to diverge from my normal flow using this awesome library.

Thanks again.

**Comment by wihl** [comment]
Yeah, I agree that leaving out AdOperation seems like an oversight. I filed an issue for this as well (b/150955016). Glad you are enjoying the library and thanks for the feedback!

**Comment by wihl** [comment]
`AdOperation` is added to the next version of `MutateOperation`. I can't share the release date but it will follow the previous release pattern.
