### ISSUE TITLE
Exception not being parsed properly

### ISSUE THREAD

**Issue by MarTango** [googleads/google-ads-python#24]
Related to #8

There still seems to be an issue, with `AttributeError: '_Rendezvous' object has no attribute 'request_id'` on [this line](https://github.com/googleads/google-ads-python/blob/master/google/ads/google_ads/client.py#L363). This can easily be replicated with a `GoogleAdsService.search` request with an syntactically invalid query.

**Comment by BenRKarl** [comment]
Hi @MarTango - 

Thanks for bringing this up! Indeed it appears to be a bug of some kind. We're investigating and should post a resolution or bug fix soon.

**Comment by BenRKarl** [comment]
@MarTango can you clarify which version of Python you're using when you encounter this error?

**Comment by MarTango** [comment]
3.7.2

On 23 Jan 2019 17:52, "Ben Karl" <notifications@github.com> wrote:

@MarTango <https://github.com/MarTango> can you clarify which version of
Python you're using when you encounter this error?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/googleads/google-ads-python/issues/24#issuecomment-456901152>,
or mute the thread

**Comment by BenRKarl** [comment]
@MarTango See the above PR that links to this issue for context on the bug.

Temporarily you can work around the issue by manually installing `grpcio==1.17.0` into your environment after installing `google-ads`, specifically (if you're using `pip`):

```
$ pip install google-ads
$ pip uninstall grpcio
$ pip install grpcio==1.17.0
```

**Comment by MarTango** [comment]
Good news!
Thanks!

(Github isn't allowing me to comment, so I'm replying to the email instead)

**Comment by MarTango** [comment]
Unfortunately that temporary solution doesn't work for me.

I get a `TypeError: Object of type bytes is not JSON serializable`

**Comment by BenRKarl** [comment]
@MarTango Thanks for sharing this info. I suspect it's related to the issue I described in the PR. Pinning those dependency versions is a short-term stopgap; we're working on a more complete fix that should hopefully address the larger issue.

Can you tell me what type of request you're making to generate this error?

**Comment by MarTango** [comment]
I think any invalid GAQL query will do it: e.g. `next(google_ads_service.search(customer_id, "SELECT campaign.idz FROM campaign").__iter__())`

**Comment by BenRKarl** [comment]
@MarTango - I just posted a PR that should address these errors. Specifically the `Object of type bytes is not JSON serializable` is addressed [here](https://github.com/googleads/google-ads-python/pull/27/files#diff-88c45bf019178ddc73da07f39bde0f64R701). In the trailing metadata (a.k.a. response headers) we receive from the API the values are sometimes `bytes` so that default handler converts them when they're encountered.

**Comment by MarTango** [comment]
Looks like #27 has fixed this - thanks!
