### ISSUE TITLE
v3 not available, neither search_stream 

### ISSUE THREAD

**Issue by mbaader** [googleads/google-ads-python#241]
Hi,

I've updated the google ads python library on my server today, but when I try to use v3 in my scripts, I get the error:

> Error: Specified Google Ads API version "v3" does not exist. Valid API versions are: "v2", "v1"

And if I try to use v2 together with 'ga_service.search_stream', I get the error:

> Error: 'GoogleAdsServiceClient' object has no attribute 'search_stream

Here's the response I get, when I retry to update the library:

> Requirement already up-to-date: google-ads in /home/ec2-user/.local/lib/python3.6/site-packages
> Requirement already up-to-date: google-auth-oauthlib<1.0.0,>=0.0.1 in /home/ec2-user/.local/lib/python3.6/site-packages (from google-ads)
> Requirement already up-to-date: google-api-core<2.0.0,>=1.7.0 in /home/ec2-user/.local/lib/python3.6/site-packages (from google-ads)
> Requirement already up-to-date: googleapis-common-protos<2.0.0,>=1.5.8 in /home/ec2-user/.local/lib/python3.6/site-packages (from google-ads)
> Requirement already up-to-date: grpcio<2.0.0,>=1.18.0 in /home/ec2-user/.local/lib/python3.6/site-packages (from google-ads)
> Requirement already up-to-date: PyYAML<6.0,>=5.1 in /home/ec2-user/.local/lib/python3.6/site-packages (from google-ads)
> Requirement already up-to-date: requests-oauthlib>=0.7.0 in /home/ec2-user/.local/lib/python3.6/site-packages (from google-auth-oauthlib<1.0.0,>=0.0.1->google-ads)
> Requirement already up-to-date: google-auth in /home/ec2-user/.local/lib/python3.6/site-packages (from google-auth-oauthlib<1.0.0,>=0.0.1->google-ads)
> Requirement already up-to-date: protobuf>=3.4.0 in /home/ec2-user/.local/lib/python3.6/site-packages (from google-api-core<2.0.0,>=1.7.0->google-ads)
> Requirement already up-to-date: six>=1.10.0 in /home/ec2-user/.local/lib/python3.6/site-packages (from google-api-core<2.0.0,>=1.7.0->google-ads)
> Requirement already up-to-date: requests<3.0.0dev,>=2.18.0 in /home/ec2-user/.local/lib/python3.6/site-packages (from google-api-core<2.0.0,>=1.7.0->google-ads)
> Requirement already up-to-date: setuptools>=34.0.0 in /home/ec2-user/.local/lib/python3.6/site-packages (from google-api-core<2.0.0,>=1.7.0->google-ads)
> Requirement already up-to-date: pytz in /home/ec2-user/.local/lib/python3.6/site-packages (from google-api-core<2.0.0,>=1.7.0->google-ads)
> Requirement already up-to-date: oauthlib>=3.0.0 in /home/ec2-user/.local/lib/python3.6/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.0.0,>=0.0.1->google-ads)
> Requirement already up-to-date: rsa<4.1,>=3.1.4 in /home/ec2-user/.local/lib/python3.6/site-packages (from google-auth->google-auth-oauthlib<1.0.0,>=0.0.1->google-ads)
> Requirement already up-to-date: pyasn1-modules>=0.2.1 in /home/ec2-user/.local/lib/python3.6/site-packages (from google-auth->google-auth-oauthlib<1.0.0,>=0.0.1->google-ads)
> Requirement already up-to-date: cachetools<5.0,>=2.0.0 in /home/ec2-user/.local/lib/python3.6/site-packages (from google-auth->google-auth-oauthlib<1.0.0,>=0.0.1->google-ads)
> Requirement already up-to-date: certifi>=2017.4.17 in /home/ec2-user/.local/lib/python3.6/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2.0.0,>=1.7.0->google-ads)
> Requirement already up-to-date: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/ec2-user/.local/lib/python3.6/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2.0.0,>=1.7.0->google-ads)
> Requirement already up-to-date: idna<3,>=2.5 in /home/ec2-user/.local/lib/python3.6/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2.0.0,>=1.7.0->google-ads)
> Requirement already up-to-date: chardet<4,>=3.0.2 in /home/ec2-user/.local/lib/python3.6/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2.0.0,>=1.7.0->google-ads)
> Requirement already up-to-date: pyasn1>=0.1.3 in /home/ec2-user/.local/lib/python3.6/site-packages (from rsa<4.1,>=3.1.4->google-auth->google-auth-oauthlib<1.0.0,>=0.0.1->google-ads)

This does not seem to be the most recent build.

What's wrong?

Regards
Mat

**Comment by wihl** [comment]
The first obvious thing is that you need Python 3.7 for v5.0 of this library (which supports API V3 that includes streaming).

**Comment by mbaader** [comment]
Uh - when was this change posted in your blog? The latest information I find is this one, where Python 3.6 was required:
https://ads-developers.googleblog.com/2019/04/python-2-deprecation-in-ads-api-client.html
Even with version 4.0, the requirement was still python 3.6:
https://ads-developers.googleblog.com/2019/10/python-2-deprecation-in-google-ads-api.html

Google does not find anything Python 3.7 related in your blog:
https://www.google.com/search?q=site%3Aads-developers.googleblog.com++Python+3.7

Did I miss something?

**Comment by wihl** [comment]
Since V4.1, the setup.py has required Python 3.7. See also https://github.com/googleads/google-ads-python/issues/197

We only announce major Python version dependencies on the blog, not minor versions.

**Comment by wihl** [comment]
Closing this issue. Feel free to re-open if there are still open questions.

**Comment by lsdventures** [comment]
thanks
