### ISSUE TITLE
google-ads-python

### ISSUE THREAD

**Issue by jaypatrickhoward** [googleads/google-ads-python#258]
For new projects, is it preferable to use this library (google-ads-python) or googleads-python-lib?

For completeness, am asking there as well.

**Comment by wihl** [comment]
For new projects, use the new Google Ads API (google-ads-python). While it is still in beta, it is evolving whereas the legacy API will not have any new features. If you write to the new API, you won't have to rewrite your code when the old API is sunset.

**Comment by advance512** [comment]
@wihl When will the old Google Ads API planned to be sunsetted?

**Comment by wihl** [comment]
Google hasn't announced official timing. It will be approximately one year after the new API exits beta and achieves full feature parity.

**Comment by keithvsr** [comment]
For anyone like myself who may stumble upon this issue in future, @wihl advice above is incorrect, at least presently. [googleads-python-lib](https://github.com/googleads/googleads-python-lib/) is for the  [Google Ad Manager API](https://developers.google.com/ad-manager/api/start), whereas this repo [google-ads-python](https://github.com/googleads/google-ads-python/) is for the [Google Ad API](https://developers.google.com/google-ads/api/docs/start). They are not the same.
