### ISSUE TITLE
[API Issue] SearchGoogleAdsRequest fails if there are too many results

### ISSUE THREAD

**Issue by MarTango** [googleads/google-ads-python#26]
I believe that this is an issue with the underlying API, but I wasn't sure where to bring it up. I currently can't tell what the error message is from this library, but my own wrapper for the api suggests that the response from the server is:
```json
{
  "error": {
    "code": 503,
    "message": "The service is currently unavailable.",
    "status": "UNAVAILABLE"
  }
}
```

I believe using `page_token` and `page_size` does not resolve this.

**Comment by MarTango** [comment]
Never mind!
With python, all I needed to do was provide the `timeout` kwarg to `.search()`

**Comment by BenRKarl** [comment]
Thanks for reporting @MarTango - what value did you pass for `timeout`? I'll take a look at some point to see what I can learn.

**Comment by MarTango** [comment]
I passed in `timeout=45`. 30 failed and 37.5 worked. I believe (from briefly looking at the source code) that the default is 25?

**Comment by MarTango** [comment]
I had another look at [the code](https://github.com/googleads/google-ads-python/blob/master/google/ads/google_ads/v0/services/google_ads_service_client_config.py) and it looks like the default timeout is already at 60? Maybe the issue I had isn't easily replicable.
