### ISSUE TITLE
"add-shopping-product-listing-group-tree" - example is missing for Python

### ISSUE THREAD

**Issue by mbaader** [googleads/google-ads-python#274]
Hi,

I can't find the Python example for "Add Shopping Product Listing Group Tree" neither on GitHub 

https://github.com/googleads/google-ads-python/tree/master/examples/shopping

...nor in the online documentation:

https://developers.google.com/google-ads/api/docs/samples/add-shopping-product-listing-group-tree

Are there any plans for that? And if yes, can we have an ETA?

Regards
Mat

**Comment by BenRKarl** [comment]
@mbaader - there's actually an open PR to add it, but we're behind on getting it reviewed and merged. Feel free to reference it in the meantime: https://github.com/googleads/google-ads-python/pull/228/files

Currently no specific timeline but hopefully this will get finalized in the near term since the PR is already open.

**Comment by mbaader** [comment]
Hi BenRKarl,

thank you, great! I'll look into it.

Regards
Mat

**Comment by BenRKarl** [comment]
Keeping this open to track the completion of the `add_shopping_product_listing_group_tree` example.

**Comment by mbaader** [comment]
Hi  BenRKarl,

the wip example add_shopping_product_listing_group_tree helped a lot.

The only thing I was not able to figure out is how to set an empty value for the "other" units for non-enum case values.

In the example, there is this line of code:

`listing_group.case_value.product_condition.condition = client.get_type("ProductConditionEnum").UNSPECIFIED`

But this constuct does not work e.g. for the case value "product_brand":
I tried several approaches, but all of them failed:

listing_group.case_value.product_brand.value.value = None
listing_group.case_value.product_brand.value.value = ''
listing_group.case_value.product_brand.value = {}
and several more.

Can you give me a hint on how to do this with the python library?

Regards
Mat

**Comment by BenRKarl** [comment]
@mbaader what was the error you received when you tried to set these values? Also I believe [this documentation](https://developers.google.com/google-ads/api/docs/client-libs/python/empty-message-fields) may be helpful here.

**Comment by mbaader** [comment]
Hi BenRKarl,

thank you again for the hint. This line of code did the trick:

`listing_group.case_value.product_brand.CopyFrom(google_ads_client.get_type('ProductBrandInfo'))`

Regards
Mat

**Comment by BenRKarl** [comment]
Closing this as the example has been added: https://github.com/googleads/google-ads-python/blob/master/examples/shopping_ads/add_shopping_product_listing_group_tree.py
