### ISSUE TITLE
Setting default api version

### ISSUE THREAD

**Issue by aidiss** [googleads/google-ads-python#275]
Is it possible to set a default version for all .get_service and .get_type calls?
Currently I am writing

```py
client.get_type("CampaignOperation", version="v2")
```
It would be nice if could do this:

```py
client = GoogleAdsClient(credentials, version='v2')
```

**Comment by wihl** [comment]
That's a good idea - we'll consider it for a future release.

**Comment by mbaader** [comment]
I would also appreciate such a feature.
Currently I keep seeing scripts where the version is passed in dozens of lines of code, which is highly redundant.
