### ISSUE TITLE
How to perform conversion tracking?

### ISSUE THREAD

**Issue by mojovski** [googleads/google-ads-python#276]
Hi, 
is it possible to perform conversion tracking using this library? 
In would like to report conversions, to optimize the CPA rate by Google ads using backend python processes.

Thank you very much!

**Comment by wihl** [comment]
Since this is a generic question about the API (and not specific to Python), please ask it on the [Google Ads API forum](https://groups.google.com/forum/#!forum/adwords-api). Thanks!

**Comment by mojovski** [comment]
Hi @wihl ,
Thank you for the quick reply.

but would it be possible to use this library? 
When it comes to the ads-js-library, the call would be
`gtag('config', 'AW-CONVERSION_ID');`
