### ISSUE TITLE
Customer ID Argument Required

### ISSUE THREAD

**Issue by sclumpus** [googleads/google-ads-python#278]
I'm trying to run this example code to grab campaigns here: 
https://developers.google.com/google-ads/api/docs/samples/get-campaigns

I've configured my .yaml file with the necessary tokens and customer id. Although when I try to run the script I get this error code:  

> error: the following arguments are required: -c/--customer_id
> An exception has occurred, use %tb to see the full traceback.

I'm not sure what I'm missing as the customer id is specified in my .yaml file already. I'd appreciate any help on this.

Thank you!

**Comment by trabelsirami** [comment]
This line of code indicates that the -c and --customer_id are required in the command line.

**Comment by sclumpus** [comment]
Oh okay I get it, got it to work. Thanks!
