### ISSUE TITLE
Cannot get campaigns from MCC account

### ISSUE THREAD

**Issue by SolvoSupport** [googleads/google-ads-python#283]
I ussing mcc account credentials to log in but I get an empty response 

```
ga_service = client.get_service('GoogleAdsService', version='v3')

    query = ('SELECT campaign.id, campaign.name FROM campaign '
             'ORDER BY campaign.id')

    # Issues a search request using streaming.
    response = ga_service.search_stream(customer_id, query=query)

    try:
        for batch in response:
            for row in batch.results:
                print(f'Campaign with ID {row.campaign.id.value} and name '
                      f'"{row.campaign.name.value}" was found.')
    except GoogleAdsException as ex:
        print(f'Request with ID "{ex.request_id}" failed with status '
              f'"{ex.error.code().name}" and includes the following errors:')
        for error in ex.failure.errors:
            print(f'\tError with message "{error.message}".')
            if error.location:
                for field_path_element in error.location.field_path_elements:
                    print(f'\t\tOn field: {field_path_element.field_name}')
```

How can I access customers campaign from a mcc api call?

**Comment by davedavis** [comment]
Hi @SolvoSupport 
Not sure if this will help.
I've been getting the list of client accounts using the row.customer_client_link.client_customer resource, then looping over each, calling the get campaigns method (like yours above), passing in the account name for each call with the client.

**Comment by wihl** [comment]
Your code looks fine, but as @davedavis alluded to, you need to specify the correct `customer_id`. If your MCC has access to that customer account, it will return the list of campaigns.

I'm going to close this issue. Feel free to re-open if you are still having problems.
