### ISSUE TITLE
Authenticating with a service account via auth.yaml file

### ISSUE THREAD

**Issue by ben519** [googleads/google-ads-python#286]
I'm trying to authenticate to the ads api using a service account. My issue is highly related to #178. Under [*Service Account Configuration* of the google-ads.yaml file](https://github.com/googleads/google-ads-python/blob/master/google-ads.yaml) it states

> ... and remove the four OAuth credentials above.

As far as I can tell, the "four OAuth credentials above" are `developer_token`, `client_id`, `client_secret`, and `refresh_token`. However, when I remove these and attempt

```
from google.ads.google_ads.client import GoogleAdsClient

client = GoogleAdsClient.load_from_storage('config/auth_google-ads.yaml')
```

I get the error

```
Traceback (most recent call last):
  File "/Users/bgorman/anaconda3/envs/datasci/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-44-a80034bf5f9d>", line 1, in <module>
    client = GoogleAdsClient.load_from_storage('config/auth_google-ads.yaml')
  File "/Users/bgorman/anaconda3/envs/datasci/lib/python3.7/site-packages/google/ads/google_ads/client.py", line 158, in load_from_storage
    config_data = config.load_from_yaml_file(path)
  File "/Users/bgorman/anaconda3/envs/datasci/lib/python3.7/site-packages/google/ads/google_ads/config.py", line 44, in validation_wrapper
    config_dict = func(*args, **kwargs)
  File "/Users/bgorman/anaconda3/envs/datasci/lib/python3.7/site-packages/google/ads/google_ads/config.py", line 60, in parser_wrapper
    config_dict = func(*args, **kwargs)
  File "/Users/bgorman/anaconda3/envs/datasci/lib/python3.7/site-packages/google/ads/google_ads/config.py", line 130, in load_from_yaml_file
    return parse_yaml_document_to_dict(yaml_doc)
  File "/Users/bgorman/anaconda3/envs/datasci/lib/python3.7/site-packages/google/ads/google_ads/config.py", line 45, in validation_wrapper
    validate_dict(config_dict)
  File "/Users/bgorman/anaconda3/envs/datasci/lib/python3.7/site-packages/google/ads/google_ads/config.py", line 82, in validate_dict
    str(_REQUIRED_KEYS)))
ValueError: A required field in the configuration data was not found. The required fields are: ('developer_token',)
```

When I include my developer token, I get the error

```
google.auth.exceptions.RefreshError: ('unauthorized_client: Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested.', '{\n  "error": "unauthorized_client",\n  "error_description": "Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested."\n}')
```

Advice on this would be much appreciated. Thanks!

**Comment by bmwilly** [comment]
@ben519 did you figure out a way to do this? I have the same issue.

**Comment by BenRKarl** [comment]
@ben519 @bmwilly The meaningful error here is the second one, and it's not related to the presence of the developer token. It appears as though the credentials in your local JSON file may not be configured properly. You might want to revisit the [instructions for setting up Service Account Auth](https://developers.google.com/google-ads/api/docs/client-libs/python/oauth-service) and see if you may have missed a step.

**Comment by bmwilly** [comment]
Thanks, I figured it out. A few notes for others who stumble across this and are confused by the current state of the docs: 
- The [guide for migrating from the AdWords API to the Google Ads API](https://developers.google.com/google-ads/api/docs/migration) says that the credentials you were using will still be valid. This is not true, since Google Ads API requires [granting impersonation abilities](https://developers.google.com/google-ads/api/docs/oauth/service-accounts#granting_impersonation_abilities), and the AdWords API does not 
- As suggested above, don't comment out the `developer_token` key 
- The `impersonated_email` key in your `googleads.yaml` should be your Google account email, not the Service Account email

**Comment by BenRKarl** [comment]
@bmwilly thanks for following up and posting the solution!
