### ISSUE TITLE
Video Campaigns creation and management from API

### ISSUE THREAD

**Issue by iamsaurabhgupt** [googleads/google-ads-python#287]
Hi Team,

When can we have the availability of mutating video campaigns on Google Ads API?
We are making a platform for launching ads on Youtube and it becomes a crucial requirement.
Please help to prioritise.

Thanks in advance.

**Comment by wihl** [comment]
This has been a long standing request but there are no plans to implement it the Google Ads API. AdWords scripts can [mutate video campaigns](https://developers.google.com/google-ads/scripts/docs/features/video-campaigns).

**Comment by iamsaurabhgupt** [comment]
@wihl thanks for your prompt reply. 
Can you please explain the rationale for this? 
Everything else in Google Ads ecosystem seems to be available on the API. 
If this is intentional, then we'll have to make adjustments to our platform accordingly.

**Comment by wihl** [comment]
This was an intentional executive decision. You should plan accordingly. I recommend the [forum](https://groups.google.com/forum/#!forum/adwords-api) to discuss this further as the issue is not specific to Python.

**Comment by iamsaurabhgupt** [comment]
@wihl Thanks a lot for the explanation. We'll make changes accordingly.
