### ISSUE TITLE
Google Ads API v4

### ISSUE THREAD

**Issue by matt-ideationmill** [googleads/google-ads-python#288]
With Google Ads API v4 release this week, can we please get an ETA on the Python client library?

Also, seems like it's still on v2 on PyPI according to docs. Similarly, the following error is returned with any attempt to call v4 (after pip installing -U google-ads)
`ValueError: Specified Google Ads API version "v4" does not exist. Valid API versions are: "v2", "v1"`

[related forum post](https://groups.google.com/g/adwords-api/c/J5yHodLeuCM/m/LWKe3IWeBAAJ)

**Comment by BenRKarl** [comment]
Hi @matt-ideationmill I expect that v4 support will be released by the end of this week, if not sooner.

Also support for v3 was released in version 5.0.0 of this library, so if you upgrade your dependency to the most recent version you should be able to use v3.

**Comment by BenRKarl** [comment]
@matt-ideationmill just letting you know that version 6.0.0 is released, which supports API v4_0.
