### ISSUE TITLE
segments.date is not returned in query response

### ISSUE THREAD

**Issue by apurvis** [googleads/google-ads-python#29]
before the release of 0.7 today/yesterday, i had this AWQL and it was fine:
```sql
SELECT
  date,
  customer.id,
  campaign.id,
  campaign.name,
  metrics.cost_micros
FROM campaign
WHERE metrics.impressions > 0
  AND date >= '2019-11-22'
  AND date <= '2019-12-22'
```

this broke with the release of 0.7.  after some fiddling i figured out that we now have to use `segments`, so i updated it to be:
```sql
SELECT
  segments.date,
  customer.id,
  campaign.id,
  campaign.name,
  metrics.cost_micros
FROM campaign
WHERE metrics.impressions > 0
  AND segments.date >= '2019-11-22'
  AND segments.date <= '2019-12-22'
```

this runs but... when i inspect the rows that are returned, the `segments.date` does not appear at all.
```
customer {
  resource_name: "customers/9704954372"
  id {
    value: 9704954372
  }
}
campaign {
  resource_name: "customers/9704954372/campaigns/1355772182"
  id {
    value: 1234
  }
  name {
    value: "Search|Branded|Blah"
  }
}
metrics {
  cost_micros {
    value: 2025690000
  }
}
```

what gives?

**Comment by BenRKarl** [comment]
@apurvis - thanks for bringing this up! We're currently working on an update to this library that will bring it up to par with the new API version. Once it's released it should resolve this issue. Apologies for the inconvenience!

**Comment by BenRKarl** [comment]
The new version of the library (0.7.0) will expose the `date` field on responses, so this should be resolved now.
