### ISSUE TITLE
How to add criteria Location and Language in keyword planner forecast?

### ISSUE THREAD

**Issue by toannhu96** [googleads/google-ads-python#291]
I know that we have to create ads plan first then get this plan id pass to `generate keyword forecast`. I only see there is only filter for date range support in the this repo code but not see any filters for Location and Language criteria?
Please help me. Tks.

**Comment by BenRKarl** [comment]
@toannhu96 sorry for the late response on this - could you be a bit more specific about what you're trying to do? Are you trying to call a method on the `KeywordPlanService` or get data from one of the [report](https://developers.google.com/google-ads/api/fields/latest/overview) resources?

**Comment by BenRKarl** [comment]
Closing this issue as stale, but please reopen if needed.
