### ISSUE TITLE
Linking/creating account for user that granted adwords scope

### ISSUE THREAD

**Issue by aidiss** [googleads/google-ads-python#294]
I would like to add client account that provided adwords scope to manager account.
I was able to get id_token and access_token via by using

```js
gapi.signin2.render("my-signin2", {scope: "https://www.googleapis.com/auth/adwords", ...})
```

How can id_token and access_token be used to create link clients account to my manager account?

**Comment by BenRKarl** [comment]
@aidiss you shouldn't need to use access tokens to link a manager account to a client account. [This example](https://github.com/googleads/google-ads-python/blob/master/examples/account_management/link_manager_to_client.py) shows how to do it, by issuing a link request then accepting it.
