### ISSUE TITLE
Cannot use Google Ads API versions 3 or 4 with python

### ISSUE THREAD

**Issue by ConradoMecchi** [googleads/google-ads-python#295]
Issues:

- No module named 'google.ads.google_ads.v4'
- Specified Google Ads API version "v4" does not exist. Valid API versions are: "v2", "v1"

For months, I've been stuck in version 2 of the Google Ads API.
Now that version 4 has things necessary to run my business, I really need to use it and can't postpone solving my issue anymore.
The issue is that whatever I run a python code with version 4, I get this error (equivalent error when I try version 3):
ValueError: Specified Google Ads API version "v4" does not exist. Valid API versions are: "v2", "v1"

My Python google-ads api version is updated to version 6.0 (currently the latest). I am using Anaconda with Python 3.7.4 and 3.7.7 (currently the latest). Whether I use Jupyter or Spyder, I get the same error message.
I tried uninstalling google-ads library (pip uninstall google-ads), but the kernel never stops working, even if I let it run the uninstall for an entire night. Maybe this is a tip to the root cause?
I tried to run the code below as an example, which Google makes available in its documentation, but other codes of my own that work in version 2 get the same error and don't work on versions 3 or 4.

#!/usr/bin/env python
"""This example illustrates how to get campaign criteria.
Retrieves negative keywords in a campaign.
"""

import sys

from google.ads.google_ads.client import GoogleAdsClient
from google.ads.google_ads.errors import GoogleAdsException

def main(client, customer_id):
    ga_service = client.get_service('GoogleAdsService', version='v4')

    query = ('SELECT campaign.id, campaign.name, ad_group.id, ad_group.name, '
             'ad_group_criterion.criterion_id, '
             'ad_group_criterion.keyword.text, '
             'ad_group_criterion.keyword.match_type, '
             'metrics.impressions, metrics.clicks, metrics.cost_micros '
             'FROM keyword_view WHERE segments.date DURING LAST_7_DAYS '
             'AND campaign.advertising_channel_type = \'SEARCH\' '
             'AND ad_group.status = \'ENABLED\' '
             'AND ad_group_criterion.status IN (\'ENABLED\', \'PAUSED\') '
             'ORDER BY metrics.impressions DESC '
             'LIMIT 50')

    # Issues a search request using streaming.
    response = ga_service.search_stream(customer_id, query)
    keyword_match_type_enum = client.get_type(
        'KeywordMatchTypeEnum', version='v4').KeywordMatchType
    try:
        for batch in response:
            for row in batch.results:
                campaign = row.campaign
                ad_group = row.ad_group
                criterion = row.ad_group_criterion
                metrics = row.metrics
                keyword_match_type = keyword_match_type_enum.Name(
                    criterion.keyword.match_type)
                print(f'Keyword text "{criterion.keyword.text.value}" with '
                      f'match type "{keyword_match_type}" '
                      f'and ID {criterion.criterion_id.value} in '
                      f'ad group "{ad_group.name.value}" '
                      f'with ID "{ad_group.id.value}" '
                      f'in campaign "{campaign.name.value}" '
                      f'with ID {campaign.id.value} '
                      f'had {metrics.impressions.value} impression(s), '
                      f'{metrics.clicks.value} click(s), and '
                      f'{metrics.cost_micros.value} cost (in micros) during '
                      'the last 7 days.')
    except GoogleAdsException as ex:
        print(f'Request with ID "{ex.request_id}" failed with status '
              f'"{ex.error.code().name}" and includes the following errors:')
        for error in ex.failure.errors:
            print(f'\tError with message "{error.message}".')
            if error.location:
                for field_path_element in error.location.field_path_elements:
                    print(f'\t\tOn field: {field_path_element.field_name}')
        sys.exit(1)

if __name__ == '__main__':
    google_ads_client = GoogleAdsClient.load_from_storage( 'THE PATH TO MY GOOGLE ADS YAML FILE' )
    main(google_ads_client, 'MY CUSTOMER ID')

--
Please, what should I do?

**Comment by BenRKarl** [comment]
@ConradoMecchi Thanks for filing this - this feels like an issue with the version of the library. It's definitely odd that your machine hangs when you run `pip uninstall google-ads`.  What do you see when you run `python -m pip freeze` and if you try `python -m pip install google-ads==6.0.0` does that help get the latest version installed?

**Comment by ConradoMecchi** [comment]
Hi, Ben,

Jacksons Five has a song about friend Ben. I will play it in your honour here, because you solved the issue.

When I ran pip freeze, I realized I was stuck with a google-ads version 3.3:

Note: you may need to restart the kernel to use updated packages.alabaster==0.7.12
anaconda-client==1.7.2
...
google-ads==3.3.0
google-api-core==1.16.0
google-api-python-client==1.7.11
google-auth==1.12.0
google-auth-httplib2==0.0.3
google-auth-oauthlib==0.4.1
google-cloud-core==1.3.0
google-cloud-storage==1.26.0
google-resumable-media==0.5.0
googleads==24.1.0
googleapis-common-protos==1.6.0
greenlet==0.4.16
...

By forcing the version with the code you suggested (python -m pip install google-ads==6.0.0), pip freeze showed me that I finally had the version I thought I had installed in my machine:

(base) C:\Users\aclme>python -m pip freeze
alabaster==0.7.12
anaconda-client==1.7.2
...
google-ads==6.0.0
google-api-core==1.16.0
google-api-python-client==1.7.11
google-auth==1.12.0
google-auth-httplib2==0.0.3
google-auth-oauthlib==0.4.1
google-cloud-core==1.3.0
google-cloud-storage==1.26.0
google-resumable-media==0.5.0
googleads==24.1.0
googleapis-common-protos==1.6.0
greenlet==0.4.16
...

So my code works now. Thank you very much.
