### ISSUE TITLE
Intermittent HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by KevinMars** [googleads/google-ads-python#296]
Hi,

```
File "/usr/local/lib/python3.7/site-packages/googleads/ad_manager.py", line 859, in DownloadReportToFile
    response = self.url_opener.open(report_url)
  File "/usr/lib64/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib64/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

We are having intermittent issues with pulling reports. The same request may work once and then not work when making the same request a few seconds later and vice versa.

We are using the following method for report downloads,

googleads.ad_manager.AdManagerClient.LoadFromStorage()
report_downloader = self.client.GetDataDownloader(version="v202002")
report_job_id = report_downloader.WaitForReport("OUR_REPORT_QUERY")

For authentication, we have a googleads.yaml with path_to_private_key_file pointing to a service account credentials json. Nothing in the service account permissions has changed recently. 

Thank you,
Kevin

**Comment by BenRKarl** [comment]
Hi @KevinMars - this is actually the wrong library. If this is still an issue for you, can you resubmit it to [googleads-python-lib](https://github.com/googleads/googleads-python-lib)? My suspicion, since this is auth related, is that it's coming from the oauth servers and not the Ads API, so I'd expect this to have been resolved by now.
