### ISSUE TITLE
Intermittent ssl_transport_security Corruption

### ISSUE THREAD

**Issue by QuinRiva** [googleads/google-ads-python#297]
We are using GoogleAds Service to pull Customer and Label data.  Jobs are run in parallel using `multiprocessing`, with each customer being queried on a separate thread.

Randomly, the following error is encountered.  Whilst 2 weeks ago we never had this issue, we are currently unable to run our scripts with out it failing at some point - it always fails at a different point, and occasionally makes it the whole way through without failure.

```
E0831 01:34:47.263326350   25786 ssl_transport_security.cc:507] Corruption detected.
E0831 01:34:47.263433284   25786 ssl_transport_security.cc:483] error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
E0831 01:34:47.263444722   25786 ssl_transport_security.cc:483] error:1000008b:SSL routines:OPENSSL_internal:DECRYPTION_FAILED_OR_BAD_RECORD_MAC
E0831 01:34:47.263450999   25786 secure_endpoint.cc:208]     Decryption error: TSI_DATA_CORRUPTED
``` 

Using v.6.0.0 of the library.

**Comment by BenRKarl** [comment]
@QuinRiva Sorry for the delayed response on this - are you continuing to have this problem today with the newer versions of the library?

**Comment by BenRKarl** [comment]
Closing this as stale, but please reopen if this continues to be an issue.
