### ISSUE TITLE
Get_keyword_stats.py (reporting example in google-ads-python):not working

### ISSUE THREAD

**Issue by ShantanuKhanapure** [googleads/google-ads-python#298]
Hello!
I run example python script (https://github.com/googleads/google-ads-python/blob/master/examples/reporting/get_keyword_stats.py).

I have all the necessary set up done for google ads api

my yaml file looks like below
developer_token: jvX-------A
client_id: 274---------com
client_secret: heU-------Imr9
refresh_token: 1//0g-uNgZ-----yrHH6QElune1j6l0Tc
login_customer_id: (My google ads manager id, I tried both with and without putting this value)

I tried running the file in "jupyter notebook" as well as in "terminal". At both places, the file is not executing. Please find the errors below

### **Jupyter Notebook:**

usage: ipykernel_launcher.py [-h] -c CUSTOMER_ID
ipykernel_launcher.py: error: the following arguments are required: -c/--customer_id
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3339: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

### **Terminal** ( As its is suggested [here](https://github.com/googleads/google-ads-python/issues/92)

MacBook-Air-57:yaml_with_account_id_cmd harshadkhanapure$ python get_keyword.py -c 9574386950
  File "get_keyword.py", line 54
    print(f'Keyword text "{criterion.keyword.text.value}" with '
                                                               ^
SyntaxError: invalid syntax
MacBook-Air-57:yaml_with_account_id_cmd harshadkhanapure$ python get_keyword.py -c/-- 9574386950
  File "get_keyword.py", line 54
    print(f'Keyword text "{criterion.keyword.text.value}" with '
                                                               ^

MacBook-Air-57:yaml_with_account_id_cmd harshadkhanapure$ python get_keyword.py -c/-- 3969569860
  File "get_keyword.py", line 54
    print(f'Keyword text "{criterion.keyword.text.value}" with '
                                                               ^

MacBook-Air-57:yaml_with_account_id_cmd harshadkhanapure$ python get_keyword.py -c 3969569860
  File "get_keyword.py", line 54
    print(f'Keyword text "{criterion.keyword.text.value}" with '

I tried using both Manager Account ID and Child Account but code did not work for both. Kindly let me know how can we resolve this issue.

**Comment by ShantanuKhanapure** [comment]
I tried executing the code line by line and hardcoding the values for "**customer id"(3969569860)** in the code, its giving error at the following line: I tried two ways as below 

**1st way**
    parser.add_argument('--3969569860', type=str,required=True, help='The Google Ads customer ID.')
    args = parser.parse_args()
**error**
    ArgumentError: argument --3969569860: conflicting option string: --3969569860



**second way**
    parser.add_argument('-c','--3969569860', type=str,required=True, help='The Google Ads customer ID.')
    args = parser.parse_args()

**error**
ArgumentError: argument -c/--3969569860: conflicting option string: --3969569860

**Comment by BenRKarl** [comment]
@ShantanuKhanapure what's the error you get when you invoke the script with: `python get_keyword.py -c 9574386950`

Based on the above it's hard to tell what the error is. You shouldn't need to update the calls to the argument parser, if you do then there's a bug we need to fix. However I can run the example fine locally so I wonder if there's an issue with your environment.

**Comment by samsitta** [comment]
Line 64 should be:
`keyword_match_type_enum.Name(row.ad_group_criterion.keyword.match_type)`

**Comment by BenRKarl** [comment]
@ShantanuKhanapure @samsitta with the recent changes to this example, these problems should no longer exist. Please reopen this issue or create a new one if you're still having problems with it!

**Comment by BenRKarl** [comment]
@hiann983 If you're running `get_campaigns` then it sounds like a different error from what's described here, would you mind opening a [new bug report](https://github.com/googleads/google-ads-python/issues/new/choose) and completing the steps in the template so that we have enough information to investigate? Thanks!

**Comment by Albita88** [comment]
> I tried executing the code line by line and hardcoding the values for "**customer id"(3969569860)** in the code, its giving error at the following line: I tried two ways as below
> 
> **1st way** parser.add_argument('--3969569860', type=str,required=True, help='The Google Ads customer ID.') args = parser.parse_args() **error** ArgumentError: argument --3969569860: conflicting option string: --3969569860
> 
> **second way** parser.add_argument('-c','--3969569860', type=str,required=True, help='The Google Ads customer ID.') args = parser.parse_args()
> 
> **error** ArgumentError: argument -c/--3969569860: conflicting option string: --3969569860

I've got the same error. Any solution?

**Comment by Albita88** [comment]
Hi all, 
my situation is exactly the same as @ShantanuKhanapure.

Same script, same issue.
