### ISSUE TITLE
includeZeroImpressions true to query

### ISSUE THREAD

**Issue by Clarkbar36** [googleads/google-ads-python#300]
Hello,

I'm trying to pull some metrics by day out of the API. Query below: 

```
ad_group_query = (
    'SELECT ad_group.campaign, ad_group.id, ad_group.name, metrics.phone_calls, segments.date, campaign.name '
    'FROM ad_group '
    'WHERE ad_group.status = "ENABLED" '
    f'AND segments.date BETWEEN {start_date} AND {yesterday} ')

ad_group_response = ga_service.search_stream(customer_id, query=ad_group_query)

```
I would like to add in `includeZeroImpressions = true`, as I am missing some expected output that has zero impressions with it. 

According to the documentation this can be done, but I'm not sure where I can add it using this Python library's functions: [Documentation](https://developers.google.com/adwords/api/docs/guides/zeroimpression-structure-reports#including_zero_impressions) 

Is this possible with this package?

**Comment by BenRKarl** [comment]
@Clarkbar36 thanks for the question! This library uses the new Google Ads API, which has slightly different functionality than the AdWords API. That documentation you linked to is for the AdWords API and doesn't apply here, but we have a separate set of documentation that explains how the concept of zero impressions works. See [this page](https://developers.google.com/google-ads/api/docs/reporting/zero-impressions).

In sort, search queries should always return campaigns with zero impressions by default. To exclude them you just need to add a filter clause to your query, as shown in that page I linked above.

**Comment by Clarkbar36** [comment]
Thanks for the response. I thought that was the case, but I'm seeing inconsistencies with the data out of the API.  My pull is pulling out the metrics.phone_calls, at the ad_group level. In Google I see: 
![image](https://user-images.githubusercontent.com/29664468/92510411-d01d4d80-f1d9-11ea-9c1f-666be9326225.png)

When I run the same date from the API, with the query from OP, I don't get any data returned. I see this for a few instances with zero impressions. Any idea why those wouldn't be returning?

**Comment by BenRKarl** [comment]
@Clarkbar36 I'm going to reopen this so it doesn't get buried and will take a look as soon as possible. Meanwhile, since this issue doesn't appear to be specific to this library, I'd suggest also posting the question to our API [support forum](https://support.google.com/google-ads/thread/new), or reaching out to our [support team](https://support.google.com/google-ads/gethelp), where we have specialists who can also look into the problem and help.

**Comment by BenRKarl** [comment]
@Clarkbar36 were you able to get any help from the support forum or support team? Since this issue isn't specific to this library I'm going to close this - sorry for the back and forth.
