### ISSUE TITLE
Google Ads API - UserListService in Python

### ISSUE THREAD

**Issue by SarojaRaghunath** [googleads/google-ads-python#309]
This is regarding the Python code structure on implementing the user list (UserListService) using Google Ads API

Sample JSON structure of rule_based_user_list in Adwords API:
{'rule_based_user_list':{"prepopulation_status":"REQUESTED", "expression_rule_user_list":{"rule":{"rule_type":"OR_OF_ANDS", "rule_item_groups"**:[{"rule_items":[{"name":"url__", "string_rule_item":{"operator":"CONTAINS", "value":"abc.com"}}]**}]}}}}

Code snippet of Google Ads API:
userlist_service = client.get_service('UserListService', version=googleads_version)
userlist_operation = client.get_type('UserListOperation', version=googleads_version)
userlist_rule = userlist_operation.create

_# basic details_
userlist_rule.name.value = 'Website audience created via API'
userlist_rule.description.value = "Description"
userlist_rule.membership_life_span.value = 30
userlist_rule.membership_status = client.get_type('UserListMembershipStatusEnum', version=googleads_version).OPEN
userlist_rule.eligible_for_search.value = True
userlist_rule.eligible_for_display.value = True

_# rule_based_user_list setup_ 
userlist_rule.rule_based_user_list.prepopulation_status = client.get_type('UserListPrepopulationStatusEnum', version=googleads_version).REQUESTED
userlist_rule.rule_based_user_list.expression_rule_user_list.rule.rule_type = client.get_type('UserListRuleTypeEnum', version=googleads_version).OR_OF_ANDS

_# rule_item_groups_
rule_item_group = client.get_type("UserListRuleItemGroupInfo", version=googleads_version)
userlist_rule.rule_based_user_list.expression_rule_user_list.rule.rule_item_groups.extend([rule_item_group])

_# rule_items_
rule_item = client.get_type("UserListRuleItemInfo", version=googleads_version)
rule_item.name.value = "url__"

_#string_rule_item_
string_rule_item = client.get_type("UserListStringRuleItemInfo", version=googleads_version)
string_rule_item.operator = client.get_type('UserListStringRuleItemOperatorEnum', version=googleads_version).CONTAINS
string_rule_item.value.value = "abc.com"

How to **combine string_rule_item with rule_item to form rule_item_groups**? Please share the sample code in Python for better clarity. We are not able to proceed further on this implementation.

Thanks.

**Comment by BenRKarl** [comment]
Hi @SarojaRaghunath 

You can modify the `rule_item` directly to include the `string_rule_item` information. From there you need to add it onto a `UserListRuleItemGroupInfo` object, which you then add into the list of rule item groups on the rule itself. I've written out the steps in the below example:

```py
...
# modify the rule item directly to make it a string rule item
rule_item = client.get_type("UserListRuleItemInfo")
rule_item.name.value = "url__"
rule_item.string_rule_item.operator = client.enums.UserListStringRuleItemOperatorEnum.CONTAINS
rule_item.string_rule_item.value = "abc.com"

# append the rule item to a group
group = client.get_type("UserListRuleItemGroupInfo")
group.rule_items.append(rule_item)

# append the group onto the user list rule
userlist_rule.rule_based_user_list.expression_rule_user_list.rule.rule_item_groups.append(group)
```

Let me know if you have any other questions!
