### ISSUE TITLE
Response to issues #29 and #30

### ISSUE THREAD

**Issue by apurvis** [googleads/google-ads-python#31]
Google's github policies forbid me to respond to issues, so I'm opening a new issue to respond to @BenRKarl's [response to my ticket](https://github.com/googleads/google-ads-python/issues/29#issuecomment-459407078)

@BenRKarl - 
1. when are these fixes going to be released? 
1. why wasn't it ready to go when a breaking change to the API was released?

I thought this was the **official** client library. We have a large amount of adwords spend dependent on this library working; to suddenly break the world like this without having an official client library ready seems like borderline technological malpractice.

**Comment by wihl** [comment]
I'm sorry for the interruption. Two things to be aware of:

1. The Google Ads API is currently in beta. It is not recommended that you use it for production purposes. We are not guaranteeing any uptime during this beta phase. It may not be able handle large loads in the current state.
2. The client libraries are released 48 hours after the API is updated. With the new API, this time should be shorter and more consistent than AdWords API client library releases.

The new client library should be released by tomorrow, 5PM ET at the latest. Likely, it will be earlier.

Thanks for your consideration.

**Comment by BenRKarl** [comment]
Following up on this thread - version 0.7.0 has been released and should address your issues @apurvis.

And to expand on @wihl's point - once the API is out of beta, breaking changes won't be introduced when new versions are released. The client libraries will remain stable and non-backwards-compatible changes will be released on major version boundaries.
