### ISSUE TITLE
How could I set bidding strategy to MANUAL_CPC without `enhanced_cpc_enabled `

### ISSUE THREAD

**Issue by Rukeith** [googleads/google-ads-python#315]
Here is my example

```
def main(client, customer_id, campaign_id):
    campaign_service = client.get_service("CampaignService", version="v5")
    # Create campaign operation.
    campaign_operation = client.get_type("CampaignOperation", version="v5")
    campaign = campaign_operation.update
    campaign.resource_name = campaign_service.campaign_path(
        customer_id, campaign_id
    )
    campaign.status = client.get_type("CampaignStatusEnum", version="v5").PAUSED
    campaign.manual_cpc.enhanced_cpc_enabled = False
    fm = protobuf_helpers.field_mask(None, campaign)
    campaign_operation.update_mask.CopyFrom(fm)

    # Update the campaign.
    try:
        campaign_response = campaign_service.mutate_campaigns(
            customer_id, [campaign_operation]
        )
    except google.ads.google_ads.errors.GoogleAdsException as ex:
        print(
            'Request with ID "%s" failed with status "%s" and includes the '
            "following errors:" % (ex.request_id, ex.error.code().name)
        )
        for error in ex.failure.errors:
            print('\tError with message "%s".' % error.message)
            if error.location: 
                for field_path_element in error.location.field_path_elements:
                    print("\t\tOn field: %s" % field_path_element.field_name)
        sys.exit(1)

    print("Updated campaign %s." % campaign_response.results[0].resource_name)
```

I am trying to set the bidding strategy to Manual CPC, but it doesn't work. How could I make it correct?

**Comment by Rukeith** [comment]
@BenRKarl It's not working
I found an article [https://developers.google.com/google-ads/api/docs/hotel-ads/bidding/assign-strategies#assign-strategy](url)
But it only has Java example

**Comment by BenRKarl** [comment]
Hi @Rukeith could you add some more detail about the error you're getting? You want to use `manual_cpc` as the bidding strategy for a `campaign`, and in the above example you're doing that with:

```py
campaign.manual_cpc.enhanced_cpc_enabled = False
```

Do you get the results you're looking for if you set it to `True`?

**Comment by Rukeith** [comment]
Hi @BenRKarl 
Here is the screenshot, which the result I expect.
If I set `campaign.manual_cpc.enhanced_cpc_enabled = True`. The checkbox will be enabled, but I only want to use manual CPC. The code works fine, I won't get any error. It just cannot change the bidding strategy which I expect

![截圖 2020-09-06 10 34 08](https://user-images.githubusercontent.com/7069605/94160767-8f028a00-feb7-11ea-8962-180cca901789.png)

**Comment by BenRKarl** [comment]
@Rukeith when updating the campaign and setting the `manual_cpc` field, does it help to do the following, as in the [documentation](https://developers.google.com/google-ads/api/docs/client-libs/python/empty-message-fields) I shared earlier:

```py
campaign.manual_cpc.CopyFrom(client.get_type("ManualCpc", version="v5"))
```

That should allow you to turn on `manual_cpc` without `enhanced_cpc_enabled`.

**Comment by Rukeith** [comment]
@BenRKarl I have tried it. It still not work ="=

**Comment by Rukeith** [comment]
@BenRKarl do you have any further information?

**Comment by BenRKarl** [comment]
Hi @Rukeith sorry for my delayed response! The interface for empty messages like `ManualCpc` is quite clumsy in Python. One thing I noticed in your request in the `update_mask`, which is a field that tells the API which fields are being mutated, `manual_cpc` is missing. Does it help if you manually insert this field, like this:

```py
fm = protobuf_helpers.field_mask(None, campaign)
fm.paths.append("manual_cpc")
campaign_operation.update_mask.CopyFrom(fm)
```

**Comment by Rukeith** [comment]
@BenRKarl 

I got the error like this

```
Request made: ClientCustomerId: 5909684848, Host: googleads.googleapis.com:443, Method: /google.ads.googleads.v5.services.CampaignService/MutateCampaigns, RequestId: 6Va4tN_-69H-lJ5lW-wR8A, IsFault: True, FaultMessage: The field cannot be cleared.
Request with ID "6Va4tN_-69H-lJ5lW-wR8A" failed with status "INVALID_ARGUMENT" and includes the following errors:
	Error with message "The field cannot be cleared.".
		On field: operations
		On field: update
		On field: manual_cpc
```

**Comment by BenRKarl** [comment]
@Rukeith taking a step back - you want to use `ManualCpc` but without enhanced cpc. Going back to your very first example where you set `campaign.manual_cpc.enhanced_cpc_enabled = False` does it work if you _also_ manually add that field to the field_mask, like this:

```py
fm = protobuf_helpers.field_mask(None, campaign)
fm.paths.append("manual_cpc.enhanced_cpc_enabled")
campaign_operation.update_mask.CopyFrom(fm)
```

**Comment by Rukeith** [comment]
@BenRKarl Thanks, it works.
