### ISSUE TITLE
Google Ads Api Docs are down

### ISSUE THREAD

**Issue by amaurymercier** [googleads/google-ads-python#322]
Hello, the google ads api developer documentation (https://developers.google.com/google-ads/api/docs/) has been down for several days now.

Is there any update on this ?

Thanks a lot

**Comment by Just1B** [comment]
It's not down, just disable your add blocker 😉

**Comment by davedavis** [comment]
Hi Amy.
Not down for me. Unblock origin default blocking lists actually block the developer docs site(s). Try disabling it and it should work?
