### ISSUE TITLE
change portfolio troas goal in shopping campaign

### ISSUE THREAD

**Issue by stacey2021** [googleads/google-ads-python#324]
Hey guys, 
i try to change the troas goal under portfolio troas bidding strategy, but couldn't do it successfully. i can make the troas goal change by running the python file in the normal troas bidding campaign. but for a campaign under the portfolio troas bidding, when i run my code, the troas goal can be changed but it also moves out of the portfolio bidding. May i ask if there is a way to make the portfolio troas goal change? thank you!
Stacey

**Comment by BenRKarl** [comment]
@stacey2021 could you add some more details, such as which file are you modifying (i.e. is it one of our examples?), and what errors do you receive?

**Comment by BenRKarl** [comment]
Closing this issue as stale, but please reopen if needed.
