### ISSUE TITLE
Keyword Planning Service - 429 Resource Exhausted grpc error

### ISSUE THREAD

**Issue by barney-mcmahon-jet2** [googleads/google-ads-python#327]
Hi, 

I am creating a number of keyword plans within the planning service however I am getting a RESOURCE_EXHAUSTED error (which also shows up as a 429 Resource Exhausted grpc error in addition to the API exception) after around 2000-3000 mutate operations. 

I cannot then run any further mutate operations that day, implying that it's not a QPS limit that I am exceeding, and the API Metrics in the GCP console do not indicate that I have exceeded any of the quota limits stated here: https://developers.google.com/google-ads/api/docs/best-practices/quotas. 

Please could someone advise what is causing this error?

Thanks,

Barney

**Comment by wihl** [comment]
no response in 20 days. Closing the bug. Reopen if necessary.

**Comment by varunsingh3640** [comment]
Hi , I am Also Facing the same issue
