### ISSUE TITLE
get_campaign_criterion_bid_modifier_simulations.py not providing query results

### ISSUE THREAD

**Issue by kgawl** [googleads/google-ads-python#329]
Hi,

I am trying to use the get_campaign_criterion_bid_modifier_simulations.py script but cannot get it to provide me with results. When I provide the customer id and the associated campaign id from get_campaigns.py no results are returned. The code says those are the only values I need to get a result so I am not sure why nothing comes back. 

What I am running for get_campaigns.py (returns a list of valid results (# signs to redact customer and campaign info)):
python get_campaigns.py -c ####

[Campaigns log.txt](https://github.com/googleads/google-ads-python/files/5430438/Campaigns.log.txt)

What I am running for get_campaign_criterion_bid_modifier_simulations.py (returns no results):
python get_campaign_criterion_bid_modifier_simulations.py -c #### -i ###

[attempt get_campaign_criterion_bid_modifier_simulations log.txt](https://github.com/googleads/google-ads-python/files/5430463/attempt.get_campaign_criterion_bid_modifier_simulations.log.txt)

Any advice on this would be greatly appreciated!

**Comment by BenRKarl** [comment]
@kgawl Campaigns need to meet a specific set of prerequisites before they can generate simulations, take a look at the documentation [here](https://developers.google.com/google-ads/api/docs/bid-simulations/prerequisites?hl=en).

I recommend reaching out to the  [support forum](https://support.google.com/google-ads/thread/new), or [support team](https://support.google.com/google-ads/gethelp), if you have further questions. They're a better resource for general API questions.
