### ISSUE TITLE
"message": " Version v2 is deprecated. Requests to this version will be blocked."

### ISSUE THREAD

**Issue by RahulGosavi94** [googleads/google-ads-python#332]
My databricks notebook is failing with following error while reading data through Google API: 

Failure:
Message: Status(StatusCode=InvalidArgument, Detail="Request contains an invalid argument.")
Failure: { "errors": [ { "errorCode": { "requestError": "UNKNOWN" }, "message": " Version v2 is deprecated. Requests to this version will be blocked." } ] }

Previously my notebook was working fine but since last 3 days it is failing with above error. Can someone please help me on this case?

**Comment by BenRKarl** [comment]
Hi @RahulGosavi94 - per our developer blog (see [this post](https://ads-developers.googleblog.com/2020/08/google-ads-api-v2-sunset-reminder.html)) `v2` has been deprecated. You'll want to upgrade your application to use `v3` or above.

**Comment by RahulGosavi94** [comment]
Thank you Ben. It's working for me now
