### ISSUE TITLE
"v6" does not exist

### ISSUE THREAD

**Issue by hyemink73** [googleads/google-ads-python#337]
Hi
I am constantly getting the following server errors when trying to send requests using the v6 API (the latest sample code).

ValueError: Specified Google Ads API version "v6" does not exist. Valid API versions are: "v5", "v4", "v3", "v2"

any suggestion to resolve the issue?

**Comment by wihl** [comment]
Are you running the latest version of the client library?

**Comment by hyemink73** [comment]
Hi wihl.
Yes, I've downloaded the latest version of zip file and ran the following command : 
pip install google-ads

but still getting the version error :(

**Comment by hyemink73** [comment]
resolved it with this command :
pip install --upgrade google-ads
