### ISSUE TITLE
MutateOperation doesn't allow update final_urls

### ISSUE THREAD

**Issue by estevopaz** [googleads/google-ads-python#347]
When we try update final_urls:
- mutate() raise "Field 'ad.final_urls' cannot be modified by 'UPDATE' operation."
- mutate_ads() allow it, but it doesn't provide partial_failure attribute

This blocks completely our integration, which is already in testing status.
It would be very very appreciate, set an high priority to this problem.

Don't hesitate ask me for more details or whatever to help with this task.

**Comment by estevopaz** [comment]
Another problematic restriction is that mutate_ads() doesn't allow update PAUSED AdGroups:
```
error_code { ad_error: UPDATING_AD_WITH_NO_ENABLED_ASSOCIATION }
message: "The ad is not associated with any enabled AdGroupAd, and cannot be updated."
```

**Comment by estevopaz** [comment]
This problem is becoming very problematic in our business,
we are raising the limit of elements in the AdGroup for many advertisers.
Any update?

**Comment by BenRKarl** [comment]
@estevopaz can you add some detail about which service you're using? Is it `AdService` or `AdGroupAdService`? Ads are only mutable via an `AdGroupAd` so that might be the issue if you're using `AdService`

**Comment by BenRKarl** [comment]
@estevopaz Sorry I had that backwards - your options are to use `AdService.MutateAds`, which doesn't support partial failure, or to use `GoogleAdsService.Mutate` with partial failure set to false.

It seems asymmetrical for MutateAds not to support partial failure. I'm going to see if I can determine why that's the case and will get back to you.

**Comment by estevopaz** [comment]
The problem is one method supports partial failure but not update and vice-versa.
And we need a method that supports partial failure and updates the Final URLs at the same time.

**Comment by estevopaz** [comment]
Just to simplify, the ideal behavior for our business, would be just to allow updating the Final URLs through `GoogleAdsService.Mutate` service.
Currently, we are forced to pause the previous Ad and create a new one.

**Comment by BenRKarl** [comment]
Thanks @estevopaz I'm looking into why partial failure isn't compatible with the Ad resource in either method.

What's the behavior you get when you try to use `GoogleAdsService.Mutate` with an Ad operation and partial failure set to True, do you get an error back?

**Comment by estevopaz** [comment]
Raise an error when you try to update the Final  URLs which forces you to pause and create a new Ad.
In fact, I guess it prevents any attribute update.

**Comment by BenRKarl** [comment]
So it prevents you from making any mutations in the request, even to non-Ad resources? Just wondering if the entire request is rejected or just the Ad mutations.

**Comment by estevopaz** [comment]
If you want, you can pass me a list of mutations to test.
Currently, we don't have problems with mutation of:
- `ad_group.status`
- `ad_group_criterion.status`

**Comment by BenRKarl** [comment]
For example, if you pass a single request with two operations, one that mutates an AdGroup.status field, and a second that mutates an Ad.final_urls field, with partial failure set to True - does the whole request fail or does just the Ad.final_urls mutate operation fail, while the AdGroup.status operation succeeds?

**Comment by estevopaz** [comment]
Yes, partial failure works fine, the problem is the behavior incoherence preventing mutate final_urls.

**Comment by BenRKarl** [comment]
Ah ok so you do receive a partial error response saying that Ads.final_urls can't be updated, is that right? Just making sure I totally understand so I can try to get a more sensible behavior implemented.

**Comment by estevopaz** [comment]
Yes, exactly, thank you very much for your attention ;)

**Comment by BenRKarl** [comment]
@estevopaz I believe this may have been fixed by now, can you confirm whether you're able to update `final_urls` currently?

**Comment by BenRKarl** [comment]
Closing this since it's gone stale, but please reopen if this issue persists.
