### ISSUE TITLE
Call-only Ads created as Old version

### ISSUE THREAD

**Issue by bertorres** [googleads/google-ads-python#362]
I'm creating Call-Only Ads through Google Ads API and the Ads are being created as an older version because in order to validate an Ad I have to go into the Ad and click on "SAVE NEW VERSION" button.
I'm using Google Ads 8.0 python library.

Service used: google.ads.google_ads.v6.GoogleAdsServiceClient.mutate
operations example:
```
[ad_group_ad_operation {
  create {
    status: ENABLED
    ad {
      type: CALL_ONLY_AD
      call_only_ad {
        country_code: "US"
        phone_number: "(201) 555-0000"
        business_name: "My business"
        description1: "Call us - Mustang"
        description2: "Mustang - Call us pls."
        phone_number_verification_url: "https://www.mybusiness.com"
      }
      display_url: "www.mybusiness.com"
    }
    ad_group: "customers/111111111/adGroups/2222222222"
  }
}]
```

**Comment by BenRKarl** [comment]
@bertorres thanks for pointing this out. This doesn't appear to be related to this library specifically, would you please reach out to our  [support forum](https://support.google.com/google-ads/thread/new), or [support team](https://support.google.com/google-ads/gethelp), where we have specialists who focus on more general API issues.
