### ISSUE TITLE
GRPC error: "Channel deallocated!"

### ISSUE THREAD

**Issue by Gigioliva** [googleads/google-ads-python#366]
When I try to run multiple search_streams on multiple threads I get this error:
```
Headers: {}
Fault: {
  "created": "@1610532108.079202000",
  "description": "Error received from peer ipv4:142.250.180.106:443",
  "file": "src/core/lib/surface/call.cc",
  "file_line": 1063,
  "grpc_message": "Channel deallocated!",
  "grpc_status": 1
}
```
Do you know what the problem is?

------------
`google-ads = 8.1.0`
`grpcio = 1.34.0`

**Comment by smkacper** [comment]
I am having the exact same issue even without multi-threading. I am simply executing search_stream for different accounts, one after another, and every single one fails with this error.

`google-ads==8.2.0`
`grpcio==1.35.0`

**Comment by BenRKarl** [comment]
This is likely due to the issue described in #384 - I'm going to close, but please reopen if you're able to reproduce the error with the grpc client and iterator in the same function scope.
