### ISSUE TITLE
LIKE operator in where clause not working as expected

### ISSUE THREAD

**Issue by stijnvanlieshout** [googleads/google-ads-python#367]
Python: 3.7
API version: v6
Google ads library version: 8.1.0

The following call returns the expected `abc` campaign: 

```
query = (
  """
    SELECT
        campaign.name,
        metrics.clicks
    FROM campaign
        WHERE campaign.name = 'abc' 
  """
)

ga_service = client.get_service('GoogleAdsService', version='v6')
response = ga_service.search(customer_id, query)

for row in response:
    print(row) # Logs row for abc campaign
```

But when I swap the `=` where clause above for the `LIKE` clause below I get no results back (whereas I expect the `abc` campaign to be returned since it contains "a"):

```
...
    WHERE campaign.name LIKE 'a' 
```

The like operator **does** return the `abc` campaign in exact match:

```
...
    WHERE campaign.name LIKE 'abc' 
```

I also tried CONTAINS and REGEXP_MATCH without success. How can I fetch campaigns with contains string filtering?

**Comment by davedavis** [comment]
Try using %

```
WHERE segments.date BETWEEN {date_range}
                AND campaign.name LIKE '%abc%' 
```

**Comment by stijnvanlieshout** [comment]
Awesome, that fixed it. Thanks @davedavis!

**Comment by BenRKarl** [comment]
Thank you, @davedavis!
