### ISSUE TITLE
search_stream response grpc failure - "assertion failed: pthread_mutex_lock(mu) == 0"

### ISSUE THREAD

**Issue by totalhack** [googleads/google-ads-python#369]
Version: google-ads==8.1.0
OS: Both Mac OS 10.14 and an Ubuntu image in docker.
Python 3.7.9

I'm running a simple query to get `customer` records. The first (and only) record returns fine when looping over the response, but resp.next() hangs on the second iteration and then fails with the error below. 

Rough outline of how I'm iterating:

```python
        resp = service.search_stream(customer_id, myquery)
        data = []
        for batch in resp:
            for row in batch.results:
                data.append(custom_func(row))
```

Example error stepping through code, same thing happens when just letting it loop:

```
(Pdb) resp.next()
E0116 10:02:43.142981000 4558001600 metadata.cc:253]                   WARNING: 1 metadata elements were leaked
E0116 10:02:43.143255000 4558001600 metadata.cc:260]                   mdelem 'user-agent' = 'grpc-python/1.34.1 grpc-c/14.0.0 (osx; chttp2)'
E0116 10:02:43.143288000 4558001600 metadata.cc:253]                   WARNING: 1 metadata elements were leaked
E0116 10:02:43.143310000 4558001600 metadata.cc:260]                   mdelem ':authority' = 'googleads.googleapis.com:443'
E0116 10:02:43.143330000 4558001600 metadata.cc:253]                   WARNING: 1 metadata elements were leaked
E0116 10:02:43.143348000 4558001600 metadata.cc:260]                   mdelem 'request-id' = 'Fy0yCC-kgfA1M_eRM54bng'
E0116 10:02:43.143471000 4558001600 metadata.cc:253]                   WARNING: 1 metadata elements were leaked
E0116 10:02:43.143696000 4558001600 metadata.cc:260]                   mdelem 'alt-svc' = 'h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"'
E0116 10:02:43.144288000 4558001600 metadata.cc:253]                   WARNING: 1 metadata elements were leaked
E0116 10:02:43.144310000 4558001600 metadata.cc:260]                   mdelem 'content-disposition' = 'attachment'
E0116 10:02:43.144568000 4558001600 sync_posix.cc:67]                  assertion failed: pthread_mutex_lock(mu) == 0
```

This does not happen and my code works fine when switching to a regular `search` based approach.

**Comment by BenRKarl** [comment]
@totalhack In issue #384 we realized that the stream will get closed if the response iterator is in a separate function scope from the service client, and I wonder if the same thing is happened when you pass `row` to `custom_func`. Can you confirm whether keeping `row` in the same scope as the other objects helps the problem?

**Comment by BenRKarl** [comment]
Closing this as the scope issue described in #384 is the likely cause, but please reopen if this is reproducible with the grpc client and iterator in the same scope.

**Comment by saber-solooki** [comment]
I get the same error again when I initialize the service client in a different method and process the response in a separate method
google-ads==18.0.0
Python 3.9.9
OS: Mac os 12.4

```
customer_api_response = _get_customer() # initialize googleads_client and request by search_stream method
_process_customer_response(customer_api_response). # iterate over response
```
Iterate over response like described [here](https://developers.google.com/google-ads/api/docs/reporting/streaming)
