### ISSUE TITLE
How could I update campaign bidding strategy with standard bidding strategies

### ISSUE THREAD

**Issue by Rukeith** [googleads/google-ads-python#372]
I found this document [link](https://developers.google.com/google-ads/api/docs/campaigns/bidding/assign-strategies#standard_bidding_strategies).

Standard bidding strategies don't have python example.
How could I update the campaign bidding strategy with standard bidding strategies?

**Comment by BenRKarl** [comment]
@Rukeith Here's the [Python example](https://github.com/googleads/google-ads-python/blob/master/examples/shopping_ads/add_shopping_smart_ad.py), it's just not included in that set of docs. I'll see if we can get it added in. Thanks for pointing this out.

**Comment by Rukeith** [comment]
Hi @BenRKarl thank you provide me this.
But how could I update bidding_strategy to `MAXIMIZE_CONVERSION_VALUE`  without target_roas?

Which like this.
![截圖 2021-02-25 13 27 22](https://user-images.githubusercontent.com/7069605/109107720-3472a000-776d-11eb-806c-6114cbc1474c.png)

**Comment by Rukeith** [comment]
Sorry @BenRKarl 
Do you have any advice?
