### ISSUE TITLE
How to access summary row in search results

### ISSUE THREAD

**Issue by ddoskind** [googleads/google-ads-python#374]
I'm sorry if this is documented somewhere, but I wasn't able to find any information on it.

Both `GoogleAdsServiceClient.search()` and `GoogleAdsServiceClient.search_stream()` take an optional argument `summary_row_setting` which can be used to include a summary row in the response via `SearchGoogleAdsResponse.summary_row`.

However, both search methods return a `GRPCIterator` which as far as I can see doesn't expose that field—it only allows for iterating over `SearchGoogleAdsResponse.results`.

Is there a canonical way to access the summary row?

**Comment by ddoskind** [comment]
I realized the above only applies for `GoogleAdsServiceClient.search()`. In the `GoogleAdsServiceClient.search_stream()`, the last `SearchGoogleAdsStreamResponse` returned will have a populated `summary_row` attribute that contains the aggregated values.

We can just use `search_stream()` instead of `search()`, so it's not a problem if it's not possible to access the summary row using the latter method. Ticket can be closed if that's intended behavior.

**Comment by BenRKarl** [comment]
Hi @ddoskind - unfortunately this is not yet possible in both cases. It's been an issue for some time and we're actively working on a solution. You can track the initial issue here: https://github.com/googleads/google-ads-python/issues/111

**Comment by ddoskind** [comment]
@BenRKarl Just to clarify, I was able to retrieve the summary row with the following code:
````python
client = ads_client.GoogleAdsClient(credentials, DEV_TOKEN, login_customer_id=MCC_ID)
service = client.get_service('GoogleAdsService')

query = """
        SELECT campaign.id, campaign.name, metrics.clicks, metrics.impressions
        FROM campaign
        ORDER BY campaign.id"""

setting = client.get_type('SummaryRowSettingEnum').SummaryRowSetting.SUMMARY_ROW_WITH_RESULTS
# Issues a search request using streaming.
response = service.search_stream(CLIENT_ID, query=query, summary_row_setting=setting)

for batch in response:
    summary_row = batch.summary_row
    for row in batch.results:
        print(
            f"Campaign with ID {row.campaign.id} and name "
            f'"{row.campaign.name}" was found with {row.metrics.impressions} '
            f'impressions and {row.metrics.clicks} clicks'
        )
print(
    f'Total {summary_row.metrics.impressions} impressions and '
    f'{summary_row.metrics.clicks} clicks'
)
````

So it seems it's possible when using the `search_stream` interface. Or am I misunderstanding?

**Comment by BenRKarl** [comment]
@ddoskind You're right, in that example `batch` is an instance of `SearchGoogleAdsStreamResponse` so it should contain all the fields defined on its [proto](https://github.com/googleapis/googleapis/blob/master/google/ads/googleads/v6/services/google_ads_service.proto#L353)

**Comment by sfontana** [comment]
@ddoskind Here's what works for me (version 10.0.0):

```python
service = client.get_service('GoogleAdsService')
search_request = client.get_type('SearchGoogleAdsStreamRequest')

search_request.customer_id = customer_id
search_request.query = query
search_request.summary_row_setting = summary_row_setting.value

response = service.search_stream(search_request)
```

where `summary_row_setting.value` is one of [these enums](https://github.com/googleads/google-ads-python/blob/6c242d341fe9b4764a4377807d698ccc8a7aef74/google/ads/googleads/v6/enums/types/summary_row_setting.py#L31): 

```python

	class SummaryRowSettingEnum(proto.Message):
    r"""Indicates summary row setting in request parameter."""

	  class SummaryRowSetting(proto.Enum):
	      r"""Enum describing return summary row settings."""
	      UNSPECIFIED = 0
	      UNKNOWN = 1
	      NO_SUMMARY_ROW = 2
	      SUMMARY_ROW_WITH_RESULTS = 3
	      SUMMARY_ROW_ONLY = 4
```


[This example](https://github.com/googleads/google-ads-python/blob/e44a050b7f737e31d4417785ea9e4462818450d7/examples/reporting/get_keyword_stats.py#L51) helped me and it seems to be the canonical way of setting the summary row flag.

I can confirm that the summary row can be found in the last response of the batch.

**Comment by BenRKarl** [comment]
@sfontana that's exactly right, thanks for sharing.

There's more details about request objects in the [migration guide](https://developers.google.com/google-ads/api/docs/client-libs/python/library-version-10#request_objects) for version 10.0.0 of this library.
