### ISSUE TITLE
No Call Metrics Call Details Report Equivalent?

### ISSUE THREAD

**Issue by totalhack** [googleads/google-ads-python#375]
Hi,

I've looked through your examples and the v6 [docs](https://developers.google.com/google-ads/api/fields/v6/overview), but I don't see an equivalent way to produce the [Call Metrics Call Details Report](https://developers.google.com/adwords/api/docs/appendix/reports/call-metrics-call-details-report). That report is critical to any business that relies on phone calls.

Is there perhaps an undocumented way to get those attributes in a report? Is my only option to use the v201809 Google Adwords API? 

Thanks for your help.

**Comment by totalhack** [comment]
Hey there, I just wanted to check in on this and see if I could at least get insight into your plans and timeline.

I've currently worked around the issue by doing an integration with v201809, but it's not ideal. Outside of having the manage the other API integration, the call detail report provides less granularity than what is available in the Google Ads UI. Namely, the call detail report only gives you the users area code (instead of the full caller ID), and it only reports at the ad group level vs the keyword level in the UI. 

Are there plans to provide call reporting via the Ads API that is equivalent to what can be done in the UI? This is sorely needed for proper call attribution and offline conversion uploads. Thanks.

**Comment by BenRKarl** [comment]
@totalhack - apologies for the delayed response. This issue tracker is intended only for issues with this client library, for more general API issues like migrating reports I recommend reaching out to the [support forum](https://support.google.com/google-ads/thread/new), or our [support team](https://support.google.com/google-ads/gethelp). They're better equipped to answer questions like this.
