### ISSUE TITLE
Keyword plan ad group keyword : max length ?

### ISSUE THREAD

**Issue by Just1B** [googleads/google-ads-python#376]
Hello 👋

I use the Google Ads Api to collect some keywords_ideas every month.

Sometime, from a call to another, keywords are not proposed any more.

To feed the discrepancies, the historical metric is fine : https://developers.google.com/google-ads/api/docs/keyword-planning/generate-historical-metrics

But, recently , i got some errors :

- **KEYWORD_HAS_TOO_MANY_WORDS** for _paco rabanne pure xs for her eau de parfum 80 ml_ ( seed : ['Paco Rabanne'] )

- **KEYWORD_TEXT_TOO_LONG** for _land rover range rover sport svr 2017 land rover range rover sport 5.0 l v8 supercharged svr_ ( seed : ['SVR', 'Labo SVR', 'Laboratoire SVR'] )

Didn't find the response in the protos : https://github.com/googleads/google-ads-python/blob/master/google/ads/google_ads/v6/proto/errors/keyword_plan_ad_group_keyword_error_pb2.py

So, my question is : **what is the maximum length for a keyword in a keyword plan.**

Thanks

**Comment by BenRKarl** [comment]
@Just1B - I believe the limitations are 10 words and/or 80 characters per keyword. I don't see this documented anywhere, so I'll file a bug for us to add these limitations [here](https://developers.google.com/google-ads/api/docs/best-practices/quotas#planning_services). Please reopen this if you encounter any behavior that contradicts the limits I mentioned above.
