### ISSUE TITLE
get_campaign.py returns nothing

### ISSUE THREAD

**Issue by AFirouzi** [googleads/google-ads-python#381]
Hi everyone,

I am a new user of google ads API and I try to retrieve some data using this python client library.
I already set developer token, client_id, client_secret, and refresh token in the `google-ads.yaml` file.
When I try `python get_campaigns.py --customer_id=<my_customer_id>`, it returns nothing.
Is there anyone else who encountered the same problem?

Thanks for your help!

**Comment by davedavis** [comment]
Hi @AFirouzi 
What do you mean it returns nothing? 
Do you have the login_customer_id set in the yaml file? Is it the parent MCC/MC of the my_customer_id that you passed?

**Comment by AFirouzi** [comment]
Hi @davedavis 
Thanks for the reply.
In `get_campaigns.py` (from the examples) it should print found campaigns. 
   
    ga_service = client.get_service("GoogleAdsService", version="v6")

    query = """
        SELECT campaign.id, campaign.name
        FROM campaign
        ORDER BY campaign.id"""

    # Issues a search request using streaming.
    response = ga_service.search_stream(customer_id, query=query)

    try:
        for batch in response:
            for row in batch.results:
                print(
                    f"Campaign with ID {row.campaign.id} and name "
                    f'"{row.campaign.name}" was found.'
                )

but it prints nothing. 
I didn't set login_customer_id before, but I just did it, and no difference.
About the second question, I am not sure that I understand it correctly but `my_customer_id` is the same as `login_customer_id` .
Which is 10 digits and I found it in google ads itself.

**Comment by davedavis** [comment]
Hi @AFirouzi 
Yes, that needs to be set. But it's not the same as the customer ID. 

The login_customer_id is the ID of the manager account that your customer ID is under. This is the account where you got your API developer token. 

Please note though that you won't be able to access your account unless your developer token was approved or unless your customer ID is a test account.

**Comment by AFirouzi** [comment]
Thanks @davedavis,
It solved my problem.

**Comment by davedavis** [comment]
You're welcome. It's pretty confusing that it's not called Manager Account ID for most people.
