### ISSUE TITLE
v6: New Error: "Enum ChangeEventResourceType has no name defined for value 13"

### ISSUE THREAD

**Issue by mbaader** [googleads/google-ads-python#382]
Hi, 

since last week I keep getting the above mentioned error while performing this code:

    VERSION = 'v6'
    change_resource_type_enum = google_ads_client.get_type(
          'ChangeEventResourceTypeEnum', version=VERSION).ChangeEventResourceType
    client_type_enum = google_ads_client.get_type(
          'ChangeClientTypeEnum', version=VERSION).ChangeClientType
    resource_change_operation_enum = google_ads_client.get_type(
          'ResourceChangeOperationEnum', version=VERSION).ResourceChangeOperation
    query = ('SELECT '
             'change_event.ad_group,'
             'change_event.campaign, '
             'change_event.change_date_time, '
             'change_event.change_resource_type, '
             'change_event.changed_fields, '
             'change_event.client_type, '
             'change_event.resource_change_operation, '
             'change_event.user_email, '
             'change_event.resource_name '
             'FROM change_event {}'
             'ORDER BY change_event.change_date_time '
             'LIMIT {}'.format(time_filter_string, limit)
            )
    response = execute_search(ga_service, str(customer_id), query)
    for batch in response:
      for row in batch.results:
        change_event = row.change_event
        ad_group = change_event.ad_group
        campaign = change_event.campaign
        change_resource_type = change_resource_type_enum.Name(change_event.change_resource_type)

Error: "Enum ChangeEventResourceType has no name defined for value 13"

The issue seems to be that the "ChangeEventResourceType" v6 now (after the 6.1 update) contains 14 enums, while the current v6 version of the google-ads-pyhton library here: /google/ads/google_ads/v6/proto/enums/change_event_resource_type_pb2.py only addresses 9 of them:

 values=[
    _descriptor.EnumValueDescriptor(
      name='UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AD', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AD_GROUP', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AD_GROUP_CRITERION', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CAMPAIGN', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CAMPAIGN_BUDGET', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AD_GROUP_BID_MODIFIER', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CAMPAIGN_CRITERION', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],

So - will this problem be fixed with the library updates this week?

**Comment by arammaliachi** [comment]
@mbaader seems like as part of the newer versions enums have moved from being a dictionary to a list of tuples. In the following shape:

```` 
[
("VALUE_1", "1"),
("VALUE_2", "2"),
("VALUE_3", "3")
]
````

You can create back a dict from this list of tuples as following:
`my_enum_dict = {t[1]: t[0] for t in resource_change_operation_enum}`

Access the response value directly from the newly created dictionary.

**Comment by mbaader** [comment]
Hi @all - after upgrading to the just released [google-ads-python-v.9.0.0](https://github.com/googleads/google-ads-python/releases/tag/9.0.0) this issue no longer exists, since the library now addresses all now 14 ChangeEventResourceType enums correctly.

Cheers

**Comment by BenRKarl** [comment]
@mbaader Sorry I didn't respond and close this issue out sooner. For minor API releases, like 6_1, you might expect to experience issues like this, where the objects client library haven't caught up to those in the API. Normally we will try to update the library within a few days of the API release, this one was slightly later because of the US holiday on Monday.
