### ISSUE TITLE
Incorrect import path in v6 service docstrings

### ISSUE THREAD

**Issue by henribru** [googleads/google-ads-python#389]
There's an incorrect import path in the examples in a number of v6 service docstrings. Here's `CampaignBidModifierServiceClient.get_campaign_bid_modifier` as an example:
```
           >>> from google.ads import googleads_v6
            >>>
            >>> client = googleads_v6.CampaignBidModifierServiceClient()
            >>>
            >>> resource_name = client.campaign_bid_modifier_path('[CUSTOMER_ID]', '[CAMPAIGN_ID]', '[CRITERION_ID]')
            >>>
            >>> response = client.get_campaign_bid_modifier(resource_name)
```
`googleads_v6` doesn't exist, I assume it's meant to be `from google.ads.google_ads import v6` or perhaps `from google.ads.google_ads import v6 as googleads_v6`.

This is also the case in the return type: "A :class:`~google.ads.googleads_v6.types.CampaignBidModifier` instance."

**Comment by BenRKarl** [comment]
@henribru thanks for catching this, we'll get it fixed ASAP.

**Comment by BenRKarl** [comment]
@henribru I may have initially misread this - these incorrect paths are in the docstrings, correct? So they're not generating any errors for you?

**Comment by henribru** [comment]
Correct, it's just incorrect documentation, not a bug.

**Comment by BenRKarl** [comment]
With version 10.0.0 this issue shouldn't be a problem anymore because these files are generated totally differently.
