### ISSUE TITLE
No Planning Examples

### ISSUE THREAD

**Issue by eryk260** [googleads/google-ads-python#39]
Several other libraries (.NET, Java, PHP) have a `planning` example folder covering keyword idea generation and traffic estimation. Is this likely to come to the Python library any time soon?

**Comment by BenRKarl** [comment]
Hi @eryk260! Thanks for posting the question. These examples are indeed planned for this library. Unfortunately I can't predict exactly when they'll be added, but I hope to get them out in the near future.

I'll leave this issue open for now and will close it once the new examples are published.

**Comment by BenRKarl** [comment]
@eryk260 just following up here that these examples are not available, see [here](https://github.com/googleads/google-ads-python/tree/master/examples/planning)
