### ISSUE TITLE
Updating Promotion Extensions, switching between discount_types

### ISSUE THREAD

**Issue by BBalazsJurgen** [googleads/google-ads-python#402]
Hello,
here's an interesting question. I can update an existing promotion extension no problem IF either:
- The discount_type fields (percent_off, money_amount_off: currency_code, amount_micros) are not modified
- If the update does NOT switch between percent_off and money_amount_off.

However, how would one update a promotion extension to switch say, from percent_off to money_amount_off?
Simply setting currency_code and amount_micros does not work, we get an invalid argument error:
`"Request contains an invalid argument."`
This is logical, because ONLY ONE of percent_off or money_amount_off can be set, and this would result in both fields being set.

Thus, the original setting (in this case, percent_off) should be unset somehow. But how would you go about this? Simply doing:
`extension_feed_item.promotion_feed_item.percent_off = None`
does not work, you obviously get a:
`None has type <class 'NoneType'>, but expected one of: (<class 'int'>,)`
error.

So, how would you go about updating a promotion extension to switch from percent_off to money_amount_off in an update operation? (or should you go for the evil workaround of removing extension and creating a brand new, barely different one?)

**Comment by wihl** [comment]
Discussion was moved to the [forum](https://groups.google.com/g/adwords-api/c/0_sIZPhhyyA/m/eoqK43JZDAAJ)
