### ISSUE TITLE
Your YAML file is incorrectly configured for OAuth2

### ISSUE THREAD

**Issue by hondy12345** [googleads/google-ads-python#403]
I was processed "OAuth Desktop Application Flow"(https://developers.google.com/google-ads/api/docs/client-libs/python/oauth-desktop)
and “Installation”(https://developers.google.com/google-ads/api/docs/client-libs/python/installation).
And I wrote client_id, client_secret and refresh_token on ~/google-ads.yaml

But when run `python setup.py test`, error occured.
Do you know the cause of this?

```error
======================================================================
ERROR: test_load_from_env_versioned (tests.client_test.GoogleAdsClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kazuki/projects/google-ads-python/tests/client_test.py", line 271, in test_load_from_env_versioned
    Client.GoogleAdsClient.load_from_env(version="v4")
  File "/Users/kazuki/projects/google-ads-python/google/ads/googleads/client.py", line 226, in load_from_env
    kwargs = cls._get_client_kwargs(config_data)
  File "/Users/kazuki/projects/google-ads-python/google/ads/googleads/client.py", line 182, in _get_client_kwargs
    "credentials": oauth2.get_credentials(config_data),
  File "/Users/kazuki/projects/google-ads-python/google/ads/googleads/oauth2.py", line 113, in get_credentials
    raise ValueError(
ValueError: Your YAML file is incorrectly configured for OAuth2. You need to define credentials for either the OAuth2 installed application flow (('client_id', 'client_secret', 'refresh_token')) or service account flow (('json_key_file_path', 'impersonated_email')).

----------------------------------------------------------------------
Ran 158 tests in 7.626s
```

**Comment by wihl** [comment]
Hi, the unit tests (`python setup.py test`) are independent of the `google-ads.yaml` configuration. I confirmed this by putting invalid values in a google-ads.yaml file and then re-trying the unit tests.

A couple of suggestions:

- Did you modify the `client_test.py` file?
- Could you try the latest version from GitHub, which has not yet been released as a new version to PyPi? We have made some [changes](https://github.com/googleads/google-ads-python/commit/b60541920bcc2910b7200948ae5a07db5cad6694) to the unit tests.

Please re-open this issue if problems persist.
