### ISSUE TITLE
DEFAULT_CLIENT_ID Not Defined Error

### ISSUE THREAD

**Issue by samsamph** [googleads/google-ads-python#404]
I'm trying to get the refresh token so I can start working with Google Ads API. However, I am getting this error when I tried to run the generate_refresh_token.py file which I found in this link: https://github.com/googleads/googleads-python-lib/blob/master/examples/adwords/authentication/generate_refresh_token.py

I basically copy the whole code and created a python file on my env. But then when I tried to run it, I am getting this error: 'name DEFAULT_CLIENT_ID not defined.'

I already have a client ID and client secret, which I copy and pasted to the DEFAULT_CLIENT_ID and DEFAULT_CLIENT_SECRET variables of the generate_refresh_token.py file. 

Please help me fix the error. Appreciate your response. Thanks.

**Comment by shailavij** [comment]
Hi Sam,
           Could you please let me know , whether you are working on Google ads Test account or Production account.

I assume that , you have not yet generate your refresher token. Please try to run below code in prompt, it will generate web link.
From that link , Log into the Google Account you use to access your AdWords account and go to the following URL .
It will again create a secret code for you. From there try to paste secret code in your command prompt , this will generate a refresher token for you. Make sure developer token & login customer id in YAML file are correct.
                                                                                                                                                
 Script to run :python generate_refresh_token.py --client_id INSERT_CLIENT_ID --client_secret INSERT_CLIENT_SECRET

Hope this will fix your error.

![image](https://user-images.githubusercontent.com/49098763/114372580-a1a18f80-9b79-11eb-99df-bdeba5fb6d1e.png)

**Comment by BenRKarl** [comment]
@samsamph that file you linked to is for a different library, the old AdWords API client library. If you're using this library, which is for the new Google Ads API, then you will want to use one of the scripts in [this folder](https://github.com/googleads/google-ads-python/tree/master/examples/authentication). The docs for this library live [here](https://developers.google.com/google-ads/api/docs/client-libs/python), which contain the necessary steps to set up authentication. Take a look at those, and reopen this issue if you continue having problems!
