### ISSUE TITLE
How to get all videoAds without beacon? 

### ISSUE THREAD

**Issue by elad2109** [googleads/google-ads-python#414]
I'm not sure what to put in the withCondition to get all such only beaconsless videoAds.

```
var videoAds = AdsApp
                .videoAds()
                .withCondition('????')                    
                .get();
```

I have seen the doc, but wasn't sure what `where clause` could fit.
https://developers.google.com/google-ads/scripts/docs/reference/adsapp/adsapp_ad

**Comment by wihl** [comment]
This a question re: https://developers.google.com/google-ads/scripts

Please follow the directions at https://developers.google.com/google-ads/scripts/community

Closing.
