### ISSUE TITLE
ValueError: A required field in the configuration data was not found. The required fields are: ('developer_token',)

### ISSUE THREAD

**Issue by samsamph** [googleads/google-ads-python#415]
I'm trying to run the keyword stats report (file found here: https://github.com/googleads/google-ads-python/blob/master/examples/reporting/get_keyword_stats.py) via the Google Ads API. I have the googleads.yaml file setup already. But when I run the report, I'm getting an error that says: `ValueError: A required field in the configuration data was not found. The required fields are: ('developer_token',)`

I have all the required fields in the googleads.yaml file. Please see screenshot below for reference. What could have gone wrong in my code? Why is it not reading the 'developer_token' I have in the googleads.yaml file?

![Screen Shot 2021-05-03 at 3 50 17 PM](https://user-images.githubusercontent.com/50799332/116853133-1e2f0780-ac28-11eb-93ef-caed7ad39c97.png)

**Comment by BenRKarl** [comment]
Hi @samsamph - your example indicates you're using the YAML config format from our old [AdWords client library](https://github.com/googleads/googleads-python-lib), this library uses a different format, you can read more about it in the [documentation](https://developers.google.com/google-ads/api/docs/client-libs/python/configuration). Also see the example [here](https://github.com/googleads/google-ads-python/blob/master/google-ads.yaml).
