### ISSUE TITLE
Arguments required error on keyword_stats.py file

### ISSUE THREAD

**Issue by samsamph** [googleads/google-ads-python#416]
I'm running the get_keyword_stats.py [file](https://github.com/googleads/google-ads-python/blob/master/examples/reporting/get_keyword_stats.py) on my env. However, I ran into an error that says: `the following arguments are required:`

I filled in the parser.add_argument section in the code with the account customer ID from my MCC. 

```
# The following argument(s) should be provided to run the example.
    parser.add_argument(
        "-c",
        "--customer_id",
        type=str,
        required=True,
        help="The Google Ads customer ID.",
```

I tried adding the customer ID in the "--customer_id" but it did not go through, I also tried adding it in the "-c", both without dash. However, it also didn't work. Which part here should I put the customer ID and should it have a dash or without?

**Comment by BenRKarl** [comment]
Hi @samsamph - those arguments should be provided via the command line when executing the example, so from your terminal you would run:

```
python get_keyword_stats.py -c <INSERT CUSTOMER ID HERE>
```
