### ISSUE TITLE
Get Daily Keywords Stat Instead of Aggregate Data 

### ISSUE THREAD

**Issue by samsamph** [googleads/google-ads-python#417]
Hi, I ran this [file](https://github.com/googleads/google-ads-python/blob/master/examples/reporting/get_keyword_stats.py) to pull the keyword stats of my account, I was able to successfully download the data. However, it is an aggregate data for the last 7 days. Is there a way for me to get data on a daily basis for the last 7 days instead of the total? Thank you

**Comment by BenRKarl** [comment]
Hi @samsamph - yes, if you add [`segments.day_of_week`](https://developers.google.com/google-ads/api/fields/v7/segments#segments.day_of_week) to the select clause then the response will be broken out by ad group criterion and the day of the week, (i.e. `TUESDAY`). If you want to review some more general information about creating reports I recommend taking a look at our [report documentation](https://developers.google.com/google-ads/api/fields/v7/overview), there's a  list of [other segments](https://developers.google.com/google-ads/api/fields/v7/segments) you can reference, as well as a [query builder](https://developers.google.com/google-ads/api/fields/v7/overview_query_builder) that should be helpful for creating the queries you need.
