### ISSUE TITLE
still having issues with get_campaigns

### ISSUE THREAD

**Issue by hiann983** [googleads/google-ads-python#419]
Hi! I saw lots of same issues that I have with get_campaigns.py
I saw some solutions through issues such as #278 and I also tried `python get_campaign.py -c 1234567890` when I tried to call through terminal but it returns nothing. I also did put the manager account id in google ads yaml file.

What should I do at this point?

Thank you!

**Comment by BenRKarl** [comment]
Hi @hiann983 are you receiving an error when running the example, or just not receiving any results from the API? If the issue is that you're not receiving any results then the account you're using likely doesn't have any campaigns. Try running the [`add_campaigns.py`](https://github.com/googleads/google-ads-python/blob/master/examples/basic_operations/add_campaigns.py) example first

**Comment by hiann983** [comment]
@BenRKarl  Hi! So when I run the code in jupyter, I got the normal issues that ppl have which is `ipykernel_launcher.py: error: the following arguments are required: -c/--customer_id`. I found that I have to put `python get_campaign.py -c 1234567890` in the command line so I put this line in the terminal and I got nothing(let me know if this is not what you mean when you mention that solution to other ppl)

**Comment by BenRKarl** [comment]
@hiann983 It sounds like the issue is that your Client customer account doesn't have any campaigns to return. If you run the [`add_campaigns.py`](https://github.com/googleads/google-ads-python/blob/master/examples/basic_operations/add_campaigns.py) example with your Client customer ID are you able to add a campaign? If so, goes `get_campaigns.py` return different results now that a campaign as been added to the Client customer account?

**Comment by hiann983** [comment]
@BenRKarl so my client customer does have some campaigns since I was able to get them through google adwords api. I just need to get the same campaigns through google ads api with new yaml file

**Comment by BenRKarl** [comment]
@hiann983 without an error message or logs or a stack trace it's hard to identify the issue, are you able to enable logs using [these instructions](https://developers.google.com/google-ads/api/docs/client-libs/python/logging)? If you can retrieve logs please make sure to redact identifying information (like your Client customer ID) before pasting them here.

**Comment by hiann983** [comment]
@BenRKarl I would like to drop what I got below!
![image](https://user-images.githubusercontent.com/83656929/117048509-0356b300-ad4e-11eb-9121-31c84cda6a69.png)
(Like this, nothing returned)
And below is the error traceback that I got when I run get_campaigns
![image](https://user-images.githubusercontent.com/83656929/117048660-326d2480-ad4e-11eb-8662-1e3b3919a5cb.png)

Thank you so much!

**Comment by BenRKarl** [comment]
@hiann983 This looks like nothing is being passed for the `-c` flag. On line 57 at the top I see there's a `print(args.customer_id)` statement does that print anything? Similarly is anything printed if you run `echo $CLIENT_ID` from the environment your notebook is running in? My guess is that the `$CLIENT_ID` environment variable may not be set properly.

**Comment by hiann983** [comment]
@BenRKarl Client id is written in the yaml file and nothing is printed for `print(args.customer_id)`. Do you think I should continue with google adwords api? The only thing that matters with adwords was that when I call ad groups, I always get RateExceededError and it says try after 24 hours

**Comment by hiann983** [comment]
@BenRKarl Just to make clear, I posted everything that I have for now
![image](https://user-images.githubusercontent.com/83656929/117097186-e5b53800-ada5-11eb-9421-badab50fca41.png)
![image](https://user-images.githubusercontent.com/83656929/117097210-f5348100-ada5-11eb-9da6-83c5f9480d47.png)

**Comment by BenRKarl** [comment]
@hiann983 in this client library (as opposed to the old [AdWords client library](https://github.com/googleads/googleads-python-lib)) the client customer ID is not read from configuration. When running `get_campaigns.py` it must be provided as a command line argument.

In your [earlier comment](https://github.com/googleads/google-ads-python/issues/419#issuecomment-832135415) you shared the invocation you're using:

```
python get_campaigns.py -c $CLIENT_ID 2> example.log
```

If you set the `$CLIENT_ID` variable equal to the Client customer ID in your yaml file (for example: `CLIENT_ID=1234567890`) then this should work.

You can also update the example directly it you aren't able to change the execution environment.

First, on line 58 of the example you pasted, make this change:

```py
```

**Comment by hiann983** [comment]
@BenRKarl Hi! one last question: when you are referring to the client customer id, are you talking about 'login_customer_id' in yaml file or the customer account id that are linked to my manager account?

**Comment by BenRKarl** [comment]
I'm referring to the customer account ID that's linked to your manager account. To retrieve that ID, see the `Client customer ID` section in [these docs](https://developers.google.com/google-ads/api/docs/first-call/overview#config).
