### ISSUE TITLE
Authenticate_In_Web_App is seemingly for the desktop flow, not the web application flow

### ISSUE THREAD

**Issue by austincollinpena** [googleads/google-ads-python#422]
https://github.com/googleads/google-ads-python/blob/master/examples/authentication/authenticate_in_web_application.py

The docs here appear also to be for the desktop version:

https://developers.google.com/google-ads/api/docs/client-libs/python/oauth-web

**Comment by BenRKarl** [comment]
Thanks @austincollinpena, you're right, and this is actually already captured in an existing issue (#130), which we're working on currently.
