### ISSUE TITLE
SIGSEGV when using new copy_from method

### ISSUE THREAD

**Issue by alasdair-fowler-deliveroo** [googleads/google-ads-python#424]
**Describe the bug:**
SIGSEGV when using new copy_from method

**Steps to Reproduce:**
Any time the googleads_client.copy_from is called. I tried updating existing code which worked with CopyFrom and ran in to SIGSEGV. I then tried a snippet from [here](https://github.com/googleads/google-ads-python/blob/master/examples/basic_operations/update_campaign.py), to make sure it wasn't my code:

```
import argparse
import logging
import sys

from google.ads.googleads.errors import GoogleAdsException
from google.ads.googleads.client import GoogleAdsClient
from google.api_core import protobuf_helpers

googleads_client = GoogleAdsClient('credentials', 'developer_token')
campaign_service = googleads_client.get_service("CampaignService")

# Create campaign operation.
campaign_operation = googleads_client.get_type("CampaignOperation")
campaign = campaign_operation.update
customer_id = '123456789'
campaign_id = '123456789'
campaign.resource_name = campaign_service.campaign_path(
    customer_id, campaign_id
)

campaign_status_enum = googleads_client.get_type(
    "CampaignStatusEnum"
).CampaignStatus.PAUSED

campaign.network_settings.target_search_network = False
# Retrieve a FieldMask for the fields configured in the campaign.
print("Try using copy_from:\n\n")

googleads_client.copy_from(
    campaign_operation.update_mask,
    protobuf_helpers.field_mask(None, campaign._pb),
)

print(campaign_operation)
```

**Expected behavior:**
Not to get a SIGSEGV

**Screenshots:**
N/A

**Library version and API version:**
Python 3.7.0
API v7 (although not relevant as not related to API requests)
Library 11.0.0
No other non-default libraries

**Request/Response Logs:**
N/A as no requests made

**Additional context:**

**Comment by alasdair-fowler-deliveroo** [comment]
It looks like the copy_from method doesn't work with `None` as an argument, something like the following runs successfully
`googleads_client.copy_from(
    campaign_operation.update_mask,
    protobuf_helpers.field_mask(googleads_client.get_type('Campaign')._pb, campaign._pb),
)`

**Comment by BenRKarl** [comment]
@alasdair-fowler-deliveroo thanks for pointing this out, do you happen to have a stack trace you could share?

**Comment by alasdair-fowler-deliveroo** [comment]
Hi @BenRKarl, I'm afraid all you get is `Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)` as it's not an Exception

**Comment by BenRKarl** [comment]
@alasdair-fowler-deliveroo got it - I'm having trouble reproducing this. You say this happens _every_ time you call `copy_from`? Regardless of what's passed into the method? What versions of this library's [dependencies](https://github.com/googleads/google-ads-python/blob/master/setup.py#L19) are you using?

**Comment by alasdair-fowler-deliveroo** [comment]
It seems to be every time the first argument is None, for example below

```
from google.ads.googleads.client import GoogleAdsClient
from google.api_core import protobuf_helpers

googleads_client = GoogleAdsClient('credentials', 'developer_token')

ad_group_operation = googleads_client.get_type(
    "AdGroupOperation", version='v7'
)
ad_group = ad_group_operation.update

ad_group.resource_name = 'customers/123456789/adGroups/123456789'

googleads_client.copy_from(
    ad_group_operation.update_mask,
    protobuf_helpers.field_mask(None, ad_group._pb),
)
```

Just checking dependencies, 1 sec

**Comment by alasdair-fowler-deliveroo** [comment]
Dependency versions:
google-auth-oauthlib=0.4.4
google-api-core=1.26.3
googleapis-common-protos=1.53.0
grpcio=1.37.1
proto-plus=1.18.1
PyYAML=5.4.1
pep562=1.0
nox=2020.12.31

**Comment by BenRKarl** [comment]
Very odd - I still can't reproduce, even when pointing to these same versions. Do you have an issue when _just_ calling:

```py
protobuf_helpers.field_mask(None, ad_group._pb)
```

...without the call to `copy_from`?

**Comment by alasdair-fowler-deliveroo** [comment]
I do

**Comment by alasdair-fowler-deliveroo** [comment]
`protobuf_helpers.field_mask(googleads_client.get_type("AdGroup", version='v7')._pb, ad_group._pb)` works though

**Comment by BenRKarl** [comment]
@alasdair-fowler-deliveroo this appears to be an issue in the field mask helper of the `google-api-core` library, would you mind filing an issue on [their tracker](https://github.com/googleapis/python-api-core/issues) so that that team can investigate it?
