### ISSUE TITLE
Unresolved reference url_seed

### ISSUE THREAD

**Issue by DeveloperMos** [googleads/google-ads-python#426]
https://github.com/googleads/google-ads-python/blob/66c5a3fc4099fa069c02f00e6de195cbd9f1017a/examples/planning/generate_keyword_ideas.py#L71

request.url_seed.url = page_url

**Comment by BenRKarl** [comment]
@DeveloperMos thanks for pointing this out, we'll get this updated as soon as possible.

**Comment by BenRKarl** [comment]
Fixed in https://github.com/googleads/google-ads-python/pull/440
