### ISSUE TITLE
Use of Python 3.6 incompatible with v5,v6,v7 after new release

### ISSUE THREAD

**Issue by bbalbon** [googleads/google-ads-python#433]
I saw that a [recent Issue](https://github.com/googleads/google-ads-python/issues/331) resulted in a [PR](https://github.com/googleads/google-ads-python/pull/353/files) that was merged to allow later versions of this library to be compatible with Python 3.6. However, I'm using the latest version of the google-ads python package (11.0.0) and I'm still encountering the same import error described in that issue^.

This is due to the swap of the following two files after "google_ads" became "googleads". [First version](https://github.com/googleads/google-ads-python/blob/86e5525f95e86bb10f06fc946bd8fb14ce712f70/google/ads/google_ads/v6/__init__.py) [Second version](https://github.com/googleads/google-ads-python/blob/589952affe089408a7f9cc64196e8511df08f032/google/ads/googleads/v6/__init__.py).

I'm wondering if it's still possible to use an older version of the package that's compatible with Python 3.6 seeing as this file has now been removed in the most recent release (v7). If this is the case, what version of the package might that be. 

Or, is there any other way to use the package with Python 3.6? Would it be possible to implement the same solution outlined in that previous PR for the current version (v7)? Our current service infra would not support an upgrade to 3.7 to facilitate the use of this package as is. 

Reproduce via this line: After creating a client --> `client.get_service('GoogleAdsService')` while sys using Python 3.6

**Comment by bbalbon** [comment]
Perhaps v9.0.0 is what I'm looking for? https://pypi.org/project/google-ads/9.0.0/. I see the updates I commented on above rolled out in 10.0.0 https://developers.google.com/google-ads/api/docs/client-libs/python/library-version-10

**Comment by BenRKarl** [comment]
@bbalbon what is the exact error that is raised for you?

**Comment by bbalbon** [comment]
Hi @BenRKarl thanks for the quick response. The one from the file above. "ImportError: This module requires Python 3.7 or later"

**Comment by bbalbon** [comment]
I'm thinking that the new release (google-ads==11.0.0) is only compatible with v5, v6, v7, as I see from this error `ValueError: Specified Google Ads API version "v4" does not exist. Valid API versions are: "v7", "v6", "v5"`. 

If this is the case, I think the Readme should include this info and also specify that Python 3.7+ is required. As trying to instantiate a service using any of the compatible versions (5,6,7) leads to the same ImportError stating that Python 3.7+ is required. Maybe a message saying the last supported release for Python 3.6 is google-ads==9.0.0 would suffice as this is the version I'm using and it's now working. 

This all makes sense when browsing through the version history in this repo, but it's just not apparent in your documentation. If you still do plan to support Python 3.6 with the latest release (or it actually is supported and this is a bug) then a simple test would be to change the version requirement in any of the compatible version `__init__` files as this is where this error is raised. [Example](https://github.com/googleads/google-ads-python/blob/589952affe089408a7f9cc64196e8511df08f032/google/ads/googleads/v6/__init__.py)

**Comment by bbalbon** [comment]
Okay sounds good. Thanks @BenRKarl . Any idea when the fix might be deployed?

**Comment by BenRKarl** [comment]
I opened a PR to fix this here: https://github.com/googleads/google-ads-python/pull/435

**Comment by bbalbon** [comment]
Okay awesome, sounds good. I'll keep an eye on that PR's status. Thanks @BenRKarl @wihl

**Comment by BenRKarl** [comment]
@bbalbon this issue is fixed in 11.0.1 of this library, you should be able to use Python 3.6+ with v5, v6 and v7 of the Google Ads API.
