### ISSUE TITLE
Please add python_version to dataclasses dependency

### ISSUE THREAD

**Issue by badanin-dmitry-playrix** [googleads/google-ads-python#437]
like this `'dataclasses >= 0.6, < 1.0.0; python_version < "3.7"',`

**Comment by BenRKarl** [comment]
@badanin-dmitry-playrix thanks for pointing this out, we'll get it updated shortly.

Is this causing any errors for you, or is the problem that you just don't want to install this module in 3.7, where it's native?

**Comment by badanin-dmitry-playrix** [comment]
Yes. We run script with custom PYTHON_PATH set to path to site-packages installed using `pip install --prefix`, and external dataclasses module being used.

**Comment by BenRKarl** [comment]
Got it - PR is open here: https://github.com/googleads/google-ads-python/pull/438

**Comment by badanin-dmitry-playrix** [comment]
Thank you

**Comment by BenRKarl** [comment]
11.0.2 is published with this change. Thanks again for pointing it out!
