### ISSUE TITLE
Get Account Hierarchy Example - PERMISSION_DENIED Errors on Inaccessible Accounts/MCs With Depth > 1

### ISSUE THREAD

**Issue by davedavis** [googleads/google-ads-python#441]
I'm working on a project where I have to get the account list for a complex and deep hierarchy (using all 6 levels) and it's determined by the logged in user, so cannot be set manually (no manager ID can be specified). 

When running the the get_account_hierarchy example, it works as expected until it reaches a sub-MCC that contains accounts that are inaccessible by the user. 

In the screenshot below, you can see the example is initialized and the **top level accessible** customers are listed. 
The first accessible customer (91) is a directly linked account, not an MCC, so it prints correctly.

The second accessible customer (93) contains a whole bunch of directly managed accounts and sub MCCs. 
The IDs are all returned from the customer service get_customer() method. 

The problem occurs when one of those IDs returned is a sub manager account with accounts that are inaccessible to the user. In the below screenshot, it's querying the manager account ending (17) and getting a permission denied error.

![image](https://user-images.githubusercontent.com/5341256/119241797-155b9280-bb51-11eb-9a41-325b31c7bbc5.png)

You can see that this manager account, accessible to the user, contains two accounts that are inaccessible to the user

![image](https://user-images.githubusercontent.com/5341256/119242002-6324ca80-bb52-11eb-88aa-fe7e7c7bb1ad.png)

![image](https://user-images.githubusercontent.com/5341256/119242035-98311d00-bb52-11eb-878c-b88ca207f24f.png)

The user does not have access to any accounts in that Manager account. So, when it's queried, they cause the error (I think). 

So my question is, how can I bypass/skip these? I can't seem to figure out a way to differentiate between these as the customer_client object doesn't contain a field is exactly the same as all the rest (manager: True, Level: 1 etc.). Do I have to handle this situation by catching the exception or is there a more elegant way to do it? 

An example request ID if needed is: zApa0OQuxgx9gmrhr2kkxw

Many thanks in advance.

**Comment by laurachevalier4** [comment]
Hey @davedavis! To help us understand what's happening here so that we can better advise you, can you mail your client-side logs to googleadsapi-support@google.com, include the login customer ID, and call out Anash (@AnashOommen) so that we can have a look? Thanks!

**Comment by davedavis** [comment]
Sure @laurachevalier4. Appreciate the reply. 

I think this is specifically related to the example in this library though.

Basically, say a user has access to a lot of manager accounts and sub manager accounts, if one of the sub manager accounts contains accounts that the user does not have access to, the error occurs in the get_account_hierarchy example.

The example recursively goes through the initial list of accessible accounts, then calls the get_cuatomer() method passing in the resource name, but it doesn't check if the user has access to the account its calling that method on. It's assuming it has access because it's a child in the list accessible customers tree.

In a multi level MC tree, the example is returning account IDs that the user doesn't have access to, and it's erroring out when trying to get the info about those accounts. 

I'd add in the check to the example, but I don't know how to check if a user has access to an account ID programmatically. Is there a way?

**Comment by laurachevalier4** [comment]
Gotcha, I had forgotten the [ListAccessibleCustomers](https://developers.google.com/google-ads/api/docs/account-management/listing-accounts) method checks for customers accessible to the OAuth credentials and ignores the login customer ID. Thanks for clarifying!

The only way I can think to check if a user has access to an account, other than the try/except approach, is to query the [`customer_user_access`](https://developers.google.com/google-ads/api/fields/v8/customer_user_access_query_builder) resource. You could do something like:
<img width="894" alt="Screen Shot 2021-06-10 at 5 00 49 PM" src="https://user-images.githubusercontent.com/15260006/121597103-491e2f80-ca0e-11eb-94f0-eddb8af7a0dd.png">
using the email address of the OAuth user (or the user ID if you have it). Then you can check whether the [AccessRole](https://developers.google.com/google-ads/api/reference/rpc/v7/AccessRoleEnum.AccessRole) is one of `STANDARD`, `ADMIN`, or `READ_ONLY` (or whichever one of those is needed for your use case). 

Hope this helps!

**Comment by davedavis** [comment]
Thanks @laurachevalier4 
That works, but means that you have to do a second query on all sub accounts before getting the account names (or ignoring if there's no access role). So I won't update the example, not even with the try-catch approach as this could probably be called an edge case (5 levels deep). 

I think letting the user pick their manager account from the initial list and querying the sub accounts with the ID of the chosen MC is the cleanest approach using the fewest requests. 

Thanks for your help. 

Appreciate the help, this was driving me mad.

**Comment by laurachevalier4** [comment]
Great idea, sounds like a solid middle ground 👍
