### ISSUE TITLE
How to creat properly a text label then attach it to an ad.

### ISSUE THREAD

**Issue by ohangyu** [googleads/google-ads-python#442]
Hello!
So i was trying to create a Text Label for attach it to my ads in further steps but i am actually stuck at the beginning.

This is my newbie intent in python:

def add_text_label(client, customer_id):
        label_service = client.get_service("LabelService")
        label_operations = []
        label_operation = client.get_type("LabelOperation")
        text_label = label_operation.create
        text_label.background_color = '#98ABA7'
        text_label.description = "feed_ads_management"
        label_operations.append(label_operation)
        label_response = label_service.mutate_labels(customer_id=customer_id, operations=label_operations)

it gives a keyerror of background_color which i don't really see why. According to https://developers.google.com/google-ads/api/reference/rpc/v7/TextLabel the object should have only 2 fields: "background_color" and "description".

This is a try of creating similar process following the code sample "Add Expanded Text Ads".

After having created the label, according to my understanding, i should  pass one or more AdGroupAdLabelOperation to AdGroupAdLabelService.MutateAdGroupAdLabels, where each AdGroupAdLabelOperation includes an AdGroupAdLabel instance for each ad/label pair. 

I am really newbie in programming and the whole theory seems quite difficult to execute for me. Is there any example of the process? Has anyone done anything similar before?

Many thanks in advance!

**Comment by laurachevalier4** [comment]
Hey @ohangyu! Your code is almost there; it looks like you're setting fields on the `Label` object, when it sounds like you want to be setting fields on the `TextLabel` object, which is nested within the `Label`. When you do `label_operation.create`, a [`Label`](https://developers.google.com/google-ads/api/reference/rpc/v7/Label) is returned, and that label has a `text_label` field representing the [`TextLabel`](https://developers.google.com/google-ads/api/reference/rpc/v7/TextLabel) object. So you might change your code to look something like:
```
def add_text_label(client, customer_id):
    label_service = client.get_service("LabelService")
    label_operations = []
    label_operation = client.get_type("LabelOperation")
    label = label_operation.create
    label.text_label.background_color = '#98ABA7'
    label.text_label.description = "feed_ads_management"
    label.name = "some_name"  # required per https://developers.google.com/google-ads/api/reference/rpc/v7/Label#name
    label_operations.append(label_operation)
    label_response = label_service.mutate_labels(customer_id=customer_id, operations=label_operations)
``` 

Hope this helps!

**Comment by ohangyu** [comment]
> Hey @ohangyu! Your code is almost there; it looks like you're setting fields on the `Label` object, when it sounds like you want to be setting fields on the `TextLabel` object, which is nested within the `Label`. When you do `label_operation.create`, a [`Label`](https://developers.google.com/google-ads/api/reference/rpc/v7/Label) is returned, and that label has a `text_label` field representing the [`TextLabel`](https://developers.google.com/google-ads/api/reference/rpc/v7/TextLabel) object. So you might change your code to look something like:
> 
> ```
> def add_text_label(client, customer_id):
>     label_service = client.get_service("LabelService")
>     label_operations = []
>     label_operation = client.get_type("LabelOperation")
>     label = label_operation.create
>     label.text_label.background_color = '#98ABA7'
>     label.text_label.description = "feed_ads_management"
>     label.name = "some_name"  # required per https://developers.google.com/google-ads/api/reference/rpc/v7/Label#name
>     label_operations.append(label_operation)
>     label_response = label_service.mutate_labels(customer_id=customer_id, operations=label_operations)
> ```
> 
> Hope this helps!

Yeah, thankyou so much!!!
