### ISSUE TITLE
How to pull data automatically from Google Ads API to my local machine

### ISSUE THREAD

**Issue by samsamph** [googleads/google-ads-python#443]
I would like to schedule to run my code and pull data from Google Ads API everyday at 6AM. How do I do that? So far, I have to run the code manually on my local machine to pull the data that I want via Google Ads API. I know there is a way to schedule the data pulling, I'm just not sure how. Thanks for your help.

**Comment by lindah2020** [comment]
You could use cronjobs to schedule your script

**Comment by Just1B** [comment]
Or you could use a scheduler like airflow in a vps : https://airflow.apache.org/

If you prefer managed services, you could also check :  https://cloud.google.com/composer

**Comment by wihl** [comment]
Closing as not a bug, not relevant to this specific library and didn't use our suggested template.
