### ISSUE TITLE
About appending new AdVideoAsset to AppAdInfo's youtube_videos.

### ISSUE THREAD

**Issue by umutg4d** [googleads/google-ads-python#446]
Hello, I am trying to add new youtube video asset to my existing AppAdInfo instance and it creates the asset successfully but disabled other youtube videos. Looking for examples here (https://github.com/googleads/google-ads-python/blob/master/examples/advanced_operations/add_smart_display_ad.py) but i think the mentality here is the same as the code down here. Thanks for any suggestions.
`

      ad_id = "123112312312"
      asset_service = client.get_service("AssetService")

      asset_operation = client.get_type("AssetOperation")
      media_bundle_asset = asset_operation.create
      media_bundle_asset.type_ = client.get_type(
          "AssetTypeEnum"
      ).AssetType.YOUTUBE_VIDEO
      media_bundle_asset.youtube_video_asset.youtube_video_id = youtube_video_id
      mutate_asset_response = asset_service.mutate_assets(customer_id=customer_id, operations=[asset_operation])
      ad_asset_resource_name = mutate_asset_response.results[0].resource_name
      
      ad_service = client.get_service("AdService")
      
      ad_service_operation = client.get_type("AdOperation")
  
      ad = ad_service_operation.update
      ad.resource_name = ad_service.ad_path(
          customer_id, ad_id
      )
      ad_video_asset = client.get_type("AdVideoAsset")
      ad_video_asset.asset = ad_asset_resource_name
      ad.app_ad.youtube_videos.append(ad_video_asset)
      client.copy_from(
          ad_service_operation.update_mask,
          protobuf_helpers.field_mask(None, ad._pb),
      )
      response = ad_service.mutate_ads(
          customer_id=customer_id, operations=[ad_service_operation]
      )
`

**Comment by BenRKarl** [comment]
When updating like this, that field will _overwrite_ the existing list, not merge with it. What you should do here is instead of creating a new `update` object, use the existing `Ad` by issuing a `GET` request, for example:

```py
ad_service = client.get_type("AdService")
ad = ad_service.get_ad(resource_name="INSERT RESOURCE NAME")
ad_service_operation = client.get_type("AdOperation")
ad_service_operation.update = ad
ad.app_ad.youtube_videos.append(ad_video_asset)
# ... same remaining steps.
```
