### ISSUE TITLE
Support for v8?

### ISSUE THREAD

**Issue by kalugny** [googleads/google-ads-python#447]
It was released a few days ago :)

**Comment by chengxianghu** [comment]
> It was released a few days ago :)

But it looks like python client library still only supports up to v7 at the moment.
When could we expect v8 be available via python client library? Thank you in advance

**Comment by BenRKarl** [comment]
Hello! We're expecting to publish a new version of this library with support for v8 today or tomorrow.

**Comment by BenRKarl** [comment]
Hi all - following up to let you know that version `12.0.0` was published today, which supports `v8`
