### ISSUE TITLE
[Question] How to properly use the `validate_only` flag?

### ISSUE THREAD

**Issue by vmgustavo** [googleads/google-ads-python#448]
I am trying to use the `validate_only` flag to not operate on the account using the Google Ads API  from Python to mutate AdGroup information. However I haven't found a proper way to do this.

I tried to set the flag using the Google Ads Client:

```
client = GoogleAdsClient.load_from_storage(path=credentials, version='v7')
client.validate_only = True
```

The last method I tried was to set using the Ad Group Service:

```
ad_group_service = client.get_service('AdGroupService')
ad_group_service.validate_only = True
```

And the request mutated the Ad Group for both cases. What is the correct way to just validate the request?

**Comment by BenRKarl** [comment]
Hi @vmgustavo you'll need to set that option on the request object manually, see [these docs](https://developers.google.com/google-ads/api/docs/client-libs/python/library-version-10#request_objects) for more details. There's an example in the [`validate_text_ad`](https://github.com/googleads/google-ads-python/blob/master/examples/campaign_management/validate_text_ad.py#L58) example using the `AdGroupAdService.mutate_ad_group_ads` method.
