### ISSUE TITLE
Unable to run the code

### ISSUE THREAD

**Issue by ujvalgandhi1** [googleads/google-ads-python#469]
Team,

I am trying to execute this block of code

parser.add_argument(
        "-c",
        "--customer_id",
        type=str,
        required=True,
        help="The Google Ads customer ID.",
    )
    args = parser.parse_args()

I am confused on what to enter for customer_id -- I have two Google Ads Account and I have a manager account. I have tried xxx-xxx-xxxx and/or xxxxxxxxxx without any luck
I keep getting the following arguments are required: -c/-

Can you please assist on how to populate this code block?

**Comment by BenRKarl** [comment]
Hi @ujvalgandhi1 - this value is passed via the command line when executing the example, so for instance, note the `-c` flag in the below command:

```sh
python examples/basic_operations/get_campaigns.py -c 123456789
```

**Comment by ujvalgandhi1** [comment]
Should the customer id be the manager account or individual accounts?

**Comment by BenRKarl** [comment]
In this case it should be an individual account, also referred to as a client account. If a manager account is required it will be specified in the name of the parameter, for example [here](https://github.com/googleads/google-ads-python/blob/master/examples/account_management/create_customer.py#L69)

**Comment by ujvalgandhi1** [comment]
Thank you for the clarification. Works now. Thanks for creating resources
for us.

**Comment by BenRKarl** [comment]
No problem, thanks for reaching out!

**Comment by ujvalgandhi1** [comment]
Ben

Is there a code sample to run an ad/campaign performance report and export
the output to a Pandas dataframe? I am searching everywhere but am hitting
blocks. The code examples have me running the code via a terminal, I want
to use VSCode to test the code and eventually want to automate it (the
daily pull) using a cloud VM.

Regards,
Ujval
