### ISSUE TITLE
When creating new asset from youtube video google.api_core.exceptions.InternalServerError: 500 Internal error encountered. exception occurs.

### ISSUE THREAD

**Issue by umutg4d** [googleads/google-ads-python#470]
Hello, I want to create new asset from youtube video id using this code 
`    

          client = GoogleAdsClient.load_from_storage(version="v7", path='./googleads_test/credentials/google-ads-2.yaml')
          youtube_video_id = youtube_video_dict[video_name]
          asset_service = client.get_service("AssetService")
          # Construct an asset operation and populate its fields.
          asset_operation = client.get_type("AssetOperation")
          media_bundle_asset = asset_operation.create
          media_bundle_asset.type_ = client.get_type(
              "AssetTypeEnum"
          ).AssetType.YOUTUBE_VIDEO
          media_bundle_asset.youtube_video_asset.youtube_video_id = youtube_video_id
          mutate_asset_response = asset_service.mutate_assets(customer_id=customer_id, operations=[asset_operation])
          upload_asset_resource_name = mutate_asset_response.results[0].resource_name
          print(f"Uploaded asset resource name - {upload_asset_resource_name}")
          return upload_asset_resource_name` 
and it gives me 'google.api_core.exceptions.InternalServerError: 500 Internal error encountered.' this error, here is the traceback of the exception:
> File "/usr/local/airflow/.local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 73, in error_remapped_callable
    return callable_(*args, **kwargs)
File "/usr/local/airflow/.local/lib/python3.7/site-packages/grpc/_interceptor.py", line 221, in __call__
    compression=compression)
File "/usr/local/airflow/.local/lib/python3.7/site-packages/grpc/_interceptor.py", line 257, in _with_call
    return call.result(), call
File "/usr/local/airflow/.local/lib/python3.7/site-packages/grpc/_channel.py", line 333, in result
    raise self
File "/usr/local/airflow/.local/lib/python3.7/site-packages/grpc/_interceptor.py", line 247, in continuation
    compression=new_compression)
File "/usr/local/airflow/.local/lib/python3.7/site-packages/grpc/_interceptor.py", line 271, in with_call
    compression=compression)
File "/usr/local/airflow/.local/lib/python3.7/site-packages/grpc/_interceptor.py", line 257, in _with_call
    return call.result(), call
File "/usr/local/airflow/.local/lib/python3.7/site-packages/grpc/_channel.py", line 333, in result
    raise self
File "/usr/local/airflow/.local/lib/python3.7/site-packages/grpc/_interceptor.py", line 247, in continuation
    compression=new_compression)
File "/usr/local/airflow/.local/lib/python3.7/site-packages/grpc/_interceptor.py", line 271, in with_call
    compression=compression)
File "/usr/local/airflow/.local/lib/python3.7/site-packages/grpc/_interceptor.py", line 256, in _with_call
    request)
File "/usr/local/airflow/.local/lib/python3.7/site-packages/google/ads/googleads/interceptors/exception_interceptor.py", line 169, in intercept_unary_unary
    self._handle_grpc_failure(response)
File "/usr/local/airflow/.local/lib/python3.7/site-packages/google/ads/googleads/interceptors/exception_interceptor.py", line 141, in _handle_grpc_failure
    raise self._get_error_from_response(response)
File "/usr/local/airflow/.local/lib/python3.7/site-packages/grpc/_interceptor.py", line 247, in continuation
    compression=new_compression)
File "/usr/local/airflow/.local/lib/python3.7/site-packages/grpc/_channel.py", line 934, in with_call
    return _end_unary_response_blocking(state, call, True, None)
File "/usr/local/airflow/.local/lib/python3.7/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
status = StatusCode.INTERNAL
details = "Internal error encountered."
debug_error_string = "{"created":"@1626201771.016013175","description":"Error received from peer ipv4:142.250.188.202:443","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Internal error encountered.","grpc_status":13}"

And if i want to run the same code from my local machine (MAC OS X:ProductVersion:10.14.4) it works without any problem, the problem exists when the same code runs inside docker container which has these os informations.
<img width="445" alt="Screen Shot 2021-07-13 at 22 12 52" src="https://user-images.githubusercontent.com/8229273/125511454-3b502c37-5658-47ff-b06a-12e104fe6f48.png">

Google Ads API version: 11.0.2

Thanks.

**Comment by BenRKarl** [comment]
Hi @umutg4d - can you compare the requests that are sent from each environment and see if there are any differences? Note that if you share the logs here you should make sure to redact any personally identifiable information, such as customer ID, etc.

**Comment by umutg4d** [comment]
Thanks @BenRKarl. This is the log files from the script running inside the container 
> Host: googleads.googleapis.com
Headers: {
  "developer-token": "REDACTED",
  "x-goog-api-client": "gl-python/3.7.10 grpc/1.36.1 gax/1.26.1",
  "x-goog-request-params": "customer_id=my_customer_id"
}
Request: customer_id: "my_customer_id"
operations {
  create {
    type_: YOUTUBE_VIDEO
    youtube_video_asset {
      youtube_video_id: "ebY3IIkGhmg"
    }
  }
}
Response
Headers: {
  "google.ads.googleads.v7.errors.googleadsfailure-bin": "\n%\n\u0002P\u0002\u0012\u001fAn internal error has occurred.\u0012\u0016Pt8Nurzza-L7I7xVu51eJg",
  "grpc-status-details-bin": "\b\r\u0012\u001bInternal error encountered.\u001a\u0001\nCtype.googleapis.com/google.ads.googleads.v7.errors.GoogleAdsFailure\u0012?\n%\n\u0002P\u0002\u0012\u001fAn internal error has occurred.\u0012\u0016Pt8Nurzza-L7I7xVu51eJg",
  "request-id": "Pt8Nurzza-L7I7xVu51eJg"
}
Fault: {
  "created": "@1626250203.251602723",
  "description": "Error received from peer ipv4:172.217.12.234:443",
  "file": "src/core/lib/surface/call.cc",
  "file_line": 1067,
  "grpc_message": "Internal error encountered.",
  "grpc_status": 13
}

And the script running inside my local machine gives me this log, it doesn't contain any request or response info

> Request made: ClientCustomerId: 6069239353, Host: googleads.googleapis.com, Method: /google.ads.googleads.v7.services.AssetService/MutateAssets, RequestId: qqyDQu7gbW2dUIl_jBTdmA, IsFault: False, FaultMessage: None

**Comment by umutg4d** [comment]
Hi @BenRKarl , do you have any news about the issue, or do i need to give more information for your further research about it?

**Comment by BenRKarl** [comment]
Hi @umutg4d I looked through our logs and found that the only difference between the two requests is the youtube video IDs. Are you able to upload both IDs via your local machine? Just curious if this is a problem with the request payload and not the particular environment.

**Comment by umutg4d** [comment]
Hi @BenRKarl , I think i have found the problem here, before the asset resource creation process, the code also uploads the related videos to Youtube via Youtube Data Api. And after uploading step, it immediately proceeds to asset resource creation step. And when i invoke `time.sleep(120)` before the second process starts, it works without any error.

**Comment by BenRKarl** [comment]
Oh I see, so it was trying to create the video asset before the YouTube video existed. It makes sense that would generate an error, however it should be more informative than just an INTERNAL error.  I'll file a bug with the team to improve the error message, meanwhile will close this. Thanks!
