### ISSUE TITLE
Please publish a built distribution (wheel)

### ISSUE THREAD

**Issue by busunkim96** [googleads/google-ads-python#474]
**Describe the problem you are trying to solve:**

The lack of a built distribution (wheel) makes it harder for tools to determine package dependencies.

As an example, if you visit https://libraries.io/pypi/google-ads the package is listed as having 0 dependencies. For comparison see https://libraries.io/pypi/pytest, where it lists the number of dependencies and links to each of them. The public [BigQuery dataset](https://packaging.python.org/guides/analyzing-pypi-package-downloads) also doesn't list any dependencies for this package.

![image](https://user-images.githubusercontent.com/8822365/127404700-23348163-7c19-4583-8395-71255125f4f7.png)
This is a side effect of only a source distribution being published to PyPI. The problem is described in this blog post: [Why PyPI Doesn't Know Your Projects Dependencies](https://dustingram.com/articles/2018/03/05/why-pypi-doesnt-know-dependencies/). In the future, it's expected that tools will be able to fetch declared dependencies from source distributions as well. However, at present, the easiest way to make metadata available is to publish a built distribution. 

**Describe the solution you'd like:**
Publish a `bdist` in addition to the `sdist` (source distribution).

I believe this package can be published as a "pure python wheel". https://packaging.python.org/guides/distributing-packages-using-setuptools/#pure-python-wheels

**Describe alternatives you've considered:**

**Additional context:**

I work on the Cloud libraries and have been looking for dependents of `google-api-core` and `google-auth` to apply a change like the one in #473 to minimize diamond dependency conflicts. The primary way I've been finding dependents is through the PyPI BigQuery dataset.

**Comment by laurachevalier4** [comment]
Hey @busunkim96! The wheel is [uploaded](https://pypi.org/project/google-ads/14.0.0/#files), does it look ok? Are there any other steps we need to get the dependencies populated?

**Comment by busunkim96** [comment]
Hi @laurachevalier4,

Looks good to me! https://pypi.org/project/google-ads/14.0.0/#history still lists 0 dependencies, but I think it's because the wheel was added to an already existing version. I expect it will be resolved with the next release.

Thanks!
