### ISSUE TITLE
About google_ads and gogoleads

### ISSUE THREAD

**Issue by libin777** [googleads/google-ads-python#475]
when I use python to call google-ads==13.0.0, there will be two packages that can be used, namely google_ads and googleads, but I found that google_ads is only updated to v6, and googleads is updated to v8.
Will google_ads be updated synchronously? Where can I find the difference between these two parts?
If anyone knows, can you tell me

**Comment by wihl** [comment]
As of [version 10](https://developers.google.com/google-ads/api/docs/client-libs/python/library-version-10#module_path) the module path changed from `google_ads` to `googleads`, removing the underscore (`_`). For all usage of v10 and onward, you should use `import google.ads.googleads`

**Comment by libin777** [comment]
Do you know when google_ads will go offline?
