### ISSUE TITLE
CampaignCriterionOperation does not work when bid_modifier value is set to 0.0 or None

### ISSUE THREAD

**Issue by siciarek** [googleads/google-ads-python#476]
When I try to update campaign criterion via CampaignCriterionOperation I run

```python
criterion = operation.update
criterion.resource_name = criterion_resource_name
criterion.bid_modifier = bid_modifier
self.api.update_mask(criterion, operation)
```

the code works fine when I set values from the 0.1 - 10.0 range

But there are two special values like
0.0 - which sets in google ads panel value -100%
None - which sets the criterion bid_modifier off (remove the field from object) - in google ads panel visible as dash

![image](https://user-images.githubusercontent.com/27905/128483754-4266c3b8-856a-4a91-a5e2-145635014e7c.png)

Setting those values was available in version `9.0.0` and of course is available to set via Google Ads Panel.

**Comment by wihl** [comment]
Your question is a good one, but should since it is generic to the API, rather than specific to the Python client lib, please post it on our online forums https://groups.google.com/forum/#!forum/adwords-api where you will get a more detailed and likely timely response.

FMI: https://developers.google.com/google-ads/api/support

**Comment by siciarek** [comment]
I am afraid that the problem is lib related. I got an answer from the forum recommended by you:
```
According to this guide, the modifier must be in the range: 0.1 - 10.0. Most targetable criteria types support modifiers. Use 0 (not 0.0) to opt out of a Device type. 
```
So i triplechecked assignment bid_modifier as 0 (integer value) and just after the assignment it is casted into float.
but zero value is not affected to the mask.

**From google client log**

```
Method: /google.ads.googleads.v8.services.CampaignCriterionService/MutateCampaignCriteria
Host: googleads.googleapis.com
Headers: {
  "developer-token": "REDACTED",
  "login-customer-id": "7281957450",
  "x-goog-api-client": "gl-python/3.9.6 grpc/1.39.0 gax/1.31.0 gapic/13.0.0",
  "x-goog-request-params": "customer_id=3783286648"
}
Request: customer_id: "3783286648"
operations {
  update {
    resource_name: "customers/3783286648/campaignCriteria/14178383920~30000"
    bid_modifier: 1.100000023841858
  }
  update_mask {
    paths: "resource_name"
    paths: "bid_modifier"
  }
}
operations {
  update {
    resource_name: "customers/3783286648/campaignCriteria/14178383920~30001"
    bid_modifier: 0.3499999940395355
  }
  update_mask {
    paths: "resource_name"
    paths: "bid_modifier"
  }
}
operations {
  update {
    resource_name: "customers/3783286648/campaignCriteria/14178383920~30002"
    bid_modifier: 0.0
  }
  update_mask {
    paths: "resource_name"
  }
}

```
