### ISSUE TITLE
How to extract fields from a response for any arbitrary query (and with enums translated)?

### ISSUE THREAD

**Issue by jakenieto** [googleads/google-ads-python#480]
Hi!

So I am currently trying to extract all fields from a response, for _any arbitrary_ query. I found a way to do this for the most part:

```    
def __executeSelectQuery(self, query: str, customerId: str) -> list:
        #create return list
        responseList = [] 
        response = self.__ga_service.search_stream(customerId, query=query)
        try:
            for batch in response:
                # get a list of all field names in the queries
                fieldsList = batch.field_mask.paths._values
                responseList.append(fieldsList)
                # for each row in the query response, append the data to the list
                for row in batch.results:
                    valueRow = []
                    value = operator.attrgetter(field)(row)
                    valueRow.append(value)

```
The code above uses the ` batch.field_mask.paths._values`, which is a list of all the query properties I selected for. (i.e. if my query looks like:
```
SELECT
                campaign.id, 
                campaign.name
FROM campaign
```

Then  ` batch.field_mask.paths._values = ['campaign.id', 'campaign.name']`

Now using this, I can extract the exact fields that I wanted from the query by using this function call `operator.attrgetter(field)(row)`, which effectively does `row.<field>` (but if it is nested field it can extract that). The issue I have now is that when extracting the fields I get the _enum value_. I don't want to have to call each individual service to translate an enum since this method is meant to extract data in a way that it could work for **ANY** query. Is there a way I could translate any arbitrary enum, or acquire my data differently so that I get the translated enum to begin with?

**Comment by laurachevalier4** [comment]
Hey @jakenieto! Apologies for the delay; have you found a workaround here? If not, can you share an example of the end result you'd be looking for? From what I understand, you want to be able to take any arbitrary GoogleAdsRow, and extract all values for the fields you selected; is that correct? So in the example you gave, would you be looking for something like `[12345, 'My Campaign']`? And for enums specifically, if you were querying for something like `campaign.status`, you'd want to see ['ENABLED' instead of 2](https://github.com/googleads/google-ads-python/blob/b0403e0891c11f9c8aa54d0c28455c8a0502ccd5/google/ads/googleads/v8/enums/types/campaign_status.py#L35)?

**Comment by laurachevalier4** [comment]
If you're looking for a generic tool to extract values from API object fields, we have a helper for this purpose at https://github.com/googleads/google-ads-python/blob/main/google/ads/googleads/util.py#L26.

As an example, I could use it like this to get the name of a campaign from a campaign object:
```python
get_nested_attr(campaign, "name")
> 'Campaign #1'
```
It also works for dot-delimited field paths, which is what are returned in field masks for nested attributes (as you've shown):
```python
get_nested_attr(ad_group_ad, "ad.name")
> 'Ad #1'
```

**Comment by poojitha-gandra25** [comment]
HI @jakenieto I'm trying to do the same thing as you are ! Trying to get all the columns in the query instead of doing a row.columnname for every column we need !  Could you share your solution here please ! Thanks

**Comment by poojitha-gandra25** [comment]
I have tried the below to retrieve all the columns required as json and then download the report's as csv or json 
but the below code wouldn't give us the all the columns in the GAQL query and some of them are being sent as field_masks. Please suggest on how i can retrieve these columns ! Thanks 
approach 1:
for customer_id in account_list:
            stream = ga_service.search_stream(customer_id=customer_id, query=query)
            for batch in stream:
                 for row in batch.results:
                    pro_dict = proto.Message.to_dict(row)
                    print(pro_dict)

approach 2:
for customer_id in account_list:
            stream = ga_service.search_stream(customer_id=customer_id, query=query)
             for row in stream:
              json_str = json_format.MessageToJson(row._pb, preserving_proto_field_name=True)
               d = json.loads(json_str)
                df = pd.json_normalize(data=d['results'])
                print(" df is ", df.columns)
