### ISSUE TITLE
Error  customer_user_access_error: DISALLOWED_ACCESS_ROLE  with example code update_user_access.py

### ISSUE THREAD

**Issue by landybird** [googleads/google-ads-python#482]
I tried with `update_user_access`exmaple you provide [update_user_access](https://github.com/googleads/google-ads-python/blob/master/examples/account_management/update_user_access.py) But I always get error  like 

```

error_code {
    customer_user_access_error: DISALLOWED_ACCESS_ROLE
  }
  message: "Unable to add or update the access role as specified."
```

**Comment by laurachevalier4** [comment]
Hey @landybird! This doesn't look like it's specific to the google-ads-python client library so I'd recommend reaching out on [the forum](https://developers.google.com/google-ads/api/support) and sending more information about the precise change you're making, excluding any PII and including an example request ID so we can look into it further. Without any more information, my recommendation would be to make sure the user you are authenticating with has permission to change the access level of the user you are passing into the example.

This [help article](https://support.google.com/google-ads/answer/9977851) might add some clarity; it explains what manager account users can do in linked client accounts, and what they can do in the manager accounts.
