### ISSUE TITLE
ETA for the next version of the Python library supporting v8_1 of the Google Ads API?

### ISSUE THREAD

**Issue by mbaader** [googleads/google-ads-python#483]
Hi,

I just wanted to ask if there is an ETA for the next version of the Python library, supporting v8_1 of the Google Ads API?
According to [this announcement](https://ads-developers.googleblog.com/2021/08/announcing-v81-of-google-ads-api.html), it's been overdue for a week now.

Regards
Mat

**Comment by BenRKarl** [comment]
Hi @mbaader - we released support for v8_1 this morning with version 14.0.0 of this library.

Please note there is a new required configuration parameter, which is described [here](https://developers.google.com/google-ads/api/docs/client-libs/python/protobuf-messages).
