### ISSUE TITLE
Cannot check peer: missing selected ALPN property error

### ISSUE THREAD

**Issue by zisha** [googleads/google-ads-python#488]
**Describe the bug:**
I am attempting to access the google-ads API from behind a corporate firewall. 
When code reaches ga_service.search() the Cannot check peer: missing selected ALPN property error is produced.

**Steps to Reproduce:**
call ga_service.search()

**Expected behavior:**
return results

**Client library version and API version:**
google-ads                        12.0.0
google-api-core                   1.30.0
google-auth                       1.32.0 
google-auth-oauthlib              0.4.5
google-cloud-bigquery             2.20.0
google-cloud-core                 1.7.0
google-crc32c                     1.1.2 
google-resumable-media            1.3.1
googleapis-common-protos          1.53.0
grpcio                            1.38.1    

argcomplete==1.12.3
backports.entry-points-selectable==1.1.0
cachetools==4.2.2
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
colorama==0.4.4
colorlog==4.8.0
distlib==0.3.2
filelock==3.0.12
google-ads==12.0.0
google-api-core==1.30.0
google-auth==1.32.0
google-auth-oauthlib==0.4.5
google-cloud-bigquery==2.20.0
google-cloud-core==1.7.0
google-crc32c==1.1.2
google-resumable-media==1.3.1
googleapis-common-protos==1.53.0
grpcio==1.38.1
idna==2.10
nox==2020.12.31
oauthlib==3.1.1
packaging==20.9
pep562==1.1
platformdirs==2.2.0
proto-plus==1.18.1
protobuf==3.17.3
py==1.10.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pyparsing==2.4.7
pytz==2021.1
PyYAML==5.4.1
requests==2.25.1
requests-oauthlib==1.3.0
rsa==4.7.2
six==1.16.0
urllib3==1.26.4
virtualenv==20.6.0

**Request/Response Logs:**
D0831 10:56:39.595000000 16412 src/core/ext/filters/client_channel/lb_policy_registry.cc:42] registering LB policy factory for "grpclb"
D0831 10:56:39.596000000 16412 src/core/ext/filters/client_channel/lb_policy_registry.cc:42] registering LB policy factory for "priority_experimental"
D0831 10:56:39.596000000 16412 src/core/ext/filters/client_channel/lb_policy_registry.cc:42] registering LB policy factory for "weighted_target_experimental"
D0831 10:56:39.596000000 16412 src/core/ext/filters/client_channel/lb_policy_registry.cc:42] registering LB policy factory for "pick_first"
D0831 10:56:39.597000000 16412 src/core/ext/filters/client_channel/lb_policy_registry.cc:42] registering LB policy factory for "round_robin"
D0831 10:56:39.597000000 16412 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc:322] Using native dns resolver
D0831 10:56:39.598000000 16412 src/core/ext/xds/certificate_provider_registry.cc:33] registering certificate provider factory for "file_watcher"
D0831 10:56:39.598000000 16412 src/core/ext/filters/client_channel/lb_policy_registry.cc:42] registering LB policy factory for "cds_experimental"
D0831 10:56:39.598000000 16412 src/core/ext/filters/client_channel/lb_policy_registry.cc:42] registering LB policy factory for "xds_cluster_impl_experimental"
D0831 10:56:39.599000000 16412 src/core/ext/filters/client_channel/lb_policy_registry.cc:42] registering LB policy factory for "xds_cluster_resolver_experimental"
D0831 10:56:39.599000000 16412 src/core/ext/filters/client_channel/lb_policy_registry.cc:42] registering LB policy factory for "xds_cluster_manager_experimental"
E0831 10:56:39.599000000 16412 src/core/lib/debug/trace.cc:65] Unknown trace var: 'transport_security'
D0831 10:56:48.568000000 16412 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc:269] Start resolving.
I0831 10:56:48.607000000 16412 src/core/tsi/ssl_transport_security.cc:223]      HANDSHAKE START -       TLS client start_connect  - !!!!!!
I0831 10:56:48.608000000 16412 src/core/tsi/ssl_transport_security.cc:223]                 LOOP -    TLS client enter_early_data  - !!!!!!
I0831 10:56:48.608000000 16412 src/core/tsi/ssl_transport_security.cc:223]                 LOOP -   TLS client read_server_hello  - !!!!!!
I0831 10:56:49.756000000 16412 src/core/tsi/ssl_transport_security.cc:223]                 LOOP - TLS client read_server_certifi  - !!!!!!
I0831 10:56:49.756000000 16412 src/core/tsi/ssl_transport_security.cc:223]                 LOOP - TLS client read_certificate_st  - !!!!!!
I0831 10:56:49.757000000 16412 src/core/tsi/ssl_transport_security.cc:223]                 LOOP - TLS client verify_server_certi  - !!!!!!
I0831 10:56:49.757000000 16412 src/core/tsi/ssl_transport_security.cc:223]                 LOOP - TLS client read_server_key_exc  - !!!!!!
I0831 10:56:49.758000000 16412 src/core/tsi/ssl_transport_security.cc:223]                 LOOP - TLS client read_certificate_re  - !!!!!!
I0831 10:56:49.759000000 16412 src/core/tsi/ssl_transport_security.cc:223]                 LOOP - TLS client read_server_hello_d  - !!!!!!
I0831 10:56:49.759000000 16412 src/core/tsi/ssl_transport_security.cc:223]                 LOOP - TLS client send_client_certifi  - !!!!!!
I0831 10:56:49.759000000 16412 src/core/tsi/ssl_transport_security.cc:223]                 LOOP - TLS client send_client_key_exc  - !!!!!!
I0831 10:56:49.760000000 16412 src/core/tsi/ssl_transport_security.cc:223]                 LOOP - TLS client send_client_certifi  - !!!!!!
I0831 10:56:49.760000000 16412 src/core/tsi/ssl_transport_security.cc:223]                 LOOP - TLS client send_client_finishe  - !!!!!!
I0831 10:56:49.761000000 16412 src/core/tsi/ssl_transport_security.cc:223]                 LOOP -       TLS client finish_flight  - !!!!!!
I0831 10:56:49.761000000 16412 src/core/tsi/ssl_transport_security.cc:223]                 LOOP - TLS client read_session_ticket  - !!!!!!
I0831 10:56:49.761000000 16412 src/core/tsi/ssl_transport_security.cc:223]                 LOOP - TLS client process_change_ciph  - !!!!!!
I0831 10:56:49.764000000 16412 src/core/tsi/ssl_transport_security.cc:223]                 LOOP - TLS client read_server_finishe  - !!!!!!
I0831 10:56:49.765000000 16412 src/core/tsi/ssl_transport_security.cc:223]                 LOOP - TLS client finish_client_hands  - !!!!!!
I0831 10:56:49.765000000 16412 src/core/tsi/ssl_transport_security.cc:223]                 LOOP -                TLS client done  - !!!!!!
I0831 10:56:49.765000000 16412 src/core/tsi/ssl_transport_security.cc:223]       HANDSHAKE DONE -                TLS client done  - !!!!!!
D0831 10:56:49.765000000 16412 src/core/lib/security/transport/security_handshaker.cc:183] Security handshake failed: {"created":"@1630421809.765000000","description":"Cannot check peer: missing selected ALPN property.","file":"src/core/lib/security/security_connector/ssl_utils.cc","file_line":162}
I0831 10:56:49.766000000 16412 src/core/ext/filters/client_channel/subchannel.cc:1012] Connect failed: {"created":"@1630421809.765000000","description":"Cannot check peer: missing selected ALPN property.","file":"src/core/lib/security/security_connector/ssl_utils.cc","file_line":162}
D0831 10:56:49.766000000 16412 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc:247] In cooldown from last resolution (from 1198 ms ago). Will resolve again in 28802 ms
I0831 10:56:49.767000000 16412 src/core/ext/filters/client_channel/subchannel.cc:955] Subchannel 00000189E4A6FB30: Retry immediately
I0831 10:56:49.767000000 16412 src/core/ext/filters/client_channel/subchannel.cc:980] Failed to connect to channel, retrying
Request made: ClientCustomerId: 1288155833, Host: googleads.googleapis.com:443, Method: /google.ads.googleads.v8.services.GoogleAdsService/Search, RequestId: None, IsFault: True, FaultMessage: failed to connect to all addresses

**Comment by BenRKarl** [comment]
Hi @zisha - are you using a [proxy](https://github.com/googleads/google-ads-python/blob/master/google-ads.yaml#L81) to make requests? If so it seems like your proxy server may not be configured properly.

**Comment by zisha** [comment]
Thanks for the response @BenRKarl. My local windows machine is going thru a proxy and a firewall. I also ran this on a unix server which is not going thru a proxy but is behind a firewall with the same results. Seems to be a firewall issue rather than a proxy issue.

**Comment by BenRKarl** [comment]
Thanks @zisha in the second test, where you do *not* go through a proxy, do you have the [`http_proxy`](https://github.com/googleads/google-ads-python/blob/main/google-ads.yaml#L81) configuration value set?

I'll see if I can help pinpoint the issue, but this does seem to be something network related, which we may not be able to help much with here.

**Comment by BenRKarl** [comment]
Closing this since it doesn't seem like we can do anything to help, but please reopen if you find an issue with this library.
