### ISSUE TITLE
Convert Enum Value to Name

### ISSUE THREAD

**Issue by totalhack** [googleads/google-ads-python#489]
I've read the documentation [here](https://developers.google.com/google-ads/api/docs/client-libs/python/protobuf-messages#retrieving_enum_names) regarding the changes with v10, but the example for "Retrieving enum names" doesn't quite show what I think it intends...

The protobuf way allowed you use the Name method to get a enum name from an enum int directly. So this worked:

`status_enum.CampaignStatus.Name(1)`

But the proto-plus example is not really showing the same thing. It assumes you have or can get a status object, rather than just having an int.

```
campaign = client.get_type("Campaign")
campaign.status = client.enums.CampaignStatusEnum.PAUSED
# To read the name of campaign status
print(campaign.status.name)
```

So what is the proper way with proto-plus to convert from an int to the name? One hacky way would be to create a reverse map from `client.enums.CampaignStatusEnum.__members__`, but I'm hoping there is something better. 

In case you are wondering about the use case, I'm getting rows back from a query and converting `to_dict` to operate on the row as I had been previously. That automatically converts the enums to values rather than names. In the past with protobuf I could just pass that value to `Name` and swap in the "name" corresponding to that value.

**Comment by totalhack** [comment]
OK, looks like I just wasn't familiar enough with the python Enum type this is using now. Something like this works:

`client.get_type("CampaignStatusEnum").CampaignStatus(1).name`

or 

`client.enums.CampaignStatusEnum(1).name`

**Comment by poojitha-gandra25** [comment]
Hi i see you are converting to_dict to operate on the row . In my case some columns in the GAQL query are seen as field_masks -> 
'fieldMask': 'adGroupCriterion.criterionId,adGroupCriterion.keyword.text,segments.date,campaign.id,customer.currencyCode,customer.descriptiveName,customer.timeZone,campaign.biddingStrategy,campaign.biddingStrategyType,biddingStrategy.name,segments.clickType,campaign.name,campaign.status,segments.conversionActionCategory,segments.conversionAction,segments.conversionActionName,segments.device,adGroupCriterion.positionEstimates.estimatedAddClicksAtFirstPositionCpc,adGroupCriterion.positionEstimates.estimatedAddCostAtFirstPositionCpc,customer.id,adGroupCriterion.positionEstimates.firstPageCpcMicros,adGroupCriterion.positionEstimates.firstPositionCpcMicros,adGroupCriterion.urlCustomParameters,adGroupCriterion.negative,adGroupCriterion.keyword.matchType,adGroupCriterion.qualityInfo.postClickQualityScore,adGroupCriterion.qualityInfo.qualityScore,adGroupCriterion.qualityInfo.searchPredictedCtr,segments.slot,adGroupCriterion.status,adGroupCriterion.systemServingStatus,adGroupCriterion.positionEstimates.topOfPageCpcMicros,adGroup.id', 'requestId': 'PaWYkBUuvL43tO1ut4okCw'}

Could you please suggest how you can retrieve these columns and their values?
