### ISSUE TITLE
CALL_ONLY_AD enum value (6) no longer exists

### ISSUE THREAD

**Issue by totalhack** [googleads/google-ads-python#490]
**Describe the bug:**

I'm upgrading from client library version v8.x to v13.0.0 and got the following error when trying to sync CALL_ONLY_ADs:

`ValueError: 6 is not a valid AdType`

The ad_group_ad.ad.type_ value is the integer 6 after doing `to_dict` on the row returned from the search API. Yet the enum for `AdType` seems to no longer have that value (excerpt from vars() output shown below):

```
              '_value2member_map_': {0: <AdType.UNSPECIFIED: 0>,
                                     1: <AdType.UNKNOWN: 1>,
                                     2: <AdType.TEXT_AD: 2>,
                                     3: <AdType.EXPANDED_TEXT_AD: 3>,
                                     7: <AdType.EXPANDED_DYNAMIC_SEARCH_AD: 7>,
                                     8: <AdType.HOTEL_AD: 8>,
                                     9: <AdType.SHOPPING_SMART_AD: 9>,
                                     10: <AdType.SHOPPING_PRODUCT_AD: 10>,
                                     12: <AdType.VIDEO_AD: 12>,
                                     13: <AdType.GMAIL_AD: 13>,
                                     14: <AdType.IMAGE_AD: 14>,
                                     15: <AdType.RESPONSIVE_SEARCH_AD: 15>,
                                     16: <AdType.LEGACY_RESPONSIVE_DISPLAY_AD: 16>,
                                     17: <AdType.APP_AD: 17>,
                                     18: <AdType.LEGACY_APP_INSTALL_AD: 18>,
                                     19: <AdType.RESPONSIVE_DISPLAY_AD: 19>,
                                     20: <AdType.LOCAL_AD: 20>,
                                     21: <AdType.HTML5_UPLOAD_AD: 21>,
                                     22: <AdType.DYNAMIC_HTML5_AD: 22>,
                                     23: <AdType.APP_ENGAGEMENT_AD: 23>,
                                     24: <AdType.SHOPPING_COMPARISON_LISTING_AD: 24>,
                                     25: <AdType.VIDEO_BUMPER_AD: 25>,
                                     26: <AdType.VIDEO_NON_SKIPPABLE_IN_STREAM_AD: 26>,
                                     27: <AdType.VIDEO_OUTSTREAM_AD: 27>,
                                     28: <AdType.VIDEO_TRUEVIEW_DISCOVERY_AD: 28>,
                                     29: <AdType.VIDEO_TRUEVIEW_IN_STREAM_AD: 29>,
                                     30: <AdType.VIDEO_RESPONSIVE_AD: 30>,
                                     31: <AdType.SMART_CAMPAIGN_AD: 31>,
                                     32: <AdType.CALL_AD: 32>}})
```

**Expected behavior:**

The enum value 6 for the ad type, which is returned by the API, should map to CALL_ONLY_AD as it did before. 

**Client library version and API version:**

Client library version: v13
Google Ads API version: v7

```
google-ads==13.0.0
google-api-core==1.31.2
google-api-python-client==2.0.2
google-auth==1.35.0
google-auth-httplib2==0.1.0
google-auth-oauthlib==0.4.5
googleads==28.0.0
googleapis-common-protos==1.53.0
```

EDIT: I see that from v7 to v8 of the Google Ads API the CALL_ONLY_AD type is changed/removed and replaced by CALL_AD. But I still think this is a bug. Either Google Ads API v7 is not supported when using v13 of this library and it should fail with a message to that effect, or CALL_ONLY_AD should have been left in the enum (a better intermediate solution in my opinion).

At any rate I will have to jump to v8 it seems. Was hoping to do this more incrementally since there are so many breaking changes.

**Comment by BenRKarl** [comment]
Hi @totalhack - `CALL_ONLY_AD` has been replaced with `CALL_AD`, see this [blog post](https://ads-developers.googleblog.com/2021/06/call-ads-replace-call-only-ads-in.html) for details. 

Also you _can_ use `v8` of the API with version 12.0.0 and above of this client library. There are a few new features in `v8_1` that are only available in version `14.0.0` though, which are outlined in the [release notes](https://developers.google.com/google-ads/api/docs/release-notes#v810_2021-08-11). If your concern is upgrading to version `14.0.0` due to the changes in protobuf messages, you can set the new config parameter `use_proto_plus` to `True` (as described [here](https://github.com/googleads/google-ads-python/issues/486)) and the library will function as it does for version `13.0.0`.

Hope that helps!
