### ISSUE TITLE
Please update nox

### ISSUE THREAD

**Issue by regiohelden-dev** [googleads/google-ads-python#492]
**Describe the problem you are trying to solve:**
The currently pinned release of `nox==2020.12.31` prevents installing the latest releases of `colorlog`.

**Describe the solution you'd like:**
Please update nox to a more recent release as it currently prevents upgrading colorlog.
`nox==2020.12.31` has [colorlog==<5.0.0](https://github.com/theacodes/nox/blob/319c796f6de7d5706d75da107ec20568ad5baf51/setup.py#L54) pinned whereas `nox==2021.6.12` allows up to [<7.0.0](https://github.com/theacodes/nox/blob/787dfaa87eb47c590e407acb0b5a63922725c291/setup.py#L54)

**Describe alternatives you've considered:**
No alternative as long as nox is used.

**Additional context:**

**Comment by wihl** [comment]
This has been addressed in https://github.com/googleads/google-ads-python/pull/495
