### ISSUE TITLE
ModuleNotFoundError: No module named 'google.ads.google_ads'

### ISSUE THREAD

**Issue by roundrobin** [googleads/google-ads-python#497]
**Describe the bug:**
`ModuleNotFoundError: No module named 'google.ads.google_ads'`

**Steps to Reproduce:**
```
import google.ads.google_ads.client
GOOGLE_ADS_SERVICE = _ADS_CLIENT.get_service("GoogleAdsService", version="v8")
```
After installing the package I can't seem to use it in my python script.

**Expected behavior:**

**Client library version and API version:**
Client library version: google-ads==12.0.0
Google Ads API version: v8
Python Version: Python 3.6.9 :: Anaconda, Inc.
pip 21.2.4 from (python 3.6)

**Comment by laurachevalier4** [comment]
Hey @roundrobin. As of client library version 10.0.0, the package should be imported as: 
```
import google.ads.googleads.client
```
where `google_ads` becomes `googleads`. You can see this in any of our examples as well (e.g. [create_customer.py](https://github.com/googleads/google-ads-python/blob/main/examples/account_management/create_customer.py#L28)). Hope this helps!

**Comment by roundrobin** [comment]
Perfect thanks!
