### ISSUE TITLE
The required field was not present

### ISSUE THREAD

**Issue by deepakinfoweb** [googleads/google-ads-python#500]
We have tried to add products to the "product group". We are getting the error "The required field was not present.". We have used the listing group type 'Unit' instead of 'SUBDIVISION'.

google reference link:https://developers.google.com/google-ads/api/reference/rpc/v7/ListingGroupTypeEnum.ListingGroupType

Request :

[{"create": {
"resource_name": "customers/7370860149/adGroupCriteria/125570209334~-1",
"status": "ENABLED",
"listing_group": {
"type_": "UNIT",
"case_value": {
"product_item_id": {
"value": "4309645"
}
}
}
}}]

Response:

Request made: ClientCustomerId: 7370860149, Host: googleads.googleapis.com, Method: /google.ads.googleads.v8.services.AdGroupCriterionService/MutateAdGroupCriteria, RequestId: Q77qbmf_DLxStVWee378aA, IsFault: True, FaultMessage: The required field was not present.
Request with ID 'Q77qbmf_DLxStVWee378aA' failed with status 'INVALID_ARGUMENT' and includes the following errors:
Error with message 'The required field was not present.'.
On field: operations
On field: create
On field: listing_group
On field: parent_ad_group_criterion

**Comment by BenRKarl** [comment]
You need to set the `parent_ad_group_criterion` with the resource name of the criterion that represents the root node of the tree, see [here](https://github.com/googleads/google-ads-python/blob/main/examples/shopping_ads/add_shopping_product_listing_group_tree.py#L377) for an example.
