### ISSUE TITLE
Listing group referenced in the operation was not found in the ad group.

### ISSUE THREAD

**Issue by deepakinfoweb** [googleads/google-ads-python#501]
We have also added **parent_ad_group_criterion**  in the request. Still, We are getting the error The required field was not present.

Request input json :
[{"create": {
        "resource_name": "customers/7370860149/adGroupCriteria/125570209334~-1",
        "status": "ENABLED",
        "listing_group": {
            "type_": "UNIT",
            "case_value": {
                "product_item_id": {
                    "value": "4309645"
                }
            },
            "parent_ad_group_criterion": "customers/7370860149/adGroupCriteria/125570209334~-1"
        }
    }}]

Response : 

Request made: ClientCustomerId: 7370860149, Host: googleads.googleapis.com, Method: /google.ads.googleads.v8.services.AdGroupCriterionService/MutateAdGroupCriteria, RequestId: ML0n3nvxfc6VX1TNxmoTcA, IsFault: True, FaultMessage: Listing group referenced in the operation was not found in the ad group.
Request with ID 'ML0n3nvxfc6VX1TNxmoTcA' failed with status 'INVALID_ARGUMENT' and includes the following errors:
        Error with message 'Listing group referenced in the operation was not found in the ad group.'.
                On field: operations
                On field: create
                On field: listing_group
                On field: parent_ad_group_criterion

**Comment by BenRKarl** [comment]
@deepakinfoweb In your logs here the resource name for the parent ad group criterion is the same as what's specified for the child criterion. Your requests should first create a root node criterion, then use the resource name for that criterion as the parent for additional `UNIT` criterion. See [this example](https://github.com/googleads/google-ads-python/blob/main/examples/shopping_ads/add_shopping_product_listing_group_tree.py) for reference, specifically line [77](https://github.com/googleads/google-ads-python/blob/main/examples/shopping_ads/add_shopping_product_listing_group_tree.py#L77), which shows the root node being created.
