### ISSUE TITLE
how do to we add product_item_id to product group using api 

### ISSUE THREAD

**Issue by deepakinfoweb** [googleads/google-ads-python#503]
We have already implemented the code from the mentioned (1). But we are stuck on how do we add product_item_id(2) to the newly generated category "New Product group". Please help us on that

1) **Add Shopping Product Listing Group Tree**  Link : 
https://developers.google.com/google-ads/api/docs/samples/add-shopping-product-listing-group-tree?hl=en#python

2)**ProductItemIdInfo** : https://developers.google.com/google-ads/api/reference/rpc/v8/ProductItemIdInfo

Response :

Removing existing listing group tree...
Found an ad group criterion with resource name: 'customers/7370860149/adGroupCriteria/125570209334~293946777986'.
Removed 1 ad group criteria.
request ::::: [create {
  resource_name: "customers/7370860149/adGroupCriteria/125570209334~-1"
  status: ENABLED
  listing_group {
    type_: SUBDIVISION
  }
}
, create {
  status: ENABLED
  listing_group {
    type_: UNIT
    case_value {
      product_condition {
        condition: NEW
      }
    }
    parent_ad_group_criterion: "customers/7370860149/adGroupCriteria/125570209334~-1"
  }
  ad_group: "customers/7370860149/adGroups/125570209334"
}
, create {
  resource_name: "customers/7370860149/adGroupCriteria/125570209334~-2"
  status: ENABLED
  listing_group {
    type_: SUBDIVISION
    case_value {
      product_condition {
      }
    }
    parent_ad_group_criterion: "customers/7370860149/adGroupCriteria/125570209334~-1"
  }
}
, create {
  status: ENABLED
  listing_group {
    type_: UNIT
    case_value {
      product_brand {
        value: "New Product group"
      }
    }
    parent_ad_group_criterion: "customers/7370860149/adGroupCriteria/125570209334~-2"
  }
  ad_group: "customers/7370860149/adGroups/125570209334"
}
, create {
  status: ENABLED
  listing_group {
    type_: UNIT
    case_value {
      product_brand {
      }
    }
    parent_ad_group_criterion: "customers/7370860149/adGroupCriteria/125570209334~-2"
  }
  ad_group: "customers/7370860149/adGroups/125570209334"
}
]
Added ad group criteria for the listing group tree with the following resource names:
	customers/7370860149/adGroupCriteria/125570209334~293946777986
	customers/7370860149/adGroupCriteria/125570209334~297302142375
	customers/7370860149/adGroupCriteria/125570209334~297302142215
	customers/7370860149/adGroupCriteria/125570209334~1426284292462
	customers/7370860149/adGroupCriteria/125570209334~295737126946
5 criteria added.

**Comment by BenRKarl** [comment]
Hi @deepakinfoweb you would need to set the [`product_item_id`](https://developers.google.com/google-ads/api/reference/rpc/v8/ListingDimensionInfo?hl=en#product_item_id) field on the `ListingDimensionInfo` objects created in [this example](https://github.com/googleads/google-ads-python/blob/main/examples/shopping_ads/add_shopping_product_listing_group_tree.py#L96).
