### ISSUE TITLE
AttributeError: '_StreamingResponseIterator' object has no attribute 'DESCRIPTOR'

### ISSUE THREAD

**Issue by hamzavg** [googleads/google-ads-python#505]
**Describe the bug:**
I am attempting to ultimately create a dataframe with the response from a GAQL Query via GoogleAdsClient

I am able to correctly query with the follow:
`response = client.get_service('GoogleAdsService', version="v8").search_stream(customer_id=customer_id, query=query)
`
I am able to see the output of the query by simply calling `batch.results'

I am attempting to convert it into a JSON to then map into a dataframe

But when I try to convert `batch.results` into a JSON or dict for data processing, it shoots the errors below

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/hamzahasham/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/google/protobuf/json_format.py", line 137, in MessageToJson
    return printer.ToJsonString(message, indent, sort_keys)
  File "/Users/hamzahasham/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/google/protobuf/json_format.py", line 204, in ToJsonString
    js = self._MessageToJsonObject(message)
  File "/Users/hamzahasham/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/google/protobuf/json_format.py", line 209, in _MessageToJsonObject
    message_descriptor = message.DESCRIPTOR
AttributeError: '_StreamingResponseIterator' object has no attribute 'DESCRIPTOR'
```

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/hamzahasham/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/google/protobuf/json_format.py", line 175, in MessageToDict
    return printer._MessageToJsonObject(message)
  File "/Users/hamzahasham/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/google/protobuf/json_format.py", line 209, in _MessageToJsonObject
    message_descriptor = message.DESCRIPTOR
AttributeError: 'google.protobuf.pyext._message.RepeatedCompositeCo' object has no attribute 'DESCRIPTOR'
```

**Expected behavior:**
Turn a protobuf MessageToJson and/or MessageToDict functions

**Client library version and API version:**
Client library version:
Google Ads API version:

alembic==1.7.1
anyio==3.3.0
apache-airflow==2.1.3
apache-airflow-providers-ftp==2.0.1
apache-airflow-providers-http==2.0.0
apache-airflow-providers-imap==2.0.1
apache-airflow-providers-snowflake==2.0.0
apache-airflow-providers-sqlite==2.0.1
apispec==3.3.2
argcomplete==1.12.3
asn1crypto==1.4.0
attrs==20.3.0
azure-common==1.1.27
azure-core==1.18.0
azure-storage-blob==12.8.1
Babel==2.9.1
backoff==1.11.1
backports.entry-points-selectable==1.1.0
beautifulsoup4==4.10.0
blinker==1.4
boto3==1.18.36
botocore==1.21.36
cachetools==4.2.2
cattrs==1.5.0
certifi==2021.5.30
cffi==1.14.6
chardet==4.0.0
charset-normalizer==2.0.4
click==7.1.2
clickclick==20.10.2
colorama==0.4.4
colorlog==4.8.0
commonmark==0.9.1
croniter==1.0.15
cryptography==3.4.8
defusedxml==0.7.1
dill==0.3.4
distlib==0.3.3
dnspython==2.1.0
docutils==0.16
email-validator==1.1.3
filelock==3.0.12
Flask==1.1.4
Flask-AppBuilder==3.3.2
Flask-Babel==1.0.0
Flask-Caching==1.10.1
Flask-JWT-Extended==3.25.1
Flask-Login==0.4.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.5.1
Flask-WTF==0.14.3
flatten-json==0.1.13
google==3.0.0
google-ads==14.0.0
google-api-core==1.31.2
google-api-python-client==1.12.8
google-auth==1.35.0
google-auth-httplib2==0.1.0
google-auth-oauthlib==0.4.6
google-cloud-core==2.0.0
google-cloud-translate==3.4.0
googleapis-common-protos==1.53.0
graphviz==0.17
greenlet==1.1.1
grpcio==1.40.0
gspread==4.0.1
gunicorn==20.1.0
h11==0.12.0
httpcore==0.13.6
httplib2==0.19.1
httpx==0.19.0
idna==3.2
importlib-metadata==4.8.1
importlib-resources==1.5.0
inflection==0.5.1
iso8601==0.1.16
isodate==0.6.0
itsdangerous==1.1.0
Jinja2==2.11.3
jmespath==0.10.0
jsonschema==3.2.0
lazy-object-proxy==1.6.0
lockfile==0.12.2
Mako==1.1.5
Markdown==3.3.4
marketorestpython==0.5.12
MarkupSafe==1.1.1
marshmallow==3.13.0
marshmallow-enum==1.5.1
marshmallow-oneofschema==3.0.1
marshmallow-sqlalchemy==0.23.1
msrest==0.6.21
nox==2020.12.31
numpy==1.21.2
oauth2client==4.1.3
oauthlib==3.1.1
openapi-schema-validator==0.1.5
openapi-spec-validator==0.3.1
oscrypto==1.2.1
packaging==21.0
pandas==1.3.2
pendulum==2.1.2
platformdirs==2.3.0
prison==0.2.1
proto-plus==1.18.1
protobuf==3.4.0
psutil==5.8.0
py==1.10.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pycryptodomex==3.10.1
Pygments==2.10.0
PyJWT==1.7.1
pyOpenSSL==20.0.1
pyparsing==2.4.7
pyrsistent==0.18.0
python-daemon==2.3.0
python-dateutil==2.8.2
python-nvd3==0.15.0
python-slugify==4.0.1
python3-openid==3.2.0
pytz==2021.1
pytzdata==2020.1
PyYAML==5.4.1
requests==2.26.0
requests-oauthlib==1.3.0
rfc3986==1.5.0
rich==10.9.0
rsa==4.7.2
s3transfer==0.5.0
setproctitle==1.2.2
six==1.16.0
sniffio==1.2.0
snowflake-connector-python==2.6.0
snowflake-sqlalchemy==1.2.5
soupsieve==2.2.1
SQLAlchemy==1.3.24
SQLAlchemy-JSONField==1.0.0
SQLAlchemy-Utils==0.37.8
swagger-ui-bundle==0.0.8
tabulate==0.8.9
tenacity==6.2.0
termcolor==1.1.0
text-unidecode==1.3
unicodecsv==0.14.1
uritemplate==3.0.1
urllib3==1.26.6
virtualenv==20.8.0
Werkzeug==1.0.1
WTForms==2.3.3
zipp==3.5.0

**Request/Response Logs:**

 
**Anything else we should know about your project / environment:**

**Comment by BenRKarl** [comment]
@hamzavg can you confirm whether you have the `use_proto_plus` configuration set to `True`? Based on the above I'm assuming you do. It looks like you're trying to convert a `proto-plus` message to JSON using the workflow for a regular `protobuf` message. See [these docs](https://developers.google.com/google-ads/api/docs/client-libs/python/protobuf-messages#serializing_to_json) that show the different ways to handle converting the two message types to JSON.
