### ISSUE TITLE
ImportError: No module named google_auth_oauthlib.flow

### ISSUE THREAD

**Issue by jcherian** [googleads/google-ads-python#506]
Can you please address my question below with ads-api support's referral?

Thanks,

Johns

Trying to follow Step 3 in the following [link](https://developers.google.com/google-ads/api/docs/client-libs/python/oauth-desktop) on your site. My client secrets file is in the same folder as my authenticating script from which I am executing the script.

Also tried as an Admin user.

Admin@Johnss-MacBook-Pro authentication % ./authenticate_in_desktop_application.py --client_secrets_path="./client_secret_668523324263-17e6ooohj9rea1n086apnmdmfbbkfo57.apps.googleusercontent.com.json"

Traceback (most recent call last):

  File "./authenticate_in_desktop_application.py", line 26, in <module>

    from google_auth_oauthlib.flow import InstalledAppFlow

ImportError: No module named google_auth_oauthlib.flow

Admin@Johnss-MacBook-Pro authentication % 

Thanks,

Johns

-----------ads-api support's referral---------------------------
<div dir="ltr" class="gmail_attr" style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">---------- Forwarded message ---------<br>From:<span> </span><strong class="gmail_sendername" dir="auto">Google Ads API Direct Support</strong><span> </span><span dir="auto">&lt;googleadsapi-support@google.com&gt;</span><br>Date: Mon, Sep 27, 2021 at 11:41 PM<br>Subject: RE: Error in running authentication script for desktop oauth flow on mac book<br>To: jcherian@gmail.com &lt;jcherian@gmail.com&gt;<br></div><br style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Hi Johns,<br><br>Thank you for reaching out to our API support team.<br><br>In the trace that you sent over, I can see that it's returning the "<i>ImportError: No module named google_auth_oauthlib.flow</i>". This may indicate an issue in your Python setup and is likely outside of our API support team's scope.<br><br>That said, I would recommend that you reach out instead to the Python client library owners, via this<span> </span><a href="https://github.com/googleads/google-ads-python/issues" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://github.com/googleads/google-ads-python/issues&amp;source=gmail&amp;ust=1632931287421000&amp;usg=AFQjCNHIfx2hA0ZrREPGmn3nP7_9_E_sJQ" style="color: rgb(17, 85, 204);">link</a>, for further assistance.<br><br>Best regards,<br><br>

Peter Laurence Napa OliquinoGoogle Ads API Team |   | Peter Laurence Napa OliquinoGoogle Ads API Team | Peter Laurence Napa Oliquino | Google Ads API Team
-- | -- | -- | -- | --
  | Peter Laurence Napa OliquinoGoogle Ads API Team | Peter Laurence Napa Oliquino | Google Ads API Team
Peter Laurence Napa Oliquino
Google Ads API Team
 

<img src="https://ci4.googleusercontent.com/proxy/ACI-gt0x5aqNQ9K0it_FXE_Qw6voVmVINRPAKnC95bcfEBDoH7V24afSNMoTEhJGRChwSWdB3abBCni2rTLzb848QghT5crI9_RlIyteuwg_FBqqWU0IsK51t-bGJFyRvZWC_3yMcqg89UbfoMGuUTBM_zRTESj7ghUBZJOvfbnSqY3V80KCIE03Cmflp3w=s0-d-e1-ft#https://google-dev-relations.my.salesforce.com/servlet/servlet.ImageServer?oid=00D1U000001174p&amp;esid=0184Q00001E6aES&amp;from=ext"><br><br>ref:_00D1U1174p._5004Q2OUZqt:<wbr>ref</div>

**Comment by davedavis** [comment]
Hi @jcherian
Can you post the exact code you're using, including the import statements?

Could you also post the output of the "pip freeze" command?

**Comment by BenRKarl** [comment]
@jcherian as @davedavis implied it looks like you need to install the library's dependencies. See [this guide](https://developers.google.com/google-ads/api/docs/client-libs/python/installation#installing_the_library_from_github) on how to install the library from GitHub. Namely, see step number `3` where you need to run `python -m pip install .` from the root directory, that should install the necessary module here.
