### ISSUE TITLE
The error code is not in this version

### ISSUE THREAD

**Issue by vzpd** [googleads/google-ads-python#507]
Hello,
I´ve got this issue when I try to edit a budget.
![image](https://user-images.githubusercontent.com/28712045/135226142-5e183bdd-cf83-4b9e-89fd-be6ddd87e44a.png)
"requestId": "2943VLA4FzYS2AphRmwqTw"

**Comment by BenRKarl** [comment]
@vzpd It appears that there's an issue with how your payment profile is configured. Would you please reach out to [our support team](https://developers.google.com/google-ads/api/support) for assistance?
