### ISSUE TITLE
 Client library configuration is missing the required "use_proto_plus" key

### ISSUE THREAD

**Issue by samsamph** [googleads/google-ads-python#509]
Hi, I'm getting an error whenever I run my code. This issue is recent, has there been any changes that I'm not aware of. How do I update my code to comply with the new protocol. Here's the full error: The client library configuration is missing the required "use_proto_plus" key. Please set this option to either "True" or "False". For more information about this option see the Protobuf Messages guide: https://developers.google.com/google-ads/api/docs/client-libs/python/protobuf-messages

It says that I need to set "use_proto_plus" key to True. But It doesn't say which part of the code to add it to. Has anyone encountered this issue? What did you do to get around the error? Appreciate your help. Thanks

**Comment by wihl** [comment]
Add it to your `google-ads.yaml` like in [this example](https://github.com/googleads/google-ads-python/blob/5079490a5f5faa128a7edf050c80baa1addeaf9f/google-ads.yaml#L18).
