### ISSUE TITLE
Which the name of the statuses refer to the value of the statuses?

### ISSUE THREAD

**Issue by Ryo-Oku** [googleads/google-ads-python#510]
**What is your question?**

Hello

I have the question about this: 
https://github.com/googleads/google-ads-python/blob/main/google/ads/googleads/v8/enums/types/ad_group_ad_status.py

Which the name of the statuses refer to the value of the statuses?

UNSPECIFIED=0
UNKNOWN=1
ENABLED=2
PAUSED=3
REMOVED=4

Are these correct?

What will be the status when I get an ad that has not been approved?

Thanks,

**Comment by BenRKarl** [comment]
Hi @Ryo-Oku - to know whether an ad is approved, you would need to inspect a different field, which is [`ad_group_ad.policy_summary.approval_status`](https://developers.google.com/google-ads/api/reference/rpc/v8/AdGroupAdPolicySummary#approval_status). Hope that answers your question, please reopen this if not and add some additional detail.
