### ISSUE TITLE
Specified type 'google_ads_failure' does not exist in Google Ads API v8

### ISSUE THREAD

**Issue by elad2109** [googleads/google-ads-python#511]
I have two issues:

I'm calling G-Ads API to bulk remove ads ([code](https://github.com/google/bowling-compliance-ads-remover/blob/main/src/main.py#L440))

    for error_detail in error_details:
                # Retrieve an instance of the google_ads_failure class from the client
                failure_message = gAdsServiceWrapper.client.get_type("google_ads_failure")
                # Parse the string into a google_ads_failure message instance.
                # To access class-only methods on the message we retrieve its type.
                google_ads_failure = type(failure_message)
                failure_object = google_ads_failure.deserialize(error_detail.value)
    
                for error in failure_object.errors:
                    # Construct and print a string that details which element in
                    # the above ad_group_operations list failed (by index number)
                    # as well as the error message and error code.
                    print("A partial failure at index "
                          f"{error.location.field_path_elements[0].index} occurred "
                          f"\nError message: {error.message}\nError code: "
                          f"{error.error_code}")
                    index_array.append(error.location.field_path_elements[0].index)
                    error_array.append({"error_message": error.message, "error_code": error.error_code})

1) I get a partial error
2) And the code fails to parse it (taken form the official [website]( https://developers.google.com/google-ads/api/docs/samples/handle-partial-failure?hl=uk#python))

My terminal shows:

Partial failures occurred. Details will be shown below.

```
Traceback (most recent call last):
  File "D:\projects\bowling\venv\lib\site-packages\google\ads\googleads\client.py", line 426, in get_type
    message_class = getattr(type_classes, name)
  File "D:\projects\bowling\venv\lib\site-packages\google\ads\googleads\v8\__init__.py", line 1753, in __getattr__
    raise AttributeError(f"unknown type {name!r}.")
AttributeError: unknown type 'google_ads_failure'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\projects\bowling\src\main.py", line 535, in <module>
    main(args.top_id)
  File "D:\projects\bowling\src\main.py", line 141, in main
    removed_ads_count = remove_disapproved_ads_for_account(account)
  File "D:\projects\bowling\src\main.py", line 206, in remove_disapproved_ads_for_account
    remove_ads(ad_removal_operations, ads_to_remove_json, account_id)
  File "D:\projects\bowling\src\main.py", line 300, in remove_ads
    index_array, error_array = _print_results(response_chunk)
  File "D:\projects\bowling\src\main.py", line 439, in _print_results
    failure_message = gAdsServiceWrapper.client.get_type("google_ads_failure")
  File "D:\projects\bowling\venv\lib\site-packages\google\ads\googleads\client.py", line 428, in get_type
    raise ValueError(
ValueError: Specified type 'google_ads_failure' does not exist in Google Ads API v8
```

**Comment by BenRKarl** [comment]
Hi @elad2109  - when calling `get_type` you'll want to use the name of the protobuf message, which in this case is [GoogleAdsFailure](https://developers.google.com/google-ads/api/reference/rpc/v8/GoogleAdsFailure), so to be specific:

```
failure_message = gAdsServiceWrapper.client.get_type("GoogleAdsFailure")
```

See also our complete [`handle_partial_failure`](https://github.com/googleads/google-ads-python/blob/main/examples/error_handling/handle_partial_failure.py#L173) example, which it seems you'r emulating here.

Hope that helps!

**Comment by elad2109** [comment]
Thanks, do you know where I got this mistake from?

`failure_message = gAdsServiceWrapper.client.get_type("google_ads_failure")`

I'm sure I copied it from an official doc. I didn't write it myslef.

**Comment by BenRKarl** [comment]
@elad2109 I do not, the interface for `get_type` has always been the same. It looks like the change was made in [this commit](https://github.com/google/bowling-compliance-ads-remover/commit/6ba44c1b3392aea237af5e671928bac90e18ab09) about two weeks ago.
