### ISSUE TITLE
Google Ads API error -- Fatal error: Uncaught Error: Class 'Google\Auth\OAuth2' not found in /var/www/html/google-ads-php/examples/Authentication/AuthenticateInDesktopApplication.php:71 

### ISSUE THREAD

**Issue by rinkisub** [googleads/google-ads-python#512]
OS : linux
Technology : PHP 

I have follow all steps, but still facing error.
![image](https://user-images.githubusercontent.com/90371446/136004808-023aa3f0-5223-480f-875e-94180f386316.png)

Please help

**Comment by BenRKarl** [comment]
Hi @rinkisub - this page is only for issues related to the Python client library, since I see that you've already opened an issue with the correct PHP library ([google-ads-php](https://github.com/googleads/google-ads-php/issues)), I'm going to close this out.
