### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by XinyuTian** [googleads/google-ads-python#517]
When I make multiple requests of `SearchGoogleAdsStreamRequest` and process the downloaded data in sequential, after 30-60 minutes the connection fails with the following error message. 

```
Request made: ClientCustomerId: 6837196774, Host: googleads.googleapis.com, Method: /google.ads.googleads.v8.services.GoogleAdsService/SearchStream, RequestId: None, IsFault: True, FaultMessage: Connection reset by peer
Traceback (most recent call last):
  File "/stitchfix/z-pyenv/pyenv/versions/3.8/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 106, in __next__
    return next(self._wrapped)
  File "/stitchfix/z-pyenv/pyenv/versions/3.8/lib/python3.8/site-packages/google/ads/googleads/interceptors/response_wrappers.py", line 98, in __next__
    raise e
  File "/stitchfix/z-pyenv/pyenv/versions/3.8/lib/python3.8/site-packages/google/ads/googleads/interceptors/response_wrappers.py", line 95, in __next__
    self._failure_handler(self._underlay_call)
  File "/stitchfix/z-pyenv/pyenv/versions/3.8/lib/python3.8/site-packages/google/ads/googleads/interceptors/exception_interceptor.py", line 71, in _handle_grpc_failure
    raise self._get_error_from_response(response)
  File "/stitchfix/z-pyenv/pyenv/versions/3.8/lib/python3.8/site-packages/google/ads/googleads/interceptors/response_wrappers.py", line 85, in __next__
    message = next(self._underlay_call)
  File "/stitchfix/z-pyenv/pyenv/versions/3.8/lib/python3.8/site-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/stitchfix/z-pyenv/pyenv/versions/3.8/lib/python3.8/site-packages/grpc/_channel.py", line 642, in _next
    return self._next_response()
  File "/stitchfix/z-pyenv/pyenv/versions/3.8/lib/python3.8/site-packages/grpc/_channel.py", line 617, in _next_response
    raise self
grpc._channel._SingleThreadedRendezvous: <_SingleThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connection reset by peer"
	debug_error_string = "{"created":"@1634246959.841699306","description":"Error received from peer ipv4:142.251.45.106:443","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"Connection reset by peer","grpc_status":14}"
```

**Comment by BenRKarl** [comment]
Thanks @XinyuTian - can you clarify whether the `ga_service` object stays in the same function scope while you're processing the stream? For context see [these docs](https://developers.google.com/google-ads/api/docs/client-libs/python/streaming-iterators). If the service is initialized in a different scope from where the stream is processed, it can cause the connection to be closed.

**Comment by XinyuTian** [comment]
@BenRKarl Are you still working on it? Thanks!

**Comment by XinyuTian** [comment]
@BenRKarl Here I attached the complete code in case you wonder where ga_service is defined. Btw, client is defined in a different scope. 
```    
ga_service = client.get_service("GoogleAdsService")

query = create_reports_query(SOME_ARGS)

df = pd.DataFrame()

for cc_id in google_ads_client_customer_id:
    logger.info(f"Downloading from client customer ID: {cc_id}...")

    # Download reports.
    report_request = client.get_type("SearchGoogleAdsStreamRequest")
    report_request.customer_id = cc_id.replace("-", "")
    report_request.query = query
    response = ga_service.search_stream(report_request)

    for batch in response:
        for row in batch.results:
            df = df.append([list(attrgetter(attr)(row))])
    logger.info(f"Size of the data {df.shape}")
```

**Comment by grace-zavolock** [comment]
Hi @BenRKarl - any thoughts on why this connection failure could be happening?

**Comment by BenRKarl** [comment]
Hi @XinyuTian - sorry for the delay, I'm still working through this one, will try to have an update soon. Thank you for your patience.

**Comment by XinyuTian** [comment]
@BenRKarl Do you have an ETA when this will be fixed? We can better make our work plans based on it.

**Comment by BenRKarl** [comment]
Hi @XinyuTian after asking around for advice from other domain experts, it seems the issue might be that you're hitting the time 60 minute time limit for maintaining an open connection to our servers. To remedy this, you can either call `get_service` to recreate a new gRPC channel, or update your logic to handle dropped gRPC connections and restart your process from where it left off.

I think the quickest test would be to try creating a new channel via `get_service` before 60 minutes is up to see if that helps you get through your requests without errors, then to decide which implementation suggested above it preferable.

Let me know if you have any questions!

**Comment by XinyuTian** [comment]
Hi @BenRKarl  thank you for the inputs. I doubt if it's a 60 minute time limit because most of them failed at 30-40 minutes. 
I tried to re-connect via `get_service ` for each each request, but this single request takes more than 30 minutes and it failed at ~35 minutes in. I have already break down the jobs, so each request is relatively small. How do I create a new channel while running this?
```
response = ga_service.search_stream(report_request)
for batch in response:
    for row in batch.results:
        XXXXXXXXXX
```

**Comment by BenRKarl** [comment]
@XinyuTian Hmmm, ok, there might be a different issue going on here. I'd like to investigate this further using more specific details about your account. You mentioned that you already opened a Case with our support team, right? Would you please respond to that Case and ask that they escalate it to me? You can reference this Issue. I'll close this for now since this doesn't seem to be an issue with this client library.

**Comment by gonzaatcroud** [comment]
> Hi @XinyuTian after asking around for advice from other domain experts, it seems the issue might be that you're hitting the time 60 minute time limit for maintaining an open connection to our servers. To remedy this, you can either call `get_service` to recreate a new gRPC channel, or update your logic to handle dropped gRPC connections and restart your process from where it left off.
> 
> I think the quickest test would be to try creating a new channel via `get_service` before 60 minutes is up to see if that helps you get through your requests without errors, then to decide which implementation suggested above it preferable.
> 
> Let me know if you have any questions!

Hi! Interesting that you mention this 60-minute time limit, if I'm using a SearchStream, how can I pick up after it fails? I could count the number of rows I went through, but that seems impractical given that it might already gone through an hour worth of data and may need to skip over millions of records.
