### ISSUE TITLE
Assignment not allowed to repeated field

### ISSUE THREAD

**Issue by saksham49** [googleads/google-ads-python#524]
**What is your question?**

I was trying to Generate Keyword Ideas by using Google Ads API and I was following this [post](https://www.danielherediamejias.com/python-keyword-planner-google-ads-api/). 

However, on running the code I received the following error:

```
Traceback (most recent call last):
  File ".\keywords.py", line 130, in <module>
    list_keywords = main(client, "472-538-6852", ["2840"], "1000", ["mortgage"], None)
  File ".\keywords.py", line 64, in main
    request.geo_target_constants = location_rns
AttributeError: Assignment not allowed to repeated field "geo_target_constants" in protocol message object.
```

Any assistance would be greatly appreciated!!

**Comment by BenRKarl** [comment]
@saksham49 In your configuration for this client library, what do you have `use_proto_plus` set to? If it's set to `True` this should work fine, however if it's set to `False` (which is appears to be, based on the error message), you should instead use `extend`, for example:

`request.geo_target_constants.extend(location_rns)`

For more details on the behavior for repeated fields, see [these docs](https://developers.google.com/google-ads/api/docs/client-libs/python/protobuf-messages#repeated_fields).

If you have any other questions or issues please reopen this issue!

**Comment by techperfect** [comment]
Very Helpful!!! Thx!
