### ISSUE TITLE
Query parameters escaping

### ISSUE THREAD

**Issue by xzkostyan** [googleads/google-ads-python#525]
**What is your question?**

How user-input parameters can be escaped automatically in query? Are there any particular best practices for this library?

```python
name = ... # user-input variable

query = 'SELECT customer_client.id, customer_client.descriptive_name FROM customer_client WHERE AND customer_client.descriptive_name = "{}"'.format(name)

googleads_service = client.get_service('GoogleAdsService')
googleads_service.search(customer_id=connection.customer_xid, query=query)
```

In example above user can produce `QueryError.BAD_VALUE` if `name = 'tes"t'`.

**Comment by BenRKarl** [comment]
@xzkostyan there's no way for the API to escape quotation marks for you. If you expect your user input to contain quotation marks I recommend escaping them manually before sending them to the API.

**Comment by xzkostyan** [comment]
I meant the library, which makes communication with the API easier, not the API itself. Okay then. I'll write own escaping.
