### ISSUE TITLE
Modifying responsive search ads through the API

### ISSUE THREAD

**Issue by IKlaskyHopjump** [googleads/google-ads-python#529]
**What is your question?**

I was referred to post here from the Google Ads API Team as I had an implementation related question. I would like to modify text in existing responsive search ads through the API, but the only example for modifying ad text is for expanded text ads [here](https://developers.google.com/google-ads/api/docs/ads/mutate-ads?hl=en). Any guidance on implementing this for responsive search ads would be appreciated.

**Comment by BenRKarl** [comment]
Hi @IKlaskyHopjump - modifying an existing RSA is pretty similar to modifying a text ad. Let's say you are starting with an ad ID for an RSA, like in the example you linked. You just modify the [`responsive_search_ad`](https://developers.google.com/google-ads/api/reference/rpc/v9/Ad#responsive_search_ad) field on an ad:

```py
ad_service = client.get_service("AdService")
ad_operation = client.get_type("AdOperation")

# Update ad operation.
ad = ad_operation.update
ad.resource_name = ad_service.ad_path(customer_id, ad_id)

# Note that when updating these repeated fields in this way,
# it will replace the existing list for the ad, not add to it.
ad.responsive_search_ad.headlines.append("New headline")
ad.responsive_search_ad.descriptions.append("New headline")
ad.responsive_search_ad.path1 = "path 1"
ad.responsive_search_ad.path2 = "path 2"

# Create the update mask and add it onto the operation.
client.copy_from(
    ad_operation.update_mask, protobuf_helpers.field_mask(None, ad._pb)
)

# Updates the ad in a mutate request.
ad_response = ad_service.mutate_ads(
    customer_id=customer_id, operations=[ad_operation]
)
```

Hope that helps, feel free to reopen this issue if you have additional questions.

**Comment by IKlaskyHopjump** [comment]
Thanks so much for your detailed response! I'm specifically interested to know the best way to change the text in a given headline instead of making a completely new headline. Any info on this would be greatly appreciated.

**Comment by BenRKarl** [comment]
@IKlaskyHopjump you would need to just replace that text, so for example, say you have an add that looks like this:

```
ad {
    responsive_search_ad {
        headlines: ["hello", "goodbye"]
    }
}
```

And you want to change `"hello"` to something like `"hello!!"`, you need to create an ad that looks like this:

```
ad {
    responsive_search_ad {
        headlines: ["hello!!", "goodbye"]
    }
}
```

Can you do that in code with the following line, similar to what happens in my above example:

```py
ad.responsive_search_ad.headlines.extend(["hello!!", "goodbye"])
```

Does that help?

**Comment by IKlaskyHopjump** [comment]
Yes it does. Thanks!

**Comment by IKlaskyHopjump** [comment]
@BenRKarl Thanks again for your help with this, and as a follow up would you be able to tell me how I could use the API to find the value the params are currently set at? As far as I can tell there doesn't seem to be any way to check this through the UI and I'd like to be able to check that the params are being uploaded correctly.
