### ISSUE TITLE
Filling the existing Ad with new assets

### ISSUE THREAD

**Issue by e-lepilov** [googleads/google-ads-python#530]
Hi there,
I faced the problem of adding new assets to an existing ad (**Ad Type=AppAd**). The problem is that if, for example, I have an ad that has 4 video assests + 3 text assests (description and two headers) 
It looks like this 
https://ibb.co/hMBRJf8

And now I want to upload one more video ad and one text asset (actually it's more, but I'll simplify it to add one video ad in order not to put complicated logic in the code). The upload works, but all four old video assets get the status REMOVED. This looks like this
https://ibb.co/zPjXLP6

```
def update_ad(
    client: GoogleAdsClient,
    customer_id: str,
    ad_id: int,

) -> None:
    """Method for update exist ad with new assets"""
    description="Best space cruise ever." # hardcode
    ad_service = client.get_service("AdService", version=GOOGLE_API_VERSION)
    ad_operation = client.get_type("AdOperation")
    asset_resource_name = 'customers/2309565764/assets/18484165148' # hardcode

    ad = ad_operation.update
    ad.resource_name = ad_service.ad_path(customer_id, ad_id)
    ad.app_ad.descriptions.append(create_ad_text_asset(client, description))
    ad.app_ad.youtube_videos.append(create_ad_video_asset(client, asset_resource_name))
    client.copy_from(
        ad_operation.update_mask, protobuf_helpers.field_mask(None, ad._pb)
    )
    # Updates the ad.
    ad_service.mutate_ads(
        customer_id=customer_id, operations=[ad_operation]
    )
```
Is my query logic wrong, or is there a restriction on adding an Asset to an existing ad through the API?

**Comment by BenRKarl** [comment]
@e-lepilov when you update a repeated field it overwrites the existing items in the API, instead of adding to them. I would recommend retrieving the ad from the API using a `search` request and updating the complete list of items, for example say you want to add an item to the `descriptions` field:

```py
query = """
    SELECT 
      ad_group_ad.ad.app_ad.descriptions 
    FROM ad_group_ad 
    WHERE ad_group_ad.ad.id = <YOUR AD ID>"""

ga_service = client.get_service("GoogleAdsService")
# Retrieve the existing ad from the API
response = ga_service.search(customer_id=customer_id, query=query)
# Retrieve the ad object from the response
ad = response.results[0].ad_group_ad.ad
# Add a new description to the existing list
ad.app_ad.descriptions.append("New description")

# Proceed with your same update request logic
...
```

**Comment by e-lepilov** [comment]
@BenRKarl thank you,
 I apologize for the reopening, but how do you determine the type of operation in this approach? Right now I'm getting 
```
   error_code {
    request_error: OPERATION_REQUIRED
  }
```
If I add     
   ` ad = ad_operation.update` after `ad = response.results[0].ad_group_ad.ad`, then I redefine the value of the ad variable
   How do I specify the correct type?

**Comment by BenRKarl** [comment]
@e-lepilov no problem, please feel free to reopen if you need help 😄 

The type of operation you need depends on which service and method you're using, since you're using the [`AdService.MutateAds`](https://developers.google.com/google-ads/api/reference/rpc/v9/AdService#mutateads) method, you can see, by looking at the docs, that method uses a [`MutateAdsRequest`](https://developers.google.com/google-ads/api/reference/rpc/v9/MutateAdsRequest) object, which includes a list of [`AdOperation`](https://developers.google.com/google-ads/api/reference/rpc/v9/AdOperation) objects.

Based on your description I think you're using the right type of operation, but you're not setting the ad on it correctly. Sorry I forgot to mention in my first snippet that your update request logic needs to be slightly different, here's a more complete example:

```py
query = """
    SELECT 
      ad_group_ad.ad.app_ad.descriptions 
    FROM ad_group_ad 
    WHERE ad_group_ad.ad.id = <YOUR AD ID>"""

ga_service = client.get_service("GoogleAdsService")
# Retrieve the existing ad from the API
response = ga_service.search(customer_id=customer_id, query=query)
# Retrieve the ad object from the response
ad = response.results[0].ad_group_ad.ad
# Add a new description to the existing list
ad.app_ad.descriptions.append("New description")

# Proceed with your (almost) same update request logic
ad_service = client.get_service("AdService")
ad_operation = client.get_type("AdOperation")

# Copy the ad onto the AdOperation object's "update" field.
client.copy_from(ad_operation.update, ad)
# Still need to set the update mask.
client.copy_from( 
    ad_operation.update_mask, protobuf_helpers.field_mask(None, ad._pb)
)
# Updates the ad.
ad_service.mutate_ads(
    customer_id=customer_id, operations=[ad_operation]
)
```

**Comment by e-lepilov** [comment]
It almost worked, it worked with descriptions but didn't work with the video asset. Old video assets are still deleted
   https://ibb.co/SJNjw0z
   
```
    query = f"""
        SELECT 
          ad_group_ad.ad.app_ad.descriptions 
        FROM ad_group_ad 
        WHERE ad_group_ad.ad.id = {ad_id}"""
    description = 'Test'
    asset_resource_name = 'customers/2309565764/assets/18484165148'
    ga_service = client.get_service("GoogleAdsService")
    # Retrieve the existing ad from the API
    response = ga_service.search(customer_id=customer_id, query=query)
    # Retrieve the ad object from the response
    ad = response.results[0].ad_group_ad.ad
    # Add a new description to the existing list
    ad.app_ad.descriptions.append(create_ad_text_asset(client, description))
    
    # THIS PLACE
    # Add a new video to the existing list
    ad.app_ad.youtube_videos.append(create_ad_video_asset(client, asset_resource_name))

    # Proceed with your (almost) same update request logic
    ad_service = client.get_service("AdService")
    ad_operation = client.get_type("AdOperation")

    # Copy the ad onto the AdOperation object's "update" field.
    client.copy_from(ad_operation.update, ad)
    # Still need to set the update mask.
    client.copy_from(
        ad_operation.update_mask, protobuf_helpers.field_mask(None, ad._pb)
    )
    # Updates the ad.
    ad_service.mutate_ads(
        customer_id=customer_id, operations=[ad_operation]
    )
```
    
  Could you please help this it?

**Comment by BenRKarl** [comment]
@e-lepilov that's because the search query doesn't include the `youtube_videos` field, so the existing list isn't included in the `ad` object you're working on. If you update the search query to the below it should work, and keep his in mind for any other repeated fields you may want to update:

```py
query = """
    SELECT
      ad_group_ad.ad.app_ad.descriptions,
      ad_group_ad.ad.app_ad.youtube_videos
    FROM ad_group_ad 
    WHERE ad_group_ad.ad.id = {ad_id}"""        
```

**Comment by e-lepilov** [comment]
It worked! Thank you so much for your help!
