### ISSUE TITLE
Conversion actions sets for Campaign

### ISSUE THREAD

**Issue by nightlyds** [googleads/google-ads-python#532]
**Describe the bug:**
Hello, we have some strange behavior with conversion actions for campaign, in case of one conversion action in campaign everything works fine, but instead if we have 2 or more conversion actions (a set of conversion actions), we get nothing.

**Steps to Reproduce:**
There is short code example, which could help to understand the exact problem:

```python
from google.ads.googleads.client import GoogleAdsClient

client = GoogleAdsClient.load_from_storage()
google_ads_service = client.get_service("GoogleAdsService")

campaign_conversion_actions_response = google_ads_service.search(
    customer_id="your_customer_id,
    query="SELECT campaign.selective_optimization.conversion_actions FROM campaign",
)

# Imagine we have only one conversion action in the campaign
# so then, we will get its resource_name
print(*list(row.campaign.selective_optimization.conversion_actions
           for row in campaign_conversion_actions_response)) # ['customers/your_customer_id/conversionActions/conversion_action_id']

# But in case 2 or more conversion actions in the campaign
# e. g. set of converion actions, we will get empty list
print(*list(row.campaign.selective_optimization.conversion_actions
           for row in campaign_conversion_actions_response)) # []
```

**Expected behavior:**
So I think it should return all available and attached conversion actions for the campaign. In case if it do, but I misunderstand something, please let me know.

**Client library version and API version:**
Client library version: v8
Google Ads API version: 14.0.0

**Comment by laurachevalier4** [comment]
Hey @nightlyds! Thanks for your question. Conversion action sets are not supported in the API, but I don't think this behavior -- where conversion actions that are part of a conversion action set are not getting returned when querying `campaign.selective_optimization.conversion_actions` -- is expected. I recommended reaching out to the direct support team (googleadsapi-support@google.com) with more details about the error, including request and response logs and the customer ID(s) for which you are seeing this.

**Comment by nightlyds** [comment]
Hi @laurachevalier4 thank you for your answer! I will figure out.
