### ISSUE TITLE
How to migrate batch jobs?

### ISSUE THREAD

**Issue by ageofneil** [googleads/google-ads-python#533]
We're migrating from googleads to this library in preparation for the April 2022 deadline.  I'm having trouble migrating our batch jobs. Any help would be appreciated.

Here is an example of some code I'm trying to migrate. It performs a batch update of adgroup bids and status:

```
# helper function to build update ads group operations
def UpdateBuildAdgroupOperations(batch_job_helper, update_adgroups):
    adgroup_operations = [
        {
            'xsi_type': 'AdGroupOperation',
            'operand': {
                'id': int(i[0]),
                'status': i[2],
                'biddingStrategyConfiguration': {
                    'bids': [
                        {
                            'xsi_type': 'CpaBid',
                            'bid': {
                                'microAmount': int(i[1]),
                            }
                        }
                    ]
                }
            },
            'operator': 'SET'
        }
        for i in update_adgroups]
    return adgroup_operations

# data to update. A list of list of lists retrieved from a SQL query
data  = [[adgroup_id, bid,status]

# create batch jobs
batch_job_helper = client.GetBatchJobHelper(version='v201809')
batch_job = AddBatchJob(client)
      
operations = UpdateBuildAdgroupOperations(batch_job_helper, data)
batch_job_helper.UploadOperations(upload_url, operations)

```

I've been reading the batch job docs (https://developers.google.com/google-ads/api/docs/batch-processing/overview) with no success success in migrating our current code base.

**Comment by BenRKarl** [comment]
@ageofneil have you looked at [this example](https://github.com/googleads/google-ads-python/blob/main/examples/campaign_management/add_complete_campaigns_using_batch_job.py#L374), which shows how to use batch jobs to add a new campaign? The link there points to the section where we add ad_groups. I imagine the logic is quite similar to what you're doing above.

**Comment by BenRKarl** [comment]
Closing this issue, but please re-open with further questions if needed.
