### ISSUE TITLE
Hi there, I wonder if anyone has an example of how to pull all product level data in Shopping Campaigns. I'm trying to create a report that shows products without conversions or clicks in the last 14 days. I can see how to do it on Java but not sure what on Python. The products are in various different ad groups.

### ISSUE THREAD

**Issue by HazelW87** [googleads/google-ads-python#534]
**Describe the problem you are trying to solve:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by BenRKarl** [comment]
@HazelW87 can you share details of how you do it in Java? I could probably translate it to Python for you.

**Comment by BenRKarl** [comment]
@HazelW87 assuming this is no longer an issue, please re-open with more details if it is. Thanks!
