### ISSUE TITLE
google-api-core dependency version

### ISSUE THREAD

**Issue by andrewkisel** [googleads/google-ads-python#535]
google-ads 14.1.0 requires google-api-core >= 2.0.1, < 3.0.0 which causes dependency conflicts with google-api-python-client that requires google-api-core>=1.21.0,<3.0.0dev.

"ERROR: pip's dependency resolver does not currently take into account all the packages that are installed.
This behaviour is the source of the following dependency conflicts.
google-ads 14.1.0 requires google-api-core<3.0.0,>=2.0.1, but you have google-api-core 1.21.0 which is incompatible."

The issue is related to this PR: https://github.com/googleads/google-ads-python/pull/473 that is closed.

**Comment by BenRKarl** [comment]
@andrewkisel I think this is a non-issue for this library. `google-api-core` is working to deprecate support for Python 2, and once `google-api-python-client` removes Python 2 support it will set its minimum version for `google-api-core` to 2.0.1 just like this library. Assuming you're using Python 3, the solution for you is to update `google-api-core` to version 2.0.1 or above.
