### ISSUE TITLE
cannot retrieve display ad data from ad_group_ad

### ISSUE THREAD

**Issue by hirochachacha** [googleads/google-ads-python#54]
I was trying to retrieve display ad data from ad_group_ad.
I succeeded to get data before by using adwords API library.
However, I failed to get data by using new google-ads API library.

```python
import google.ads.google_ads.client

_DEFAULT_PAGE_SIZE = 1000
CUSTOMER_ID = <XXXXXXX>


if __name__ == "__main__":
    client = google.ads.google_ads.client.GoogleAdsClient.load_from_storage()
    ga_service = client.get_service("GoogleAdsService", version="v1")
    query = "SELECT ad_group_ad.ad.type FROM ad_group_ad"

    results = ga_service.search(CUSTOMER_ID, query=query, page_size=_DEFAULT_PAGE_SIZE)

    for row in results:
       print(row)
```

I have questions:
  1. Is this known limitation?
  2. If so, are there any schedules to support it?

Thanks.

**Comment by BenRKarl** [comment]
Hi @hirochachacha thank you for the question. Can you clarify exactly what type of ad you're trying to retrieve? You can see [this list](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v0.enums#adtype) of type from AdWords for reference.

**Comment by hirochachacha** [comment]
Hi @BenRKarl, thank you for your reply.

> Can you clarify exactly what type of ad you're trying to retrieve? You can see this list of type from AdWords for reference.

I am trying to retrieve MULTI_ASSET_RESPONSIVE_DISPLAY_AD in terms of [old API](https://developers.google.com/adwords/api/docs/reference/v201809/AdGroupAdService.Ad.Type).  
Perhaps, it is called LEGACY_RESPONSIVE_DISPLAY_AD in [new API](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v1.enums#adtype)? (I'm not sure)

**Comment by BenRKarl** [comment]
@hirochachacha thank you for the information! Multi asset responsive display ads have not yet been added to the Google Ads API, but they will be added in a future release. I can't say exactly when, but it's a high priority in order to have the Google Ads API reach parity with the AdWords API. I'll leave this issue open for now and will follow up to comment and close it once multi assets responsive display ads are available.

**Comment by hirochachacha** [comment]
It looks like `RESPONSIVE_DISPLAY_AD` was supported some days ago. 

https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v1.enums#adtype

I've confirmed that I can retrieve ads data via `GoogleAdsService`.
I haven't tested create operation yet, but closing this for now.
