### ISSUE TITLE
Can not get accessible customers list

### ISSUE THREAD

**Issue by grish97** [googleads/google-ads-python#545]
Error
google.api_core.exceptions.ServiceUnavailable: 503 403:Forbidden

**Client library version and API version:**

Client library version:
Google Ads API version: V8

**Request/Response Logs:**

status = StatusCode.UNAVAILABLE 
 debug_error_string = "{
     "created":"@1639404481.454734236",
     "description":"Error received from peer ipv6:[2a00:1450:4001:803::200a]:443",
     "file":"src/core/lib/surface/call.cc",
     "file_line":1069,
     "grpc_message":"403:Forbidden",
     "grpc_status":14
}"

**Comment by laurachevalier4** [comment]
Hey @grish97! Based on the error code, this appears to be an authorization issue, which wouldn't be specific to the Python client library. Can you make sure your yaml file is [configured](https://developers.google.com/google-ads/api/docs/client-libs/python/configuration) properly and has all the required [credentials](https://developers.google.com/google-ads/api/docs/first-call/overview#config)? If, after verifying your credentials, you are still running into this, please reach out to the support team (googleadsapi-support@google.com), including any API request/response logs (with the request ID).

If you are only running into this issue when trying to get accessible customers, but are seeing successful requests when running other Google Ads API methods, please provide a code sample (succeeding vs. not) or a request ID so we can better understand the issue. Thanks!
