### ISSUE TITLE
How to Upload new page feed data?

### ISSUE THREAD

**Issue by workingxx92** [googleads/google-ads-python#546]
How to Upload new page feed data?

<img width="1062" alt="Screen Shot 2021-12-14 at 7 16 36 PM" src="https://user-images.githubusercontent.com/86577210/145996628-743c25ce-3cd4-4f4d-a474-6599fbcd3c5c.png">

**Comment by laurachevalier4** [comment]
Hey @workingxx92! In the future, please only post questions that are specific to google-ads-python here. For this question, you can reference https://support.google.com/google-ads/answer/7166527. If you have questions about uploading page feed  data via API, have a look at the [documentation](https://developers.google.com/google-ads/api/docs/dynamic-search-ads/dsa-page-feeds) and reach out to the [Google Ads API support](https://developers.google.com/google-ads/api/support) team if you still need help.
