### ISSUE TITLE
Apply a recommendation, apply parameters library

### ISSUE THREAD

**Issue by Theofanis-Nakos** [googleads/google-ads-python#549]
i am creating a tool that applies google ads recommendations, from the google ads api. In most of the cases what we need to do is pass the recommendation id and it will be applied. But on some of the recommendations we need to add special apply parameters. What i have noticed is that one the apply recommendation examples here : https://developers.google.com/google-ads/api/docs/recommendations there is a commented part on how to apply a recommendation with extra parameters in all the languages except python. Is there a specific library or function you can point me to?

**Comment by laurachevalier4** [comment]
Hey @Theofanis-Nakos, thanks for your question! Looks like we'll need to update the example. You can reference the docs for this [ApplyRecommendationOperation documentation](https://developers.google.com/google-ads/api/reference/rpc/v9/ApplyRecommendationOperation) to help you understand what these various additional parameters might entail. In the meantime, I think the equivalent text ad example for Python, which you can use to infer the code for other `apply_parameters`, would look something like this:
```py
def main(client, customer_id, recommendation_id):
    recommendation_service = client.get_service("RecommendationService")

    apply_recommendation_operation = client.get_type(
        "ApplyRecommendationOperation"
    )

    apply_recommendation_operation.resource_name = recommendation_service.recommendation_path(
        customer_id, recommendation_id
    )
    
    # This is where we override the recommended ad when a TextAdRecommendation is applied.
    override_ad = client.get_type("Ad")
    override_ad.resource_name = "INSERT_AD_ID_HERE"
    apply_recommendation_operation.text_ad.ad = override_ad

    recommendation_response = recommendation_service.apply_recommendation(
        customer_id=customer_id, operations=[apply_recommendation_operation]
    )

    print(
        "Applied recommendation with resource name: "
        f"'{recommendation_response.results[0].resource_name}'"
    )
```
