### ISSUE TITLE
Service Accounts working on Google Ads API

### ISSUE THREAD

**Issue by pamsilva** [googleads/google-ads-python#55]
Hi,

You indicate [here](https://developers.google.com/google-ads/api/docs/oauth/cloud-project#service_accounts) that service accounts are currently not supported by Google Ads API.

Is there an estimate for this feature? Or an alternative that supports the same functionality?
My use case requires service accounts to authenticate services in Google Ads, but mainly requires those services to act on behalf of an user, and have that users's visibility over ads accounts.

We are developing new services, and would rather not have to user AdWords api to implement this since is being discontinued. However, we need the functionality on Google Ads API.

Thanks for the attention.

**Comment by BenRKarl** [comment]
Hi @pamsilva - let me ask around for more information on this. I'll get back to you as soon as I can.

**Comment by BenRKarl** [comment]
Hi @pamsilva this is something that we'll add in the future. I've added a label to this issue to designate it as a feature request. Once it's added I'll follow up here to point to the PR and close the issue.

**Comment by BenRKarl** [comment]
Hi @pamsilva service accounts were added in this PR: https://github.com/googleads/google-ads-python/pull/129 and were published in version 2.4.0.
