### ISSUE TITLE
How to set login_customer_id later in code

### ISSUE THREAD

**Issue by zoltanmihaly** [googleads/google-ads-python#550]
The _Login customer ID configuration_ part of the [google-ads.yaml](https://github.com/googleads/google-ads-python/blob/c143e81804e237a9549dd5936503d921033c4e5a/google-ads.yaml#L47) example suggests it should be possible to have my `developer_token`, `client_id`, `client_secret`, `refresh_token` and `use_proto_plus` configuration set in my `google-ads.yaml` file, but then have my `login_customer_id` configuration set separately later in code:

> You can also specify this later in code if your application uses multiple manager account + OAuth pairs.

Could you please share a Python example on how to do this? I had a look at the Python library config [documentation](https://developers.google.com/google-ads/api/docs/client-libs/python/configuration), but that only has examples on setting all configuration parameters either in YAML or in code, and does not cover how to set some in YAML and `login_customer_id` later in code.

**Comment by laurachevalier4** [comment]
Hey @zoltanmihaly. I think what that means is that you can set the `login_customer_id` directly on the `GoogleAdsClient` object.

For instance, you could omit it from your google-ads.yaml, and then add it into your script:
```py
def main(client, customer_id, login_customer_id):
    # Set login_customer_id directly on the GoogleAdsClient object. 
    # Note that login_customer_id should be a str.
    client.login_customer_id = login_customer_id
    ga_service = client.get_service("GoogleAdsService")

    query = """
        SELECT
          campaign.id,
          campaign.name
        FROM campaign
        ORDER BY campaign.id"""

    response = ga_service.search_stream(customer_id=customer_id, query=query)
```
You'd just need to make sure you set this value before instantiating the service(s) from which you'll be making your request. Does that make sense?

**Comment by zoltanmihaly** [comment]
Hey @laurachevalier4. Amazing, all makes sense now. Your code is working fine for me, thanks for the clear example!
