### ISSUE TITLE
How to get keyword search volume?

### ISSUE THREAD

**Issue by vciric** [googleads/google-ads-python#551]
Hi,

First of all, great work! Very impresive library! 
I am finding my way arround, and for now I maged to login and get a basic auth done.

Can you please tell me, how can I get a historical (overal, global) search volume for particular keyword? I need that info for further planning.

Best regards,
Vladimir

**Comment by laurachevalier4** [comment]
Hey @vciric, you might want to have a look at the [`keyword_view`](https://developers.google.com/google-ads/api/fields/v9/keyword_view) reporting resource. If you need help with reporting more generally, take a look at our reporting [guide](https://developers.google.com/google-ads/api/docs/reporting/overview) and our google-ads-python reporting [examples](https://github.com/googleads/google-ads-python/tree/main/examples/reporting). 

If you have any follow-up questions about keyword reporting, please send them to the [support forum](https://developers.google.com/google-ads/api/support), as this is not specific to the Python client library. Thanks!
