### ISSUE TITLE
PROHIBITED_FIELD_IN_WHERE_CLAUSE for 'responsive_display_ad.youtube_videos.asset'

### ISSUE THREAD

**Issue by zoltanmihaly** [googleads/google-ads-python#553]
**Describe the bug:**

I've built the following query using the [v9 Interactive Query Builder](https://developers.google.com/google-ads/api/fields/v9/ad_group_ad_query_builder) to retrieve all Responsive Display Ads running YouTube video assets:

```
SELECT ad_group.id, ad_group_ad.ad.id FROM ad_group_ad WHERE ad_group_ad.ad.type = 'RESPONSIVE_DISPLAY_AD' AND ad_group_ad.ad.responsive_display_ad.youtube_videos.asset IS NOT NULL
```

However, I'm unable to run this query with the Python library as I get a PROHIBITED_FIELD_IN_WHERE_CLAUSE error with message:

> "The following field may not be used in WHERE clause: \'ad_group_ad.ad.responsive_display_ad.youtube_videos.asset\'."

I'm assuming this is an error with the client library not the query, since I've built the query with the official query builder.

**Steps to Reproduce:**

Run the following Python code:

```
from google.ads.googleads.client import GoogleAdsClient

ads_client = GoogleAdsClient.load_from_storage()
ga_service = ads_client.get_service('GoogleAdsService', version='v9')

CUSTOMER_ID = "1234567890" # The given Google Ads customer ID

query = """
    SELECT
        ad_group.id,
        ad_group_ad.ad.id
    FROM ad_group_ad
    WHERE
        ad_group_ad.ad.type = 'RESPONSIVE_DISPLAY_AD'
        AND ad_group_ad.ad.responsive_display_ad.youtube_videos.asset IS NOT NULL
    """

response = ga_service.search_stream(customer_id=CUSTOMER_ID, query=query)

for batch in response:
    for row in batch.results:
        print(row)
```

**Expected behavior:**

Return all Responsive Display Ads that are using YouTube video assets using the above query.

The use of YouTube video assets is optional for Responsive Display Ads (i.e. RDAs) and so it'd be a nice feature to have this query supported to pull only the RDAs that run YT video assets, as opposed to pull in all RDAs then loop though all of them and check individually if they run YT video assets. I'm working on a video asset reporting script for large accounts with hundreds of RDAs (only some of which will have YT video assets).

**Client library version and API version:**
Client library version: 14.1.0
Google Ads API version: v9

**Request/Response Logs:**

>google.ads.googleads.errors.GoogleAdsException: (<_SingleThreadedRendezvous of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "Request contains an invalid argument."
        debug_error_string = "{"created":"@1640093884.956000000","description":"Error received from peer ipv4:142.251.39.10:443","file":"src/core/lib/surface/call.cc","file_line":1070,"grpc_message":"Request contains an invalid argument.","grpc_status":3}"
\>, <_SingleThreadedRendezvous of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "Request contains an invalid argument."
        debug_error_string = "{"created":"@1640093884.956000000","description":"Error received from peer ipv4:142.251.39.10:443","file":"src/core/lib/surface/call.cc","file_line":1070,"grpc_message":"Request contains an invalid argument.","grpc_status":3}"
>, errors {
  error_code {
    query_error: PROHIBITED_FIELD_IN_WHERE_CLAUSE
  }
  message: "The following field may not be used in WHERE clause: \'ad_group_ad.ad.responsive_display_ad.youtube_videos.asset\'."
}
request_id: "m-jo-hq4Ev93a6rFMK0BQQ"
, 'm-jo-hq4Ev93a6rFMK0BQQ')
 
**Anything else we should know about your project / environment:**
N/A

**Comment by laurachevalier4** [comment]
Hey @zoltanmihaly! You're right, it looks like this is considered a valid query by the GAQL Query [Validator](https://developers.google.com/google-ads/api/fields/v9/query_validator). I was able to determine that this is not a problem specific to the google-ads-python client library by running the same query through a [cURL request](https://developers.google.com/google-ads/api/docs/query/cookbook#curl). That said, I'm not sure if this is an issue with the validator (i.e. this is in fact an invalid query) OR this should be valid and there is a bug in the API causing it to return this error message. I'll file a bug for this and let you know more details as I get them.

**Comment by laurachevalier4** [comment]
Hey @zoltanmihaly, I've confirmed that this is in fact an invalid query, and that the Query Validator needs to be updated to disallow this. The reason this query is invalid is that repeated fields are not filterable; in your case, the repeated field is `ad_group_ad.ad.responsive_display_ad.youtube_videos`. If you wanted to filter on this field, you would need to do so on the client side, filtering the query results after they're returned from the Google Ads API. Hope this helps!
