### ISSUE TITLE
Update Ad Parameters via API

### ISSUE THREAD

**Issue by IKlaskyHopjump** [googleads/google-ads-python#555]
I've found the python example [script](https://github.com/googleads/google-ads-python/blob/c143e81804e237a9549dd5936503d921033c4e5a/examples/campaign_management/set_ad_parameters.py) that shows how to create ad params 1 and 2 to be super helpful. I'm now looking for how to modify this script in order to update the ad params instead of creating new ones. I've been to the AdParameterOperation [page](https://developers.google.com/google-ads/api/reference/rpc/v9/AdParameterOperation?hl=en), but still haven't been able to figure it out.

Any help would be greatly appreciated!

Thanks,

Ian

**Comment by laurachevalier4** [comment]
Hey @IKlaskyHopjump! Have you tried looking at other examples for guidance on how to update objects? The general flow should be similar enough to apply here. [Here](https://github.com/googleads/google-ads-python/blob/c143e81804e237a9549dd5936503d921033c4e5a/examples/campaign_management/update_campaign_criterion_bid_modifier.py#L32) is an example of updating a campaign criterion, which might be useful reference. In the case of ad parameters, you would:
1) Create the [ad parameter operation](https://developers.google.com/google-ads/api/reference/rpc/v9/AdParameterOperation)
2) Set a variable to the `update` field, which is an [AdParameter](https://developers.google.com/google-ads/api/reference/rpc/v9/AdParameter) object
3) Set the ad parameter's resource_name to that of the ad parameter you want to update
4) Set any other fields that you want to update
5) Use a field mask to make the update. [Here](https://developers.google.com/google-ads/api/docs/client-libs/python/field-masks) is a useful doc explaining field masks in Python, and you can also reference the campaign criterion example to see how they are used to make updates.
6) Send the mutate request

I hope this gives you what you need to modify the script for your use case. Let us know if you still need help, and where in the process above you're struggling.

**Comment by IKlaskyHopjump** [comment]
Thank you so much @laurachevalier4! I was able follow that format and fix my script.

The only question I have left is if there are any examples for finding what the current params are for a given ad group and criterion. I haven't been able to find where to do this.

**Comment by laurachevalier4** [comment]
Hey @IKlaskyHopjump, have a look at the [GAQL query builder tool](https://developers.google.com/google-ads/api/fields/v9/ad_parameter_query_builder) for the ad_parameter resource. 

For example, you can build a query like:
```sql
SELECT
ad_parameter.ad_group_criterion
FROM ad_parameter
WHERE
ad_group.id = 123
AND ad_group_criterion.criterion_id = 456
```

**Comment by IKlaskyHopjump** [comment]
Thanks again @laurachevalier4!
