### ISSUE TITLE
Outdated comment about where to find default timeout

### ISSUE THREAD

**Issue by henribru** [googleads/google-ads-python#556]
**Describe the bug:**
`set_custom_client_timeouts.py` contains a comment about where to find the default timeout setting, but the structure of the library has changed since then so it no longer applies: https://github.com/googleads/google-ads-python/blob/main/examples/misc/set_custom_client_timeouts.py#L60-L63
**Steps to Reproduce:**
N/A
**Expected behavior:**
N/A
**Client library version and API version:**
Client library version: v.14.1.0 
Google Ads API version: v9.0

**Request/Response Logs:**

N/A
 
**Anything else we should know about your project / environment:**

**Comment by BenRKarl** [comment]
Thanks @henribru we'll take this as a feature request and get it fixed asap.
