### ISSUE TITLE
Assignment not allowed to repeated field "conversions" in protocol message object

### ISSUE THREAD

**Issue by panukuulu** [googleads/google-ads-python#559]
Trying to implement code sample https://developers.google.com/google-ads/api/docs/conversions/upload-clicks?hl=en#python using googleads-30.0.0

Seems to be an issue with this line:

` request.conversions = [click_conversion] `

returns an error:

`Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.3\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<string>", line 3, in <module>
  File "C:\Python39\lib\site-packages\google\protobuf\internal\python_message.py", line 675, in setter
    raise AttributeError('Assignment not allowed to repeated field '
AttributeError: Assignment not allowed to repeated field "conversions" in protocol message object.`

My click_conversions looks like: 

`gclid: "Cj0KCQiAw9qOBhC-ARIsAG-rdn7H0PLLPzj19IIWAKcoYz63zoYwV4Ca-_82RkyvIVAVPSGTHvHpnAIaAi5_EALw_wcB"
conversion_action: "customers/000000000/conversionActions/000000"
conversion_date_time: "2022-01-06 19:30:06+02:00"
conversion_value: 1.28
currency_code: "USD"
custom_variables {
  conversion_custom_variable: "type"
  value: "purchase"
}`

I suppose one is not allowed to assign to repeated fields but I don't see how to proceed. I think appending with request.conversions.append(click_conversion) creates a malformed request.

Anyone got a clue on how to get this to work?

Thank you for your help

**Comment by sakkammadam** [comment]
You have to use append.
Since it gets associated to conversions header - there is no malformed request. 
I then clear conversions using `del request.conversions[:]` and then upload the next batch.

**Comment by panukuulu** [comment]
Thanks, that works. Brilliant.

**Comment by BenRKarl** [comment]
Thanks @sakkammadam
