### ISSUE TITLE
Google Ads API does not work with Python 3.10.0 due to grpc compilation issue

### ISSUE THREAD

**Issue by ravikrray** [googleads/google-ads-python#561]
I faced this issue while importing the "google-ads" package. It internally uses cygrpc.cpython-310-darwin.so

pip install google-ads
import -> from google.ads.googleads.client import GoogleAdsClient
While building the project I see -

.
.
.
ImportError: dlopen(/Users/souravroy/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so, 2): no suitable image found.  Did find:
	/Users/souravroy/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so: mach-o, but wrong architecture
	/Users/souravroy/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so: mach-o, but wrong architecture
For reference -

souravroy@Souravs-MacBook-Air gmads % file $(which python)
/Users/souravroy/bin/python: Mach-O 64-bit executable arm64
souravroy@Souravs-MacBook-Air gmads % 
grpcio version

souravroy@Souravs-MacBook-Air gmads % pip show grpcio
Name: grpcio
Version: 1.43.0
Summary: HTTP/2-based RPC framework
Home-page: https://grpc.io
Author: The gRPC Authors
Author-email: grpc-io@googlegroups.com
License: Apache License 2.0
Location: /Users/souravroy/go/lib/python3.10/site-packages
Requires: six
Required-by: google-ads, google-cloud-bigquery, grpcio-status
python version - Python 3.10.0
I am using M1 chip macbook air.

Any workaround for this issue?

However, as of now we have proceeded with Python 3.9.9 version and it is working fine with this version but not 3.10.0 .

**Comment by BenRKarl** [comment]
This issue is blocked by a related issue in gRPC: https://github.com/grpc/grpc/issues/27506

Right now it seems that the best workaround is to use Python 3.9. It may be possible to manually enter an x86 shell, which would allow you to use Python 3.10, but I'm unsure whether there are performance side effects with that solution. I'm looking into it now and will report back once I have more details.

**Comment by BenRKarl** [comment]
It's possible that you can get the correct behavior with Python 10 by manually switching to an x86 shell using the below command:

`arch -x86_64 /bin/bash`

However, as I mentioned, I don't have a way of knowing the performance side effects of doing this. Unless you have a specific need that requires Python 3.10, I recommend using Python 3.9 for now.

**Comment by BenRKarl** [comment]
Closing this issue for now, since it can't be resolved by this library.

**Comment by manuganji** [comment]
The deadline for AdWords sunset is approaching and with this issue I can't use this library on Mac. Could you please try for a resolution?

**Comment by manuganji** [comment]
It's not working with Python 3.9 either to me.
