### ISSUE TITLE
Prepared Statements / Bind Variables for GAQL

### ISSUE THREAD

**Issue by AlexJMohr** [googleads/google-ads-python#567]
**Describe the problem you are trying to solve:**

Currently you have to glue queries together by concatenating strings. This is error-prone and vulnerable to SQL injection problems (not really, since multiple statements aren't allowed, but you get the idea)

Consider the following query:

```py
q = r"some unsanitary input which may contain 'single quotes'"
query = f"""
    SELECT campaign.id
    FROM campaign
    WHERE campaign.name LIKE '%{q}%'
"""
```

This will result in a syntax error since the input contains single quotes. The seemingly obvious solution is to sanitize your own inputs but that not is as easy to get 100% right.

**Describe the solution you'd like:**

Prepared statements (Bind Variables)

```py
query = """
    SELECT campaign.id
    FROM campaign
    WHERE campaign.name LIKE '%%s%'
"""
client.search(query, variables=[q])
```
The query would be pre-prepared server-side before injecting variable values in order to validate syntax. Then the variable values are escaped and bound to the placeholders. The is exactly what most DBMS do (for example, PostgreSQL with psycopg)

Alternative syntax for bind variables:
- `%s` - positional in list of arguments (python/psycopg style)
- `%(q)s` - dictionary lookup (python/psycopg style)
- `:n` where `n` is an index into a list of arguments

**Describe alternatives you've considered:**

A programmatic query builder, like in #182 

**Additional context:**

**Comment by BenRKarl** [comment]
It's unfortunately out of scope for this library to do query sanitation or preparation, however if you'd like to see this implemented at the API level please submit a feature request via our [support forum](https://groups.google.com/g/adwords-api)
