### ISSUE TITLE
Why Campaign Type is fetching numeric values?

### ISSUE THREAD

**Issue by rohinibandi** [googleads/google-ads-python#568]
Hi 

I am using GoogleAds API v8 to fetch Campaigns Advertising Channel type. We are getting a numerical values like 2,4,8 instead of string values. Is there a way to convert numeric values to string values for Advertising Channel type?

from google.ads.googleads.client import GoogleAdsClient
from google.ads.googleads.errors import GoogleAdsException

Query to fetch the data: 

def get_campaigns(client,customer_id):
    ga_service = client.get_service("GoogleAdsService", version='v8')
    query = """
       SELECT 
       customer.descriptive_name, 
       segments.date, 
       campaign.advertising_channel_type,
       campaign.id,
       campaign.name, 
       metrics.cost_micros, 
       metrics.clicks, 
       metrics.impressions 
       FROM campaign where segments.date DURING LAST_14_DAYS"""
       
+----------------+--+
| campaign.advertising_channel_type |
+----------------+--+
| 2                         |
| Shopping           |
| 4                         |
| 8                         |
| Local                  |
| Search               |
| Display               |
+----------------+--+

**Comment by BenRKarl** [comment]
Hi @rohinibandi see [this page](https://developers.google.com/google-ads/api/docs/client-libs/python/protobuf-messages#retrieving_enum_names) in our documentation. It explains how to do this in both of the available protobuf interfaces this library exposes.
