### ISSUE TITLE
I cannot find certain files after installing the google-ads module from PyPi

### ISSUE THREAD

**Issue by kylezengo** [googleads/google-ads-python#570]
I installed the google-ads module from PyPi with pip, but I cannot find the "examples" directory described [here](https://developers.google.com/google-ads/api/docs/client-libs/python/oauth-desktop). I can find it when I clone the client library from GitHub.

I reached out to the support channel, but I was then directed here.

**Comment by BenRKarl** [comment]
Hi @kylezengo when we package the library for PyPi we intentionally leave out the `examples` and `test` dirs to reduce the binary size. If you intend to run the examples, you should clone the repository from GitHub.
