### ISSUE TITLE
Flattened GAQL results

### ISSUE THREAD

**Issue by zoltanmihaly** [googleads/google-ads-python#572]
**Flattened GAQL results?**

Using Google Ads scripts, it seems to be [possible](https://developers.google.com/google-ads/scripts/docs/features/search) to get a flattened output when running a GAQL report instead of getting nested GoogleAdsRow objects: 

> If you would prefer a flattened result, you can issue an AdsApp.report call using GAQL.

Is this also possible when using the Google Ads API Python client library? If not, what's the suggested way to flatten GoogleAdsRow query results when using this library?

**Comment by BenRKarl** [comment]
@zoltanmihaly there's no mechanism that allows you to flatten a response object, to do so you would need to implement this in your application.

If you just want to use a field path to retrieve nested values, we do have [a utility](https://github.com/googleads/google-ads-python/blob/main/google/ads/googleads/util.py#L26) that will help with this, it just won't affect the structure of the target object. Here's an example:

```
from google.ads.googleads.util import get_nested_attr

get_nested_attr(campaign, "manual_cpc.enhaned_cpc_enabled")

# >> False
```
