### ISSUE TITLE
Python client v9 throwing USER_PERMISSION_DENIED error

### ISSUE THREAD

**Issue by gabriel-viviani** [googleads/google-ads-python#573]
**What is your question?**

Hello support team,

I'm migrating from old python client that will be deprecated soon to v9 one.
When loading config values from dict I receive following error:

Request with ID `HIDDEN (idk if I should show this)` failed with status `PERMISSION_DENIED` and includes the following errors:
```
Error with message "User doesn't have permission to access customer. Note: If you're accessing a client customer, the manager's customer id must be set in the 'login-customer-id' header. See https://developers.google.com/google-ads/api/docs/concepts/call-structure#cid".
```

And yes, I'm setting
[login_customer_id](https://developers.google.com/google-ads/api/docs/concepts/call-structure#cid) on the config dict as well.

I'm receiving this error when trying to run a pytest execution that [creates a budget](https://github.com/googleads/google-ads-python/blob/2a1d6062221f6aad1992a6bcca0e7e4a93d2db86/examples/basic_operations/add_campaigns.py#L39).

Tricky thing is that I have a previous test that runs:
    `assert ads_client.credentials.valid is True`
and it passes.

I've also used other GoogleAdsClient setup forms, (loading envs from yaml and env).

**Please let me know if any extra info is needed**

**Comment by ritaoraqui** [comment]
Hi Gabriel, were you able to solve? I have the same issue opened.

**Comment by BenRKarl** [comment]
Hi @gabriel-viviani and @ritaoraqui given that you're setting the login-customer-id properly, this issue is better addressed by our general API support. Would you please reach out to our [support forum](https://groups.google.com/forum/#!forum/adwords-api)?

**Comment by ritaoraqui** [comment]
> Hi @gabriel-viviani and @ritaoraqui given that you're setting the login-customer-id properly, this issue is better addressed by our general API support. Would you please reach out to our [support forum](https://groups.google.com/forum/#!forum/adwords-api)?

Sure, thanks Ben!
