### ISSUE TITLE
access annotation data (refine) with keyword ideas service

### ISSUE THREAD

**Issue by techperfect** [googleads/google-ads-python#574]
**What is your question?**
Hi,

Some guidance would be appreciated here.

When I call the main function from 
[generate_keyword_ideas.py](https://github.com/googleads/google-ads-python/blob/310a488b6fdad9d5beea8fa4b166edce779a2511/examples/planning/generate_keyword_ideas.py#L35-L97)
I get back a  list object that has a placeholder for the keyword [annotations](https://developers.google.com/google-ads/api/reference/rpc/v8/KeywordPlanKeywordAnnotationEnum.KeywordPlanKeywordAnnotation)
however it is empty for all keywords in the set (I am referring to cases where annotations should be available, at least they in the keyword planner) 
Eg.
text: "nike air max advantage"
keyword_annotations {
}
, keyword_idea_metrics {
  competition: HIGH
  monthly_search_volumes {
    month: JULY
    year: 2020
    monthly_searches: 90

All other standard metrics that are also available through the UI are there, but not the annotations. 

Can you provide some guidance about how to access it? Thank you
I add the following two lines，
keyword_annotation = client.enums.KeywordPlanKeywordAnnotationEnum   
request.keyword_annotation = keyword_annotation  
but no success. 
The error message is (AttributeError: Assignment not allowed to repeated field "keyword_annotation" in protocol message object.). 
how can i solve this problem?

**Comment by techperfect** [comment]
Now I fix it.
the following two lines:
keyword_annotation = client.enums.KeywordPlanKeywordAnnotationEnum.KEYWORD_CONCEPT
request.keyword_annotation = keyword_annotation

**Comment by BenRKarl** [comment]
@techperfect thanks for posting your solution!
