### ISSUE TITLE
Pyhton Examples for Migration to asset-based DSA?

### ISSUE THREAD

**Issue by mbaader** [googleads/google-ads-python#575]
Hi there,

in your guide to "[Asset-based workflow for creating DSA page feeds](https://developers.google.com/google-ads/api/docs/dynamic-search-ads/dsa-page-feeds#asset-based_workflow_for_creating_dsa_page_feeds)" there are still only examples for Java. When will there be examples for Python? Is there a chance that those will show up before April 27, 2022, when the auto migration is scheduled to start?

(I [posted](https://groups.google.com/g/adwords-api/c/vA_wtjV4fZs) this question in the Google Ads API Forum, they pointed me here.)

Regards
Mat

**Comment by BenRKarl** [comment]
@mbaader the example should be there for you now.

**Comment by mbaader** [comment]
Great  - Ty very much!
