### ISSUE TITLE
Get specific report fields

### ISSUE THREAD

**Issue by kmylk** [googleads/google-ads-python#582]
**What is your question?**
I have questions about  how to get specific report fields , we can specify fields in search query , but how to list all available fields for specific report type.  Can you please provide an example? 
 I see related info present here https://developers.google.com/google-ads/api/fields/v10/ad_group, do we have a way get that resource fields from API?

I am looking for alternative https://github.com/googleads/googleads-python-lib/blob/master/examples/adwords/v201809/reporting/get_report_fields.py

**Comment by davedavis** [comment]
Hi @kmylk
Another similar question cropped up a while back.

#480 

It uses a utility to get nested attributes. 
https://github.com/googleads/google-ads-python/blob/main/google/ads/googleads/util.py#L26

Is this what you're looking for?

**Comment by kmylk** [comment]
Hi @davedavis , thank you. It's similar, but not exactly. 
I am looking for something to list all available attributes for report. 
Example: 
plugin: ad_group
question: how get all available fields for ad_group report,  (may be something by query , '`select * from ad_group`' to get all columns from table)
expected_result : list all attributes fields for a specific  report (id, name, ad_rotation_mode, audience_setting.use_audience_grouped, base_ad_group.....) for ex. ad_group

**Comment by BenRKarl** [comment]
@kmylk unfortunately there's no formal way to do this via the API, but protobuf objects do expose [functionality](https://googleapis.dev/python/protobuf/latest/google/protobuf/message.html#google.protobuf.message.Message.DESCRIPTOR) that might be helpful here. 

For any type that comes back from the API, you can list every available field on it. It won't, for example, tell you _everything_ that's available in, for example, the [`campaign_audience_view`](https://developers.google.com/google-ads/api/fields/latest/campaign_audience_view) but you can inspect the objects that it exposes.

For example, this report allows you to select the `campaign` resource. If you want a list of every possible field on a `campaign`, you can do this:

```py
# Starting with a GoogleAdsRow object, and
# assuming you have `use_proto_plus` set to true:
fields = [field.name for field in row.metrics._pb.DESCRIPTOR.fields]
```

You can do this for _any_ protobuf object that comes from the API, including `metrics`, `segments`, even the `GoogleAdsRow` type itself. One caveat is that it doesn't appear to give nested fields, so if you want that you may need to devise some type of recursive solution.
