### ISSUE TITLE
Question about the proto-plus version used in the library

### ISSUE THREAD

**Issue by ReptilianBrain** [googleads/google-ads-python#583]
Good morning. 

I was wondering if there is a reason behind locking proto-plus to 1.18.1 ?

(https://github.com/googleads/google-ads-python/blob/main/setup.py#L24)

I'm asking because there is an option in the proto-plus library I was using in a past version of the google-ads library that has been removed in 1.18.1 but is enabled in most recent version. 

When using Message.to_dict() there is a paramater "including_default_value_fields" that is not in version 1.18.1. 

v.1.18.1 link 
https://github.com/googleapis/proto-plus-python/blob/cfd5b6caca3fa9add89d8c69ea620505dd90dd7c/proto/message.py#L378

More recent version example
v1.19.0 link 
https://github.com/googleapis/proto-plus-python/blob/6cb2a4eddfdcc1f0bedcdac81e8b66170638eeea/proto/message.py#L383

And I think this is where the change has been made ?? around the release of v8_1 ?

https://github.com/googleads/google-ads-python/commit/b31324d3c6ebe2f17a0367f8d210644014c53837

**Comment by BenRKarl** [comment]
Hi @ReptilianBrain - the reason is that we have really strict performance requirements for this library and have had regressions from proto-plus in the past, so it's been safest to pin to a specific version. However we can run some tests to check newer versions and will bump this if possible in an upcoming release.

**Comment by ReptilianBrain** [comment]
Ok thank you very much for taking the time to look into this.

**Comment by BenRKarl** [comment]
@ReptilianBrain brief update here - we're doing performance testing on the newer version of proto-plus to see if it can be supported here. I'll provide an update once we have a conclusion.

**Comment by BenRKarl** [comment]
This was updated in version `15.1.0`
