### ISSUE TITLE
How to access all the columns in the query

### ISSUE THREAD

**Issue by poojitha-gandra25** [googleads/google-ads-python#588]
**What is your question?**

I have tried the below to retrieve all the columns required as json and then download the report's as csv or json
but the below code wouldn't give us all the columns in the GAQL query and some of them are being sent as field_masks. Could you Please suggest on how i can retrieve the columns in field_masks! Thanks

**approach 1:**
```
for customer_id in account_list:
stream = ga_service.search_stream(customer_id=customer_id, query=query)
for batch in stream:
      for row in batch.results:
            pro_dict = proto.Message.to_dict(row)
            print(pro_dict)
```

**approach 2:**
```
for customer_id in account_list:
        stream = ga_service.search_stream(customer_id=customer_id, query=query)
        for row in stream:
                 json_str = json_format.MessageToJson(row._pb, preserving_proto_field_name=True)
                d = json.loads(json_str)
                df = pd.json_normalize(data=d['results'])
                print(" df is ", df.columns)

df.to_csv(file_path, index=False, header=True)
```
The above dataframe.columns isn't showing all the columns that i mentioned in the GAQL query. I see they are part of the filed_masks n the json string. Please suggest how i can access those columns? 

**approach 3:** 
```
for customer_id in account_list:
            stream = ga_service.search_stream(customer_id=customer_id, query=query)
            for batch in stream:
                all_data = []
                for row in batch.results:
                    single_row = dict()

                    single_row["criterion_id"] = row.ad_group_criterion.criterion_id
                    single_row["keyword.text"] = row.ad_group_criterion.keyword.tex

                    all_data.append(single_row)
```

if i have 20 columns required there's going to be 20 lines of single_row["key"] = row.ad_group for the above approach and some of the columns are also generating enum values. 

if i try below i'm getting googleadsrow not subscriptable error. Please suggest
```
all_data = []
for batch in stream:    
                for row in batch.results:
                    single_row = dict()
                    field = self.report_config["fields"] -> storing all the required columns in a list
                    for v in field:
                       single_row[v] = row[v]
                       all_data.append(single_row)

```

**Comment by BenRKarl** [comment]
@poojitha-gandra25 the reason not all the fields are appearing in each row is likely that those fields have null values. To know the full set of requested fields you can access the field mask on the `batch` object (as we call it in our examples), which is actually an instance of a [`SearchGoogleAdsStreamResponse`](https://developers.google.com/google-ads/api/reference/rpc/v10/SearchGoogleAdsStreamResponse). For example:

```py
for batch in stream:
    fields = batch.field_mask.paths
    ...
```
