### ISSUE TITLE
How to get  text field value for segments.ad_network_type

### ISSUE THREAD

**Issue by hsFallen** [googleads/google-ads-python#590]
Hi,
Try to get ad_network_type text value (CONTENT,MIXED, etc.) as per documentation, but returns int value. 
[documentation](https://developers.google.com/google-ads/api/fields/v10/campaign#segments.ad_network_type)
`query = f"""
        SELECT
some fields ...,
            segments.ad_network_type
        FROM campaign
        WHERE segments.date BETWEEN '{arrow.get(start).format('YYYY-MM-DD')}' AND '{arrow.get(end).format('YYYY-MM-DD')}'"""`

response processing:
`            return [
                {
some fields ...,
                    "ad_network_type": row.segments.ad_network_type
                }
                for row in response
            ]`
but it returns a numeric value. How can I get text value?     API v10.
<img width="1036" alt="Снимок экрана 2022-02-26 в 15 14 05" src="https://user-images.githubusercontent.com/66151790/156116495-ec77ad26-47b9-44db-9f53-25ef0f0d2018.png">

**Comment by hsFallen** [comment]
Possible solution  - turn on [Protobuf Messages](https://developers.google.com/google-ads/api/docs/client-libs/python/protobuf-messages)

**Comment by BenRKarl** [comment]
@hsFallen retrieving these values is different depending on whether you have proto-plus enabled or not. [This section](https://developers.google.com/google-ads/api/docs/client-libs/python/protobuf-messages#retrieving_enum_names) of the guide you linked to explains the two different strategies.
