### ISSUE TITLE
What's the canonical way of accessing error enums

### ISSUE THREAD

**Issue by ddoskind** [googleads/google-ads-python#592]
It's clear from the documentation that the preferred way to interact with enums is to use the `GoogleAdsClient`'s `enums` attribute, e.g.
```python
campaign.status = client.enums.CampaignStatusEnum.PAUSED
```

However, there are also enum types in error messages, let's take [`FieldErrorEnum`](https://developers.google.com/google-ads/api/reference/rpc/v10/FieldErrorEnum) as an example. This type doesn't seem to be accessible in the same way:
```python
>>> client.enums.FieldErrorEnum
<snip>
AttributeError: '_EnumGetter' object has no attribute 'FieldErrorEnum'
```

When handling errors, it's sometimes required to distinguish between different error enum values. I currently access them by instantiating the wrapper using the client's `get_type` method and using the contained enum values:
```python
FieldErrorEnum = client.get_type('FieldErrorEnum')
...
if error_code.field_error == FieldErrorEnum.FieldError.IMMUTABLE_FIELD:
   ...
```

But I was wondering whether there's a better way to do so?

**Comment by BenRKarl** [comment]
@ddoskind you're already using the best workflow. Even though errors are technically enums, they are generated in a different location than the other, formal enums, and we haven't yet added a convenience interface for accessing them. It's on our radar though, and hopefully we'll be able to add it in an upcoming release.
