### ISSUE TITLE
Example Contribution Scope

### ISSUE THREAD

**Issue by davedavis** [googleads/google-ads-python#593]
Hi Maintainers. 
Hoping to submit a few more examples and was wondering how granular is too granular?

For example, I'm working on an Experiments service in a personal project and want to submit an example or how to list experiments in an account. However, the Experiment resource is just another resource handled by the GoogleAdsService. Effectively, it's just a slight modification to the GAQL and a few other bits, but otherwise the same as any other example. 

How useful is this? Obviously, examples can't be created for every single resource. So should we limit example contributions to noel areas not covered in other examples or is it fine to submit?

Thanks

**Comment by BenRKarl** [comment]
Hi @davedavis - the contribution scope for examples is pretty flexible, if there's something you think is important to highlight please feel free to submit a PR with a description of why you think it's important. We may end up translating it to the other client libraries, but even if not, we welcome any contributions that you think are valuable.
