### ISSUE TITLE
GoogleAdsService doesn't properly apply retries when Retry is passed in

### ISSUE THREAD

**Issue by Kache** [googleads/google-ads-python#597]
**Describe the bug:**

`GoogleAdsService` provides `search()`, which accepts a [`retry: google.api_core.retry.Retry`](https://github.com/googleapis/python-api-core/blob/c89f55d10df50c222d05ea046e07e05ef7d17725/google/api_core/retry.py#L223). The Retry decorator ends up only getting [applied on the first request](https://github.com/googleads/google-ads-python/blob/0b928474b588422f421aadf12948538378fc770f/google/ads/googleads/v10/services/services/google_ads_service/client.py#L3292-L3294), making it effectively useless for large results with many pages.

Subsequent requests are issued by `SearchPager`, [initialized a few lines down](https://github.com/googleads/google-ads-python/blob/0b928474b588422f421aadf12948538378fc770f/google/ads/googleads/v10/services/services/google_ads_service/client.py#L3298-L3300), where `retry` is not passed in, thus making it unavailable [at evocation](https://github.com/googleads/google-ads-python/blob/main/google/ads/googleads/v10/services/services/google_ads_service/pagers.py#L71-L73), where every `SearchPager._method()` call is not retry-decorated.

**Steps to Reproduce:**

Functionally, this occurs with a query returning a large number of results, such that a transient network transport error is likely to occur at least once while paging results. I had a query that had at least 3,260,000 rows (more on this below under "Anything else..."), but this can be observed with any query with more than one page of results.

It is behaviorally evident by putting a breakpoint in `google.api_core.gapic_v1.method._GapicCallable` [where decorators are applied](https://github.com/googleapis/python-api-core/blob/c89f55d10df50c222d05ea046e07e05ef7d17725/google/api_core/gapic_v1/method.py#L137-L141). `retry` is populated with the passed in `Retry()` on the first request, but `retry` is `DEFAULT` for subsequent requests and set to `None`.

**Expected behavior:**

Passing `retry=Retry()` to `GoogleAdsService.search()` calls should apply the retry decoration to every request for each page of results, not just the first request.

**Client library version and API version:**
Client library version: 15.0.0
Google Ads API version: v9 and v10

**Request/Response Logs:**

Can be provided if needed.
 
**Anything else we should know about your project / environment:**

An investigation into GoogleAdsService.search_stream() revealed that the Retry() mechanism wraps the entire stream, once. This suggests that on occurrence of a transient error, the entire stream will start over from the beginning instead of only retrying the increment and continuing on. From this point, either the retry._deadline is already exceeded or the long-running retry is just as likely to encounter another transient error, i.e. Retry() is completely ineffective. I was originally using `search_stream()`, falling back to `search()` when using `Retry()` didn't seem to help, only to discover this bug.

There probably isn't actually 3,260,000 rows of results to the query. This query historically only returns about 3K rows, but we recently upgraded our API version to v10. Running this query using API v9 returns the expected ~3K rows, so it looks like there's yet _some other bug_ with v10.

**Questions & Going forward**

 1. I've opened https://github.com/googleads/google-ads-python/pull/598 that fixes Retry() for search().
 2. It's unclear in the Python client how the gRPC layer handles transient errors while streaming, but the apparent conclusion is that a retry-fixed search() will be more resilient than search_stream() because [search() is able to retry around transient network errors but search_stream() is not](https://developers.google.com/google-ads/api/rest/common/search). Is that accurate?
 3. Docs recommend search_stream() for large results -- is there a way, perhaps undocumented (as Retry() isn't formally documented either), that lets us configure incremental retries for search_stream()?

**Comment by BenRKarl** [comment]
Hi @Kache thanks for bringing this to our attention and for providing so much detail. I'll answer your questions inline below:

1. I believe you are correct that there is no way for streaming response to be retried mid-stream, which is a limitation of the Google Ads API. I'm not sure if there is a plan to make this work, but I'll create a feature request for it.
2. The issue with retries not working for paged requests is problematic, I added a comment to your PR and will help coordinate with the maintainers of the generator we use, which I believe is where those fixes should go.
3. The issue with your query going from ~3k rows to ~3.2m rows is a known bug that I believe was fixed today (3/17) so if you're able to retry it hopefully you should be able to go back to `search_stream`

Let me know if I'm missing anything above, and whether the large respond issue continues to persist.

**Comment by BenRKarl** [comment]
Closing this since the issue was moved to the generator repo.
