### ISSUE TITLE
keyword_plan_idea_service_client.py

### ISSUE THREAD

**Issue by pratiksha-cobiro** [googleads/google-ads-python#60]
Hello

I am trying to run the service KeywordPlanIdeaService in keyword_plan_idea_service_client.py.

```
File "/Code/new_/ai_analyzer/venv/lib/python3.7/site-packages/google/ads/google_ads/v1/services/keyword_plan_idea_service_client.py", line 249, in generate_keyword_ideas
    url_seed=url_seed,
TypeError: Parameter to MergeFrom() must be instance of same class: expected google.protobuf.StringValue got str.

```
I can't import google.protobuf.StringValue and also can't find the format of UrlSeed. 

How do I run this service.

Also when I am trying to use rest api from this url 
'https://googleads.googleapis.com/v1/customers/' + customer_id + ':generateKeywordIdeas/', I am only able get keywords when I give customer_id of MCC account. but if I try to give ids of linked accounts to MCC one, it does not work, as it fails in authentication.

So , do I have to obtain separate authentication token for each linked accounts to MCC account?

Regards
Pratiksha

**Comment by pratiksha-cobiro** [comment]
I figured out from pull request of example. although I do have this question regarding the authentication that do I have to obtain separate authentication token for each linked accounts to MCC account?

and what is the rate limit of API.

**Comment by wihl** [comment]
These are standard support questions that are best asked through regular channels. See https://developers.google.com/google-ads/api/support

Rate limits are linked on the same page: https://developers.google.com/google-ads/api/docs/access-levels

Thanks!
