### ISSUE TITLE
Issue with SearchGoogleAdsRequest method

### ISSUE THREAD

**Issue by Sunil310** [googleads/google-ads-python#601]
**Hi ,
I am getting the below error message and need your help to understand where i'm going wrong. **

#####################################
Traceback (most recent call last):
  File "vault_code.py", line 118, in <module>
    generate_report(google_ads_client, x, _DEFAULT_PAGE_SIZE,qry,mode='w')
  File "vault_code.py", line 44, in generate_report
    response = ga_service.search(query)
  File "[/usr/share/cdp/python-3.7/lib/python3.7/site-packages/google/ads/googleads/v9/services/services/google_ads_service/client.py](https://peanut-hue.cargill.com/hue/filebrowser/view=/usr/share/cdp/python-3.7/lib/python3.7/site-packages/google/ads/googleads/v9/services/services/google_ads_service/client.py)", line 3163, in search
    request = google_ads_service.SearchGoogleAdsRequest(request)
  File "[/usr/share/cdp/python-3.7/lib/python3.7/site-packages/proto/message.py](https://peanut-hue.cargill.com/hue/filebrowser/view=/usr/share/cdp/python-3.7/lib/python3.7/site-packages/proto/message.py)", line 488, in __init__
    % (self.__class__.__name__, mapping,)
TypeError: Invalid constructor input for SearchGoogleAdsRequest: "SELECT campaign.name,ad_group.id,ad_group.name,ad_group.type,customer.currency_code,customer.descriptive_name,ad_group_ad.ad.expanded_text_ad.path1,ad_group_ad.ad.expanded_text_ad.path2,ad_group_ad.ad.expanded_text_ad.headline_part1,ad_group_ad.ad.expanded_text_ad.headline_part2,ad_group_ad.ad.expanded_text_ad.description,ad_group_ad.ad.expanded_text_ad.description2,ad_group_ad.ad.gmail_ad.teaser.business_name,metrics.average_cpc,metrics.ctr,metrics.interactions,metrics.conversions,metrics.all_conversions_from_interactions_rate,metrics.average_cost,metrics.impressions,segments.date,segments.day_of_week,segments.quarter,metrics.clicks,metrics.cost_micros,metrics.active_view_ctr FROM ad_group_ad WHERE segments.date BETWEEN '2022-03-21' AND '2022-03-22'"

############################
**I am using Python 3.7. Below is the code snippet :**

def generate_report(client, customer_id, page_size,qry,mode):
    ga_service = client.get_service("GoogleAdsService", version="v8")
    query=qry  ### this is same as the query you see in the logs above
    search_request = client.get_type("SearchGoogleAdsStreamRequest")
    search_request.customer_id = customer_id
    search_request.query = query
    response = ga_service.search_stream(search_request)
    print(response)
    #response = ga_service.search_stream(customer_id,query)  ### I also tried this
    

for x in ids:  ## ids is an array of client ids
        if x==ids[0]:
            generate_report(google_ads_client, x, _DEFAULT_PAGE_SIZE,qry,mode='w')
        else:
            generate_report(google_ads_client, x, _DEFAULT_PAGE_SIZE,qry,mode='a')

**Comment by BenRKarl** [comment]
@Sunil310 all of the parameters for `SearchStream` are keyword parameters, so your first attempt should look like:

```py
response = ga_service.search_stream(request=search_request)
```

Feel free to re-open if that doesn't resolved your issue.

**Comment by Sunil310** [comment]
I am not sure which libraries you would be interested in ... these are all the google libraries I have installed

google 3.0.0
google-ads 14.1.0
google-api-core 1.31.5
google-api-python-client 1.12.3
google-auth 2.6.0
google-auth-httplib2 0.1.0
google-auth-oauthlib 0.4.6
googleapis-common-protos 1.54.0


###### I am simply executing the below block #####

import google.ads.googleads.client
google_ads_client = google.ads.googleads.client.GoogleAdsClient.load_from_storage("google-ads.yaml")
ga_service = google_ads_client.get_service("GoogleAdsService", version="v8")
query="SELECT campaign.name,ad_group.id,ad_group.name,ad_group.type,customer.currency_code,customer.descriptive_name,ad_group_ad.ad.expanded_text_ad.path1,ad_group_ad.ad.expanded_text_ad.path2,ad_group_ad.ad.expanded_text_ad.headline_part1,ad_group_ad.ad.expanded_text_ad.headline_part2,ad_group_ad.ad.expanded_text_ad.description,ad_group_ad.ad.expanded_text_ad.description2,ad_group_ad.ad.gmail_ad.teaser.business_name,metrics.average_cpc,metrics.ctr,metrics.interactions,metrics.conversions,metrics.all_conversions_from_interactions_rate,metrics.average_cost,metrics.impressions,segments.date,segments.day_of_week,segments.quarter,metrics.clicks,metrics.cost_micros,metrics.active_view_ctr FROM ad_group_ad WHERE segments.date BETWEEN '2022-03-22' AND '2022-03-23'"

search_request = google_ads_client.get_type("SearchGoogleAdsStreamRequest")
search_request.customer_id = "6359513076"
search_request.query = query
response = ga_service.search_stream(search_request)
print(response)

**Comment by Sunil310** [comment]
@BenRKarl can you please suggest

**Comment by Sunil310** [comment]
Hi team,
Would appreciate a quick response here. This code is in our production environment which stopped working approx. a month ago. The exact same code was working smoothly since 1 yr. Not sure what changed.
