### ISSUE TITLE
Concurrent upload of UserIdentifier to single OfflineUserDataJob.

### ISSUE THREAD

**Issue by BharamagoudaEps** [googleads/google-ads-python#605]
We are trying to upload few millions (25 Million) of identfiers to google, as we have limits on API, this is what we are trying ,

1. Created 'google_client' using access tokens
2. Created 'user_list' 
3. Created 'offline_user_data_job' using 'OfflineUserDataJobService' service
4. Create a function which takes the 'google_client', 'user_list', 'offline_user_data_job' and small portion of dataframe to be uploaded. This function is called in parallel by spark.
5. Within this function, (PARALLEL PROCESSING)
               5.1 Create request for 'AddOfflineUserDataJobOperations'
               5.2 Initialize the request with 'offline_user_data_job' ( This will tag a request to job.
               5.3 Create operations using the input data. and assign to request.operations
               5.4 submit the 'AddOfflineUserDataJobOperations' request
               5.5 Repeat step 5.1 to 5.4 till all data is submitted to Google.
6. On submitting all the 'AddOfflineUserDataJobOperations' request, finally call 'run_offline_user_data_job' which triggers the upload.

Issue details:
We are facing 'database_error: CONCURRENT_MODIFICATION' error when we are submitting "'AddOfflineUserDataJobOperations' request" in parallel. ( Step 5.4)

(<_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.INVALID_ARGUMENT\n\tdetails = "Request contains an invalid argument."\n\tdebug_error_string = "
{
    "created": "@1647967680.852767877",
    "description": "Error received from peer ipv4:172.253.122.95:443",
    "file": "src/core/lib/surface/call.cc",
    "file_line": 903,
    "grpc_message": "Request contains an invalid argument.",
    "grpc_status": 3
}
"\n>, <_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.INVALID_ARGUMENT\n\tdetails = "Request contains an invalid argument."\n\tdebug_error_string = "
{
    "created": "@1647967680.852767877",
    "description": "Error received from peer ipv4:172.253.122.95:443",
    "file": "src/core/lib/surface/call.cc",
    "file_line": 903,
    "grpc_message": "Request contains an invalid argument.",
    "grpc_status": 3
}
"\n>, errors {\n  error_code {\n    database_error: CONCURRENT_MODIFICATION\n  }\n  message: "Multiple requests were attempting to modify the same resource at once. Please retry the request."\n}\nrequest_id: "jUsAGBf4dnPrg6XQX8TEbA"\n, \'jUsAGBf4dnPrg6XQX8TEbA\')',)

Can you help in identifying the issues and also how to resolve it, so that we can upload quickly.

**Comment by BenRKarl** [comment]
Hi @BharamagoudaEps - this sounds like a limitation of the API and not something that can be fixed on our end. My suggestion would be to try to sort the identifiers you're working on so that you don't issue mutations for the same resource from separate processes. If you have further questions, please submit an issue to our [support forum](https://groups.google.com/forum/#!forum/adwords-api), where they'll be able to better support you. This Issues tracker is only for issues specific to this library.
