### ISSUE TITLE
Not able to export bidding_strategy.type in csv

### ISSUE THREAD

**Issue by AashisAashu** [googleads/google-ads-python#606]
**Describe the bug:*I am not able to export the values of  bidding_strategy.type in csb using the code examples/migration/campaign_report_to_csv.py. Got the error as AttributeError: type*

**Steps to Reproduce:*Add the column bidding_strategy.type in select part of the code.BiddingStrategyType in Headers and row.bidding_strategy.type in writer.writerow part. Run the code. Got the error as AttributeError: type*

**Expected behavior:* The code should be able to export the value of bidding_strategy.type in csv without error*

**Client library version and API version:**
Client library version:
Google Ads API version:

**Request/Response Logs:**

 
**Anything else we should know about your project / environment:**

**Comment by BenRKarl** [comment]
@AashisAashu assuming you have [`use_proto_plus`](https://github.com/googleads/google-ads-python/blob/main/google-ads.yaml#L18) set to `True`, some field names must be appended with a `_` character, specifically you likely need to change:

```py
bidding_strategy.type
```

to:

```py
bidding_strategy.type_
```

For more details see [this documentation](https://developers.google.com/google-ads/api/docs/client-libs/python/protobuf-messages#field_names_that_are_reserved_words)
