### ISSUE TITLE
TypeError: Invalid constructor input for SearchGoogleAdsRequest

### ISSUE THREAD

**Issue by Sunil310** [googleads/google-ads-python#609]
**Describe the bug:**
Raising an new issue here since i didn't get a response on #601 
I have started receiving this error : TypeError: Invalid constructor input for SearchGoogleAdsRequest
This code was working fine a month ago. 

**Steps to Reproduce:**
import google.ads.googleads.client

google_ads_client = google.ads.googleads.client.GoogleAdsClient.load_from_storage("google-ads.yaml")
ga_service = google_ads_client.get_service("GoogleAdsService", version="v8")

query="SELECT campaign.name,ad_group.id,ad_group.name,ad_group.type,customer.currency_code,customer.descriptive_name,ad_group_ad.ad.expanded_text_ad.path1,ad_group_ad.ad.expanded_text_ad.path2,ad_group_ad.ad.expanded_text_ad.headline_part1,ad_group_ad.ad.expanded_text_ad.headline_part2,ad_group_ad.ad.expanded_text_ad.description,ad_group_ad.ad.expanded_text_ad.description2,ad_group_ad.ad.gmail_ad.teaser.business_name,metrics.average_cpc,metrics.ctr,metrics.interactions,metrics.conversions,metrics.all_conversions_from_interactions_rate,metrics.average_cost,metrics.impressions,segments.date,segments.day_of_week,segments.quarter,metrics.clicks,metrics.cost_micros,metrics.active_view_ctr FROM ad_group_ad WHERE segments.date BETWEEN '2022-03-22' AND '2022-03-23'"

search_request = google_ads_client.get_type("SearchGoogleAdsStreamRequest")
search_request.customer_id = "6359513076"
search_request.query = query
response = ga_service.search_stream(search_request)
print(response)

**Client library version and API version:**
Client library version:  1.12.3 (google-api-python-client)
Google Ads API version: 14.1.0  (google-ads)

aenum==3.1.8
anyio==3.5.0
apiclient==1.0.4
appdirs==1.4.4
APScheduler==3.8.1
argcomplete==1.12.3
asgiref==3.5.0
azure-core==1.21.1
azure-storage-blob==12.9.0
bcrypt==3.2.0
beautifulsoup4==4.10.0
bitarray==2.3.5
bs4==0.0.1
cachetools==5.0.0
case-conversion==2.1.0
certifi==2021.10.8
cffi==1.15.0
chardet==4.0.0
charset-normalizer==2.0.11
click==8.0.3
clipboard==0.0.4
colorama==0.4.4
colorlog==6.6.0
colour==0.1.5
cramjam==2.5.0
cryptography==36.0.1
cursor==1.3.4
DateTime==4.3
decorator==4.4.2
dill==0.3.4
distlib==0.3.4
docopt==0.6.2
et-xmlfile==1.1.0
fastapi==0.73.0
fastparquet==0.8.0
filelock==3.4.2
fire==0.4.0
fsspec==2022.1.0
fuzzywuzzy==0.18.0
gender-guesser==0.4.0
google==3.0.0
google-ads==14.1.0
google-api-core==1.31.5
google-api-python-client==1.12.3
google-auth==2.6.0
google-auth-httplib2==0.1.0
google-auth-oauthlib==0.4.6
googleapis-common-protos==1.54.0
grpcio==1.43.0
gssapi==1.7.2
h11==0.13.0
hdfs==2.6.0
html-text==0.5.2
httplib2==0.20.2
httptools==0.3.0
idna==3.3
imageio==2.14.1
imageio-ffmpeg==0.4.5
importlib-metadata==4.10.1
impyla==0.17.0
infi.systray==0.1.12
inflect==5.4.0
isodate==0.6.1
joblib==1.1.0
kafka-python==2.0.2
kerberos==1.3.1
krb5==0.2.0
lxml==4.7.1
lz4==3.1.10
maybe-else==0.2.1
mbstrdecoder==1.1.0
moviepy==1.0.3
msal==1.16.0
msoffcrypto-tool==5.0.0
msrest==0.6.21
nltk==3.6.7
nox==2022.1.7
ntlm-auth==1.5.0
numpy==1.18.4
O365==2.0.17
oauth2client==4.1.3
oauthlib==3.2.0
office365==0.3.15
Office365-REST-Python-Client==2.3.10
olefile==0.46
openpyxl==3.0.9
packaging==21.3
pandas==1.3.5
paramiko==2.9.2
parsedatetime==2.6
pathmagic==0.3.14
Pillow==9.0.0
platformdirs==2.4.1
praw==7.5.0
prawcore==2.3.0
prettierfier==1.0.3
proglog==0.1.9
proto-plus==1.18.1
protobuf==3.17.3
psycopg2==2.9.3
pure-sasl==0.6.2
py==1.11.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pydantic==1.9.0
pydub==0.25.1
pyinstrument==4.1.1
pyiotools==0.3.18
PyJWT==2.3.0
pylzma==0.5.0
pymiscutils==0.3.14
PyNaCl==1.5.0
pyodbc==4.0.32
pyparsing==3.0.7
PyPDF2==1.26.0
pyperclip==1.8.2
PyQt5==5.15.6
PyQt5-Qt5==5.15.2
PyQt5-sip==12.9.1
pysftp==0.2.9
pyspellchecker==0.6.3
pyspnego==0.3.1
pysubtypes==0.3.18
python-dateutil==2.8.2
python-docx==0.8.11
python-dotenv==0.19.2
python-snappy==0.6.0
pytz==2021.3
PyYAML==5.4.1
readchar==3.0.5
regex==2022.1.18
requests==2.27.1
requests-kerberos==0.14.0
requests-ntlm==1.1.0
requests-oauthlib==1.3.1
requests-toolbelt==0.9.1
rsa==4.8
Send2Trash==1.8.0
SharePlum==0.5.1
sharepy==1.3.0
simplejson==3.17.6
six==1.16.0
sniffio==1.2.0
soupsieve==2.3.1
starlette==0.17.1
stringcase==1.2.0
subprocess32==3.5.4
tabulate==0.8.9
termcolor==1.1.0
thrift==0.11.0
thrift-sasl==0.4.3
tqdm==4.62.3
typepy==1.3.0
typing-extensions==4.0.1
tzlocal==2.1
update-checker==0.18.0
uritemplate==3.0.1
urllib3==1.26.8
uvicorn==0.17.1
uvloop==0.16.0
virtualenv==20.13.0
watchgod==0.7
websocket-client==1.2.3
websockets==10.1
xlrd==1.2.0
XlsxWriter==3.0.2
zipp==3.7.0
zope.interface==5.4.0

**Request/Response Logs:**
Traceback (most recent call last):
File "vault_code.py", line 118, in
generate_report(google_ads_client, x, _DEFAULT_PAGE_SIZE,qry,mode='w')
File "vault_code.py", line 44, in generate_report
response = ga_service.search(query)
File "[/usr/share/cdp/python-3.7/lib/python3.7/site-packages/google/ads/googleads/v9/services/services/google_ads_service/client.py](https://peanut-hue.cargill.com/hue/filebrowser/view=/usr/share/cdp/python-3.7/lib/python3.7/site-packages/google/ads/googleads/v9/services/services/google_ads_service/client.py)", line 3163, in search
request = google_ads_service.SearchGoogleAdsRequest(request)
File "[/usr/share/cdp/python-3.7/lib/python3.7/site-packages/proto/message.py](https://peanut-hue.cargill.com/hue/filebrowser/view=/usr/share/cdp/python-3.7/lib/python3.7/site-packages/proto/message.py)", line 488, in init
% (self.class.name, mapping,)
TypeError: Invalid constructor input for SearchGoogleAdsRequest: "SELECT campaign.name,ad_group.id,ad_group.name,ad_group.type,customer.currency_code,customer.descriptive_name,ad_group_ad.ad.expanded_text_ad.path1,ad_group_ad.ad.expanded_text_ad.path2,ad_group_ad.ad.expanded_text_ad.headline_part1,ad_group_ad.ad.expanded_text_ad.headline_part2,ad_group_ad.ad.expanded_text_ad.description,ad_group_ad.ad.expanded_text_ad.description2,ad_group_ad.ad.gmail_ad.teaser.business_name,metrics.average_cpc,metrics.ctr,metrics.interactions,metrics.conversions,metrics.all_conversions_from_interactions_rate,metrics.average_cost,metrics.impressions,segments.date,segments.day_of_week,segments.quarter,metrics.clicks,metrics.cost_micros,metrics.active_view_ctr FROM ad_group_ad WHERE segments.date BETWEEN '2022-03-21' AND '2022-03-22'"

 
**Anything else we should know about your project / environment:**
I am using python 3.7

**Comment by rkiacnhg** [comment]
i am also having this issue

**Comment by BenRKarl** [comment]
@Sunil310 - per the issue with login-customer-id, see our [guide](https://developers.google.com/google-ads/api/docs/migration/login-customer-id?hl=en) on how to use this header. This header is _not always_ required, it's only necessary if you're accessing a client account using the credentials from a manager account.

**Comment by Sunil310** [comment]
Hi ,
I tried the first step in the [guide ](https://developers.google.com/google-ads/api/docs/migration/login-customer-id?hl=en), to List accessible customers... and i still get an authentication error. Please assist.

**Error logs :**

 raise self._get_error_from_response(response)
google.ads.googleads.errors.GoogleAdsException: (<_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAUTHENTICATED
        details = "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project."
        debug_error_string = "{"created":"@1648733126.703175910","description":"Error received from peer ipv4:142.250.179.170:443","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.","grpc_status":16}"
>, <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAUTHENTICATED
        details = "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project."
        debug_error_string = "{"created":"@1648733126.703175910",
		"description":"Error received from peer ipv4:142.250.179.170:443","file":"src/core/lib/surface/call.cc","file_line":1074,
		"grpc_message":"Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.","grpc_status":16}"
>, errors {
  error_code {
    authentication_error: AUTHENTICATION_ERROR
  }
  message: "Authentication of the request failed."
}
request_id: "UfupwTd91OLy6em2nR0IaA"
, 'UfupwTd91OLy6em2nR0IaA')

**Code :**
import google.ads.googleads.client
googleads_client = google.ads.googleads.client.GoogleAdsClient.load_from_storage(version="v9",path="google-ads.yaml")

customer_service = googleads_client.get_service("CustomerService")
accessible_customers = customer_service.list_accessible_customers()
result_total = len(accessible_customers.resource_names)
print(f"Total results: {result_total}")

**Comment by BenRKarl** [comment]
@Sunil310 in that case, would you please submit a question to our [support forum](https://groups.google.com/forum/#!forum/adwords-api)? That team is better equipped to answer more general API questions like this, thank you!
