### ISSUE TITLE
Clarifying requirements for deleting an existing ad_group 

### ISSUE THREAD

**Issue by benlubas** [googleads/google-ads-python#614]
I've got a bit of code that deletes all of the keyword_plan_ad_groups that get returned from another query. 

```
ops = list()
for rn in self.ad_group_rns:
    operation = self.client.get_type("KeywordPlanAdGroupOperation")
    operation.remove = rn
    ops.append(operation)

keyword_plan_ad_group_service = self.client.get_service("KeywordPlanAdGroupService")
keyword_plan_ad_group_service.mutate_keyword_plan_ad_groups(
    customer_id=self.customer_id, operations=ops
)
```
Now, this code works when there are ad groups that don't have any keywords in them. However. When there are keywords in those ad groups, I get the following error: 
```
Fault: errors {
  error_code {
    database_error: DATA_CONSTRAINT_VIOLATION
  }
  message: "The request conflicted with existing data. This error will usually be replaced with a more specific error if the request is retried."
}
```
Unfortunately, retrying doesn't get me a better error message than that. 

I would like to confirm that this is expected, and ask if there are workarounds other than "delete all the keywords in the ad_group". 

I'll also say that it should be documented somewhere. Because it's not in the API docs for this operation or the example that shows how to delete ad_groups.

**Comment by BenRKarl** [comment]
@benlubas would you mind posting this question to our [support forum](https://groups.google.com/forum/#!forum/adwords-api)? They're much better suited to address general API questions such as this.
