### ISSUE TITLE
GenerateKeywordHistoricalMetrics and  GenerateKeywordHistoricalMetricsRequest are missing from the library

### ISSUE THREAD

**Issue by ofirch55** [googleads/google-ads-python#616]
Hi
I searched in all the github project the GenerateKeywordHistoricalMetricsRequest class and I couldn't find it.
According to the google ads api documentation(https://developers.google.com/google-ads/api/reference/rpc/v10/KeywordPlanIdeaService?hl=en)
I should have function of generate_keyword_historical_metrics that gets GenerateKeywordHistoricalMetricsRequest as input but I couldn't find the function and the class in the project.
I also tried to run the following code:
client = GoogleAdsClient.load_from_dict(credentials, version='v10')
keyword_plan_idea_service = client.get_service("KeywordPlanIdeaService")
request = client.get_type("GenerateKeywordHistoricalMetricsRequest")
request.customer_id = 'xxxxxxxxxxx'
request.keywords.extend(['nurse jobs'])

keyword_ideas = keyword_plan_idea_service.generate_keyword_historical_metrics(
request=request
)
I got the following errors:
ValueError: Specified type 'GenerateKeywordHistoricalMetricsRequest' does not exist in Google Ads API v10
AttributeError: 'KeywordPlanIdeaServiceClient' object has no attribute 'generate_keyword_historical_metrics

Is it possible that there is no implementation for this functionality?
Thanks

**Comment by BenRKarl** [comment]
Hi @ofirch55 - you are correct that KeywordPlanIdeaService does _not_ have a `generate_keyword_historical_metrics` method yet. It is planned, though, and should be part of an upcoming release. I recommend keeping an eye on our [developer blog](https://ads-developers.googleblog.com/) for more details once it's completed.

**Comment by ofirch55** [comment]
Hi thanks for the answer.
When do you plan to publish the next release?
