### ISSUE TITLE
OfflineCallConversionFeedService (google adwords api) equivalent in google-ads-python (google ads api)?

### ISSUE THREAD

**Issue by jbrow70** [googleads/google-ads-python#617]
Hi,

I've also submitted this same question to Google Ads API team as some of it is a mix between both the api (google ads api) and the python client (here)

Here's what I sent to them and also what I want to pose the question here see where maybe y'all can help:

---

I've got a new question. This one around google adwords api to google ads api.

Our current process is using google adwords api to send offline call conversions to google ads. We're using OfflineCallConversionFeedService which is a bulk service there.

We basically pass call conversions like this (below is just an example):

{'callerId': '{masked_as_actual_customer_phone_number}', 'callStartTime': '20220404 175411 America/Denver', 'conversionName': 'Gross_Calls', 'conversionTime': None, 'conversionValue': None, 'conversionCurrencyCode': None, 'extra': {'ani': '{masked_as_actual_customer_phone_number}', 'date_prequeue_start': '2022-04-04 17:54:11', 'promo_code': '{masked}', 'ppc_account_id': '{masked}', 'ppc_campaign_id': '{masked}', 'ppc_provider_id': '{masked}', 'conversion_type': 'Gross_Calls', 'contact_id': '{masked}', 'order_id': '', 'conversion_value': '', 'conversion_currency_code': '', 'units_id': '', 'conversion_time': ''}}

in bulk to the service (OfflineCallConversionFeedService v201809 )

What's the equivalent to do something like this in Google Ads API? PFA a code snippet of our old process

What would be ideal is we send it this raw JSON as input and use a bulk service like we did in google adwords api for our current productionalized integration. We've been trying to use this: https://github.com/googleads/google-ads-python/blob/bdc334af6303cd63a4b5ff74a984263027cfe3a0/google/ads/googleads/v10/services/types/conversion_upload_service.py (which makes it appear we have to change a decent amount and that doesn't seem to be the "bulky way" to do it, but maybe we want to use is https://github.com/googleads/google-ads-python/blob/bdc334af6303cd63a4b5ff74a984263027cfe3a0/google/ads/googleads/v10/services/types/feed_service.py instead since that's more equivelant to what we were doing in google adwords. I realize these are talking about the google ads api python client now but it's just using those underlying google ads api services/utilities).

---

Is there some examples of something similar like this in the python client for google ads api (similar to what we did in google adwords api integration)? Can you point us in the right direction? We're trying to migrate the job in the most seamless fashion, particularly since google adwords api is sunsetting later this month so time is limited! (rather not change too much code if we can avoid it). From what we see google ads api advertises that it supports basically all that was done in google adwords api, so it would make sense then there would be something equivalent in google ads api  and its python client here. 

Thanks,

Jordan
[google_adwords_api_version_code_snippet_1.zip](https://github.com/googleads/google-ads-python/files/8430160/google_adwords_api_version_code_snippet_1.zip)
,

**Comment by BenRKarl** [comment]
@jbrow70 you're going to want to use the [OfflineConversionUploadService.upload_call_conversions](https://developers.google.com/google-ads/api/reference/rpc/v10/ConversionUploadService#uploadcallconversions) method. Note that we have a bunch of useful docs focused specifically on migration, [here](https://developers.google.com/google-ads/api/docs/migration), including a [mapping of AdWords to Google Ads services](https://developers.google.com/google-ads/api/docs/migration/services). Also we have a [code example](https://github.com/googleads/google-ads-python/blob/main/examples/remarketing/upload_call_conversion.py) that shows how to upload call conversions, hopefully it's just what you're looking for.

Closing this for now, but feel free to re-open if you have further questions about this.

**Comment by jbrow70** [comment]
That helps a lot Ben and confirms we were actually on the right path, thank you! We are using upload _call_coversions (OfflineConversionUploadService) and upload_call_conversion.py example with the python client. According to https://developers.google.com/google-ads/api/docs/migration/services, OfflineCallConversionFeedService -> ConversionUploadService. That's what we've been using as part of our migration work, and it seems to have bulk capabilities out of the box which is great.

Some follow-up questions (I've also posed this to google ads api team if here isn't the right place to ask these):


One big thing we can't find an equivalent too in google ads api is  conversionName. What's that in google ads api?
Also is extras that we pass in google adwords api just custom variables in google ads api? If it is, in google adwords api we didn't have to specify custom variable ids for custom attributes we send via extra. We just sent e.g. 


'extra': {'ani': '{masked}', 'date_prequeue_start': '2022-04-04 17:54:11', 'promo_code': '{masked}', 'ppc_account_id': '{masked}', 'ppc_campaign_id': '{masked}', 'ppc_provider_id': '{masked}', 'conversion_type': 'Gross_Calls', 'contact_id': '{masked}', 'order_id': '', 'conversion_value': '', 'conversion_currency_code': '', 'units_id': '', 'conversion_time': '' as part of the payload using OfflineCallConversionFeedService  (see original posting for the full payload

But I guess that's not possible anymore just sending that way and we first have to lookup their associated custom variable ids before sending right? Then for each custom variable send the value with its id. Not ideal, but if it's what we have to do we'll get it working!

Thanks,

**Comment by BenRKarl** [comment]
@jbrow70 I'll try to answer one at a time below:

1. `conversionName` is mapped to `ConversionAction.name`. In addition to the services map, we also have this list of [feature mappings](https://developers.google.com/google-ads/api/docs/migration/features), and specifically for [conversions](https://developers.google.com/google-ads/api/docs/migration/features#conversions) that should be helpful.
2. I'm not sure what the mapping is for extras, that's definitely a question for general support, so make sure to ask them directly in your existing thread.
3. My guess is that you _will_ need to associate a conversion with a conversion action, but again I'm not sure and general API support will be the best place to ask that question.
