### ISSUE TITLE
Mutate_customer_manager_link should be called with client's customer_id.

### ISSUE THREAD

**Issue by sauravshanu** [googleads/google-ads-python#618]
This function should be called with client's `customer_id` instead. 
https://github.com/googleads/google-ads-python/blob/73e61d50150385042957e908a5a1a6632afedcc1/examples/account_management/link_manager_to_client.py#L103

**Comment by BenRKarl** [comment]
Fixed in https://github.com/googleads/google-ads-python/pull/676
