### ISSUE TITLE
failed to connect to all addresses

### ISSUE THREAD

**Issue by drew-reilly-edwards** [googleads/google-ads-python#621]
**Describe the bug:**
Running get_campaigns.py produces the followere error message:
Request made: ClientCustomerId: XXXXXXXX, Host: googleads.googleapis.com, Method: /google.ads.googleads.v10.services.GoogleAdsService/SearchStream, RequestId: None, IsFault: True, FaultMessage: failed to connect to all addresses

**Steps to Reproduce:**
run get_campaigns.py from examples folder

**Expected behavior:**
outputs: Request made: ClientCustomerId: XXXXXXXX, Host: googleads.googleapis.com, Method: /google.ads.googleads.v10.services.GoogleAdsService/SearchStream, RequestId: None, IsFault: True, FaultMessage: failed to connect to all addresses

followed by
E0423 13:19:41.144000000 14036 src/core/tsi/ssl_transport_security.cc:1504] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
every 10 seconds

**Client library version and API version:**
Client library version:15.1.1
Google Ads API version:v10

certifi==2021.10.8
charset-normalizer==2.0.12
google-ads==15.1.1
google-api-core==2.7.2
google-auth==2.6.6
google-auth-oauthlib==0.5.1
googleapis-common-protos==1.56.0
grpcio==1.44.0
grpcio-status==1.44.0
idna==3.3
oauthlib==3.2.0
packaging==21.3
proto-plus==1.19.6
protobuf==3.20.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==3.0.8
python-certifi-win32==1.6
PyYAML==5.4.1
requests==2.27.1
requests-oauthlib==1.3.1
rsa==4.8
setuptools-scm==6.4.2
six==1.16.0
tomli==2.0.1
urllib3==1.26.9
wincertstore==0.2
wrapt==1.14.0

**Request/Response Logs:**

 
**Anything else we should know about your project / environment:**

**Comment by BenRKarl** [comment]
@drew-reilly-edwards it looks like there was a failure in verifying the SSL certificate. It's not likely this was caused by the Google Ads API servers. Are you continuing to have this problem today?
