### ISSUE TITLE
google ads api  shows enum as value instead of name, in python

### ISSUE THREAD

**Issue by rais-manasiya** [googleads/google-ads-python#623]
Hi,
I am using your latest google ads api library
whilte I am trying to fetch segments.ad_network_type & segments.device value it gives me enum as value instead of name

so please sujjest me way to reslve it
below is my python code

 
    def get_campaign_data(client,account_id,start_date,end_date):
      try:
        #calling date validation funtion for start date format check
        start_date = date_validation(start_date)
        #calling date validation funtion for end date format check
        end_date = date_validation(end_date)
 
    ga_service = client.get_service("GoogleAdsService")
 
    query = "SELECT metrics.absolute_top_impression_percentage, customer.descriptive_name, metrics.active_view_impressions, metrics.active_view_measurable_impressions, campaign.advertising_channel_sub_type, segments.ad_network_type, metrics.all_conversions, metrics.all_conversions_value, campaign_budget.amount_micros, bidding_strategy.type, campaign.campaign_budget, campaign.id, campaign.name, campaign.status, metrics.clicks, metrics.conversions, metrics.conversions_value, metrics.cost_micros, metrics.current_model_attributed_conversions, metrics.current_model_attributed_conversions_value, segments.date, segments.device, campaign.manual_cpc.enhanced_cpc_enabled, campaign.percent_cpc.enhanced_cpc_enabled, metrics.gmail_secondary_clicks, metrics.impressions, campaign.labels, metrics.search_absolute_top_impression_share, metrics.search_click_share, metrics.search_exact_match_impression_share, metrics.search_impression_share, metrics.search_top_impression_share, metrics.top_impression_percentage FROM campaign WHERE segments.date BETWEEN '2022-04-25' AND '2022-04-25' ORDER BY campaign.id"
 
    search_request = client.get_type("SearchGoogleAdsStreamRequest")
    search_request.customer_id = account_id.replace('-', '')
    search_request.query = query
    response = ga_service.search_stream(search_request)
 
    data_df = pd.DataFrame()
   
    listObj = []
    for batch in response:
      for row in batch.results:
        print(row.segments)
        
        print(" \n ", row.segments.ad_network_type, row.segments.device) 
        sys.exit
        tmp_dict = {}
        
        if row.segments.device == 3 or row.segments.device == 2:
            deviceType = 'Mobile App'
        else:
            deviceType = 'Web'

        tmp_dict['account_id'] = account_id
        tmp_dict['device_type'] = row.segments.device 
        tmp_dict['media_type'] =row.segments.ad_network_type
        tmp_dict['ptnr'] = row.campaign.id
        tmp_dict['cost_inr'] = row.metrics.cost_micros/1000000
        tmp_dict['amount_inr'] = row.campaign_budget.amount_micros/1000000
        tmp_dict['absolute_top_impression_percentage'] = row.metrics.absolute_top_impression_percentage
        tmp_dict['account_descriptive_name'] = row.customer.descriptive_name

        tmp_dict['campaign_name'] = row.campaign.name
        tmp_dict['campaign_id'] = row.campaign.id
        tmp_dict['clicks'] = row.metrics.clicks
        tmp_dict['impressions'] = row.metrics.impressions
        
        tmp_dict['start_date'] = row.segments.date
        data_df = data_df.append(tmp_dict,ignore_index = True)
        listObj.append(tmp_dict)
    return listObj
    except:
    print("\n*** Function(get_campaign_data) Failed *** ",sys.exc_info())

**Comment by rais-manasiya** [comment]
Thanks Shivam, It is working now

but when I am trying to fetch **row.bidding_strategy.type** its is giving an error like 
Failed ***  (<class 'AttributeError'>, AttributeError("'type'"), <traceback object at 0x7fa5258cd300>

so can you please suggest me change

**Comment by shivamsingh262** [comment]
Please check the resource mapping,

[https://developers.google.com/google-ads/api/docs/migration/mapping#campaign_performance](url)

It should be `campaign.bidding_strategy_type` and you can access it by `row.campaign.bidding_strategy_type.name`

**Comment by BenRKarl** [comment]
Thanks @shivamsingh262 -

Also @rais-manasiya see [these docs](https://developers.google.com/google-ads/api/docs/client-libs/python/protobuf-messages#enum_name_retrieval) explaining how to access enum names.

When accessing `row.bidding_strategy.type` you will need to append an underscore to `type` like this:

```py
row.bidding_strategy.type_
```

For more details see [these docs](https://developers.google.com/google-ads/api/docs/client-libs/python/protobuf-messages#field_names_that_are_reserved_words).
