### ISSUE TITLE
Missing Advertising Channel Types 'DISCOVERY' in AdvertisingChannelTypeEnum 

### ISSUE THREAD

**Issue by rabsabius** [googleads/google-ads-python#624]
**Describe the bug:**
When querying a campaign resource to retrieve it advertising_channel_type value this warning is raised:
"UserWarning: Unrecognized AdvertisingChannelType enum value: 12"

**Steps to Reproduce:**
1- Create a Discovery Campaign Type 
2- Perform a query to retrieve advertising_channel_type field: 
ga_service = googleads_client.get_service("GoogleAdsService")
query = """SELECT campaign.advertising_channel_type FROM campaign  """

search_request = googleads_client.get_type("SearchGoogleAdsStreamRequest")
    search_request.query = query
    stream = ga_service.search_stream(search_request)
    for batch in stream:
        for row in batch.results:
            print(row.campaign.advertising_channel_type)

**Expected behavior:**
`
/home/rabsabius/.local/lib/python3.9/site-packages/proto/marshal/rules/enums.py:37: UserWarning: Unrecognized AdvertisingChannelType enum value: 12
  warnings.warn(
12
`
**Client library version and API version:**
Client library version: 15.1.1
Google Ads API version: v10

argcomplete==1.12.3
async-timeout==4.0.2
cachetools==5.0.0
certifi==2021.10.8
charset-normalizer==2.0.12
colorlog==6.6.0
Deprecated==1.2.13
distlib==0.3.4
filelock==3.6.0
google-ads==15.1.1
google-api-core==2.7.1
google-auth==2.6.2
google-auth-oauthlib==0.5.1
googleapis-common-protos==1.56.0
grpcio==1.44.0
grpcio-status==1.44.0
idna==3.3
nox==2022.1.7
oauthlib==3.2.0
packaging==21.3
platformdirs==2.5.1
proto-plus==1.19.6
protobuf==3.17.3
py==1.11.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==3.0.7
PyYAML==5.4.1
redis==4.2.2
requests==2.27.1
requests-oauthlib==1.3.1
rsa==4.8
six==1.16.0
typing-extensions==4.1.1
urllib3==1.26.9
virtualenv==20.14.0
wrapt==1.14.0

**Request/Response Logs:**
[2022-04-28 02:25:03,210 - DEBUG] Making request: POST https://accounts.google.com/o/oauth2/token
[2022-04-28 02:25:03,212 - DEBUG] Starting new HTTPS connection (1): accounts.google.com:443
[2022-04-28 02:25:03,519 - DEBUG] https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
AdvertisingChannelType.SEARCH
AdvertisingChannelType.SEARCH
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.SEARCH
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.SEARCH
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.SEARCH
AdvertisingChannelType.SEARCH
AdvertisingChannelType.SEARCH
AdvertisingChannelType.SEARCH
AdvertisingChannelType.SEARCH
AdvertisingChannelType.SEARCH
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.SEARCH
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.SEARCH
AdvertisingChannelType.SEARCH
AdvertisingChannelType.SEARCH
AdvertisingChannelType.SEARCH
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.SEARCH
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.SEARCH
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.SEARCH
AdvertisingChannelType.VIDEO
AdvertisingChannelType.VIDEO
/home/rabsabius/.local/lib/python3.9/site-packages/proto/marshal/rules/enums.py:37: UserWarning: Unrecognized AdvertisingChannelType enum value: 12
  warnings.warn(
12
12
AdvertisingChannelType.SEARCH
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.SEARCH
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.DISPLAY
AdvertisingChannelType.DISPLAY
12
AdvertisingChannelType.DISPLAY
12
12
AdvertisingChannelType.DISPLAY
[2022-04-28 02:25:05,269 - INFO] Request made: ClientCustomerId: 9064249921, Host: googleads.googleapis.com, Method: /google.ads.googleads.v10.services.GoogleAdsService/SearchStream, RequestId: LU8S4LDPzwymkbeHU_Y1ew, IsFault: False, FaultMessage: None

 
**Anything else we should know about your project / environment:**

**Comment by rabsabius** [comment]
I can confirm the same issue for AdTypeEnum as well

**Comment by wihl** [comment]
Support for Google Ads API v10_1, including Discovery Campaigns, will be added in the next few days to the upcoming v16 release of the Python client library. This has been our typical pattern that the API is released first, followed by updates to the client libraries approximately a week later.
