### ISSUE TITLE
AdvertisingChannelTypeEnum doesnt provide DISCOVERY

### ISSUE THREAD

**Issue by Rutikhal** [googleads/google-ads-python#625]
Hello

**Describe the bug:**
Enum list is not full  for AdvertisingChannelTypeEnum

**Steps to Reproduce:**
I am extracting data from API using this example code

stream = ga_service.search_stream(customer_id=account_id, query=query)
for nb,batch in enumerate(stream):
            for nr,row in enumerate(batch.results):
                    tmp_dict["AdvertisingChannel"] = row.campaign.advertising_channel_type.name
and I have an error sometimes when row.campaign.advertising_channel_type = 12 and there is no name for it.

based on docs  https://developers.google.com/google-ads/api/reference/rpc/v10/AdvertisingChannelTypeEnum.AdvertisingChannelType
should be supported also "DISCOVERY" with  12 enum  of advertising_channel_type but checking all supported Enum
client.get_type("AdvertisingChannelTypeEnum")

I see only these:

DISPLAY:3
HOTEL:5
LOCAL:8
LOCAL_SERVICES:11
MULTI_CHANNEL:7
PERFORMANCE_MAX:10
SEARCH:2
SHOPPING:4
SMART:9
UNKNOWN:1
UNSPECIFIED:0
VIDEO:6

So, I supposed that something missed.

**Expected behavior:**

using row.campaign.advertising_channel_type.name  get string value "DISCOVERY"

**Client library version and API version:**

Client library version:
google-ads==15.1.1
Google Ads API version:
Google Ads API v10

**Comment by wihl** [comment]
Support for Google Ads API v10_1, including Discovery Campaigns, will be added in the next few days to the upcoming v16 release of the Python client library. This has been our typical pattern that the API is released first, followed by updates to the client libraries approximately a week later.
