### ISSUE TITLE
`AdTypeEnum` missing `DISCOVERY_MULTI_ASSET_AD` and `DISCOVERY_CAROUSEL_AD`

### ISSUE THREAD

**Issue by ddoskind** [googleads/google-ads-python#626]
**Describe the bug:**

The [reference list](https://developers.google.com/google-ads/api/reference/rpc/v10/AdTypeEnum.AdType) of values for the `AdTypeEnum` lists the following two `AdType`s that don't seem to be included in https://github.com/googleads/google-ads-python/blob/15.1.1/google/ads/googleads/v10/enums/types/ad_type.py, namely:

* DISCOVERY_MULTI_ASSET_AD
* DISCOVERY_CAROUSEL_AD

**Steps to Reproduce:**

````python
ads_client = google.ads.googleads.client.GoogleAdsClient(None, None)
ads_client.enums.AdTypeEnum.AdType.Value('DISCOVERY_MULTI_ASSET_AD')
````

**Expected behavior:**

Both `DISCOVERY_MULTI_ASSET_AD` and `DISCOVERY_CAROUSEL_AD` are included in `AdTypeEnum`.

**Client library version and API version:**
Client library version: 15.1.1
Google Ads API version: v10

**Comment by ddoskind** [comment]
Note: This seems to be related to the [introduction of version 10.1 of the Ads API](https://ads-developers.googleblog.com/2022/04/announcing-v101-of-google-ads-api.html), which adds support for Discovery campaigns.

**Comment by wihl** [comment]
Support for Google Ads API v10_1, including Discovery Campaigns, will be added in the next few days to the upcoming v16 release of the Python client library. This has been our typical pattern that the API is released first, followed by updates to the client libraries approximately a week later.

**Comment by ddoskind** [comment]
@wihl If I might add a follow-up question, what's the recommended way of best preparing for "automatic" API version updates? Specifically, in this case we had reporting code similar in logic to this:

```python
client = google.ads.googleads.client.GoogleAdsClient(
    <CREDENTIALS>,
    <DEVELOPER_TOKEN>,
    login_customer_id=<MANGER_ACCOUNT_ID>
)
service = client.get_service('GoogleAdsService')
response = service.search(
    customer_id=<ACCOUNT_ID>,
    query='SELECT ad_group_ad.ad.type FROM ad_group_ad'
)
for entry in response:
    ad_type_name = client.enums.AdTypeEnum.AdType.Name(entry.ad_group_ad.ad.type_)
```

Once v10.1 was released, this would no longer work in any accounts that have discovery campaigns set up as the name lookup of the ad type would fail for newly returned `DISCOVERY_MULTI_ASSET_AD` and `DISCOVERY_CAROUSEL_AD` values (35 and 36).

Should enum operations such as this one always be wrapped in a `try...except` block in order to avoid potential `ValueError`s when the enumeration is extended in a minor API upgrade?

**Comment by wihl** [comment]
`try...except` is always a good defensive programming technique. Since enum additions are not considered breaking changes, this update was done in a minor version. Another technique is to be explicit about the major version number when creating the client, as we do in all the code examples: ` googleads_client = GoogleAdsClient.load_from_storage(version="v10")`

so at least your code won't break when a new major version is released.
