### ISSUE TITLE
Behavior Change in Conversion Uploads

### ISSUE THREAD

**Issue by totalhack** [googleads/google-ads-python#627]
I just updated to 15.1.1 running against v10, and I'm seeing some different behavior for both click and call conversion uploads that was not listed as a change anywhere (apologies if I missed it in migration docs or your notes).

I'll stick to the gclid example since the same thing is happening with call conversion uploads. Using `ConversionActionService` to upload a `ClickConversion` we typically backfill a few days or weeks of conversions to A) make sure any conversions that may have been missed in previous days (perhaps due to a failure) get uploaded and B) capture any updates in value as we get modifications often. Previously I could do this without issue. We run our tasks daily btw.

Now I get errors such as the following:

```
'message': 'A conversion with this timestamp already exists for this click. To upload another conversion, please use a different timestamp.', 
'code': conversion_upload_error: CLICK_CONVERSION_ALREADY_EXISTS
```

Is this a documented behavior change?  Are we now forced to do a conversion adjustment upload to capture updates? That's a bit of a pain since we don't know for sure until failure time whether Google even has the conversion...so we'd have to do the same process I'm doing above, find all partial failures, align them to the right conversion upload, and retry it as a `RESTATEMENT` adjustment. It would be a much better DX if it just did an "insert or update"-type operation like it used to (or so I thought) without needing to write special code to find and retry as updates.

Thanks for your help.

**Comment by wihl** [comment]
@totalhack Did you upgrade from v8? The change in behavior about erroring for existing uploads was changed in v9. See https://developers.google.com/google-ads/api/docs/release-notes#conversions_3

> Improved ConversionUploadService and ConversionAdjustmentService to report an error if the ClickConversion, CallConversion, or ConversionAdjustment in a mutate operation already exists or is a duplicate to another one in the same mutate operation. Prior to v9, the Google Ads API would silently ignore such operations

**Comment by totalhack** [comment]
I did update from v8 so it seems that explains it. Thanks for pointing that out.

It sounds like my only options are to retry with an "adjustment" when a conversion upload fails and/or try to keep some local log of what has already succeeded in getting to Google. Honestly both are a bit ugly relative to just having this be an idempotent operation for unchanged values and having a value adjustment be made if the value changed (without needing to use a separate upload type to push a value update). Not sure what kind of sway you guys have with the underlying API team, but that's my 2 cents.

Thanks for your help.

**Comment by wihl** [comment]
Why can't you check for the `DUPLICATE*` or `*ALREADY_EXISTS` errors? If you get this error, you know you don't have to re-submit and can be certain that the previous upload worked.

**Comment by totalhack** [comment]
Of course I can always check for and ignore certain errors as a first workaround, but that's one more potentially error-prone thing I need to maintain as the API is constantly changing. And then how do I know if a value update is needed without more complex logic / logging on my end? Google says it's a dupe, but does not return the value, so I don't know which *version* of a conversion Google already has when it says it's a dupe. So I either need to always try an adjustment, or keep some log of what has succeeded to Google that hopefully stays perfectly in sync and I can use as a source of truth.

We could do all of that, or Google could simply make this an insert-or-update that doesn't complain about dupes and all of the complexity is removed on the developer side.

**Comment by wihl** [comment]
The change to return this error instead of silently ignoring duplicates was actually made to _help_ users who were really unhappy and confused with the prior behavior. This was one of the top asks the conversion team received in user feedback.

The prior behavior of succeeding while silently being a no-op doesn't address your use case, as you still wouldn't have known which succeeded. So in that sense, there is no change in behavior. Since we now report duplicates, you can be certain that the first successful one has the values you supplied.

**Comment by totalhack** [comment]
I guess I don't see what would be confusing about the insert-ignore style behavior of trying to upload a duplicate conversion. The goal is to get the conversion with that value into Google, and it did that...it doesn't qualify as an error IMO. However, if there was a different conversion value and it was silently ignoring that, I can see why that would be a bug and need better behavior.

That all said the easiest solution is still insert-or-update style behavior. It's unclear to me why there would ever be a use case where that is inappropriate, but if there is perhaps it could be controlled with a flag. The current situation does *not* allow me to be certain that the values Google has matches the values I have locally unless I keep track of a local log of which conversions I think Google has successfully received and at what value. That's doable, but again the main point is that is all unnecessary work if it just had insert-or-update behavior.
