### ISSUE TITLE
Migrating to Google Ads API v10

### ISSUE THREAD

**Issue by Sunil310** [googleads/google-ads-python#628]
Hi,
I have been notified that Google Ads API v8 have been deprecated and will stop accepting requests on May 11, 2022.
I am trying to adapt my python script to the upcoming change and migrate to v10. I refer to this [example ](https://github.com/googleads/google-ads-python/blob/73e61d50150385042957e908a5a1a6632afedcc1/examples/basic_operations/get_campaigns.py)for all code changes.

The code works fine for v8 but fails if i specify v10, it says the version doesn't exist. I was wondering if this is due to the version of the google package I have installed. In that case , could you recommend the correct version ? will installing the latest version of google-ads ( 15.1.1) from [here ](https://pypi.org/project/google-ads/) work ? I currently have 14.1.0

**Here is the code i execute:**

import google.ads.googleads.client
google_ads_client = google.ads.googleads.client.GoogleAdsClient.load_from_storage(version="v10",path="/efs/home/ps076497/code/google_ads/google-ads.yaml")   ### specifying version="v8" works fine
ga_service = google_ads_client.get_service("GoogleAdsService")

**Error msg :**
ValueError: Specified Google Ads API version "v10" does not exist. Valid API versions are: "v9", "v8", "v7"

![image](https://user-images.githubusercontent.com/102165822/165893994-a54bcffa-7785-4141-8c03-570a6eb4495a.png)

**Here are the all the package details ( pip freeze):**
aenum==3.1.8
anyio==3.5.0
apiclient==1.0.4
appdirs==1.4.4
APScheduler==3.8.1
argcomplete==1.12.3
asgiref==3.5.0
azure-core==1.21.1
azure-storage-blob==12.9.0
bcrypt==3.2.0
beautifulsoup4==4.10.0
bitarray==2.3.5
bs4==0.0.1
cachetools==5.0.0
case-conversion==2.1.0
certifi==2021.10.8
cffi==1.15.0
chardet==4.0.0
charset-normalizer==2.0.11
click==8.0.3
clipboard==0.0.4
colorama==0.4.4
colorlog==6.6.0
colour==0.1.5
cramjam==2.5.0
cryptography==36.0.1
cursor==1.3.4
DateTime==4.3
decorator==4.4.2
dill==0.3.4
distlib==0.3.4
docopt==0.6.2
et-xmlfile==1.1.0
fastapi==0.73.0
fastparquet==0.8.0
filelock==3.4.2
fire==0.4.0
fsspec==2022.1.0
fuzzywuzzy==0.18.0
gender-guesser==0.4.0
google==3.0.0
google-ads==14.1.0
google-api-core==1.31.5
google-api-python-client==1.12.3
google-auth==2.6.0
google-auth-httplib2==0.1.0
google-auth-oauthlib==0.4.6
googleapis-common-protos==1.54.0
grpcio==1.43.0
gssapi==1.7.2
h11==0.13.0
hdfs==2.6.0
html-text==0.5.2
httplib2==0.20.2
httptools==0.3.0
idna==3.3
imageio==2.14.1
imageio-ffmpeg==0.4.5
importlib-metadata==4.10.1
impyla==0.17.0
infi.systray==0.1.12
inflect==5.4.0
isodate==0.6.1
joblib==1.1.0
kafka-python==2.0.2
kerberos==1.3.1
krb5==0.2.0
lxml==4.7.1
lz4==3.1.10
maybe-else==0.2.1
mbstrdecoder==1.1.0
moviepy==1.0.3
msal==1.16.0
msoffcrypto-tool==5.0.0
msrest==0.6.21
nltk==3.6.7
nox==2022.1.7
ntlm-auth==1.5.0
numpy==1.18.4
O365==2.0.17
oauth2client==4.1.3
oauthlib==3.2.0
office365==0.3.15
Office365-REST-Python-Client==2.3.10
olefile==0.46
openpyxl==3.0.9
packaging==21.3
pandas==1.3.5
paramiko==2.9.2
parsedatetime==2.6
pathmagic==0.3.14
Pillow==9.0.0
platformdirs==2.4.1
praw==7.5.0
prawcore==2.3.0
prettierfier==1.0.3
proglog==0.1.9
proto-plus==1.18.1
protobuf==3.17.3
psycopg2==2.9.3
pure-sasl==0.6.2
py==1.11.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pydantic==1.9.0
pydub==0.25.1
pyinstrument==4.1.1
pyiotools==0.3.18
PyJWT==2.3.0
pylzma==0.5.0
pymiscutils==0.3.14
PyNaCl==1.5.0
pyodbc==4.0.32
pyparsing==3.0.7
PyPDF2==1.26.0
pyperclip==1.8.2
PyQt5==5.15.6
PyQt5-Qt5==5.15.2
PyQt5-sip==12.9.1
pysftp==0.2.9
pyspellchecker==0.6.3
pyspnego==0.3.1
pysubtypes==0.3.18
python-dateutil==2.8.2
python-docx==0.8.11
python-dotenv==0.19.2
python-snappy==0.6.0
pytz==2021.3
PyYAML==5.4.1
readchar==3.0.5
regex==2022.1.18
requests==2.27.1
requests-kerberos==0.14.0
requests-ntlm==1.1.0
requests-oauthlib==1.3.1
requests-toolbelt==0.9.1
rsa==4.8
Send2Trash==1.8.0
SharePlum==0.5.1
sharepy==1.3.0
simplejson==3.17.6
six==1.16.0
sniffio==1.2.0
soupsieve==2.3.1
starlette==0.17.1
stringcase==1.2.0
subprocess32==3.5.4
tabulate==0.8.9
termcolor==1.1.0
thrift==0.11.0
thrift-sasl==0.4.3
tqdm==4.62.3
typepy==1.3.0
typing-extensions==4.0.1
tzlocal==2.1
update-checker==0.18.0
uritemplate==3.0.1
urllib3==1.26.8
uvicorn==0.17.1
uvloop==0.16.0
virtualenv==20.13.0
watchgod==0.7
websocket-client==1.2.3
websockets==10.1
xlrd==1.2.0
XlsxWriter==3.0.2
zipp==3.7.0
zope.interface==5.4.0

**Comment by hui-ho** [comment]
it's supported since v15.0.0

https://github.com/googleads/google-ads-python/releases/tag/15.0.0

**Comment by wihl** [comment]
Installing the latest version will solve the problem. @hui-ho is correct. Thanks for replying quickly!
