### ISSUE TITLE
get recommendation example prints nothing

### ISSUE THREAD

**Issue by pratiksha-cobiro** [googleads/google-ads-python#63]
Hello

I am trying the following piece of code

https://github.com/googleads/google-ads-python/blob/master/examples/recommendations/get_text_ad_recommendations.py

It does not print anything, I have tries with multiple customer ids.
Also , by looking at the API and other example of apply recommendation , I tried to use get recommendation from Recommendation Service. I do not know what should be resource name to get recommendations for text ads. I tried with 'google.ads.googleads.v1.resources.Recommendation.TextAdRecommendation' but it gives the following error.

`google.ads.google_ads.errors.GoogleAdsException: (<_Rendezvous of RPC that terminated with:
        status = StatusCode.NOT_FOUND
        details = "Requested entity was not found."
        debug_error_string = "{"created":"@1553604325.576345000","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1036,"grpc_message":"Requested entity was not found.","grpc_status":5}"
>, <_Rendezvous of RPC that terminated with:
        status = StatusCode.NOT_FOUND
        details = "Requested entity was not found."
        debug_error_string = "{"created":"@1553604325.576345000","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1036,"grpc_message":"Requested entity was not found.","grpc_status":5}"
>, errors {
  error_code {
    request_error: BAD_RESOURCE_ID
  }
  message: "\'google.ads.googleads.v1.resources.Recommendation.TextAdRecommendation\' part of the resource name is invalid."
}
`

Kindly update how to use the example to get recommendations for text ad.

Regards
Pratiksha

**Comment by BenRKarl** [comment]
Hi @pratiksha-cobiro I'm looking into this and will follow up with more info as soon as possible! Thanks for posting the issue.

**Comment by BenRKarl** [comment]
@pratiksha-cobiro Apologies for the delay here - are you continuing to have this problem? For reference, resource names are unique identifiers for individual resources, such as recommendations. See the [reference page](https://developers.google.com/google-ads/api/docs/fields/recommendation) for recommendations for more details on each field. 

To select recommendations for text ads, you will need to filter by the `type` field, for example:

```sql
SELECT recommendation.type FROM recommendation WHERE recommendation.type = "TEXT_AD"
```

Closing this issue for now but please reopen if you have further questions.
