### ISSUE TITLE
Support protobuf 3.20.1

### ISSUE THREAD

**Issue by smoucka** [googleads/google-ads-python#631]
**Describe the problem you are trying to solve:**
Avoid downgrading the version of protobuf our app uses (currently 3.20.1) in order to also use this library. Suggesting the SDK include support for protobuf 3.20.1.
**Describe the solution you'd like:**
Bump support for protobuf like `<=3.20.1` or `<4` to capture support for protobuf 3.20.1
**Describe alternatives you've considered:**
Downgrading our app to use protobuf 3.20.0
Working around the Google Ads python SDK
**Additional context:**

**Comment by bobhancock** [comment]
3.20.1 did not contain any changes to the Python layer, so the likelihood of problems is small but it has not been tested for a release version of the library. This version or greater is being considered for the next release of the client library.

In the interim, you could download the client library source, modify setup.py to incorporate this version in the range, and install the library. Disclaimer: this would not be a supported configuration should problems arise.
