### ISSUE TITLE
Channel deallocated issue

### ISSUE THREAD

**Issue by redflashes** [googleads/google-ads-python#634]
I am trying to extract data via Google Ads API and I encounter this error many times:

It is likely not an account issue / code issue as there are times where my code succeed.

Part of the error message:
```
Request made: ClientCustomerId:  <masked>  , Host: [googleads.googleapis.com](http://googleads.googleapis.com/), Method: /google.ads.googleads.v10.services.GoogleAdsService/SearchStream, RequestId: None, IsFault: True, FaultMessage: Channel deallocated!

_SingleThreadedRendezvous: <_SingleThreadedRendezvous of RPC that terminated with:    status = StatusCode.CANCELLED    details = "Channel deallocated!"    debug_error_string = "{"created":"@<masked>","description":"Error received from peer ipv4: <masked>  ","file":"src/core/lib/surface/call.cc","file_line":904,"grpc_message":"Channel deallocated!","grpc_status":1}" >
```

I masked out certain parts of the code as I am not sure if they are sensitive

**Comment by wihl** [comment]
I suspect this is the same as https://github.com/googleads/google-ads-python/issues/384. Please verify that the grpc client and streaming iterator being used in the same function scopes. This is documented in https://developers.google.com/google-ads/api/docs/client-libs/python/streaming-iterators
