### ISSUE TITLE
Migrating to Version 16 in Composer Airflow

### ISSUE THREAD

**Issue by whubbard-rl** [googleads/google-ads-python#635]
[airflow2.requirements.txt](https://github.com/googleads/google-ads-python/files/8734492/airflow2.requirements.txt)
[log.txt](https://github.com/googleads/google-ads-python/files/8734493/log.txt)

I'm working with Google's Composer Airflow product (running off of their us-docker.pkg.dev/cloud-airflow-releaser/airflow-worker-scheduler-2-2-3/airflow-worker-scheduler-2-2-3:latest image), and we are trying to upgrade to use the v10 API. I attempted to set our python requirements to use version 16 (it is currently 14 as shown in the attached file). However, whenever I do so, I get errors from the `apache-airflow-providers-google` module, remarking that it requires a version under 14.0.1 (as reflected by [Pypi](https://pypi.org/project/apache-airflow-providers-google/6.7.0/)). The unusual thing is, our requirements file doesn't ever specify apache-airflow-providers-google, but I'm assuming that this dependency comes with the image.
With this, I'm left unsure as to how to migrate our project to properly use version 16 of the Python API interface. After consulting with Google Ads API support, I was directed to create an issue here. Is there a guide to using this library in airflow that I could refer to in our product?

**Comment by devopsangel** [comment]
@bobhancock is there any updates on this?

**Comment by bobhancock** [comment]
The changes have been made to the Python layer of protocol buffers. They
will be in the next release.

**Comment by BenRKarl** [comment]
Hi @whubbard-rl - this issue doesn't actually look like something we can fix on our end. Like you mention, the Composer image comes pre-loaded with a specific set of dependencies, and the `apache-airflow-providers-google` module, (which we don't maintain) would need to be updated to support newer versions of this library. My recommendation would be to try using a different Composer image that may include newer versions of these libraries. Could you let us know whether that's possible?

**Comment by BenRKarl** [comment]
@whubbard-rl I'm going to mark this one as closed as I don't think there's any action we can take in this library to fix the problem, but please reopen or add more details if I'm mistaken.
