### ISSUE TITLE
login_customer_id unused in API requests

### ISSUE THREAD

**Issue by rs-mkaiser** [googleads/google-ads-python#636]
**Describe the bug:**
We have migrated from Google Adwords to Google Ads API. Jobs for certain customers of ours with the same credentials started failing due to a permission issue. Reaching out to Google Ads support, they recommended setting the login_customer_id and sending them the logging of the request. Upon setting login_customer_id in the configuration dictionary, there was no change in the logged headers, and we are still unable to make API calls to our customer's Google Ads accounts.

**Steps to Reproduce:**

```
from target_google.google_api import GoogleAPI
from google.ads.googleads.client import GoogleAdsClient
from google.ads.googleads.errors import GoogleAdsException
from logging_interceptor import LocalLoggingInterceptor
import logging

client_customer_id = "redacted"
developer_token = "redacted"
refresh_token = "redacted"
client_id = "redacted"
client_secret = "redacted"
credentials = {
    "login_customer_id": "redacted",
    "developer_token": developer_token,
    "refresh_token": refresh_token,
    "client_id": client_id,
    "client_secret": client_secret,
    "use_proto_plus": False,
}
client = GoogleAdsClient.load_from_dict(credentials)
# I have tried adding the following line, *with success*, however it still is missing from headers logging
# client.login_customer_id = "redacted"

customer_id = "redacted"

_API_VERSION = "v10" # Same behavior with v9
googleads_service_client = google_api.client.get_service(
    "GoogleAdsService", interceptors=[LocalLoggingInterceptor(api_version="v10")] # Same behavior with v9
)

# Creates a query that retrieves the user list.
query = f"""
    SELECT
    user_list.size_for_display,
    user_list.size_for_search
    FROM user_list"""

# Issues a search request. Will fail due to customer access issues so we need to add the header here
search_results = googleads_service_client.search(customer_id=customer_id, query=query)
```
Our LocalLoggingInterceptor prints all log lines to stdout and looks like the following:

```
INFO Request
-------
Method: /google.ads.googleads.v9.services.GoogleAdsService/Search
Host: None
Headers: {
  "x-goog-api-client": "gl-python/3.9.9 grpc/1.43.0 gax/2.3.2 gccl/14.1.0",
  "x-goog-request-params": "customer_id=redacted"
}
Request: customer_id: "redacted"
query: "\n    SELECT\n    user_list.size_for_display,\n    user_list.size_for_search\n    FROM user_list"


Response
-------
Headers: {
  "google.ads.googleads.v9.errors.googleadsfailure-bin": "\n\u0001\n\u0002H\u0002\u0012\u0001User doesn't have permission to access customer. Note: If you're accessing a client customer, the manager's customer id must be set in the 'login-customer-id' header. See [https://developers.google.com/google-ads/api/docs/concepts/call-structure#cid\u0012\u0016aSQ0BSg5EPWTExFkPhERQg](https://developers.google.com/google-ads/api/docs/concepts/call-structure#cid%5Cu0012%5Cu0016aSQ0BSg5EPWTExFkPhERQg)",
  "grpc-status-details-bin": "\b\u0007\u0012#The caller does not have permission\u001a\u0002\[nCtype.googleapis.com/google.ads.googleads.v9.errors.GoogleAdsFailure\u0012\u0002\n\u0001\n\u0002H\u0002\u0012\u0001User](http://nctype.googleapis.com/google.ads.googleads.v9.errors.GoogleAdsFailure%5Cu0012%5Cu0002%5Cn%5Cu0001%5Cn%5Cu0002H%5Cu0002%5Cu0012%5Cu0001User) doesn't have permission to access customer. Note: If you're accessing a client customer, the manager's customer id must be set in the 'login-customer-id' header. See [https://developers.google.com/google-ads/api/docs/concepts/call-structure#cid\u0012\u0016aSQ0BSg5EPWTExFkPhERQg](https://developers.google.com/google-ads/api/docs/concepts/call-structure#cid%5Cu0012%5Cu0016aSQ0BSg5EPWTExFkPhERQg)",
  "request-id": "aSQ0BSg5EPWTExFkPhERQg"
}
Fault: errors {
  error_code {
    authorization_error: USER_PERMISSION_DENIED
  }
  message: "User doesn\'t have permission to access customer. Note: If you\'re accessing a client customer, the manager\'s customer id must be set in the \'login-customer-id\' header. See https://developers.google.com/google-ads/api/docs/concepts/call-structure#cid"
}
request_id: "aSQ0BSg5EPWTExFkPhERQg"
```

**Expected behavior:**

Expected behavior would be that login-customer-id would be present in the headers, and that we would not receive an error (or we would receive a very descriptive error). Here is what I imagine we might see:

```
Headers: {
  "x-goog-api-client": "gl-python/3.9.9 grpc/1.43.0 gax/2.3.2 gccl/14.1.0",
  "x-goog-request-params": "customer_id=redacted login_customer_id=redacted-login-customer-id"
}
```

**Client library version and API version:**
Client library version: Confirmed in both "google-ads==16.0.0", and "google-ads==14.1.0"
Google Ads API version: v9/v10

setup.py used:
install_requires=[
        "singer-python==5.1.5",
        "jsonschema==2.6.0",
        "google-ads==16.0.0",
        "backoff==1.3.2",
    ]

**Request/Response Logs:**

Logging was written above in-line.
 
**Anything else we should know about your project / environment:**

This is an ongoing issue being discussed in a Google Ads API Support ticket since May 2nd. Our project is uploading users to our customer's Google Ads user lists based on the account ID they supplied to us, and OAuth credentials that were generated. The account that is returned from customer_service.list_accessible_customers() is _different_ than the customer id we were provided, however **this is working in the Google adwords API**.

**Update**:
I was able to successfully set login_customer_id using client.login_customer_id = "redacted", however it is unclear how to determine which account we need to set as login_customer_id to access yet another, different, customer_id - the error we receive is non-descriptive, and with potentially multiple accounts listed in `customer_service.list_accessible_customers()`, it is unclear how we should proceed with parity to Google adwords which did not require this.

**Comment by wihl** [comment]
The issue you are describing is not specific to the Python library, so you will have to continue using the support channels you have already started with. I will be closing this issue. Here are some pointers that may help:

https://developers.google.com/google-ads/api/docs/migration/login-customer-id

Use https://developers.google.com/google-ads/api/docs/account-management/listing-accounts and https://developers.google.com/google-ads/api/docs/account-management/get-account-hierarchy
to find which accounts your MCC can manage. Set the `login-customer-id` to the immediate parent of the leaf advertiser account.

For example, if your hierarchy is MCC1 -> MCC2 -> MCC3 -> advertiser account, set login-customer-id to be MCC3.

`login-customer-id` is the equivalent of choosing which account to manage when logging to the Ads UI https://support.google.com/google-ads/answer/1722062?hl=en#zippy=%2Caccess-multiple-google-ads-accounts-from-the-same-google-account

**Comment by rs-mkaiser** [comment]
`login-customer-id` missing from the logged headers are not concerning to you?
