### ISSUE TITLE
Cannot remove an adgroup ad

### ISSUE THREAD

**Issue by e-lepilov** [googleads/google-ads-python#639]
Hi there!
I'm trying to remove ad using this code example

```
def main(client, customer_id, ad_group_id, ad_id):
    ad_group_ad_service = client.get_service("AdGroupAdService")
    ad_group_ad_operation = client.get_type("AdGroupAdOperation")

    resource_name = ad_group_ad_service.ad_group_ad_path(
        customer_id, ad_group_id, ad_id
    )
    ad_group_ad_operation.remove = resource_name

    ad_group_ad_response = ad_group_ad_service.mutate_ad_group_ads(
        customer_id=customer_id, operations=[ad_group_ad_operation]
    )
```
But got an error

```
  error_code {
    ad_group_ad_error: AD_TYPE_CANNOT_BE_REMOVED
  }
  message: "Cannot remove an adgroup ad with this ad type."
```
So the ad type is **APP_AD**

Is this a limitation of the API or some gogle ads limitation  or can it be removed? If so, how ?
My goal is to find a way to remove all the assets associated with a particular ad. I.e. to get the same result that I get in the google panel interface by manually deleting the assets inside the group. 
[sample image](https://ibb.co/L8NC6QP)

As [AssetOperation](https://developers.google.com/google-ads/api/reference/rpc/v10/AssetOperation?hl=en) does not support delete operations, I am looking for a way to do this  if possible for my ad type.

**Comment by e-lepilov** [comment]
I've been looking into the issue for a while and have roughly figured out the cause of the problem. Tried to go the other way through AdService instead of  AdGroupAdService

_sample for video assets_

```
    query = """
        SELECT 
          ad_group_ad.ad.app_ad.youtube_videos 
        FROM ad_group_ad 
        WHERE ad_group_ad.ad.id = '594656045916'"""

    ga_service = client.get_service("GoogleAdsService")
    # Retrieve the existing ad from the API
    response = ga_service.search(customer_id=customer_id, query=query)
    # Retrieve the ad object from the response
    ad = response.results[0].ad_group_ad.ad
    print(f'{ad.app_ad.youtube_videos}') --> return [asset: "customers/23../assets/239..", asset: "customers/230../assets/23..", "asset_3"..., "asset4"]
   
   # Here I assume assets are contained in a list, and simply clean it up by assigning an empty list
    ad.app_ad.youtube_videos=[]

    ad_service = client.get_service("AdService")
    ad_operation = client.get_type("AdOperation")

    client.copy_from(ad_operation.update, ad)
    client.copy_from(
        ad_operation.update_mask, protobuf_helpers.field_mask(None, ad._pb)
    )
    # Updates the ad.
    ad_service.mutate_ads(
        customer_id=customer_id, operations=[ad_operation]
    )
```

And this code ran successfully, but the assets are still displayed in the google interface, i.e. it looks like no change was made.
 I may have chosen the wrong way again. I would appreciate your help with this problem.

**Comment by bobhancock** [comment]
This is an API issue not an issue with the library. You can receive support by sending an email to googleadsapi-support@google.com or visiting our forum at https://groups.google.com/forum/#!forum/adwords-api.
