### ISSUE TITLE
Possibility to delete the asset links associated with ad

### ISSUE THREAD

**Issue by e-lepilov** [googleads/google-ads-python#642]
Hi there! 
I'm looking for way to stop an asset from serving, and try to do it with remove the link between asset and ad (because the google api does not support the ability to delete assets directly or delete the whole ad with type  = [APP_AD](https://developers.google.com/google-ads/api/rest/reference/rest/v10/customers.ads?hl=en#adtype) )
I've looked through all the sample code from this library and can't find anything that fits. Is it possible, in principle, to perform such a query? If so, what should be used for it?
Thanks!

**Comment by wihl** [comment]
Call `AssetSetAssetOperation` with the remove method (https://developers.google.com/google-ads/api/reference/rpc/v10/AssetSetAssetOperation#remove) and the resource name of the `AssetSetAsset` that links the Asset to the Ad.
