### ISSUE TITLE
Partial failure not accepted on GoogleAdsRequest 

### ISSUE THREAD

**Issue by matthew-kaye** [googleads/google-ads-python#643]
Hi, I tried reporting in #641, but it was closed without a working solution. If I try the recommended solution (pasted here):
```
        request = client.get_type("MutateGoogleAdsRequest")
        request.customer_id =  'MY_ID'
        request.mutate_operations = [...]
        request.partial_failure = True
        request.validate_only = True
        service = client.get_service("GoogleAdsService", version="v10")
        service.mutate(request=request)
```
then I get the error:

`AttributeError: Assignment not allowed to repeated field "mutate_operations" in protocol message object.`

Please could #641 be reopened? The original mutate method I asked about should be able to accept a `partial_failure` argument

**Comment by BenRKarl** [comment]
@matthew-kaye as @bobhancock mentioned, the error here is related to the following line:

`request.mutate_operations = [...]`

That should instead look like this:

`request.mutate_operations.extend([...])`

If you need clarity on #641 feel free to reopen it, but I can tell you that your solution above is correct in terms of using `partial_failure`

**Comment by matthew-kaye** [comment]
Cool thanks for the reply, I did find a solution in the end though can't remember if it was this one as I've now moved companies 😅 would be a good one to include in the docs for anyone else though
