### ISSUE TITLE
Remove asset from the list of asset by the asset resource_name

### ISSUE THREAD

**Issue by e-lepilov** [googleads/google-ads-python#644]
Hi there!

I try make remove operation from the list of linked [youtube_videos](https://developers.google.com/google-ads/api/reference/rpc/v9/AppAdInfo)

```
def ad_asset_remove(client, customer_id):
    query = """
         SELECT
           ad_group_ad.ad.app_ad.youtube_videos
         FROM ad_group_ad
         WHERE ad_group_ad.ad.id = '594656045916'"""

    ga_service = client.get_service("GoogleAdsService")
    response = ga_service.search(customer_id=customer_id, query=query)
    ad = response.results[0].ad_group_ad.ad
   
    print(f'BEFORE: {ad.app_ad.youtube_videos}')
  # print result
  #  BEFORE: [asset: "customers/2309565764/assets/23967118006"
  #  , asset: "customers/2309565764/assets/36881381302"
  # , asset: "customers/2309565764/assets/36881381422"
  #  , asset: "customers/2309565764/assets/36914146554"
   # , asset: "customers/2309565764/assets/23954537753"
   # , asset: "customers/2309565764/assets/23995613823"
   # ]
   
    
    print(f' {type(ad.app_ad.youtube_videos[0])}') 
    # print result
    # <class 'google.ads.googleads.v10.common.types.ad_asset.AdVideoAsset'>

   
    #Make remove operation using asset_resourse_name for first element of list
    ad.app_ad.youtube_videos.remove("customers/2309565764/assets/23967118006")

    ad_service = client.get_service("AdService")
    ad_operation = client.get_type("AdOperation")

    client.copy_from(ad_operation.update, ad)
    client.copy_from(
        ad_operation.update_mask, protobuf_helpers.field_mask(None, ad._pb)
    )
    ad_service.mutate_ads(
        customer_id=customer_id, operations=[ad_operation]
    )
```
This returns an error as ValueError, this means that the remove method did not find an item with this value  `customers/2309565764/assets/23967118006`  in the list. 
I.e. resourse_name is not really the right thing to use. And indeed, in the list the first element has the value  `asset: "customers/2309565764/assets/23967118006"`
I try to use 
` ad.app_ad.youtube_videos.remove('asset: "customers/2309565764/assets/23967118006"')` but got same error

But good news if I try to use the **pop** method instead **remove** and asset index
 ad.app_ad.youtube_videos.pop(0)
all starting work fine. This tells us that the remove method is correct. And I just need to figure out how to use the remove method with resource_name. 

Can you please recommend a solution?

**Comment by BenRKarl** [comment]
@e-lepilov let's start with the idea that you have a list of [AdVideoAsset](https://developers.google.com/google-ads/api/reference/rpc/v9/AdVideoAsset) instances and you want to remove one of them based on its properties (i.e. the resource name attached to the `asset` field). First, keep in mind that an `AdVideoAsset` is not the same thing has a `dict` so you can't do list operations in the same way.

You can however use another instance of `AdVideoAsset` in a call to remove, for example:

```py
first = client.get_type("AdVideoAsset")
first.asset = "customers/2309565764/assets/23967118006"
second = client.get_type("AdVideoAsset")
second.asset = "customers/2309565764/assets/23995613823"
videos = [first, second]
print(videos)
# [asset: "customers/2309565764/assets/23967118006"
# , asset: "customers/2309565764/assets/23995613823"
# ]
third = client.get_type("AdVideoAsset")
# Set value of "asset" to be the same as the second video.
third.asset = "customers/2309565764/assets/23995613823"
videos.remove(third)
print(videos)
# [asset: "customers/2309565764/assets/23967118006"
# ]
```

To me, it's a little cumbersome to create a new `AdVideoAsset` just to pass to the `remove` call, so you could also use a loop like this:

```py
for i, video in enumerate(ad.app_ad.youtube_videos):
    if video.asset == "customers/2309565764/assets/23967118006":
        ad.app_ad.youtube_videos.pop(i)
```

Hope that helps!
