### ISSUE TITLE
[google-ads-python-v.16.0.0] error while initialising v11 client: google-ads-Specified Google Ads API version "v11" does not exist. Valid API versions are: "v10", "v9"

### ISSUE THREAD

**Issue by srvRoy** [googleads/google-ads-python#646]
**What is your question?**
[google-ads-python-v.16.0.0] error while initialising v11 client: google-ads-Specified Google Ads API version "v11" does not exist. Valid API versions are: "v10", "v9"

16.0.0 being the latest version should support v11.
Mentioned here: https://developers.google.com/google-ads/api/docs/client-libs

Will v11 be supported in subsequent releases? When can we expect that?

**Comment by srvRoy** [comment]
Hi @google-ospo-team , @kokoro-team . Any solution to this?

**Comment by google-admin** [comment]
@googleads/aw-devrel

**Comment by bobhancock** [comment]
The library that supports v11 will be available in a couple of days.
