### ISSUE TITLE
Bug: google-ads-python v15.X.X missing new Enum in Google Ads API v10

### ISSUE THREAD

**Issue by Kache** [googleads/google-ads-python#647]
**Describe the bug:**

`AdvertisingChannelType.DISCOVERY` is new to API v10, compare:

 * https://developers.google.com/google-ads/api/reference/rpc/v10/AdvertisingChannelTypeEnum.AdvertisingChannelType
 * https://developers.google.com/google-ads/api/reference/rpc/v9/AdvertisingChannelTypeEnum.AdvertisingChannelType

And although google-ads-python 15.0.0 is supposed to support API v10: https://github.com/googleads/google-ads-python/blob/15.0.0/google/ads/googleads/client.py#L37=

That Enum is missing: https://github.com/googleads/google-ads-python/blob/15.0.0/google/ads/googleads/v10/enums/types/advertising_channel_type.py

Which caused errors for us when upgrading to API v10 ahead of the soon-coming sunset of v9. I've found the same issue in all v15.X.X versions.

**Steps to Reproduce:**

Query an entity containing an `AdvertisingChannelType.DISCOVERY` value.

**Expected behavior:**

Receive the Enum, `AdvertisingChannelType.DISCOVERY`.

**Client library version and API version:**
Client library version: v15.X.X
Google Ads API version: v10

**Request/Response Logs:**

 
**Anything else we should know about your project / environment:**

---

Our current workaround is to upgrade google-ads-python to v16.0.0, which does have the Enum defined.

Will the google-ads-python project be able to keep up with Google Ads API's [Sunset timetable](https://developers.google.com/google-ads/api/docs/sunset-dates#timetable)? With API v9 sunsetting in \~30 days and this library not yet able to support v11, the only working API & client version pair will be (v10, v16.0.0), which doesn't bring much peace of mind b/c v10 is scheduled to sunset 3\~4 months after that.

**Comment by bobhancock** [comment]
This is a bug that was corrected in >= 16.0.0. Using one of these versions is the best solution.
