### ISSUE TITLE
get_campaigns.py returns nothing

### ISSUE THREAD

**Issue by tarikbahar** [googleads/google-ads-python#649]
Hi,
I am trying to get data from Google ADS via API. For this, I am following [this document.](https://developers.google.com/google-ads/api/docs/first-call/overview)

I created my googleads.yaml file properly. After that, When I run the get_campaigns.py file in [this link,](https://github.com/googleads/google-ads-python/blob/main/examples/basic_operations/get_campaigns.py) nothing happens. It doesn't return anything. It doesn't get any errors. It doesn't write anything. It just works and finishes. I am sure I have campaigns on Google ADS but I am not getting it via API.
Thanks in advance for your help.

**Comment by bobhancock** [comment]
Please provide a code sample to reproduce the error. Be sure to sanitize the code so that no PII is exposed.

**Comment by BenRKarl** [comment]
@tarikbahar as @bobhancock mentioned could you provide more details as to how you're running the file, and what the logs show after it's executed? Instructions on how to enable logging are found [here](https://developers.google.com/google-ads/api/docs/client-libs/python/logging). Before posting any logs, please be sure they don't contain any personally identifiable information, such as developer token, client ID, client secret, or refresh token.

**Comment by BenRKarl** [comment]
@tarikbahar I'm going to close this issue as stale for now, but please reopen if you have more questions or details based on my last comment.
