### ISSUE TITLE
Force error for testing?

### ISSUE THREAD

**Issue by jstrome-lmp** [googleads/google-ads-python#651]
**What is your question?**

Hey there,

In the Python SDK, is there a way to force "GoogleAdsException" to return an error (internal_error in my case)?  I have developed an automatic retry using one of the example scripts as a guide and want to test.  If anyone has an automatic retry for internal errors that works I would appreciate that very much as well.

Thanks!

**Comment by BenRKarl** [comment]
@jstrome-lmp we have a [section of examples](https://github.com/googleads/google-ads-python/tree/main/examples/error_handling) that show different ways of handling errors, each one intentionally triggers an error. Hopefully one of those will work for your use case.
