### ISSUE TITLE
Best Way to Parse Partial_Failure_Error when Sending Multiple Conversions in One Request (conversion_upload_service.upload_call_conversions())

### ISSUE THREAD

**Issue by jbrow70** [googleads/google-ads-python#654]
Hi,

We're using this as our starting point: https://developers.google.com/google-ads/api/docs/conversions/upload-calls#python but have updated our code so that we send multiple conversions in one request (batching it) so something like this (just a basic code snippet to show what we're trying to do. not literally doing it this way):

`   request.conversions = [call_conversion1 , call_conversion2 , call_conversion3 , call_conversion4 , call_conversion5]
    request.partial_failure = True
    upload_call_conversions_response = (
        conversion_upload_service.upload_call_conversions(request=request)
    )
print(upload_call_conversions_response )`

the print results in this:

`partial_failure_error {
    code: 3
    message: "Multiple errors in \342\200\230details\342\200\231. First error: The string date time\'s format should be yyyy-mm-dd hh:mm:ss+|-hh:m., at conversions[0].call_start_date_time"
    details {
        type_url: "type.googleapis.com/google.ads.googleads.v10.errors.GoogleAdsFailure"
        value: "\n\216\001\n\003\210\002\014\022CThe string date time\'s format should be yyyy-mm-dd hh:mm:ss+|-hh:m.\032\027*\0255/26/2022 14:42+00:00\")\022\017\n\013conversions\030\000\022\026\n\024call_start_date_time\n\216\001\n\003\210\002\014\022CThe string date time\'s format should be yyyy-mm-dd hh:mm:ss+|-hh:m.\032\027*\0255/26/2022 16:00+00:00\")\022\017\n\013conversions\030\001\022\026\n\024call_start_date_time\n\216\001\n\003\210\002\014\022CThe string date time\'s format should be yyyy-mm-dd hh:mm:ss+|-hh:m.\032\027*\0255/26/2022 13:49+00:00\")\022\017\n\013conversions\030\002\022\026\n\024call_start_date_time\n\216\001\n\003\210\002\014\022CThe string date time\'s format should be yyyy-mm-dd hh:mm:ss+|-hh:m.\032\027*\0255/26/2022 14:09+00:00\")\022\017\n\013conversions\030\003\022\026\n\024call_start_date_time\n\216\001\n\003\210\002\014\022CThe string date time\'s format should be yyyy-mm-dd hh:mm:ss+|-hh:m.\032\027*\0255/26/2022 16:00+00:00\")\022\017\n\013conversions\030\004\022\026\n\024call_start_date_time"
    }
}
results {}
results {}
results {}
results {}
results {}`

Now ignore the specific errors as that's not relevant really to this question, but let's say we want to associate the right error to the right conversion upload from that one request. Each has something like conversions\030\000 conversions\030\001 conversions\030\002, etc. so that's good in that each element in the results array should be associated to the same one in the message portion of partial_failure_error but the way it's formatted (in partial_failure_error.details) there seems to be something we're missing to make it simple in the code to associate the right error to the right conversion result. Like we need to convert that partial_failure_error.details to json or something and then for every element in the results array associate to right one. What can complicate this is maybe a batch has some that succeed and some that fail. All results will come back in the response but only certain conversions will fail so it won't be exactly 1:1 there (when relating it to partial_failure_error.details) and the formatting of partial_failure_error.details just seems a little strange and we're just missing something to make parsing that data easier.

Is this something you're aware of and could share to help us in this manner?

Thanks!

**Comment by BenRKarl** [comment]
Hi @jbrow70 - you're on the right track in that you just need to parse the response and correlate the errors with their operations based on their position. If it helps, you can see our example on how to handle partial failure responses [here](https://github.com/googleads/google-ads-python/blob/main/examples/error_handling/handle_partial_failure.py).
