### ISSUE TITLE
set validate_only = True for pausing and enabling ad groups

### ISSUE THREAD

**Issue by cschweipert** [googleads/google-ads-python#656]
**What is your question?**

I need to set validate_only = True for pausing and enabling ads during development. How do I set this for the following mutate function? 

ad_group_service.mutate_ad_groups( 
            customer_id=customer_id, operations=[self.ad_group_operation]
        )

Thank you,
Christina

**Comment by BenRKarl** [comment]
Hi @cschweipert - [this documentation](https://developers.google.com/google-ads/api/docs/client-libs/python/optional-request-headers) explains how to do this.
