### ISSUE TITLE
experiment.type should be experiment.type_ in examples

### ISSUE THREAD

**Issue by anax32** [googleads/google-ads-python#658]
https://github.com/googleads/google-ads-python/blob/9541a751a2c8d8bd7abf97b0d3a9f61e0ebbcb57/examples/campaign_management/create_experiment.py#L50

The `create_experiment_resource` function as written in the example fails with the error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/proto/message.py", line 623, in __setattr__
    pb_type = self._meta.fields[key].pb_type
KeyError: 'type'
```
the python `help()` for this type gives the attribute name as `type_` with a (trailing underscore).
```
 |      type_ (google.ads.googleads.v10.enums.types.ExperimentTypeEnum.ExperimentType):
 |          The product/feature that uses this
 |          experiment.
```

If I am using the type incorrectly please let me know.

**Comment by BenRKarl** [comment]
@anax32 you're correct, thanks for flagging this. It was fixed in [this PR](https://github.com/googleads/google-ads-python/commit/5b7336b4225dd8c15d99f34006e90132797426e3#diff-824cb8f3ac1fb98121821fb5c02bef25e58bb527af652b4636e2a6c5a531b1b0)
