### ISSUE TITLE
why google-ads requires proto-plus == 1.19.6

### ISSUE THREAD

**Issue by dubirajara** [googleads/google-ads-python#659]
Hi, 
I have a question, I would like to use the latest version of google-ads and also the latest version of google-cloud-firestore, but I am having internal dependency problem with proto-plus, google-ads requires proto-plus == 1.19.6 and google-cloud-firestore requires proto-plus >= 1.20.5.

<img width="1426" alt="Captura de pantalla 2022-07-01 a las 9 25 01" src="https://user-images.githubusercontent.com/15200556/176854340-60fbc205-25f5-494c-9024-61f6d7fb22bf.png">

it is important that google-ads specifically uses version == 1.19.6, couldn't it be >= 1.19.6?

thanks

**Comment by bobhancockg** [comment]
The higher version introduced a performance regression. It was slight but
noticeable.
Bob Hancock | Google Ads API DevRel | ***@***.*** | 646-727-0741
