### ISSUE TITLE
SearchStream - ServiceUnavailable: 503 failed to connect to all addresses

### ISSUE THREAD

**Issue by BBalazsJurgen** [googleads/google-ads-python#660]
Dear Support,

We have been directed to you by the central Google Ads API group.

**Describe the bug:**
The precedent thread is available here: https://groups.google.com/g/adwords-api/c/Q-DvgmZI4K0
In short, the Google Ads API currently does not support returning aggregate data on the client level, segmented by campaign type (advertising_channel_type). The only option is to query at the campaign level and ask for SUMMARY_ROW_ONLY.
This way however, we need several SearchStream requests, one for each campaign type, and with different time periods needed, we quickly end up with (currently) 21 SearchStream requests per client account. With multiple clients, you can see this racking up into the thousands of requests very quickly.

With advice from the Google Ads API team, we went with the many-many requests, as we had no other option. However, doing everything in a linear fashion, waiting for one request to finish and starting the other would obviously take massive hours to finish. Therefore, we decided to opt for using Threading and make simultaneous calls. This works amazingly well for manageable call counts, but in this case, sometimes we get errors.
I know, making thousands of simultaneous requests is a bad idea; but we are open to alternatives, yet we had been advised that the mass requests way is the right way.

Do note that this error does not occur reliably, all the time. Sometimes, we have no issue making thousands of requests and everyhting works like a charm. However, sometimes we get the following error.

**Steps to Reproduce:**
Use Threading to send thousands of simultaneous SearchStream requests.

**Expected behavior:**
Thousands of simultaneous SearchStream answers.

**Client library version and API version:**
Client library version: 17.0.0
Google Ads API version: v11

- argcomplete==1.12.3
- bcrypt==3.2.2
- cachetools==5.0.0
- certifi==2021.10.8        
- cffi==1.15.0
- charset-normalizer==2.0.10
- colorama==0.4.4
- colorlog==6.6.0
- cryptography==36.0.1      
- cycler==0.11.0
- distlib==0.3.4
- et-xmlfile==1.1.0
- filelock==3.4.2
- flatdict==4.0.1
- fonttools==4.29.0
- google-ads==17.0.0
- google-api-core==2.8.2
- google-api-python-client==2.36.0
- google-auth==2.4.1
- google-auth-httplib2==0.1.0
- google-auth-oauthlib==0.4.6
- googleapis-common-protos==1.56.3
- greenlet==1.1.2
- grpcio==1.46.0
- grpcio-status==1.46.0
- gspread==5.1.1
- gspread-dataframe==3.2.2
- gspread-formatting==1.0.5
- httplib2==0.20.2
- icalendar==4.0.9
- idna==3.3
- jsonpickle==2.1.0
- kiwisolver==1.3.2
- lxml==4.7.1
- matplotlib==3.5.1
- mysql-connector-python==8.0.28
- mysqlclient==2.1.0
- nox==2022.1.7
- numpy==1.22.1
- oauth2client==4.1.3
- oauthlib==3.1.1
- openpyxl==3.0.9
- packaging==21.3
- pandas==1.4.0
- paramiko==2.11.0
- Pillow==9.0.0
- platformdirs==2.4.1
- proto-plus==1.19.6
- protobuf==3.17.3
- py==1.11.0
- pyasn1==0.4.8
- pyasn1-modules==0.2.8
- pycparser==2.21
- PyNaCl==1.5.0
- pyparsing==3.0.7
- pysftp==0.2.9
- python-dateutil==2.8.2
- pytz==2021.3
- PyYAML==5.4.1
- requests==2.27.1
- requests-oauthlib==1.3.0
- rsa==4.8
- scipy==1.7.3
- seaborn==0.11.2
- six==1.16.0
- SQLAlchemy==1.4.31
- uritemplate==4.1.1
- urllib3==1.26.8
- virtualenv==20.13.0
- XlsxWriter==3.0.2

**Request/Response Logs:**
NOTE that the full request/response logs would be WAY TOO LONG.
However, the notable part seems to be the following:
`report = pd.DataFrame(gafunctions.ads_get_report(cid, query, 1, summary_row_setting))
  File "\***\venv\lib\site-packages\pt_tools\gafunctions.py", line 41, in ads_get_report
  File "\***\venv\lib\site-packages\google\api_core\grpc_helpers.py", line 144, in error_remapped_callable
    response = ga_service.search_stream(request=request)        raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ServiceUnavailable: 503 failed to connect to all addresses
response = ga_service.search_stream(request=request)
    for data in response:
  File "\***\venv\lib\site-packages\pt_tools\gafunctions.py", line 100, in _getdata
    response = ga_service.search_stream(customer_id=customer_id, query=query)
  File "\***\venv\lib\site-packages\google\ads\googleads\v11\services\services\google_ads_service\client.py", line 3426, in search_stream
  File "\***\venv\lib\site-packages\google\ads\googleads\v11\services\services\google_ads_service\client.py", line 3426, in search_stream

  File "\***\venv\lib\site-packages\google\ads\googleads\v11\services\services\google_ads_service\client.py", line 3426, in search_stream
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ServiceUnavailable: 503 failed to connect to all addresses
    response = rpc(
  File "\***\venv\lib\site-packages\google\api_core\gapic_v1\method.py", line 154, in __call__
    return wrapped_func(*args, **kwargs)
  File "\***\venv\lib\site-packages\google\api_core\grpc_helpers.py", line 144, in error_remapped_callable
    response = rpc(
  File "\***\venv\lib\site-packages\google\api_core\gapic_v1\method.py", line 154, in __call__
    return wrapped_func(*args, **kwargs)
  File "\***\venv\lib\site-packages\google\api_core\grpc_helpers.py", line 144, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ServiceUnavailable: 503 failed to connect to all addresses
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ServiceUnavailable: 503 failed to connect to all addresses
    response = rpc(
  File "\***\venv\lib\site-packages\google\api_core\gapic_v1\method.py", line 154, in __call__
    return wrapped_func(*args, **kwargs)
  File "\***\venv\lib\site-packages\google\api_core\grpc_helpers.py", line 144, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ServiceUnavailable: 503 failed to connect to all addresses`

Please be so kind as to assist us in this matter.

**Comment by BenRKarl** [comment]
Hi @BBalazsJurgen thanks for sharing all of this information, and sorry that you're running into this problem. As you mentioned we typically don't recommend making requests with the python library using threading and/or multiprocessing because of how the streaming functionality works at low levels. My recommendation in this case would be to implement some retry logic anytime you encounter one of the above errors.

**Comment by zachliu** [comment]
@BenRKarl in our case (we are using python's multiprocessing pool with ~300 workers), the api stops responding and the program hangs forever after a few retries :crying_cat_face: 
could you elaborate on `how the streaming functionality works at low levels`?
multiprocessing is pretty much the only arrow in our quiver to battle against querying a large # of clients
we'd like to understand the reason behind it
