### ISSUE TITLE
Support for proto-plus>=1.19.7

### ISSUE THREAD

**Issue by kosteev** [googleads/google-ads-python#662]
**Describe the problem you are trying to solve:**
Use google-ads in conjunction with other python libraries.

**Describe the solution you'd like:**
Being able to install google-ads latest version together with proto-plus >= 1.19.7 (as it is constraint for some other libraries, e.g. autogenerated google-cloud-datacatalog-lineage which has constraint proto-plus >= 1.19.7)

**Additional context:**
In Cloud Composer we would like to install latest versions of other google libraries like google-cloud-firestore (https://github.com/googleads/google-ads-python/issues/659), google-cloud-datacatalog-lineage, etc., but this is not feasible as google-ads has dependency on old version of proto-plus, and ignoring pip conflicts is not feasible alternative.

It looks like the general concern about adding support for newer versions of proto-plus is that it has performance regression. Is it possible to do performance testing on the fresh versions of this package (https://pypi.org/project/proto-plus/#history) and decide if we can bump constraint to any other >=1.19.7 that doesn't have performance regression?
https://github.com/googleads/google-ads-python/blob/9541a751a2c8d8bd7abf97b0d3a9f61e0ebbcb57/setup.py#L28

This is a severe issue right now for Cloud Composer to have google-ads incompatible with other python google libraries of latest versions.

**Comment by kosteev** [comment]
@bobhancock @BenRKarl I would like to point your attention to this issue as it is severe enough for Cloud Composer team right now.

**Comment by BenRKarl** [comment]
@kosteev thanks for pinging on this issue. We did a round of performance testing in around March that indicated that proto-plus versions newer than `1.19.6` were too slow for this library. We're going to go back and dig into those results, and run some more tests with the most recent versions to see what the trade-offs would be today. In the meantime, is it possible to use older versions of `google-cloud-firestore` and `google-cloud-datacatalog-lineage` that are compatible with `proto-plus 1.19.6`?

**Comment by BenRKarl** [comment]
Thanks @anneadb - we're working on a fix for this that I expect will be part of the next release.

**Comment by moveingsun** [comment]
hi @BenRKarl, is there an estimate time on the next release date? this is also a blocking for us

**Comment by BenRKarl** [comment]
Hi all - we just released version [18.1.0](https://github.com/googleads/google-ads-python/releases/tag/18.1.0), which bumps our dependency on proto-plus to version 1.22.0.

**Comment by kosteev** [comment]
Thank you very much!

**Comment by moveingsun** [comment]
thanks a lot!
