### ISSUE TITLE
some of the requests seem to hang and respond slowly

### ISSUE THREAD

**Issue by CHEN-Jing194** [googleads/google-ads-python#664]
When looping through a large list of customers and making search_stream requests, some of the requests seem to hang and respond slowly (both multithreading and singlethreading ). My situation is similar to this [problem](https://github.com/googleads/google-ads-python/issues/650#issue-1272457761), but it still happens when I don't reuse the GoogleAdsService.
And strangely enough, this often happens within a few hours after 6am utc time on weekdays.The rest of the time it seems to be working fine again.
We have been directed to you by the central Google Ads API group.
The Google Ads API group says their service is working fine and that this is only happening to me. But my server network is fine too. Can you give me some advice on how to troubleshoot the problem?

**Comment by BenRKarl** [comment]
@CHEN-Jing194 can you give an example of a query that causes this behavior? I would hate to reroute you again, but this doesn't sound like a problem with this library. Regardless I'll see if I can help out before pointing you in a new direction.

**Comment by CHEN-Jing194** [comment]
@BenRKarl Hi, I solved this problem by setting the timeout parameter and catching its error to retry the request.Thanks.

**Comment by BenRKarl** [comment]
@CHEN-Jing194 that's great, thanks for letting me know!
