### ISSUE TITLE
Specified Google Ads API version "v11" does not exist. Valid API versions are: "v11", "v10", "v9"

### ISSUE THREAD

**Issue by bold-sanyamkapoor** [googleads/google-ads-python#665]
**What is your question?**
Hi,
I'm getting the following error while accessing the library : 

Specified Google Ads API version "v11" does not exist. Valid API versions are: "v11", "v10", "v9"

The code I'm trying is:
ga_service = client.get_service("GoogleAdsService")
search_request = client.get_type("SearchGoogleAdsRequest")

Please help out . Thanks !!

**Comment by BBalazsJurgen** [comment]
Hello,
I'm not affiliated with this project in any way, just somebody using the library like you do.
I've come across this message if you are trying to set the "v11" Google Ads API version, but did not upgrade the python client library to the latest version. Try to upgrade the python client library itself, the current latest version is 17.0.0.

**Comment by bold-sanyamkapoor** [comment]
@BBalazsJurgen I already have upgraded to 17.0.0 and I'm seeing valid API versions are "v11","v10","v9" but in the same error message it says that v11 does not exist. If you see the error message it is contradicting itself. I can't understand where the issue is. For better context I'm upgrading from v8 to v11. I was earlier using v8 in my codes.

**Comment by dattamegha** [comment]
Hi , I have a similar issue.
I have a python code which was running fine but now its showing error -
ValueError: Specified Google Ads API version "v11" does not exist. Valid API versions are: "v8", "v7"

Can someone please help on this? I have already downloaded the latest client library for v11 but what exactly to do post downloading it?

**Comment by dattamegha** [comment]
Also , how do I check the python client library that I am using ? and how do I upgrade it , if needed?

**Comment by BenRKarl** [comment]
@dattamegha You can check which version of this client library you have installed by running the following command from your terminal:

`python -m pip freeze`

Also [this page](https://developers.google.com/google-ads/api/docs/client-libs#supported_api_versions) has a chart that shows which version of this library correspond with the currently available API versions.

**Comment by dattamegha** [comment]
Thanks !
I have downloaded the latest client library for v11 but what exactly to do post downloading it? How do I integrate it with my python code?
