### ISSUE TITLE
ValueError: Specified service CampaignService" does not exist in Google Ads API v11

### ISSUE THREAD

**Issue by ellis-jc** [googleads/google-ads-python#669]
**Describe the bug:**
I'm attempting to use some of the code in the add_campaign_bid_modifier.py example, however I'm getting an error message:
ValueError: Specified service CampaignService" does not exist in Google Ads API v11.

I've tried changing the version when creating a client, and have tried everything from v8 to v11 and still get a similar error. 

https://github.com/googleads/google-ads-python/blob/main/examples/campaign_management/add_campaign_bid_modifier.py

**Steps to Reproduce:**
googleads_client = GoogleAdsClient.load_from_storage(version="v10")
campaign_service = client.get_service("CampaignService")

**Expected behavior:**
campaign service being returned

**Client library version and API version:**
Client library version: 17.0.0
Google Ads API version: v11, v10, v9 and v8

**Comment by BenRKarl** [comment]
@ellis-jc can you post the full error log? In some cases an unrelated error can cause this message to appear.

**Comment by BenRKarl** [comment]
@ellis-jc I'm going to close this issue as stale for now, but please reopen if you have more questions or details based on my last comment.
