### ISSUE TITLE
Proxy problems. Missing https protocol

### ISSUE THREAD

**Issue by ilia-meysak** [googleads/google-ads-python#671]
For a very long time I could not understand why the library does not work on my office computer. I knew that we are using a proxy server. And I entered its parameters into the google-ads.yaml settings file, but still nothing helped.

I began to understand the code and realized that the https protocol was missing. And I know how to fix this problem, but I can not push to this repository, I do not have access.

But I found errors in the code that I suggest you fix.

In the client.py file, on line 332, you need to remove the comma at the very end of the line. This error, but not in it there was a reason.

In the oauth2.py file, I suggest rewriting the initialize_credentials_wrapper function to include https:

    @functools.wraps(func)
    def initialize_credentials_wrapper(*args, **kwargs):
        credentials = func(*args, **kwargs)
        # If the configs contain an http_proxy, refresh credentials through the
        # proxy URI
        proxy = kwargs.get("http_proxy")
        if proxy:
            session = Session()
            session.proxies.update({"http": proxy, "https": proxy})
            credentials.refresh(Request(session=session))
        else:
            credentials.refresh(Request())
        return credentials

If this is done, then the proxy starts working correctly.

**Comment by BenRKarl** [comment]
@ilia-meysak thank you for noticing this! I'll try to get this fixed, but in the meantime you should be able to fork this repo and submit a pull request from your fork if you're interested in making the change directly.

**Comment by BenRKarl** [comment]
This will be published in the next version of the library.
