### ISSUE TITLE
[KEYWORDS] Exposing request types

### ISSUE THREAD

**Issue by louis030195** [googleads/google-ads-python#673]
**Describe the problem you are trying to solve:**

I want to have autocompletion through types on Keywords API requests.

**Describe the solution you'd like:**

Expose request types in https://github.com/googleads/google-ads-python/blob/9541a751a2c8d8bd7abf97b0d3a9f61e0ebbcb57/google/ads/googleads/__init__.py

Types:
https://github.com/googleads/google-ads-python/blob/9541a751a2c8d8bd7abf97b0d3a9f61e0ebbcb57/google/ads/googleads/v11/services/types/keyword_plan_idea_service.py

**Describe alternatives you've considered:**

N/A

**Comment by BenRKarl** [comment]
@louis030195 are you not able to retrieve these types using the `client.get_type` method? For example see [this line](https://github.com/googleads/google-ads-python/blob/main/examples/planning/generate_keyword_ideas.py#L61)

**Comment by BenRKarl** [comment]
@louis030195 I'm going to close this issue as stale for now, but please reopen if you have more questions or details based on my last comment.
