### ISSUE TITLE
How to delete the keyword planner

### ISSUE THREAD

**Issue by paulchiu188** [googleads/google-ads-python#674]
How to delete the keyword planner by using the google-ads-python code. i have already read the code samples which contain Remove Ad, Remove Ad Group from https://developers.google.com/google-ads/api/docs/samples/remove-ad-group, but i still cannot solve this issue.

![Issues · googleads_google-ads-python · GitHub - Google Chrome 26_7_2022 10_28_44](https://user-images.githubusercontent.com/110004190/180910147-61024492-ce6a-4b2b-94a2-5f6171a936ab.png)

**Comment by BenRKarl** [comment]
@paulchiu188 you would need to use the [`KeywordPlanService.MutateKeywordPlans`](https://developers.devsite.corp.google.com/google-ads/api/reference/rpc/v11/KeywordPlanService#mutatekeywordplans) method to send a remove operation using the resource name of the keyword plan you want to remove.
