### ISSUE TITLE
503 Getting metadata from plugin failed with error: 'GoogleRefreshTokenClient' object has no attribute 'before_request' when trying to Upload clicks

### ISSUE THREAD

**Issue by jakehaslamhc** [googleads/google-ads-python#678]
logging.basicConfig(level=logging.INFO, format='[%(asctime)s - %(levelname)s] %(message).5000s')
    logging.getLogger('google.ads.googleads.client').setLevel(logging.DEBUG)

    login_user = LoginUser.objects.get(user=user)
    company = Company.objects.get(id=deal.company_id)

    client_id, client_secret, developer_token = settings.CLIENT_ID, settings.CLIENT_SECRET, settings.DEVELOPER_TOKEN

    credentials = oauth2.GoogleRefreshTokenClient(
        client_id,
        client_secret,
        login_user.refresh_token
    )

    client = GoogleAdsClient(credentials, settings.DEVELOPER_TOKEN)

    click_conversion = client.get_type("ClickConversion")
    conversion_action_service = client.get_service("ConversionActionService")
    click_conversion.conversion_action = (
        conversion_action_service.conversion_action_path(
            client_id, company.conversion_name
        )
    )

    click_conversion.gclid = deal.gclid
    click_conversion.conversion_value = float(deal.deal_value if deal.deal_value else 0)
    click_conversion.conversion_date_time = make_aware(datetime.now()).strftime('%Y%m%d %H%M%S %z')

    conversion_upload_service = client.get_service("ConversionUploadService")
    request = client.get_type("UploadClickConversionsRequest")
    request.customer_id = client_id
    request.conversions.append(click_conversion)
    request.partial_failure = True
    conversion_upload_response = (
        conversion_upload_service.upload_click_conversions(
            request=request,
        )
    )
    uploaded_click_conversion = conversion_upload_response.results[0]
    print(
        f"Uploaded conversion that occurred at "
        f'"{uploaded_click_conversion.conversion_date_time}" from '
        f'Google Click ID "{uploaded_click_conversion.gclid}" '
        f'to "{uploaded_click_conversion.conversion_action}"'
    )

Does anyone know why I'm getting the above error when trying to Upload Clicks to google ads? also where do I retrieve the logs from?

**Comment by BenRKarl** [comment]
@jakehaslamhc [Here](https://developers.google.com/google-ads/api/docs/client-libs/python/logging) are instructions on how to enable logging. For your case I recommend setting it to `DEBUG` to get more detailed logs.

This _looks_ like an issue with you you're setting up your OAuth2 client. If possible I would recommend following one of [these flows](https://developers.google.com/google-ads/api/docs/client-libs/python/configuration) for configuring this library, as they're less likely to give errors. 

If necessary, could you share the full error logs here?

**Comment by jakehaslamhc** [comment]
@BenRKarl 
please see below the logs, thanks so much for your response:
AttributeError: 'GoogleRefreshTokenClient' object has no attribute 'before_request'
[2022-07-29 15:10:26,727 - INFO] Request
-------
Method: /google.ads.googleads.v11.services.ConversionUploadService/UploadClickConversions
Host: googleads.googleapis.com
Headers: {
  "developer-token": "REDACTED",
  "x-goog-api-client": "gl-python/3.8.13 grpc/1.47.0 gax/2.8.2 gccl/18.0.0 pb/3.12.2+c",
  "x-goog-request-params": "customer_id=9279051994"
}
Request: customer_id: "9279051994"
conversions {
  gclid: "EAIaIQobChMIl5ujg6-B6AIVQUPTCh0p8wmQEAAYASAAEgISNfD_BwE"
  conversion_action: "customers/1082261813693-64k52usvc9lajpb3j03c9rc2o2mqmnn7.apps.googleusercontent.com/conversionActions/0"
  conversion_date_time: "20220729 151026 +0100"
  conversion_value: 1.0
}
partial_failure: true


Response
-------
Headers: {}
Fault: {
  "created": "@1659103826.727529567",
  "description": "Error received from peer googleads.googleapis.com",
  "file": "src/core/lib/surface/call.cc",
  "file_line": 966,
  "grpc_message": "Getting metadata from plugin failed with error: 'GoogleRefreshTokenClient' object has no attribute 'before_request'",
  "grpc_status": 14
}

[2022-07-29 15:10:26,727 - WARNING] Request made: ClientCustomerId: 9279051994, Host: googleads.googleapis.com, Method: /google.ads.googleads.v11.services.ConversionUploadService/UploadClickConversions, RequestId: None, IsFault: True, FaultMessage: Getting metadata from plugin failed with error: 'GoogleRefreshTokenClient' object has no attribute 'before_request'

**Comment by jakehaslamhc** [comment]
was using the googleads.oauth2.GoogleRefreshTokenClient which is depreciated, used google.oauth2.credentials.Credentials instead and now working.
