### ISSUE TITLE
Possible To Mutate/Replace Single RSA AdTextAsset By Headline or Description Index Number?

### ISSUE THREAD

**Issue by davedavis** [googleads/google-ads-python#679]
What I'm trying to do: 
I'm trying to update/modify a single RSA headline or description, essentially by its index. 
Given an AdTextAsset or any arbitrary string and an index number, I want to update the AdTextAsset at that index. 

So let's say I want to update just headline 7 in an RSA which I have the ID for. 

I'm wondering if there's a creative way to do this without grabbing the existing ad by its ID, then parsing out all the AdTextAssets, changing the one I want, then submitting them all again with my single change. 

I'm currently manually parsing the "live" list of AdTetAssets, making my change and setting the new list of AdTextAssets.

`
ad.responsive_search_ad.headlines.extend(new_astextasset_list)`

Seems the field mask only works on the resource itself (the Ad) and not the assets in that ad. Is there a better way to do this? Or does the entire set of AdTextAssets have to be updated when any change is made to any of them?

Thanks so much.

**Comment by BenRKarl** [comment]
Hey @davedavis - to my knowledge the only way to do this is how you've described. In fact this is the workflow for updating _any_ repeated field on a resource, so unfortunately I don't think there is a more efficient path here.

**Comment by davedavis** [comment]
Thanks so much @BenRKarl
Really appreciate the input. Glad I'm on the right track and it makes sense in the context of what RSAs are. As ETA headlines and descriptions were all individually mutable by their "index" (at least in their name), I thought I may have just missed something.

Hard work is done now anyway. Thanks again!
