### ISSUE TITLE
Error in examples

### ISSUE THREAD

**Issue by timuram** [googleads/google-ads-python#682]
**Describe the bug:**
Documentation error

```
    for message in response.results:
        if not message:
            continue
```

For `ClickConversionResult`, at least, `bool(message) is True` even in case

```
{'result-conversion_action': '', 'result-conversion_date_time': '', 'result-gbraid': '', 'result-gclid': '', 'result-user_identifiers': [], 'result-wbraid': ''}
```

**Steps to Reproduce:**
Upload erroneous conversion
My code
```
        for i, result in enumerate(results):
            logger.info(
                "Processing result %s: %s, %s",
                i,
                bool(result),
                {"result-%s" % k: getattr(result, k, "absent") for k in dir(result)},
            )
``` 
results in this log record
```
Processing result 0: True, {'result-ByteSize'...'result-_extensions_by_number': {}, 'result-conversion_action': '', 'result-conversion_date_time': '', 'result-gbraid': '', 'result-gclid': '', 'result-user_identifiers': [], 'result-wbraid': ''}
```

**Expected behavior:**
`bool(message) is False`

**Client library version and API version:**
Client library version:
```
google-ads==18.0.0
```
Google Ads API version:
```
google-ads==18.0.0
google-api-core==2.8.2
google-api-python-client==2.55.0
google-auth==2.9.1
google-auth-httplib2==0.1.0
google-auth-oauthlib==0.5.2
google-cloud-bigquery==3.3.0
google-cloud-bigquery-storage==2.14.1
google-cloud-core==2.3.2
google-crc32c==1.3.0
google-resumable-media==2.3.3
googleapis-common-protos==1.56.4
grpcio==1.47.0
grpcio-status==1.47.0
```

**Request/Response Logs:**
"Request made: ClientCustomerId: XXX, Host: googleads.googleapis.com, Method: /google.ads.googleads.v11.services.ConversionUploadService/UploadClickConversions, RequestId: OJ69NYyh3cGRGqJr-0WlEA, IsFault: False, FaultMessage: None"

 
**Anything else we should know about your project / environment:**

**Comment by BenRKarl** [comment]
@timuram - by chance do you have the [`use_proto_plus`](https://github.com/googleads/google-ads-python/blob/main/google-ads.yaml#L18) option set to `False` when hitting this problem?

When I test locally with proto plus I see:

```
>>> bool(client.get_type("ClickConversionResult"))
False
```

And with proto plus disabled:

```
>>> bool(client.get_type("MutateAdGroupResult"))
True
```

And this is expected behavior. In proto-plus empty objects are designed to be falsy if none if their fields have been set. If you want to keep `use_proto_plus` set to `False` you just need to check for field presence in a slightly different way:

```py
if message.ByteSize() == 0:
    continue
```

**Comment by timuram** [comment]
May this magic be documented, please?

**Comment by BenRKarl** [comment]
@timuram There's a [section in our README](https://github.com/googleads/google-ads-python#protobuf-messages) that highlights `use_proto_plus` and points to [this page](https://developers.google.com/google-ads/api/docs/client-libs/python/protobuf-messages) in our Dev Site, which includes a small section describing [truthiness of empty messages](https://developers.google.com/google-ads/api/docs/client-libs/python/protobuf-messages#empty_message_fields). 

Happy to make updates to it if you think it could be clearer or easier to find!

**Comment by timuram** [comment]
I'm sure it will. Otherwise, I can do it myself if you don't mind against pull request
