### ISSUE TITLE
Error with client.get_type()

### ISSUE THREAD

**Issue by Achilles005** [googleads/google-ads-python#683]
ValueError: Specified type 'StringValue' does not exist in Google Ads API v10
AttributeError: unknown type 'StringValue'.

def _map_keywords_to_string_values(self, keywords):
        keyword_list = []
        for keyword in keywords:
            string_val = self.client.get_type("StringValue")
            string_val.value = keyword
            keyword_list.append(string_val)
        return keyword_list

**Comment by BenRKarl** [comment]
@Achilles005 is this part of one of our examples you're running? If you have [`use_proto_plus`](https://github.com/googleads/google-ads-python/blob/main/google-ads.yaml#L18) set to `True` then you should just be able to pass the literal string into the keyword list. To get the code working as-is, try setting `use_proto_plus` to False.
