### ISSUE TITLE
No module named 'google.ads'

### ISSUE THREAD

**Issue by KicksTerz** [googleads/google-ads-python#689]
Hello,
I've just started using the Google ads API.
After successfully updating my google-ads.yaml file with all the neccessary IDs and tokens, I am trying to make my first API call, running the get_campaigns.py file in order to get the campaign available in the ad account.
But I get the following error message:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/workspaces/GoogleAdsApi/test.ipynb Cell 10 in <cell line: 23>()
     [20] import argparse
     [21] import sys
---> [23] from google.ads.googleads.client import GoogleAdsClient
     [24] from google.ads.googleads.errors import GoogleAdsException
     [27] def main(client, customer_id):

ModuleNotFoundError: No module named 'google.ads'

Client library version: 14.0.0
Google Ads API version: 33.0.0

Describe the bug: ModuleNotFoundError: No module named 'google.ads'
Steps to Reproduce:
````
import argparse
import sys

from google.ads.googleads.client import GoogleAdsClient
from google.ads.googleads.errors import GoogleAdsException


def main(client, customer_id):
    ga_service = client.get_service("GoogleAdsService")

    query = """
        SELECT
          campaign.id,
          campaign.name
        FROM campaign
        ORDER BY campaign.id"""

    # Issues a search request using streaming.
    stream = ga_service.search_stream(customer_id=customer_id, query=query)

    for batch in stream:
        for row in batch.results:
            print(
                f"Campaign with ID {row.campaign.id} and name "
                f'"{row.campaign.name}" was found.'
            )


if __name__ == "__main__":
    # GoogleAdsClient will read the google-ads.yaml configuration file in the
    # home directory if none is specified.
    googleads_client = GoogleAdsClient.load_from_storage(version="v11")

    parser = argparse.ArgumentParser(
        description="Lists all campaigns for specified customer."
    )
    # The following argument(s) should be provided to run the example.
    parser.add_argument(
        "-c",
        "--XXXXXXXX",
        type=str,
        required=True,
        help="The Google Ads customer ID.",
    )
    args = parser.parse_args()

    try:
        main(googleads_client, args.customer_id)
    except GoogleAdsException as ex:
        print(
            f'Request with ID "{ex.request_id}" failed with status '
            f'"{ex.error.code().name}" and includes the following errors:'
        )
        for error in ex.failure.errors:
            print(f'\tError with message "{error.message}".')
            if error.location:
                for field_path_element in error.location.field_path_elements:
                    print(f"\t\tOn field: {field_path_element.field_name}")
        sys.exit(1)`
```


Expected behavior:
`Campaign with ID xxxxxxxxxxx and name "Campaign-Name-1" was found.`

**Comment by BloggingKIng** [comment]
Hi there!
Did you try:
`python -m pip install google-ads`
?

**Comment by KicksTerz** [comment]
Hi, I get a syntax error. FYI, everything is running in a docker container and the only module that fails to import is google-ads. Inside I also have numpy, pandas etc and they are bieng imported without any issue.
![image](https://user-images.githubusercontent.com/102041048/185875217-2d805e23-0073-4d02-a0d2-ef07e87046e4.png)
