### ISSUE TITLE
Please add caller phone number & etc to call_ads_view

### ISSUE THREAD

**Issue by albrtctm** [googleads/google-ads-python#696]
**Describe the problem you are trying to solve:**
Hello Team ~ Right now, there is no way for advertisers to pull caller info using call_ads_view API.

**Describe the solution you'd like:**
Add caller info metrics to call_ads_view

**Describe alternatives you've considered:**
We are downloading it manually, but we need to feed these data daily to data lake.

**Additional context:**
Saw this similar request last May.
<img width="1597" alt="Screen Shot 2022-08-30 at 5 55 57 PM" src="https://user-images.githubusercontent.com/98573314/187408007-12a3b43a-c8a5-4b5a-b1f6-2ce3dcd7833d.png">

Kudos! 😁

**Comment by BenRKarl** [comment]
Hi @albrtctm - would you please file a feature request at the [support forum](https://groups.google.com/forum/#!forum/adwords-api)? Since this request is related to the general API and not this library, it'll be best handled over there. Thanks!
