### ISSUE TITLE
How can a normal human use this library in a future proof way?

### ISSUE THREAD

**Issue by ddofborg** [googleads/google-ads-python#697]
I am sorry for this open rant, but it's been bugging me from the start of Google Ads Python Library.

I have been using Google Ad(word)s API for past 13+ years. This library is the worst of the worst I ever used. And not only in Google universe, but like ever.

This library breaks at every release.

Just a simple example of result processing. Here it requires `asset_group_listing_group_filter_result` attribute. In the version before was a `result` attribute.

    for i, result in enumerate(response.mutate_operation_responses):
        requested = mutate_operations[i]
        resource_name = (
            result.asset_group_listing_group_filter_result.resource_name
        )

Here you need to jump to raw protobuf messages to get the errors in the correct way. This makes the documentation useless.

    for result in response.mutate_operation_responses:
        for field_descriptor, value in result._pb.ListFields():
            if field_descriptor.name.endswith(suffix):
                name = field_descriptor.name[: -len(suffix)]
            else:
                name = field_descriptor.name
            print(
                f"Created a(n) {convert_snake_case_to_upper_case(name)} with "
                f"{str(value).strip()}."
            )

The same goes for most other basic things, like mutations. Before every service had own service:
    
    result = google_ads_client.get_service("CampaignCriterionService").mutate_campaign_criteria(customer_id=customer_id, operations=ops)

Now it's a generic service:

    result = google_ads_client.get_service("GoogleAdsService").mutate(customer_id=customer_id, mutate_operations=ops)

I do believe the old one works too, but for how long?

Can someone from the dev team show to me how this can be used in a future proof way? Can you just create some examples which will work from version to version without the need to change the code which is already written. Maybe just some of your own examples?

Just look at Google Ads Scripts for example. Simple API which stayed the same for years now. I mean new features are added, but old stuff still works and the structure of the scripts is exactly the same.

I have never experiences any library which makes it so complicated to use it, has inconsistent usage updates and required code updated for existing features at every update. I am not sure if I am the only one, but if there are others, please +1 this. I really hope Google Ads team will read this and reevaluate how this API is make.

**Comment by BenRKarl** [comment]
Hi @ddofborg - first, thanks for sharing this feedback, and sorry that you aren't having a good experience with the library and API. We're always open to input and are constantly trying to make improvements at all levels. If you have any specific suggestions feel free to file a feature request or pull request here, or, for general API issues, there's also our [support forum](https://developers.google.com/google-ads/api/support).

I have some thoughts about the above two examples you shared, perhaps they might be helpful for you:

1. For mutate requests, there are still individual resource-specific services that you can use. Perhaps you're thinking about `get` methods, which were removed in v10 in favor of using search queries? In any case, there are no plans to remove mutate methods, so you can safely rely on either approach. 
2. Your result processing examples appear to be doing two separate things - the first is retrieving the resource names for returned entities, the other appears to be iterating over the mutated fields of the returned entity then printing the field name and value for each. Do you think you could add a bit more detail about how you got from the first work flow to the second? And if it's helpful, feel free to describe what you're trying to accomplish with the result processing and I can help recommend a solution for you.
