### ISSUE TITLE
Broken dependency tree in release 17.0.0

### ISSUE THREAD

**Issue by lociii** [googleads/google-ads-python#698]
We're trying to [compile](https://github.com/jazzband/pip-tools#updating-requirements) requirements for `google-ads` `17.0.0` however the dependency tree is broken.

```
There are incompatible versions in the resolved dependencies:
  protobuf>=3.12.0 (from grpcio-status==1.48.1->google-ads==17.0.0->-r requirements.in (line 67))
  protobuf<5.0.0dev,>=3.15.0 (from googleapis-common-protos==1.56.4->google-ads==17.0.0->-r requirements.in (line 67))
  protobuf>=3.12.0 (from proto-plus==1.19.6->google-ads==17.0.0->-r requirements.in (line 67))
  protobuf<5.0.0dev,>=3.20.1 (from google-api-core==2.10.0->google-ads==17.0.0->-r requirements.in (line 67))
  protobuf!=3.18.*,!=3.19.*,<=3.20.0,>=3.12.0 (from google-ads==17.0.0->-r requirements.in (line 67))
```

`google-ads==17.0.0`  requires `"google-api-core >= 2.8.1, < 3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0",`

`google-api-core==2.10.0` is the latest release that satisfies this requirement. It itself requires `"protobuf >= 3.20.1, <5.0.0dev"`, see https://github.com/googleapis/python-api-core/blob/v2.10.0/setup.py  
but  
`google-ads==17.0.0` requires `protobuf >= 3.12.0, <= 3.20.0,!=3.18.*,!=3.19.*`, see https://github.com/googleads/google-ads-python/blob/17.0.0/setup.py

It's really frustrating when a once working release suddenly breaks.  
I am aware that this is not a question. It's more like a wish that this will not happen anymore.

**Comment by BenRKarl** [comment]
@lociii This should be resolved in the latest version of this library. And we're coordinating internally with the Could and Protobuf teams to try to resolve this version conflicts in the future.
