### ISSUE TITLE
ad_group_criterion_simulation: how to get simulated response with a specific max cpc bid price? 

### ISSUE THREAD

**Issue by hellogithub123454321** [googleads/google-ads-python#701]
**What is your question?**

Hello, thanks for developing this library. I was using this [query](https://github.com/googleads/google-ads-python/blob/main/examples/planning/get_ad_group_criterion_cpc_bid_simulations.py#L32) from the example script [get_ad_group_criterion_cpc_bid_simulations.py](https://github.com/googleads/google-ads-python/blob/main/examples/planning/get_ad_group_criterion_cpc_bid_simulations.py#L32), to retrieve simulated responses (clicks, cost, impressions, conversions) for a series of max CPC bid amounts from the field [ad_group_criterion_simulation.cpc_bid_point_list.points](https://developers.google.com/google-ads/api/fields/v11/ad_group_criterion_simulation#ad_group_criterion_simulation.cpc_bid_point_list.points). By default, looks like this API call would return 3 max cpc bid amount per eligible ad group criterion ID for paid search keyword ads? For example, I got the following response using your example script with ad group ID = "xyz". Note that the numbers printed below were not from real output; I modified it so the real output got kept confidential.

```
found ad group criterion CPC bid simulation for ad group ID xyz, criterion ID abcdef, start date 2022-09-05, end date 2022-09-11

	bid: 730000 => clicks: 83 cost: 6260000, impressions: 78,biddable conversions: 0.0,biddable conversions value: 0.0
	bid: 9380000 => clicks: 57 cost: 79020000, impressions: 35,biddable conversions: 0.0,biddable conversions value: 0.0
	bid: 2190000 => clicks: 22 cost: 23010000, impressions: 26,biddable conversions: 0.0,biddable conversions value: 0.0
```
In the pseudo example above, the [simulation.cpc_bid_point_list.points](https://github.com/googleads/google-ads-python/blob/main/examples/planning/get_ad_group_criterion_cpc_bid_simulations.py#L63) offers a fixed set of 3 max cpc bid amount for the input ad group and the criterion ID: 730000, 9380000, 2190000 (again, numbers are not real, just to demo my question). 

1) Is there a way to retrieve simulated clicks/impressions/cost/conversion responses, given any max cpc bid amount, that is outside of the API's default three values offered through [simulation.cpc_bid_point_list.points](https://github.com/googleads/google-ads-python/blob/main/examples/planning/get_ad_group_criterion_cpc_bid_simulations.py#L63)? For instance, could API tell me what would be the simulated impressions, costs, clicks, and conversions look like, if my max cpc bid price for the above ad group ID and criterion, was set to $0.01 aka bid = 10,000? This functionality seems available in Google Ads UI's simulator on keyword level for eligible criterion: _[You can change your bid by selecting a new bid option in the Bid Simulator](https://support.google.com/google-ads/answer/2470105?hl=en#zippy=%2Cuse-bid-simulators-on-the-search-and-display-networks)_. Hope it's available via Google Ads API as well.

2) If # 1 is impossible, could you share how did the three default bid amount get set in the [simulation.cpc_bid_point_list.points](https://github.com/googleads/google-ads-python/blob/main/examples/planning/get_ad_group_criterion_cpc_bid_simulations.py#L63)? Google Ads API doc on [Retrieve bid simulations](https://developers.google.com/google-ads/api/docs/bid-simulations/retrieve-bid-simulations) says: ["_The simulation data is a sequence of simulation points that provides a histogram of the predicted performance with different bids during the given time frame_."](https://developers.google.com/google-ads/api/docs/bid-simulations/retrieve-bid-simulations). Could you help clarify what histogram meant here? Do these three default bid amount values represent some quantile or mean / median of empirical distribution in some metrics? 

Thank you.

**Comment by BenRKarl** [comment]
Hi @hellogithub123454321 - thanks for the question, and apologies for our delayed response. I think this question would be better suited for our general [support forum](https://developers.google.com/google-ads/api/support), since it's related to the API behavior and not this specific library.
