### ISSUE TITLE
The error code is not in this version on latest

### ISSUE THREAD

**Issue by YechielFino** [googleads/google-ads-python#704]
**Describe the bug:**
I'm getting unknown error, even though i'm running on latest version (18.1.0)

**Steps to Reproduce:**
this happens when creating ad groups, not sure what is the error or what specific action is triggering it. (Have around 9425 ad group creations)

**Expected behavior:**
error would return, a number, anything

**Client library version and API version:**
Client library version: 
Google Ads API version:
atomicwrites==1.4.1
attrs==22.1.0
cachetools==5.2.0
certifi==2022.6.15
cffi==1.15.1
charset-normalizer==2.1.0
colorama==0.4.5
cryptography==38.0.1
et-xmlfile==1.1.0
falcon==3.1.0
falcon-multipart==0.2.0
google-ads==18.1.0
google-api-core==2.8.2
google-auth==2.9.1
google-auth-oauthlib==0.5.2
googleapis-common-protos==1.56.4
greenlet==1.1.3
grpcio==1.48.0
grpcio-status==1.48.0
idna==3.3
iniconfig==1.1.1
jsonschema==4.16.0
mongoengine==0.24.2
mongomock==4.1.2
numpy==1.23.1
oauthlib==3.2.0
openpyxl==3.0.10
orjson==3.7.10
packaging==21.3
pandas==1.4.3
pluggy==1.0.0
proto-plus==1.22.0
protobuf==4.21.6
py==1.11.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
PyJWT==1.5.3
pymongo==4.2.0
PyMySQL==1.0.2
pyparsing==3.0.9
pyperclip==1.8.2
pyrsistent==0.18.1
pytest==7.1.2
python-dateutil==2.8.2
python3-ldap==0.9.8.4
pytz==2022.1
PyYAML==6.0
requests==2.28.1
requests-oauthlib==1.3.1
rsa==4.9
sentinels==1.0.0
six==1.16.0
SQLAlchemy==1.4.41
tomli==2.0.1
uncurl==0.0.11
urllib3==1.26.11
waitress==2.1.2
XlsxWriter==3.0.3

**Request/Response Logs:**
esponse
-------
Headers: {
  "google.ads.googleads.v11.errors.googleadsfailure-bin": "\n,\n\u0002\b\u0001\u0012&The error code is not in this version.\u0012\u0016U8rCw9s4pwFqC-Tsdwwx4A",
  "grpc-status-details-bin": "\b\u0003\u0012%Request contains an invalid argument.\u001a\u0001\nDtype.googleapis.com/google.ads.googleads.v11.errors.GoogleAdsFailure\u0012F\n,\n\u0002\b\u0001\u0012&The error code is not in this version.\u0012\u0016U8rCw9s4pwFqC-Tsdwwx4A",
  "request-id": "U8rCw9s4pwFqC-Tsdwwx4A"
}
Fault: errors {
  error_code {
    request_error: UNKNOWN
  }
  message: "The error code is not in this version."
}
request_id: "U8rCw9s4pwFqC-Tsdwwx4A"
WARNING  google.ads.googleads.client:logging_interceptor.py:271 Request made: ClientCustomerId: , Host: googleads.googleapis.com, Method: /google.ads.googleads.v11.services.AdGroupCriterionService/MutateAdGroupCriteria, RequestId: U8rCw9s4pwFqC-Tsdwwx4A, IsFault: True, FaultMessage: The error code is not in this version.

 
**Anything else we should know about your project / environment:**

**Comment by BenRKarl** [comment]
@YechielFino thanks for filing this issue. Looking at the request ID, I can see that the problem is that the request payload is too large. We have some [limitations](https://developers.google.com/google-ads/api/docs/best-practices/quotas#grpc_limitations) on the size of request/response payloads. They're not well defined right now, but perhaps if you split your request into multiple smaller requests it will fix the issue. Meanwhile I'll file a bug to return a more meaningful error.
