### ISSUE TITLE
Custom variable id usage triggers malformed request on UploadClickConversionsRequest

### ISSUE THREAD

**Issue by sandermanneke** [googleads/google-ads-python#710]
**Describe the bug:**

When following the example on https://developers.google.com/google-ads/api/docs/conversions/upload-clicks#code_example and provide the SDK is does not map correctly to the API expected input.

When including the  custom variables id in the uploaded conversion the API returns an error that the entry is malformed. The api seems the expect customers/{customer_id}/conversionCustomVariables/{ConversionCustomVariable.conversion_custom_variable_id}
 but is receiving only the ID.
 
 Either the documentation / example is ambiguous or the SDK client should handle the conversion to the resource correctly based on the provided variables in the click_conversion = client.get_type("ClickConversion")

**Steps to Reproduce:**

I am using the custom_variable that is returned by 
    query = """
    SELECT conversion_custom_variable.id, conversion_custom_variable.name FROM conversion_custom_variable
    """

Then enter it exactly as the provided example:

conversion_custom_variable_id = str(custom_variable_id)
        conversion_custom_variable_value = str(custom_variable_value)
        conversion_custom_variable = client.get_type("CustomVariable")
        conversion_custom_variable.conversion_custom_variable = (
            conversion_custom_variable_id
        )
        conversion_custom_variable.value = conversion_custom_variable_value
        click_conversion.custom_variables.append(conversion_custom_variable)

**Expected behavior:**

I would expect that the call would go through and the client takes care of forming the API call based on the conversion_custom_variable_id

**Client library version and API version:**
google-ads==18.0.*
google-api-core
google-api-python-client
google-auth
google-auth-httplib2
google-auth-oauthlib
google-cloud-appengine-logging
google-cloud-audit-log
google-cloud-bigquery
google-cloud-bigquery-storage
google-cloud-core
google-cloud-firestore
google-cloud-logging
google-cloud-secret-manager
google-cloud-storage
google-crc32c
google-pasta
google-resumable-media
googleapis-common-protos
protobuf==3.20.*

**Request/Response Logs:**
-------
Method: /google.ads.googleads.v11.services.ConversionUploadService/UploadClickConversions
Host: googleads.googleapis.com
Headers: {
  "developer-token": "REDACTED",
  "login-customer-id": "xxxxxxxxx",
  "x-goog-api-client": "gl-python/3.8.8 grpc/1.49.1 gax/2.8.2 gccl/18.0.0 pb/3.20.0+c",
  "x-goog-request-params": "xxxxxxxxx"
}
Request: customer_id: "xxxxxxxxx"
conversions {
  gclid: "xxxxxxxxx"
  conversion_action: "customers/6533180423/conversionActions/1010030853"
  conversion_date_time: "xxxxxxxxx"
  conversion_value: 50.0
  currency_code: "EUR"
  order_id: "9189400"
  custom_variables {
    conversion_custom_variable: "19384677"
    value: "0"
  }
  user_identifiers {
    user_identifier_source: FIRST_PARTY
    hashed_email: "xxxxxxxxx"
  }
}
partial_failure: true

Response
-------
Headers: {
  "alt-svc": "xxxxxxxxx",
  "content-disposition": "attachment",
  "date": "xxxxxxxxx",
  "request-id": "xxxxxxxxx"
}
Response: partial_failure_error {
  code: 3
  message: "Resource name \'19384677\' is malformed: expected \'customers/{customer_id}/conversionCustomVariables/{ConversionCustomVariable.conversion_custom_variable_id}\'., at conversions[0].custom_variables[0].conversion_custom_variable"
  details {
    type_url: "type.googleapis.com/google.ads.googleads.v11.errors.GoogleAdsFailure"
    value: "\n\367\001\n\002\010\004\022\235\001Resource name \'19384677\' is malformed: expected \'customers/{customer_id}/conversionCustomVariables/{ConversionCustomVariable.conversion_custom_variable_id}\'.\032\n*\01019384677\"E\022\017\n\013conversions\030\000\022\024\n\020custom_variables\030\000\022\034\n\032conversion_custom_variable"
  }
}
results {
}

**Comment by sandermanneke** [comment]
Can anyone help?

@bobhancock maybe ?

**Comment by BenRKarl** [comment]
@sandermanneke apologies for the delayed response! 

I seems like you've hit a bug in our example, which I will fix shortly.

In the meantime you will need to convert the conversion custom variable to a resource name using a helper method, like this:

```py
# Here we use the GoogleAdsService.conversion_custom_variable_path helper 
# method to build a resource name from your customer ID and variable ID
googleads_service = client.get_service("GoogleAdsService")
conversion_custom_variable_id = googleads_service.conversion_custom_variable_path(
    customer_id, str(custom_variable_id)
)
conversion_custom_variable_value = str(custom_variable_value)
conversion_custom_variable = client.get_type("CustomVariable")
conversion_custom_variable.conversion_custom_variable = (
    conversion_custom_variable_id
)
conversion_custom_variable.value = conversion_custom_variable_value
click_conversion.custom_variables.append(conversion_custom_variable)
```

Doing that should help you get past this issue. Let me know if you have any other questions!
