### ISSUE TITLE
Customer match lists - upload example does not work

### ISSUE THREAD

**Issue by cwdjankoski** [googleads/google-ads-python#711]
**UPDATE 22.11.2022**  
Please see [my last comment](https://github.com/googleads/google-ads-python/issues/711#issuecomment-1326127497) for recent developments.  

--------
First of all, thank you for developing these helper libraries that massively simplify data people's lives 🙇 

**Describe the bug:**
We have encountered a strange behaviour when trying to upload Customer Match Lists via the python library. I have attached a minimal reprex script at the end of this issue - in short this is what we see:
 - we extracted and pieced together the code from [the example scripts](https://github.com/googleads/google-ads-python/blob/main/examples/remarketing/add_customer_match_user_list.py) --> we took only the important (for us) bits out and made them into a script that is more suitable for our needs
 - when we run the script we see that
   -  we can successfully create a new customer match list and see this inside the Google Ads UI ( Tools and Settings --> Audience manager )
   - however we do not see any uploads appearing inside the customer match list i.e. the audience is empty, when you click on the previously-created audience and check the "Segment members" tab it display the message

> Customers based on email, phone, and/or mailing address uploads (0 uploads)
<img width="1439" alt="Screenshot 2022-10-17 at 13 38 54" src="https://user-images.githubusercontent.com/40760374/196168099-5da5f756-2c07-4a8e-b680-c0014b7b3466.png">

**Steps to Reproduce:**
 - copy our minimal reprex script
 - *don't forget* to adjust for your customer ids, credentials
 - rerun the script with some dummy emails (not necessary - you can also try with real existing emails, does not make a difference - we left some dummy ones in there just as an example)
 - inside your google ads ui you should see now that
   - a new customer match list segment has been created
   - however you will not see any uploads inside this segment, it will be empty and display the same message as quoted above

**Expected behavior:**  
To see the customer match list uploads inside there and their last date of upload.

**Client library version and API version:**
Client library version: `google-api-python-client==2.63.0`
Google Ads API version: `v11`

```
aiohttp==3.8.3
aiosignal==1.2.0
anyio==3.6.1
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.0.8
async-timeout==4.0.2
attrs==20.3.0
Babel==2.10.3
backcall==0.2.0
bcrypt==4.0.0
beautifulsoup4==4.11.1
bleach==5.0.1
boto3==1.24.84
botocore==1.27.84
cachetools==5.2.0
certifi==2022.9.14
cffi==1.15.1
cfgv==3.3.1
charset-normalizer==2.1.1
cloudpathlib==0.10.0
commonmark==0.9.1
contourpy==1.0.5
cryptography==38.0.1
curlify==2.2.1
cycler==0.11.0
db-dtypes==1.0.4
debugpy==1.6.3
decorator==5.1.1
defusedxml==0.7.1
distlib==0.3.6
entrypoints==0.4
executing==1.0.0
facebook-business==14.0.0
fastjsonschema==2.16.1
filelock==3.8.0
fonttools==4.37.4
frozenlist==1.3.1
fsspec==2022.8.2
fuzzywuzzy==0.18.0
gcsfs==2022.8.2
google-ads==18.1.0
google-api-core==2.10.1
google-api-python-client==2.63.0
google-auth==2.12.0
google-auth-httplib2==0.1.0
google-auth-oauthlib==0.5.3
google-cloud-bigquery==3.3.3
google-cloud-bigquery-storage==2.16.1
google-cloud-core==2.3.2
google-cloud-storage==2.5.0
google-crc32c==1.5.0
google-resumable-media==2.4.0
googleapis-common-protos==1.56.4
greenlet==1.1.3
grpcio==1.49.1
grpcio-status==1.49.1
httplib2==0.20.4
identify==2.5.6
idna==3.4
ipykernel==6.15.3
ipython==8.5.0
ipython-genutils==0.2.0
jarowinkler==1.2.3
jedi==0.18.1
Jinja2==3.1.2
jmespath==1.0.1
json5==0.9.10
jsonschema==4.16.0
jupyter-core==4.11.1
jupyter-resource-usage==0.6.3
jupyter-server==1.18.1
jupyter_client==7.3.5
jupyterlab==3.4.7
jupyterlab-pygments==0.2.2
jupyterlab_server==2.15.1
jupytext==1.11.0
kiwisolver==1.4.4
Levenshtein==0.20.5
lxml==4.9.1
markdown-it-py==0.6.2
MarkupSafe==2.1.1
matplotlib==3.6.0
matplotlib-inline==0.1.6
mdit-py-plugins==0.2.6
mdurl==0.1.2
mistune==2.0.4
mmh3==3.0.0
more-itertools==8.14.0
multidict==6.0.2
mysqlclient==2.1.1
nbclassic==0.4.3
nbclient==0.6.8
nbconvert==7.0.0
nbformat==5.5.0
nbresuse==0.3.6
nest-asyncio==1.5.5
nodeenv==1.7.0
notebook==6.4.12
notebook-shim==0.1.0
numpy==1.23.3
oauth2client==4.1.3
oauthlib==3.2.1
packaging==21.3
pandas==1.5.0
pandas-gbq==0.17.9
pandocfilters==1.5.0
paramiko==2.11.0
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.2.0
platformdirs==2.5.2
pre-commit==2.20.0
prometheus-client==0.14.1
prompt-toolkit==3.0.31
proto-plus==1.22.0
protobuf==4.21.7
psutil==5.9.2
psycopg2==2.9.3
ptyprocess==0.7.0
pure-eval==0.2.2
pyarrow==9.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycountry==22.3.5
pycparser==2.21
pydata-google-auth==1.4.0
Pygments==2.13.0
pygsheets==2.0.5
PyNaCl==1.5.0
pyOpenSSL==22.1.0
pyparsing==3.0.9
pyrsistent==0.18.1
pysftp==0.2.9
python-dateutil==2.8.2
python-Levenshtein==0.20.5
pytz==2022.2.1
PyYAML==6.0
pyzmq==24.0.0
rapidfuzz==2.10.3
requests==2.28.1
requests-oauthlib==1.3.1
rich==12.5.1
rsa==4.9
s3transfer==0.6.0
scipy==1.9.1
Send2Trash==1.8.0
six==1.16.0
slack-sdk==3.18.4
sniffio==1.3.0
soupsieve==2.3.2.post1
SQLAlchemy==1.4.41
stack-data==0.5.0
terminado==0.15.0
tinycss2==1.1.1
toml==0.10.2
tomli==2.0.1
tornado==6.2
tqdm==4.64.1
traitlets==5.4.0
Unidecode==1.3.6
uritemplate==4.1.1
urllib3==1.26.12
virtualenv==20.16.5
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.4.1
yarl==1.8.1
```
**Request/Response Logs:**
You can see at the end of the script we attached as reprex that the reponse we get is `None` and the parse-response helpers from Google examples say that everything has gone through OK - no partial errors nor anything else jumps out as strange when looking at all output.  
The only problem is that the uploads seem to go ok - however they never appear in the Google Ads UI - the customer match lists in there always show 0 uploads and the lowest numbers possible (< 100).

**Anything else we should know about your project / environment:**
N/A

### **Minimal reproducible example script**
```
import os
import hashlib

from google.ads.googleads.client import GoogleAdsClient
from google.ads.googleads.errors import GoogleAdsException

# PLEASE MODIFY TO YOUR OWN IDs AND CREDENTIALS -----------------------v
GOOGLE_ADS_CUSTOMER_ID = "0001000"

google_ads_client = GoogleAdsClient.load_from_dict(
    os.getenv("GOOGLE_APPLICATION_CREDENTIALS"),
    version = "v11"
)
google_ads_client.login_customer_id = GOOGLE_ADS_CUSTOMER_ID

# PLEASE MODIFY TO YOUR OWN IDs AND CREDENTIALS -----------------------^

google_ads_service = google_ads_client.get_service("GoogleAdsService")
user_list_service = google_ads_client.get_service("UserListService")
offline_user_data_job_service = google_ads_client.get_service("OfflineUserDataJobService")

# make some dummy hashed emails 
emails = [
    "test@google.com",
    "dummy@gmail.com"
    # INSERT YOUR OWN TESTING EMAILS HERE 
]
example_hashed_emails = [
    hashlib.sha256(s.strip().lower().encode()).hexdigest()
    for s in emails
]

# create the new audience
user_list_service_client = google_ads_client.get_service("UserListService")
user_list_operation = google_ads_client.get_type("UserListOperation")


user_list = user_list_operation.create
user_list.name = "test_audience_20221013_part_1"
user_list.description = "API uploaded audience"
user_list.crm_based_user_list.upload_key_type = (
    google_ads_client.enums.CustomerMatchUploadKeyTypeEnum.CONTACT_INFO
)
# i.e. unlimited span
user_list.membership_life_span = 10_000

response = user_list_service_client.mutate_user_lists(
    customer_id = GOOGLE_ADS_CUSTOMER_ID, 
    operations = [ user_list_operation ]
)
user_list_resource_name = response.results[0].resource_name
print(
    f"User list with resource name '{user_list_resource_name}' was created."
)

GOOGLE_AUDS_AUDIENCES_QUERY = f"""

    SELECT
      user_list.id,
      user_list.description,
      user_list.resource_name,
      user_list.match_rate_percentage,
      user_list.name,
      user_list.type,
      user_list.size_for_display,
      user_list.size_for_search,
      customer.id,
      customer.manager
      
    FROM user_list
    
    WHERE customer.id = {GOOGLE_ADS_CUSTOMER_ID}
      AND user_list.resource_name = '{user_list_resource_name}'

""".strip()

audience_results = (
    google_ads_service
        .search(
            customer_id = GOOGLE_ADS_CUSTOMER_ID,
            query = GOOGLE_AUDS_AUDIENCES_QUERY
        )
)

user_list_resource_name = audience_results.results[0]


offline_user_data_job = google_ads_client.get_type("OfflineUserDataJob")
offline_user_data_job.type_ = (
    google_ads_client
    .enums
    .OfflineUserDataJobTypeEnum
    .CUSTOMER_MATCH_USER_LIST
)    
offline_user_data_job.customer_match_user_list_metadata.user_list = (
    user_list_resource_name.user_list.resource_name
)

create_offline_user_data_job_response = (
    offline_user_data_job_service.create_offline_user_data_job(
        customer_id = GOOGLE_ADS_CUSTOMER_ID,
        job = offline_user_data_job
    )
)
offline_user_data_job_resource_name = (
    create_offline_user_data_job_response.resource_name
)
print(
    "Created an offline user data job with resource name: "
    f"'{offline_user_data_job_resource_name}'."
)
offline_user_data_job_resource_name


request = google_ads_client.get_type("AddOfflineUserDataJobOperationsRequest")
request.resource_name = offline_user_data_job_resource_name
request.enable_partial_failure = True


req_operations = [ ]

user_data_with_email_address_operation = google_ads_client.get_type("OfflineUserDataJobOperation")
user_data_with_email_address = user_data_with_email_address_operation.create
user_identifier_with_hashed_email = google_ads_client.get_type("UserIdentifier")

# user identifiers
for e in example_hashed_emails:
    user_identifier_with_hashed_email.hashed_email = e
    user_data_with_email_address.user_identifiers.append(user_identifier_with_hashed_email)
    
req_operations.append(user_data_with_email_address_operation)

# fill up the request with a list of batches of 20 user emails
request.operations.extend(req_operations)

response = offline_user_data_job_service.add_offline_user_data_job_operations(
    request = request
)
print(response)


# ? --------------- OUTPUT --------------------

# %%
request
#out> 
# resource_name: "customers/123456/offlineUserDataJobs/<1234567890>"
# enable_partial_failure: true
# operations {
#   create {
#     user_identifiers {
#       hashed_email: "a091f428326b011ecb6104f08193a1196756cc8d4c98318857a6233e5cb9630f"
#     }
#     user_identifiers {
#       hashed_email: "5f2ef1dab2a6d31ee4e1ba513bb092f43fef0dcba34d749861fd9ead1721bf34"
#     }
#   }
# }

# %%
type(response)
#out> AddOfflineUserDataJobOperationsResponse

# %%
partial_failure = getattr(response, "partial_failure_error", None)

if getattr(partial_failure, "code", None) != 0:
    error_details = getattr(partial_failure, "details", [])
    for error_detail in error_details:
        failure_message = google_ads_client.get_type("GoogleAdsFailure")
        # Retrieve the class definition of the GoogleAdsFailure instance
        # in order to use the "deserialize" class method to parse the
        # error_detail string into a protobuf message object.
        failure_object = type(failure_message).deserialize(
            error_detail.value
        )
        for error in failure_object.errors:
            print(
                "A partial failure at index "
                f"{error.location.field_path_elements[0].index} occurred.\n"
                f"Error message: {error.message}\n"
                f"Error code: {error.error_code}"
            )
print("The operations are added to the offline user data job.")

#out> The operations are added to the offline user data job.
```

**Comment by Tejanth2807** [comment]
Hi,
I have followed this code with slight modifications (https://github.com/googleads/google-ads-python/blob/00673624a3fda99c5a3fbb386aa9af8287ed07de/examples/remarketing/add_customer_match_user_list.py#L137)
I am able to see that status as 'success' in UI but as per norms of google ads we unable to see the details uploaded till we have a match rate for 1000 or more customers.
![image](https://user-images.githubusercontent.com/84571275/198835174-a7d63b06-83dc-43af-99bc-6f6a81820f91.png)

**Comment by cwdjankoski** [comment]
Hi @Tejanth2807 - thanks for your reply.  
I extracted the code also from the same script that you linked to (i just have removed the parts that wrap it into a cmd line script).  
In any case - as you can perhaps see from the code I linked at the bottom of my description - it's following this script you linked 100%.  It is for some reason:
 - able to send requests successfully (no partial failure, no error messages)
 - responses come back empty (this is expected since the documentation mentions that requests are made asynchronuosly so makes sense that we do not know yet if there is some trouble happening)
 - yet with all these good / optimistic "signs" - the audiences do not appear at all in the Google Ads UI

Did you perhaps have the chance to take a look at the script i have linked to at the bottom of my description - perhaps you could spot what could be going wrong ? I would greatly appreciate it.

**Comment by cwdjankoski** [comment]
Not sure who can i tag from the team / contributors in hope to get at least some direction around this issue ?

**Comment by cwdjankoski** [comment]
**UPDATE ~ 22.11.2022**

There was some recent developments that probably change the subject of this issue. When i first submitted my issue, I was not able at all to even *see* the audience uploads inside the Google Ads UI (see my snapshot in the above thread).  
However, recently somehow the uploads have automagically appeared inside the UI ?!? We have not changed anything on our side.

While visible - now the uploads show the `Status = Failed`. I would like to ask how and where would it be possible to see the reason why these uploads have failed ?

Please see the attached snapshot for clarification on which field I mean.
![Screenshot 2022-11-24 at 09 27 42](https://user-images.githubusercontent.com/40760374/203732925-1393e8f0-7dfe-4c98-a172-bf992e3aea97.png)


As far as I have tried to poke around:
  - i could not find a way to see more details about the Status field from inside the UI
  - i could also not find a way to retrieve the reason for the failure of this upload via the Google Ads API

As mentioned in my previous message - the uploads do go through, the requests are performed successfully, the responses that come back have empty `partial_failure_error` and `warning` fields.  
Running e.g. [this snippet](https://github.com/googleads/google-ads-python/blob/fd6b65e575a9e98cb5c3c15166249442e79f2e5d/examples/remarketing/add_customer_match_user_list.py#L145L166) from the example script from the official repo outputs:
```
Offline user data job ID '27104927380' with type 'CUSTOMER_MATCH_USER_LIST' has status: PENDING
```
🤔  What could be going on ? 
Could someone please advise me on how to poke into the response / audience upload and get to some kind of logs, errors ... anything that could give us a clue on what is the problem ?  
I would really greatly appreciate it 🙇

**Comment by BenRKarl** [comment]
Hi @cwdjankoski - apologies for the delayed response here. 

You should be able to generate a report that shows any errors associated with an offline user data job, see the [`failure_reason`](https://developers.google.com/google-ads/api/fields/v12/offline_user_data_job#offline_user_data_job.failure_reason) field in particular. 

Also if you haven't already, I recommend reviewing our guide on [Audience Management](https://developers.google.com/google-ads/api/docs/remarketing/overview). This is a complicated feature and having the broader context can be really helpful when developing applications for it.

Let me know if the above helps, or if you have any further questions.

**Comment by cwdjankoski** [comment]
@BenRKarl Hi Ben, thank you for your reply.  
I sat down and re-read the example script from the repo for uploading customer match lists and - expectedly 🙂 - i noticed that i have somehow omitted this [very important line](https://github.com/googleads/google-ads-python/blob/8f38122a995a8555f503ca07d06fc1edcbf419d7/examples/remarketing/add_customer_match_user_list.py#L170-L172) in our version of the script. 🤦   

Perhaps useful for someone in the future - the effect of this would be that you can see your `OfflineUserDataJobOperation`s going through, the `response` or `partial_failure` that come back from the API would be empty, however the jobs would be stuck in "limbo" with status `PENDING` and eventually being killed.

So the lesson was to carefully read the example script and make sure you do all the calls the example script does. 🙂 

If I could add some feedback from my side - the example scripts are a bit complex and omit some very common use-cases e.g. how to empty-and-repopulate an existing audience. It would be much easier - in my opionion only - if all these different use cases are illustrated in the examples. I would be happy to contribute this - of course if you think it would be helpful and of course help me with some details (where to contribute it) and review it if it is according to good standard.  

Thank you for the reply and guidance.

**Comment by BenRKarl** [comment]
@cwdjankoski thanks for the feedback! We're always trying to make the experience of using our libraries easier, and it's helpful to know that you feel this way.

We always accept Pull Requests for new examples ([here's one](https://github.com/googleads/google-ads-python/pull/715) that's under review right now), so feel free to open a PR for feedback. Or, if you prefer, you can ask for input beforehand and myself or others may share their thoughts. If you do decide to contribute, (which I encourage you to do), take a look at our [CONTRIBUTING.md](https://github.com/googleads/google-ads-python/blob/main/CONTRIBUTING.md) file, which has guidelines that will help the review process go smoother.

**Comment by cwdjankoski** [comment]
@BenRKarl  Hi Ben,
I saw the [recent changes](https://github.com/googleads/google-ads-python/commit/15d3efa342ed035e9995b7d355addb0430ca83cc) you have done to improve the example script for customer match upload. The [latest version](https://github.com/googleads/google-ads-python/blob/main/examples/remarketing/add_customer_match_user_list.py) in main branch is excellent - thank you for making it super clear and adding lots of comments as to where and how would one do necessary adjustments - like for example [here](https://github.com/googleads/google-ads-python/blob/main/examples/remarketing/add_customer_match_user_list.py#L173-L179), it was super easy for me to understand and adjust the script now. 

Thank you for the work and effort - much appreciated 🙇
