### ISSUE TITLE
KeywordPlanCompetitionLevel object is not present in KeywordPlanHistoricalMetrics as part of GenerateKeywordIdeaResult

### ISSUE THREAD

**Issue by mcmasty** [googleads/google-ads-python#719]
**Describe the bug:** 

I am trying to use https://github.com/googleads/google-ads-python/blob/main/examples/planning/generate_keyword_ideas.py

It blows up on the first item in the result list with the following error:

```
    competition_value = idea.keyword_idea_metrics.competition.name
AttributeError: 'int' object has no attribute 'name'
  ```   
  
**Steps to Reproduce:**
Every time I run the script either in jupyter notebook or command line I get the above error:

download script and run it.

Persistent for both `True` and `False` values for `"use_proto_plus"` 

Modifying the script to print types (around line 90 in the latest version of script):
```
    list_keywords = []
    for idea in keyword_ideas:
        print("In Loop")
        list_keywords.append(idea)
        print(type(idea))
        print(type(idea.keyword_idea_metrics))
        print(type(idea.keyword_idea_metrics.competition))
```

I get the following output:  

```
In Loop
<class 'GenerateKeywordIdeaResult'>
<class 'KeywordPlanHistoricalMetrics'>
<class 'int'>
```

One Oddity, is that the `text` output shows the text value of expected ENUM, but trying to access the `.name` attribute causes the error. It seems something has been set to treat ENUM's as value, as opposed to a `name` and a `value` ....

**Expected behavior:**
```
In Loop
<class 'GenerateKeywordIdeaResult'>
<class 'KeywordPlanHistoricalMetrics'>
<class 'KeywordPlanCompetitionLevel'>
```  

**Client library version and API version:**
Python libs
```
Python 3.10.6

google-ads                        18.1.0
google-api-core                   2.10.2
google-auth                       2.14.0
google-auth-oauthlib              0.7.1
googleapis-common-protos          1.56.4
```  

Google Ads api version **v11**

**Request/Response Logs:**

Notice you can see the `name` of the enum in the text output, i.e. `LOW`

```
 
 Method: /google.ads.googleads.v11.services.KeywordPlanIdeaService/GenerateKeywordIdeas
Host: googleads.googleapis.com
Headers: {
  "developer-token": "REDACTED",
  "login-customer-id": "xxxxx",
  "x-goog-api-client": "gl-python/3.10.6 grpc/1.49.1 gax/2.10.2 gccl/18.1.0 pb/4.21.9+c",
  "x-goog-request-params": "customer_id="xxxxx"
}
Request: customer_id: "XXXXX"
keyword_seed {
  keywords: "Dental Implants"
}
keyword_plan_network: GOOGLE_SEARCH_AND_PARTNERS
language: "languageConstants/1000"
geo_target_constants: "geoTargetConstants/2840"


Response
-------
Headers: {
  "alt-svc": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"",
  "content-disposition": "attachment",
  "date": "Mon, 07 Nov 2022 17:13:01 GMT",
  "request-id": "Ex540ObVaAGFPczKMvU_kg"
}
Response: results {
  keyword_idea_metrics {
    competition: LOW
    monthly_search_volumes {
      month: OCTOBER
      year: 2021
      monthly_searches: 201000
    }
 
``` 

**Anything else we should know about your project / environment:**

Apple MBP, M1 Chip.

**Comment by BenRKarl** [comment]
@mcmasty I'm able to consistently read this value when `use_proto_plus` is set to `True`, and as expected I can generate this error when it's set to `False`.

Are you able to verify that you're correctly setting the configuration value as expected? There are more than one ways to set this value and one may override the other. For example, if you're setting it in a local yaml file, and _also_ setting it at runtime when initializing a `GoogleAdsClient`, the second configuration will override the first.

You can verify what the value is by printing:

```py
# Here "client" is an initialized GoogleAdsClient
print(client.use_proto_plus)
```

If that's `True` and you're still generating this error, then something very strange is going on. If it's `False` then you may be overriding your configuration somewhere.

**Comment by BenRKarl** [comment]
@mcmasty I'm going to close this out assuming you've found a resolution. If not please add further detail and I'll reopen it.
