### ISSUE TITLE
aggregate_metric_results field not included in GenerateHistoricalMetricsResponse

### ISSUE THREAD

**Issue by jlgleason** [googleads/google-ads-python#721]
I am trying to get the [device type breakdown](https://developers.google.com/google-ads/api/reference/rpc/v11/KeywordPlanAggregateMetricTypeEnum.KeywordPlanAggregateMetricType) using the `aggregate_metrics` field of the [GenerateHistoricalMetricsRequest](https://developers.google.com/google-ads/api/reference/rpc/v11/GenerateHistoricalMetricsRequest). Specifically, my code looks like this:

```
agg_metrics = client.get_type("KeywordPlanAggregateMetrics")
agg_metric = client.enums.KeywordPlanAggregateMetricTypeEnum.DEVICE
agg_metrics.aggregate_metric_types.append(agg_metric)

request = client.get_type("GenerateHistoricalMetricsRequest")
request.aggregate_metrics = agg_metrics 
```

However, the `aggregate_metric_results` field in the [GenerateHistoricalMetricsResponse](https://developers.google.com/google-ads/api/reference/rpc/v11/GenerateHistoricalMetricsResponse) is empty. 

Am I adding this parameter to the request correctly?

**Comment by BenRKarl** [comment]
Thanks @jlgleason, I'm able to reproduce this behavior using my own test account. When you generate this response, are you using a test account or a production account?

Right now this looks like it might be a bug in our system. If not then I will try to figure out what's causing this behavior. It's possible that the keyword plan may not have enough data to generate aggregations, but that's just a guess. I've filed a bug with the planning team to get some clarity and will follow up here as soon as I have more details.

**Comment by jlgleason** [comment]
Thanks @BenRKarl. I am using a test account, but I can try a production account if you think that will change the behavior.

**Comment by BenRKarl** [comment]
@jlgleason if possible, that would help me rule out this being an issue with using a test account.

**Comment by jlgleason** [comment]
@BenRKarl would it be possible for you to test with a production account? I don't currently have one and the application is fairly extensive.

**Comment by BenRKarl** [comment]
@jlgleason Sorry I actually did try this previously, but my responses are entirely empty, likely because of the state of the keyword plans in the production account that I have access to. I'll keep trying other accounts and in the meantime will wait for more details from the Planning team.

**Comment by BenRKarl** [comment]
@jlgleason thanks for your patience here. The issue here appears to be that the keyword plans used to generate historical metrics need a minimum of 5 keywords in order to generate a device breakdown. If you update your keyword plan accordingly, are you able to get the metrics you're looking for?

**Comment by xiaoyichungTopkee** [comment]
> 

I did try 5 normal keyword that can return device data,but also empty if set 5 unnormal keyword.it maybe not enough data to generate aggregation。please fixed the bug asap，thank you.

**Comment by BenRKarl** [comment]
@xiaoyichungTopkee could you clarify what you mean by "unnormal" keywords?

**Comment by jlgleason** [comment]
@BenRKarl I can see the device breakdown with a keyword plan of >= 5 keywords. Thanks for your help.

**Comment by xiaoyichungTopkee** [comment]
> 

For example: crmss erpds  systemsf debitsd ailsd

**Comment by BenRKarl** [comment]
@xiaoyichungTopkee I'm pretty sure that keywords like that won't return a device breakdown by design, but I'm checking to make sure. Could you help me understand your use-case that requires the use of these types of keywords?

**Comment by BenRKarl** [comment]
@xiaoyichungTopkee I confirmed that using "unnormal" keywords like the ones you've listed will not return device breakdowns, since they don't have search volume to begin with. 

Feel free to add more details if you have a specific use case you want help with.

**Comment by cantonalex** [comment]
Does anyone know how to get them for keywords that don't have more ideas generated? ie this "latutilanne" random word shows the breakdown on the line graph but not the pie chart therefore the api returns nothing for devices..
