### ISSUE TITLE
Batch Processing

### ISSUE THREAD

**Issue by Achilles005** [googleads/google-ads-python#722]
**What is your question?**

How can we use batch processing to generate keyword ideas (KeywordPlanIdeaService)?

**Comment by bobhancockg** [comment]
Please see the definition of batch processing at
https://developers.google.com/google-ads/api/docs/batch-processing/overview

The Operations section lists supported operations.

Bob Hancock | Google Ads API DevRel | ***@***.*** | 646-727-0741
