### ISSUE TITLE
google ads

### ISSUE THREAD

**Issue by jmeghana42** [googleads/google-ads-python#724]
we shifted from adwords to ads and this is the solution i found on github,can someone tell why this issue is still coming.
this is the library i used and the function thereafter,
import googleads.common
 adwords_client = googleads.common.LoadFromStorage('adwords','developer_token')
its showing this error
Traceback (most recent call last):
  File "/tmp/interpreter-input-9badebf1-cf97-42ed-9cdc-3effab50918e.tmp", line 102, in <module>
    adwords_client = googleads.common.LoadFromStorage('adwords','developer_token')
TypeError: LoadFromStorage() missing 2 required positional arguments: 'required_client_values' and 'optional_product_values'
Script failed with status: 1

**Comment by BenRKarl** [comment]
@jmeghana42 looks like you're importing the wrong library. The `googleads` module is for the old AdWords API, the newer module available in this repository is named `google_ads` and we have detailed documentation for it [here](https://developers.google.com/google-ads/api/docs/client-libs/python).
