### ISSUE TITLE
Error import when generating executable with auto-py-to-exe package

### ISSUE THREAD

**Issue by mattiaachilli** [googleads/google-ads-python#728]
Hello, I have a very strange problem, when i develop on PyCharm normally i can use perfectly the google ads library while when I generate the executable using the auto-py-to-exe and trying to execute it gives me back an error (i attached the image), what could it be?

**Comment by BenRKarl** [comment]
@mattiaachilli I'm going to close this out assuming the issue is resolved, but please add new details if needed and I'll reopen.
