### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by dmitrii-stebliuk** [googleads/google-ads-python#73]
I take a "Basic / Get campaigns example" https://github.com/googleads/google-ads-python/blob/master/examples/basic_operations/get_campaigns.py

Add `LIMIT 2` to GAQL, set `_DEFAULT_PAGE_SIZE = 1`.
I run the script:
`Actual:` I get 2 campaigns.
`Expected:` I should get 1 campaign, because my page size is 1.

How is it possible to paginate?

**Comment by wihl** [comment]
Pagination is handled automatically by the response iterator. If you
examined the HTTP traffic you would have seen that two requests were made
on your behalf. Automatic pagination is one of the advantages of the client
libraries over REST.

**Comment by dmitrii-stebliuk** [comment]
@wihl is there a way to paginate manually with a Python client library?

**Comment by wihl** [comment]
Not today but we are considering it in the future. What is your specific
use case for controlling paging?

**Comment by dmitrii-stebliuk** [comment]
@wihl We allow a user to run an arbitrary GAQL and show the paginated results.

**Comment by wihl** [comment]
But why do you need to dynamically change the page size? You could simply
set it to 1000 and let the iterator take care of it.

**Comment by dmitrii-stebliuk** [comment]
Thank you, @wihl 
The context I am talking about is GAQL Executor UI:
The use case is that a user writes a query that returns 100k items. He executres it and we want to show a pagination, and 50 items on the first page. If the user clicks 2nd page we show the second page.

It looks like we should amend the query user entered and set/update the limit to the number of items we show on the page. It does not look good for me. The correct way will be just use Python client Library pagination.

And when the user clicks to see the next page, we want to show him the items 51..100 of total 100k. And we again should run a query  to fetch 100 items out of 100k, skip first 50, and show the second page.

**Comment by wihl** [comment]
The response is forward only. You should not display results forward and
backward using the Google Ads API pagination. What you could do is set the
page size to be reasonable and cache the results in your code. When your
user goes to the end of your cache, just get the next item of the iterator
and the paging will be handled for you.
