### ISSUE TITLE
Unable to generate Refresh token using OAuth client id and secret

### ISSUE THREAD

**Issue by Aruun** [googleads/google-ads-python#730]
I have been trying to generate refresh token using generate_user_credentials.py, it was working fine till I publish the app and upgrade to basic account.  After the upgradation i am facing the following issue:
<img width="887" alt="image" src="https://user-images.githubusercontent.com/12800407/209126449-c2554bdd-f988-4ab1-b855-e59aa7fc57ea.png">

I do not see any button to bypass the screen. 

Could you please help me where I am going wrong?

**Comment by BenRKarl** [comment]
@Aruun unfortunately this appears to be an Auth issue and not something related to this library. Would you please submit a post on our [support forum](https://developers.google.com/google-ads/api/support) and someone from our support team there will respond and help with this.
