### ISSUE TITLE
version 19.0.0. or 18.2.0

### ISSUE THREAD

**Issue by Josefovo** [googleads/google-ads-python#737]
I can see, the newest version is 19.0.0, but in change log the newest version is 18.2.0 (and it looks like version 19.0.0, not only missing description in changelog).

https://github.com/googleads/google-ads-python/blob/8f38122a995a8555f503ca07d06fc1edcbf419d7/ChangeLog#L1

Please can you check it?

**Comment by BenRKarl** [comment]
Thanks @Josefovo we'll get this updated in the next release.

**Comment by BenRKarl** [comment]
This was corrected in the [version 20.0.0](https://github.com/googleads/google-ads-python/releases/tag/20.0.0) release, thanks again for pointing it out.
