### ISSUE TITLE
How to handle different GoogleAdsFailure?

### ISSUE THREAD

**Issue by davidebrunetto94** [googleads/google-ads-python#738]
Hello, I'm trying to understand how to handle GoogleAdsFailure and retry the operation when this kind of error occurs.
I'm getting these two types of errors:

- [ERROR] ServiceUnavailable: 503 The service is currently unavailable.
- [ERROR] ResourceExhausted: 429 Resource has been exhausted (e.g. check quota). [type_url: “[type.googleapis.com/google.ads.googleads.v10](http://type.googleapis.com/google.ads.googleads.v10).errors.GoogleAdsFailure”

The lines that are giving me these errors are already wrapped inside a "try except" looking something like this:
`    try:
        # Lines that might throw the exception
    except GoogleAdsException as ex:
        for error in ex.failure.errors:
            print(f'\tError with message "{error.message}".')
            if error.location:
                for field_path_element in error.location.field_path_elements:
                    print(f"\t\tOn field: {field_path_element.field_name}")`

But this types of errors are not caught. How Can I do this? Thank you

**Comment by BenRKarl** [comment]
Hi @davidebrunetto94 Just to clarify, are you trying to differentiate between the different types of [`GoogleAdsError`](https://github.com/googleapis/googleapis/blob/master/google/ads/googleads/v12/errors/errors.proto#L187) messages that can be returned by a [`GoogleAdsFailure`](https://github.com/googleapis/googleapis/blob/master/google/ads/googleads/v12/errors/errors.proto#L178) message? Categorically these are errors that come from the Google Ads API.

Or are you trying to differentiate between errors that are from the API and errors that are not from the API, such as gRPC-level errors?

**Comment by davidebrunetto94** [comment]
Hello @BenRKarl, thank you for the reply.
I'm trying to differentiate between different types of error messages that can be returned by a GoogleAdsFailure message, and how I catch when these happens in my code, to handle them correctly (for example I'd like to implement a retry pattern when a 503 error occurs).
