### ISSUE TITLE
V12 of Google Ads API "not supported" but it is somehow Valid

### ISSUE THREAD

**Issue by gelodefaultbrain** [googleads/google-ads-python#739]
I have never encountered something like this in my entire life. This is funny at the same time annoying.

Kindly take a look at this.

![image](https://user-images.githubusercontent.com/55988471/213531649-29ff2ff8-0b8a-4023-adf4-300e79575223.png)

It says that "v12" does not exist and at the same time it is a valid version. Whaaat?

By the way here is my code in initializing a GoogleAdsClient

```
        # GoogleAdsClient will read the google-ads.yaml configuration file in the
        # home directory if none is specified.
        self.googleads_client = GoogleAdsClient.load_from_storage(path="credentials/google-ads.yaml",version="v12")   
```

Can anyone tell me what's wrong? Thank you!

**Comment by gelodefaultbrain** [comment]
By the way, just a quick note. This tool I am working on works completely fine by running it as a python file but when I compile it via [pyinstaller](https://pyinstaller.org/en/stable/) it does this.

**Comment by BenRKarl** [comment]
@gelodefaultbrain thanks for sharing this! The logs indicate the error came from a call to GoogleAdsClient.get_service. My guess is that there’s a separate portion of your code that’s making this call, could you share that as well? What’s probably happening is that an error came up importing the module for the requested service, and it was mishandled by our library to indicate the version was invalid. 

It’s _possible_ that the mechanism we use to load modules dynamically is incompatible with pyinstaller. If you could share how you’re calling get_service I can try to confirm that.

**Comment by gelodefaultbrain** [comment]
> @gelodefaultbrain thanks for sharing this! The logs indicate the error came from a call to GoogleAdsClient.get_service. My guess is that there’s a separate portion of your code that’s making this call, could you share that as well? What’s probably happening is that an error came up importing the module for the requested service, and it was mishandled by our library to indicate the version was invalid.
> 
> It’s _possible_ that the mechanism we use to load modules dynamically is incompatible with pyinstaller. If you could share how you’re calling get_service I can try to confirm that.


Hi @BenRKarl ! OMG thanks for the reply! It's so nice to hear from you as one of the developers.
Sorry for the inconvenience, I was working for almost 12 hours straight and my brain was completely destroyed but still keep on going.

I managed to solve this issue by transferring the `google/` directory from the `site-packages`/ (where it contains the dependencies installed) to the directory of my compiled version of the program. I would say this is [pyinstaller](https://pyinstaller.org/en/stable/)'s fault because when compiling the program it didn't include the `google/` directory which was needed for the API via python to work.

I think you know what I mean by the `google/` directory in the `site-packages/`, it's the directory with the folders that has `ads/` and `api_core/` in it.

Again Thank you and sorry for the inconvenience! :smiley_cat:

**Comment by BenRKarl** [comment]
@gelodefaultbrain yep that makes sense and does explain this error. It probably makes sense to update that error message since it's clear that other issues aside from an invalid version number can trigger it. I'll file a bug for us to get that updated.

**Comment by gelodefaultbrain** [comment]
> @gelodefaultbrain yep that makes sense and does explain this error. It probably makes sense to update that error message since it's clear that other issues aside from an invalid version number can trigger it. I'll file a bug for us to get that updated.


Got it! Thanks! Also (correcting what I just said) the `google/` directory actually did get included after compiling , it's just that the contents of it (the directories inside the `google/` directory) did not. See image below

![image](https://user-images.githubusercontent.com/55988471/213782291-a221e36b-7d16-4de6-aeaf-9776156d7047.png)

So basically those directories named: ads , api , api_core , auth and more!

I think I'll file an issue with Pyinstaller with regards to this. Thank you!! 👍
