### ISSUE TITLE
New "Discovery" campaigns are not reporting spend

### ISSUE THREAD

**Issue by apurvis** [googleads/google-ads-python#74]
Recently Google Ads rolled out a whole new type of inventory - "Discovery" campaigns - which is in beta.

Making basic AWQL queries (spend by campaign) via this package does not seem to return any spend on these new types of campaigns. Is that expected or am I missing something?

(Similar to https://github.com/googleads/googleads-python-lib/issues/388 which I created in the wrong library)

**Comment by BenRKarl** [comment]
Hi @apurvis - thanks for opening this issue on this library. I'm still working on getting clarity on this feature and hope to have more detail as soon as possible. I'm sorry it's taking longer than we'd normally like for an issue like this!

**Comment by BenRKarl** [comment]
@apurvis I was able to confirm that Discovery campaigns aren't yet supported via the API, however we are working on adding support for them at some point in the future. Keep an eye on our [developer blog](https://ads-developers.googleblog.com/), we'll share details on it's release once it's supported.
