### ISSUE TITLE
TypeError: bases must be types when importing google-ads library

### ISSUE THREAD

**Issue by lkliufudi** [googleads/google-ads-python#744]
Hi,

I am trying to import the google-ads library but got bases must be types error (below). For now, I have to downgrade google-api-core to 2.8.1 to avoid this issue. Is there any other solution?

google-ads==18.1.0
proto-plus>=1.22.0
protobuf>=4.21.5
google-api-core==2.8.1 (works), 2.11.0 (not works)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-5da1651e> in <module>
----> 1 from google.ads.googleads.errors import GoogleAdsException
      2 from google.ads.googleads.v10 import GoogleAdsServiceClient, SearchGoogleAdsStreamResponse, SearchGoogleAdsStreamRequest
      3 from google.ads.googleads.client import GoogleAdsClient
      4 from facebook_business.api import FacebookAdsApi
      5 from facebook_business.adobjects.adaccount import AdAccount

~/cluster-env/clonedenv/lib/python3.8/site-packages/google/ads/googleads/__init__.py in <module>
     13 # limitations under the License.
     14 
---> 15 import google.ads.googleads.client
     16 import google.ads.googleads.errors
     17 import google.ads.googleads.util

~/cluster-env/clonedenv/lib/python3.8/site-packages/google/ads/googleads/client.py in <module>
     18 import pkg_resources
     19 
---> 20 from google.api_core.gapic_v1.client_info import ClientInfo
     21 import grpc.experimental
     22 import proto

~/cluster-env/clonedenv/lib/python3.8/site-packages/google/api_core/gapic_v1/__init__.py in <module>
     14 
     15 from google.api_core.gapic_v1 import client_info
---> 16 from google.api_core.gapic_v1 import config
     17 from google.api_core.gapic_v1 import config_async
     18 from google.api_core.gapic_v1 import method

~/cluster-env/clonedenv/lib/python3.8/site-packages/google/api_core/gapic_v1/config.py in <module>
     23 import grpc
     24 
---> 25 from google.api_core import exceptions
     26 from google.api_core import retry
     27 from google.api_core import timeout

~/cluster-env/clonedenv/lib/python3.8/site-packages/google/api_core/exceptions.py in <module>
     27 import warnings
     28 
---> 29 from google.rpc import error_details_pb2
     30 
     31 try:

~/cluster-env/clonedenv/lib/python3.8/site-packages/google/rpc/error_details_pb2.py in <module>
     18 # source: google/rpc/error_details.proto
     19 """Generated protocol buffer code."""
---> 20 from google.protobuf import descriptor as _descriptor
     21 from google.protobuf import descriptor_pool as _descriptor_pool
     22 from google.protobuf import message as _message

~/cluster-env/clonedenv/lib/python3.8/site-packages/google/protobuf/descriptor.py in <module>
     38 import warnings
     39 
---> 40 from google.protobuf.internal import api_implementation
     41 
     42 _USE_C_DESCRIPTORS = False

~/cluster-env/clonedenv/lib/python3.8/site-packages/google/protobuf/internal/api_implementation.py in <module>
    102   try:
    103     # pylint: disable=g-import-not-at-top
--> 104     from google.protobuf.pyext import _message
    105     _c_module = _message
    106     del _message

TypeError: bases must be types

**Comment by BenRKarl** [comment]
@lkliufudi this looks like the same problem described [here](https://github.com/protocolbuffers/protobuf/issues/10012). My guess is that the install of `protobuf` may actually be the problem; `google-api-core` is probably calling `from google.protobuf.pyext import _message` in version 2.11.0, but not in 2.8.1, which is why changing that version appears to fix the issue.

Can you take a look at the issue I linked and let me know if it helps you resolve this problem?

**Comment by BenRKarl** [comment]
@lkliufudi I'm going to close this out for now assuming you've resolved the issue, but if not please comment with more details.
