### ISSUE TITLE
Support Google Ads API version "v13" 

### ISSUE THREAD

**Issue by nazarlviv07** [googleads/google-ads-python#746]
I have tried to use the latest Google Ads API version, but it seems that the Python google-ads client library does not support the latest version.
We have the latest version of the google-ads client installed and specified in all the requirements files (currently it is 19.0.0)

`Valueerror: Specified Google Ads API version "v13" does not exist. Valid API versions are: "v12", "v11", "v10"`

**Comment by BenRKarl** [comment]
@nazarlviv07 we just released [version 20.0.0](https://pypi.org/project/google-ads/20.0.0/) that includes support for v13. Thanks!
