### ISSUE TITLE
Commenting is not possible on issues

### ISSUE THREAD

**Issue by apurvis** [googleads/google-ads-python#75]
![image](https://user-images.githubusercontent.com/231694/55775021-8ae57100-5a65-11e9-8fea-f35659ea318b.png)

**Comment by BenRKarl** [comment]
@apurvis Thanks for this, I'll comment this in that other issue you're referring to and will look into why you can't comment on Issues. You should have the ability to do so.

**Comment by BenRKarl** [comment]
@apurvis I found this issue on a different googleads repo. It seems silly to suggest, but have you tried logging in and out to see if the commenting issue persists?

https://github.com/googleads/googleads-mobile-unity/issues/397
