### ISSUE TITLE
KeyError: `client_secret` when generating user credentials

### ISSUE THREAD

**Issue by stevenhoelscher** [googleads/google-ads-python#750]
I'm following the directions [here](https://developers.google.com/google-ads/api/docs/client-libs/python/oauth-web) to generate a refresh token. In particular, I used the latest version of the [`generate_user_credentials.py` script](https://github.com/googleads/google-ads-python/blob/main/examples/authentication/generate_user_credentials.py).

I downloaded the JSON file (`~/client_secret_XXX.apps.googleusercontent.com.json`) and ran:

```
python generate_user_credentials.py -c client_secret_XXX.apps.googleusercontent.com.json
```

But hit the following error after the authorization callback occurred:
```
Traceback (most recent call last):
  File "/Users/developer/code/project/generate_user_credentials.py", line 198, in <module>
    main(args.client_secrets_path, configured_scopes)
  File "/Users/developer/code/project/generate_user_credentials.py", line 82, in main
    flow.fetch_token(code=code)
  File "/Users/developer/code/project/.venv/lib/python3.10/site-packages/google_auth_oauthlib/flow.py", line 298, in fetch_token
    kwargs.setdefault("client_secret", self.client_config["client_secret"])
KeyError: 'client_secret'
```

I was able to resolve this by adding the `installed.client_secret` key-value to the JSON file. It's not clear whether the original JSON file should have contained the `client_secret` in the first place, if the documentation needs to be updated to include this step, or some other user error on my part occurred.

```
pip freeze | grep 'google-ads'
google-ads==20.0.0
```

**Comment by BenRKarl** [comment]
@stevenhoelscher the `client_secret` key should definitely have been included in the JSON you downloaded. You shouldn't need to make any manual changes to that file. Without sharing any PII, can you tell what _was_ included in the JSON file you downloaded?

**Comment by stevenhoelscher** [comment]
```
{
  "installed": {
    "client_id": "***",
    "project_id": "***",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "redirect_uris": [
      "http://localhost"
    ]
  }
}
```

**Comment by BenRKarl** [comment]
@stevenhoelscher that is very odd, the JSON files I have look exactly like this except they have a `client_secret` key. If you try downloading the JSON again, does always lack this field? If so I wonder if there's an issue with how the project is set up in Cloud Console...

**Comment by stevenhoelscher** [comment]
Yes, this is odd! I tried downloading again but to no avail. But then I clicked on `Reset Secret` and `Download JSON` and the `client_secret` is now appearing!

**Comment by BenRKarl** [comment]
@stevenhoelscher that's great! Seems like it was just a matter of the setup in Cloud Console.
