### ISSUE TITLE
Make compatible with ``google-auth-oauthlib`` >= 1.0.0

### ISSUE THREAD

**Issue by DanielNoord** [googleads/google-ads-python#757]
**Describe the problem you are trying to solve:**

The project says it doesn't support `1.0.0` which was released. This holds us back from upgrading the authlib.

**Describe the solution you'd like:**

Declare support for `1.0.0`.

**Describe alternatives you've considered:**

/

**Additional context:**

[
PyPI](https://pypi.org/project/google-auth-oauthlib/#history)

**Comment by BenRKarl** [comment]
This shouldn't be a problem, we'll bump the version in an upcoming release.

**Comment by DanielNoord** [comment]
Thanks for the quick response! Appreciated!

**Comment by BenRKarl** [comment]
In the meantime, this dependency is _only_ used by the [`generate_user_credentials`](https://github.com/googleads/google-ads-python/blob/main/examples/authentication/generate_user_credentials.py) example and not in the business logic of the library itself, so you can safely override the version if needed.

**Comment by DanielNoord** [comment]
We're using `nix` to "manage" our dependencies. `Nix` creates reproducible builds across our dev machines but also disallows such overriding. We can apply a patch ourselves, but simply bumping the version ourselves (to `21.x` I guess) would be much easier.

**Comment by BenRKarl** [comment]
This is fixed in version [21.0.0](https://github.com/googleads/google-ads-python/releases/tag/21.0.0)
