### ISSUE TITLE
Issue with Package Incompatibility between google-ads and apache-beam 

### ISSUE THREAD

**Issue by lindapannn** [googleads/google-ads-python#758]
**What is your question?**

Hello, we are currently working on a project to send conversions to Google Ads using Apache Beam. However, we have encountered an issue with package incompatibility between the `google-ads` version that supports API V12 and later, and the latest version of `apache-beam`.

As both packages use `protobuf`, we discovered that the latest version of `apache-beam` requires `protobuf < 4.0`, while `google-ads 19.0.0`(the min version for API V12) requires `protobuf > 4.21.5`. We have already contacted the Apache Beam team regarding this issue, and they informed us that a release will be available in late April or May to support `protobuf >= 4.21.1 <4.23.0`.

We also noticed from this [website](https://developers.google.com/google-ads/api/docs/sunset-dates#python) that the sunset date for API V11 is March 29, 2023. This means that there will be a one-month period during which we will not be able to use Beam to send conversions to Google Ads.

Given this situation, we would appreciate any guidance or recommendations for an alternative solution that would work for this use case. Thanks!

**Comment by lindapannn** [comment]
@BenRKarl Thanks for your suggestion, but I'm not using Cloud Composer right now. I appreciate your help and any other ideas you might have.

**Comment by bobhancockg** [comment]
This is a known problem with Apache Beam and we are advocating for them to upgrade. They are a third party open source project over which we have no control and they are not a direct dependency of our library.

Currently, there is no solution that we can support.

If you feel confident, you can fork a version of our library and modify the following dependencies.

Dependency      Google Ads Version            Modified Version
google-api-core  >= 2.10.1, <= 2.11.0           >= 2.8.1, < 3.0.0dev, !=2.0.*, != 2.1.*, !=2.2.*, !=2.3.0
proto-plus           >= 1.22.1, < 1.23                 == 1.19.6
protobuf              >= 4.21.5                             >= 3.12.0, <= 3.20.0, !=3.18.*, !=3.19.*

You will experience slower performance but you should be able to get the same functionality. Again, we cannot support this and this is provided only as guidance.

protobuf version 3 is scheduled to be deprecated in May 2023. It will still be available, but no modifications will be back ported.
