### ISSUE TITLE
unable to query for business_name

### ISSUE THREAD

**Issue by Zainab-KS** [googleads/google-ads-python#759]
Hi team,

I am using v20.0.0 of the google-ads library and i'm getting an INVALID_ARGUMENT error for **ad_group_ad.ad.gmail_ad.teaser.business_name** when i make a call to GoogleAdsServices using the below query. I was not able to find any documentation where they have deprecated/found a replacement for this field. Can you please help investigate? 
 
query="SELECT campaign.name,ad_group.id,ad_group.name,ad_group.type,customer.currency_code,customer.descriptive_name,ad_group_ad.ad.expanded_text_ad.path1,ad_group_ad.ad.expanded_text_ad.path2,ad_group_ad.ad.expanded_text_ad.headline_part1,ad_group_ad.ad.expanded_text_ad.headline_part2,ad_group_ad.ad.expanded_text_ad.description,ad_group_ad.ad.expanded_text_ad.description2,metrics.average_cpc,metrics.ctr,metrics.interactions,metrics.conversions,metrics.all_conversions_from_interactions_rate,metrics.average_cost,metrics.impressions,segments.date,segments.day_of_week,segments.quarter,metrics.clicks,metrics.cost_micros,metrics.active_view_ctr,ad_group_ad.ad.gmail_ad.teaser.business_name FROM ad_group_ad WHERE segments.date BETWEEN '2022-03-22' AND '2022-03-23'"
 
**Error message :** 
google.ads.googleads.errors.GoogleAdsException: (<_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "Request contains an invalid argument."
        debug_error_string = "UNKNOWN:Error received from peer ipv4:142.251.36.42:443 {created_time:"2023-03-23T12:32:53.066264283+00:00", grpc_status:3, grpc_message:"Request contains an invalid argument."}"
>, <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "Request contains an invalid argument."
        debug_error_string = "UNKNOWN:Error received from peer ipv4:142.251.36.42:443 {created_time:"2023-03-23T12:32:53.066264283+00:00", grpc_status:3, grpc_message:"Request contains an invalid argument."}"
>, errors {
  error_code {
    query_error: UNRECOGNIZED_FIELD
  }
  message: "Unrecognized field in the query: \'ad_group_ad.ad.gmail_ad.teaser.business_name\'."
}
request_id: "3mMocaNiY__E2UcS7ikImQ"
, '3mMocaNiY__E2UcS7ikImQ')

**Comment by bobhancock** [comment]
It was available in version 11 of the API https://developers.google.com/google-ads/api/fields/v11/ad_group_ad. It was removed in version 12 https://developers.google.com/google-ads/api/fields/v12/ad_group_ad

**Comment by BenRKarl** [comment]
@Zainab-KS looks like this is part of the effort to [remove standalone Gmail Ads](https://ads-developers.googleblog.com/2021/06/standalone-gmail-campaigns-becoming.html). Unfortunately I don't think there's a workaround. If you have additional questions or concerns I suggest reaching out to this [support page](https://developers.google.com/google-ads/api/support).
