### ISSUE TITLE
Working with Python 3.9

### ISSUE THREAD

**Issue by dforrego** [googleads/google-ads-python#767]
**Describe the problem you are trying to solve:**
Working with Python 3.9

**Describe the solution you'd like:**
update files:
-noxfile.py: Line 18
-setup.py: Line 49

**Describe alternatives you've considered:**
-update the google documentation
-capture the version of python installed on the client's machine
-validate that it is 3.6 3.7 or 3.9
-use the minor version

**Additional context:**
the version of python 3.7 endsupport on  2023-06-27

![image](https://user-images.githubusercontent.com/25530285/230814256-33756164-8980-4933-9603-dde62d8672ca.png)

Thxs.

**Comment by BenRKarl** [comment]
@dforrego thank you for pointing this out. We have a goal to update the library for compatibility of all supported Python versions, and will be dropping 3.7 support in time for its EOL as well. Updates to the library should come in an upcoming release.

**Comment by BenRKarl** [comment]
@dforrego we updated [setup.py](https://github.com/googleads/google-ads-python/blob/main/setup.py#L51) to include 3.9 as a classifier, that should hopefully resolve any issues for you. We're also working on adding 3.9 to the list of tested versions in the noxfile, but need to do some work on our internal CI systems before releasing the change.

**Comment by dforrego** [comment]
@BenRKarl thanks for work it. if i can help with you tell me.
