### ISSUE TITLE
Commenting is not possible on issues

### ISSUE THREAD

**Issue by apurvis** [googleads/google-ads-python#77]
Tried to comment on https://github.com/googleads/google-ads-python/issues/75 but i cannot (same issue)

**Comment by wihl** [comment]
Did you try to logout and login again?

**Comment by wesleybowman** [comment]
@apurvis Do you have an adblocker on? If you do, try turning it off. I have to do that in this repo.

Note: before turning my adblocker off:
![Apr18::081138](https://user-images.githubusercontent.com/3688009/56340231-9cd7ba00-61b1-11e9-8314-2e35d0611ce6.png)

**Comment by BenRKarl** [comment]
Closing this as it doesn't seem like an issue we can fix.
