### ISSUE TITLE
-c/--customer_id error

### ISSUE THREAD

**Issue by BSkedgell** [googleads/google-ads-python#78]
Hi, I am working to get my Google Ads API setup through Python and I'm currently running into an issue with the get_campaigns.py initial request.

I have completed the setup of the API and added the developer_token, client_id, client_secret, refresh_token, and login_customer_id to my google-ads.yaml file but when I run the get_campaigns.py from the examples folder in this repository I am getting this error in my command line:

`(PythonData) BSKEG1ML1:~ bskedgell$ python get_campaigns.py 
usage: get_campaigns.py [-h] -c CUSTOMER_ID
get_campaigns.py: error: the following arguments are required: -c/--customer_id
(PythonData) BSKEG1ML1:~ bskedgell$ 
`

I'm not sure where I need to input this customer_id as I'm guessing it's the 10 digit number associated with MCC Google Ads account. It is referenced in the correct format in the google-ads.yaml file and I cannot find many resources online to troubleshoot this specific error. Also I took a look at the common errors section of this webpage (https://developers.google.com/google-ads/api/docs/common-errors) and the two errors relating to "customer_id" seem not to be causing my issue. 

Furthermore, I have confirmed that I set up the API correctly with an older version of this API (AdWords) using the googleads.yaml file and then the get get_account_hierarchy.py file from the AdWords repository. 

Here is a snippet of the API running correctly on the AdWords version:

`(PythonData) BSKEG1ML1:~ bskedgell$ python get_account_hierarchy.py 
CustomerId, Name`

Could someone help me out with this issue? Happy to document and contribute more info if needed. Thanks for your time!

**Comment by wihl** [comment]
The examples are using typical *nix command line argument formats. Assuming the client account id is 1234567890, invoke `get_campaigns` from the shell like

```
python get_campaigns.py -c 1234567890
```

There are two customer_ids at play here. The customer_id specified on the command line is the *client* account id, ie. where the ads are running. The customer_id specified in the `google-ads.yaml` is the MCC / *manager* account id. You will need both ids to make a successful call.

**Comment by BSkedgell** [comment]
Thank you!
