### ISSUE TITLE
How to assure a continue connexion to the API

### ISSUE THREAD

**Issue by MaxBarbet** [googleads/google-ads-python#784]
I have been using the API for a long time now with oAuth Playground to regenrate the refresh and access tokens.

I know want to have my app live but I found it impossible to use a service account to be connected at all times.

Do you have a code sample and tutorial somewhere which would give me the possibility to use service accounts or to automatically  get my refresh and access token up to date ? Should I use an API Key even if unsecure ?

It's been a long time and I don't see any documentation on this specifically for Google Ads API

**Comment by BenRKarl** [comment]
Hi @MaxBarbet - there actually isn't an approach for this that's specific to the Google Ads API. Obtaining credentials exists solely in the context of Google Cloud and OAuth 2, so for that reason I suggest looking at the [Google Identity](https://developers.google.com/identity/protocols/oauth2/web-server) documentation.
