### ISSUE TITLE
No data returned from search_term_view GAQL query when selecting segments.keyword.info.* fields

### ISSUE THREAD

**Issue by agalea91** [googleads/google-ads-python#785]
I'm able to get `search_term_view.search_term` metrics from the `search_term_view` report as expected using this code:

```
from google.ads.googleads.client import GoogleAdsClient
google_ads_client = GoogleAdsClient.load_from_storage(credentials_yaml)
gads_service = google_ads_client.get_service("GoogleAdsService", version="v14")

customer_id = [CUSTOMER_ID]

api_fields = [
    "search_term_view.search_term",
    "segments.date",
    "metrics.clicks",
]

start_date, end_date = "2023-02-01", "2023-02-01"

api_fields_str = ', '.join(api_fields)

query = f"""
             select {api_fields_str}
             from search_term_view
             where
                 segments.date between '{start_date}' and '{end_date}'
             order by segments.date
             limit 10
"""

response = gads_service.search_stream(customer_id=customer_id, query=query)
```

At this step I can see that `response.is_active() == True`, and I can iterate over it to fetch the data.

Now when I attempt to add one or more keyword segment (e.g. below), I no longer get the expected behavior:

```
api_fields = [
    "search_term_view.search_term",
    "segments.date",
    "segments.keyword.ad_group_criterion",
    "segments.keyword.info.match_type",
    "segments.keyword.info.text",
    "metrics.clicks",
]

...

response = gads_service.search_stream(customer_id=customer_id, query=query)
```

In this case I can see that `response.is_active() == False` and `response.code()` is `<StatusCode.OK: (0, 'ok')>`

There is nothing to iterate over in the response. Is this behavior expected?

**Comment by BenRKarl** [comment]
@agalea91 It's very possible that adding those additional segments caused the query to return no results. I suggest reviewing our [segmentation guide](https://developers.google.com/google-ads/api/docs/reporting/segmentation) for more details. And you can try swapping each segment in and out of the query to see which one causes the results to drop off.
