### ISSUE TITLE
How to create ad schedule for a specific campaing?

### ISSUE THREAD

**Issue by NativSibony** [googleads/google-ads-python#786]
I'm having trouble locating information on how to create an ad schedule for a particular campaign using the Google Ads API. Despite spending hours searching through the documentation, I couldn't find any specific details on this topic. Can you please assist me in finding the relevant instructions or resources within the Google Ads API documentation?

**Comment by BenRKarl** [comment]
@NativSibony thanks for the question! To create an ad schedule you need to create a campaign criterion, setting the [`ad_schedule`](https://developers.google.com/google-ads/api/reference/rpc/v14/CampaignCriterion#ad_schedule) field with the configuration you're looking for. 

You can reference the [add_campaign_targeting_criteria](https://github.com/googleads/google-ads-python/blob/main/examples/targeting/add_campaign_targeting_criteria.py) example to see how to create campaign criterion. To configure an ad schedule criterion operation, I believe you would need to do something like this:

```
operation = client.get_type("CampaignCriterionOperation")
criterion = operation.create
criterion.campaign = "campaign resource name"
# Set the schedule to run on Mondays between 5pm - 8pm
criterion.ad_schedule.day_of_week = client.enums.DayOfWeekEnum.MONDAY
criterion.ad_schedule.start_hour = 17
criterion.ad_schedule.end_hour = 20
```
