### ISSUE TITLE
"UNIVERSAL_APP_CAMPAIGN" missing from "enums.py"

### ISSUE THREAD

**Issue by otso** [googleads/google-ads-python#79]
Either `AdvertisingChannelTypeEnum` or `AdvertisingChannelSubTypeEnum` should include `UNIVERSAL_APP_CAMPAIGN` ([latter would be correct based on this](https://developers.google.com/adwords/api/docs/guides/mobile-app-campaigns)).

Alternatively, guidance on which types to use/example for UAC creation would be great.

**Comment by otso** [comment]
`MULTI_CHANNEL` and `APP_CAMPAIGN` missing? 

https://ads-developers.googleblog.com/2019/03/announcing-v11-of-google-ads-api.html

**Comment by wihl** [comment]
Multi_channel is [here](https://github.com/googleads/google-ads-python/blob/6defcebda26d1698f5eac62ecf8c0630163ca94a/google/ads/google_ads/v1/proto/enums/advertising_channel_type_pb2.py#L64);  App_campaign is [here](https://github.com/googleapis/googleapis/blob/f218d4053d8d2e220b9c4c8f0eeeab77e8ff12ed/google/ads/googleads/v1/enums/advertising_channel_sub_type.proto#L74)

Universal App Campaigns are now renamed just App Campaigns. See the [V1_1 blog post](https://ads-developers.googleblog.com/2019/03/announcing-v11-of-google-ads-api.html) under **Campaigns**

Hope this clears things up!

**Comment by otso** [comment]
I do not know about the internals of the library but should you really use:

`
    campaign.advertising_channel_type = 7`
`    campaign.advertising_channel_sub_type = 12
`

Instead of:

`
    campaign.advertising_channel_type = client.get_type(
        'AdvertisingChannelTypeEnum').MULTI_CHANNEL`
`campaign.advertising_channel_sub_type = client.get_type(
        'AdvertisingChannelTypeEnum').APP_CAMPAIGN
 `

The latter does not work because the enums are not exposed in the `enums.py`

**Comment by wihl** [comment]
It isn't a good idea to hard code proto enum values as you'll lose the validation that the values are correct and as intended. 

The error in your code above is that `APP_CAMPAIGN` is an enum of `AdvertisingChannelSubTypeEnum` not `AdvertisingChannelTypeEnum`

The following snippet
```
 print ("multi_channel=",client.get_type('AdvertisingChannelTypeEnum').MULTI_CHANNEL)
 print ("app_campaign=", client.get_type('AdvertisingChannelSubTypeEnum').APP_CAMPAIGN)
``` 

will produce

```
multi_channel= 7
app_campaign= 12
```
as expected.  But it isn't a best practice to hardcode these values of 7 and 12 in your code.

**Comment by otso** [comment]
Thanks @wihl this clarifies!

Any chance to get this example https://developers.google.com/adwords/api/docs/samples/python/advanced-operations#add-a-universal-app-campaign running with the new API? With the old AdWords API it works just fine for me.

**Comment by wihl** [comment]
We are working towards sample parity between the AdWords and Google Ads APIs. The priority is somewhat determined by customer demand, so your request has been noted. "We're working on it" :)

**Comment by otso** [comment]
Excellent and thanks in advance 👍
