### ISSUE TITLE
ConnectionResetError while calling google Ads api

### ISSUE THREAD

**Issue by Zainab-KS** [googleads/google-ads-python#792]
I have been getting the below Connection error message since the past 1 week : 
**google.auth.exceptions.TransportError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))**

This script was executing fine since months but all of a sudden something stopped working.
I tried to regenerate the refresh token, but I get a similar error message and i am unable to generate a new token as well:

**raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))**

Can you suggest what might be going wrong here ? I am attaching the error logs for both the scenarios for your reference: 
[Err1.txt](https://github.com/googleads/google-ads-python/files/12068849/Err1.txt)
[error while generating new request token.txt](https://github.com/googleads/google-ads-python/files/12068853/error.while.generating.new.request.token.txt)

Also, these are the google ads libraries I have installed : 
google==3.0.0
google-ads==20.0.0
google-api-core==2.11.0
google-api-python-client==2.81.0
google-auth==2.16.2
google-auth-httplib2==0.1.0
google-auth-oauthlib==0.8.0
googleapis-common-protos==1.59.0

**Comment by Zainab-KS** [comment]
Hi,
Can anyone please assist soon?

**Comment by BenRKarl** [comment]
@Zainab-KS - this issue looks like a problem with your local network, and not the API or client library. The refresh token request script uses the [google-auth-oauthlib](https://pypi.org/project/google-auth-oauthlib/) package, and since you see the same error there I believe this is a connection issue.
