### ISSUE TITLE
Create Adgroup in ACi campaign with deeplink 

### ISSUE THREAD

**Issue by HossameldeinDev** [googleads/google-ads-python#797]
**What is your question?**

I'm trying to create adgroups using this SDK, I have two type of  campaigns, ACe and ACi 
for ACe it's working perfectly using this code 

```python
            ad_group_ad.ad.app_engagement_ad.headlines.extend(
                self._create_ad_text_assets(headlines),
            )
            ad_group_ad.ad.app_engagement_ad.descriptions.extend(
                self._create_ad_text_assets(descriptions),
            )
            final_app_url = self.google_ads_client.get_type(
                'FinalAppUrl',
                version=settings.GOOGLE_ADS_API_VERSION,
            )
            final_app_url.os_type = 'IOS'
            final_app_url.url = 'www.sample.com/'
            ad_group_ad.ad.final_app_urls.extend([final_app_url])
```

but using the below code for ACi doesn't wok

```python
            ad_group_ad.ad.app_ad.headlines.extend(self._create_ad_text_assets(headlines))
            ad_group_ad.ad.app_ad.descriptions.extend(self._create_ad_text_assets(descriptions))
            final_app_url = self.google_ads_client.get_type(
                'FinalAppUrl',
                version=settings.GOOGLE_ADS_API_VERSION,
            )
            final_app_url.os_type = 'ANDROID'
            final_app_url.url = 'fbconnect://cct.com.global.foodpanda.android/.*'
            ad_group_ad.ad.final_app_urls.extend([final_app_url])
```

it produce this error 

```javascript
Fault: errors {
  error_code {
    field_error: VALUE_MUST_BE_UNSET
  }
  message: "The field cannot be set."
  location {
    field_path_elements {
      field_name: "operations"
      index: 0
    }
    field_path_elements {
      field_name: "create"
    }
    field_path_elements {
      field_name: "ad"
    }
    field_path_elements {
      field_name: "final_app_urls"
    }
  }


}

```

The below image is my adgroup that is created manually, as you can see the deeplink is an asset on its own, 
when run a python script it retrieve the headlines and descriptions but don't retrieve the deep link
when i run another python script to retrieve all assets in the campaign it retrieve TEXT and VIDEO assets but never the deep link

<img width="884" alt="Screenshot 2023-08-09 at 1 41 57 AM" src="https://github.com/googleads/google-ads-python/assets/20859983/df7dc312-841b-4413-97bf-c23ed877bded">

As it's already possible to add a deeplink using the dashboard in the browser, is not there a way to do it using the SDK? 

thanks!

**Comment by BenRKarl** [comment]
@HossameldeinDev apologies for the delayed response here. If you're still having this problem, can you clarify whether the `VALUE_MUST_BE_UNSET` occurs on create or update operations? Or is it both?

**Comment by BenRKarl** [comment]
Closing this for now since there hasn't been any activity, but please comment further if this is still an issue and I'll reopen it.
