### ISSUE TITLE
ExceptionInterceptor fails to capture error data

### ISSUE THREAD

**Issue by msaniscalchi** [googleads/google-ads-python#8]
The `ExceptionInterceptor` in [client.py](https://github.com/googleads/google-ads-python/blob/master/google/ads/google_ads/client.py) is intended to scan the response's `trailing_metadata` and parse a `GoogleAdsFailure`, which is then used to construct a detailed GoogleAdsException.

It seems that some (all?) exceptions are no longer being correctly parsed, resulting in very generic and potentially misleading error messages.

As a temporary work-around, users can catch the exception and view its trailing metadata to determine if there is an underlying Google Ads API error.

**Comment by BenRKarl** [comment]
This bug was addressed in the v0_6 release, see this new handler for background: https://github.com/googleads/google-ads-python/blob/master/google/ads/google_ads/client.py#L260

It's possible some errors still may not be handled properly, but the majority of them should be much easier to read now.
