### ISSUE TITLE
__future__ imports must occur at beginning of file

### ISSUE THREAD

**Issue by kapziel** [googleads/google-ads-python#80]
Using python 3.6 and running the keyword [recommendation service](https://github.com/googleads/google-ads-python/blob/master/examples/planning/generate_keyword_ideas.py) I get the following error:

`SyntaxError: from __future__ imports must occur at the beginning of the file`

Python version is what is bundled/maintained by Anaconda (using Spyder), deleted comments at start of file seems to fix this but that's a bit hacky.

**Comment by wihl** [comment]
@kapziel I just tested this sample with generic Python 3.6.5 and didn't have any issues. Can you double check?

**Comment by kapziel** [comment]
Sorry for the delay, tried this again and same error. I'm using python version:

`Python 3.6.3 :: Anaconda custom (64-bit)`

**Comment by BenRKarl** [comment]
Hi @kapziel unfortunately I think this is an error enforced by the version of Python bundled with Anaconda and not the default version. We wouldn't change the structure of that file to avoid the error; is it possible that there's a setting in Anaconda that might help you ignore these errors?

**Comment by kapziel** [comment]
Thanks Ben, I'll see what I can do in Anaconda.
