### ISSUE TITLE
Still having trouble generating forecast metrics for keywords

### ISSUE THREAD

**Issue by JuanAntonioCleverAds** [googleads/google-ads-python#802]
Hello @BenRKarl, the response I got here does not work https://github.com/googleads/google-ads-python/issues/791
I've seen that now the documentation has examples https://developers.google.com/google-ads/api/docs/keyword-planning/generate-forecast-metrics#python
it says that: **It then iterates through each of the results and displays each of the forecast metrics.**
bu then the code only generates forecast metrics for the campaign not for the keywords.
How can i generate forecast metrics for each keyword and not for the campaign?

Have a nice day!

**Comment by BenRKarl** [comment]
Hi @JuanAntonioCleverAds - thanks for clarifying. The ability to generate forecasts at the keyword level were actually removed, you can find more details in [this blog post](https://ads-developers.googleblog.com/2023/04/ad-group-and-keyword-forecasts-being.html). As of now, you will need to generate forecasts at the campaign level.
