### ISSUE TITLE
Use load_from_env() with GOOGLE_ADS_USE_PROTO_PLUS

### ISSUE THREAD

**Issue by FritzTheDev** [googleads/google-ads-python#807]
**What is your question?**

How can I set the required GOOGLE_ADS_USE_PROTO_PLUS to True or False to use with load_from_env() as described [here](https://developers.google.com/google-ads/api/docs/client-libs/python/configuration#configuration_using_environment_variables)?

The rest of the variables (which are strings) seem to be loading correctly from my environment, but it seems like the parsing logic is either broken or missing for turning GOOGLE_ADS_USE_PROTO_PLUS into the boolean this library expects.

I've tried it both with & without quotes around the value in question, and both capitalized & not.

```
# Arbitrary .py file
client = GoogleAdsClient.load_from_env()
```

```
# .env (example)
GOOGLE_ADS_DEVELOPER_TOKEN=""
GOOGLE_ADS_CLIENT_ID=""
GOOGLE_ADS_CLIENT_SECRET=""
GOOGLE_ADS_REFRESH_TOKEN=""
GOOGLE_ADS_LOGIN_CUSTOMER_ID=""
GOOGLE_ADS_USE_PROTO_PLUS="True"
OPENAI_API_KEY=""
API_DOMAIN=""
```

There are technical reasons that using a YAML file would be difficult to manage in a way that environment variables are not.

Am I doing something wrong or is this just broken, given that the variable is required?

Am I just going to have to bite the bullet here and figure out how to use YAML instead?

**Comment by FritzTheDev** [comment]
(Pasting what I believe to be the relevant part of the stack trace below)


```ValueError: The client library configuration is missing the required "use_proto_plus" key. Please set this option to either "True" or "False". For more information about this option see the Protobuf Messages guide: https://developers.google.com/google-ads/api/docs/client-libs/python/protobuf-messages```

**Comment by FritzTheDev** [comment]
Workaround for the time being has been to roll my own env loader function & use load_from_dict(). Seems to be working.

**Comment by BenRKarl** [comment]
@FritzTheDev sorry for the delayed response here. How are you setting this variable in the environment? I ran a few tests locally and was unable to get it to appear in `os.environ` when setting it in the terminal instance i.e. `$ GOOGLE_ADS_USE_PROTO_PLUS="true"`, however it appears when I set it in my `.bashrc` file.

**Comment by FritzTheDev** [comment]
@BenRKarl No longer working on this project, but if it's helpful, I think I was loading it via pipenv's automatic .env file loading feature.

Feel free to close.

**Comment by FritzTheDev** [comment]
Oh whoops wrong button. Didn't mean to close it myself.
