### ISSUE TITLE
Uploading Conversion via Google Ads Api

### ISSUE THREAD

**Issue by mourasss** [googleads/google-ads-python#808]
Hello,

i m using the google ads api for uploading our enhanced conversions for leads. If i understood well the documentation, we cannot upload a lot of conversions at once via the  "upload_click_conversions"  in the "ConversionUploadService". is it right ?

My second question : once we uploaded conversions via the api, why i cannot see them in the google ads UI in the conversion action panel ? how can we check that google ads it taking them into account ?

Thanks in advance

**Comment by BenRKarl** [comment]
Hi @mourasss - this question is better suited for our [general support page](https://developers.google.com/google-ads/api/support), since it's not specific to this library.
