### ISSUE TITLE
Internal server error on uploading same image asset twice

### ISSUE THREAD

**Issue by martinvy** [googleads/google-ads-python#81]
Hi. I upload an image assets into Google Ads test account. I noticed, that when I upload same image twice, but with different name, the second time it fails with Internal Server Error 500. It would be nice to handle the case on Google's side and return error like "image asset, which you are trying to upload, already exists with with name xxx and resource_name yyy".

My code looks like this:
```python
asset = asset_operation.create
asset.name.value = "test"  # resp. "test 2" the second time
asset.type = asset_type_enum.IMAGE
asset.image_asset.mime_type = mime_type_enum.IMAGE_JPEG
asset.image_asset.data.value = image_data_bytes
asset_service.mutate_assets(customer_id, [asset_operation])
```

I guess it's related to the API itself, not specifically to this Python client, but can you check it? Thanks 👍

**Comment by wihl** [comment]
Thanks for the error report @martinvy. We are looking into reproducing this.

**Comment by wihl** [comment]
This has been resolved in an earlier of Google Ads API. Uploading identical images will not generate an error, but no new id will be assigned.
