### ISSUE TITLE
Facing "user_permission_denied" issue

### ISSUE THREAD

**Issue by c45957** [googleads/google-ads-python#823]
Hello Team,

We are using GoogleAdsClient to connect with google ads and 
credentials = {
    "developer_token": secret_details['developer_token'],
    "client_id": secret_details['client_id'],
    "client_secret": secret_details['client_secret'],
    "refresh_token": secret_details['refresh_token'],
    "login_customer_id": secret_details['login_customer_id']}

google_ads_client = GoogleAdsClient.load_from_dict(credentials)

Issue : if I am trying to connect to 9101713876 account then I am using 9101713876 as login-customer-id(For this account it is working fine) and when I am trying to connect 3942718446 account then I am using 3942718446 as login-customer-id(For this account we are facing issue).
Please note: we are using it without hyphen.

Error:
google.ads.googleads.errors.GoogleAdsException: (<_InactiveRpcError of RPC that terminated with:
           status = StatusCode.PERMISSION_DENIED
           details = "The caller does not have permission"
           debug_error_string = "UNKNOWN:Error received from peer ipv4:142.251.111.95:443 {grpc_message:"The caller does not have permission", grpc_status:7, created_time:"2023-11-20T11:27:36.608292348+00:00"}"
>, <_InactiveRpcError of RPC that terminated with:
           status = StatusCode.PERMISSION_DENIED
           details = "The caller does not have permission"
           debug_error_string = "UNKNOWN:Error received from peer ipv4:142.251.111.95:443 {grpc_message:"The caller does not have permission", grpc_status:7, created_time:"2023-11-20T11:27:36.608292348+00:00"}"
>, errors {
  error_code {
    authorization_error: USER_PERMISSION_DENIED
  }
  message: "User doesn\'t have permission to access customer. Note: If you\'re accessing a client customer, the manager\'s customer id must be set in the \'login-customer-id\' header. See https://developers.google.com/g

Logs:

Request made: ClientCustomerId: None, Host: googleads.googleapis.com, Method: /google.ads.googleads.v14.services.CustomerService/ListAccessibleCustomers, RequestId: AIdXo6ZL4iVI3ydqcobMXA, IsFault: False, FaultMessage: None
Total results: 1
Customer resource name: "customers/9101713876"
 
Logging code that has been used:
import logginglogging.basicConfig(level=logging.INFO, format='[%(asctime)s - %(levelname)s] %(message).5000s')logging.getLogger('google.ads.googleads.client').setLevel(logging.INFO)
 
 
Please let us know if any other information is needed.

Regards,
Rohit Rastogi

**Comment by BenRKarl** [comment]
Hi @c45957 - this issue appears to be caused by the API itself and not this library. Would you please follow the support instructions on [this page](https://developers.google.com/google-ads/api/support/api-issues) for help?
