### ISSUE TITLE
Question of adding a existing user list to a existing ad group.

### ISSUE THREAD

**Issue by huxiaohuanzhai** [googleads/google-ads-python#824]
**What is your question?**
I am trying to add a existing user list to a existing ad group. I think it might has something to do with criterial, but there is no sample code in the document, so I was confused. I simply want to build an audience list in an ad group, how am I supposed to do that?

**Comment by BenRKarl** [comment]
Hi @huxiaohuanzhai - this issue appears to be related to the API itself and not this library. Would you please follow the support instructions on [this page](https://developers.google.com/google-ads/api/support/api-issues) for help?
