### ISSUE TITLE
Missing `get_all_image_assets` script

### ISSUE THREAD

**Issue by Sebadst** [googleads/google-ads-python#832]
In the `upload_image_asset` script [here](https://github.com/googleads/google-ads-python/blob/720b39e3538f65d1cc48ce1e92479154cfa2fc23/examples/misc/upload_image_asset.py#L17C26-L17C46), you are mentioning a `get_all_image_assets.py` script.
However, there doesn't seem to be such a script in the repo.
Could you please upload one or update that docs?
Thanks

**Comment by BenRKarl** [comment]
@Sebadst thanks for pointing this out. It looks like this reference has been missing for some time. I'm checking with the team to determine if this example is still planned, or obsolete. I'll file a bug to make an update based on what I find. In the meantime I believe you should be able to retrieve all image assets with the below GAQL query:

```
SELECT
  asset.*
  ...
FROM asset
WHERE asset.type = IMAGE
```
