### ISSUE TITLE
Add targetted audiences to ad_group

### ISSUE THREAD

**Issue by shivam-2002** [googleads/google-ads-python#836]
**Describe the problem you are trying to solve:**
Attach targetted audiences to ad_group or campaign.

**Describe the solution you'd like:**
api to attach custom audience to ad_group or campaign.

**Describe alternatives you've considered:**
I asked "how to attach audiences to ad_group" in google ads api support forum and got repetative solutions which is not working. One of the solution was https://developers.google.com/google-ads/api/docs/remarketing/audience-segments/getting-started, In this document, code for the Step 3 "Target your campaigns or ads to the audience segment." is not provided.

This "https://developers.google.com/google-ads/api/reference/rpc/v15/TargetingDimensionEnum.TargetingDimension#audience" document suggest to use targetting dimension, but field name is not mentioned for targetinng dimension. like "ad_group.targeting_setting.target_restriction_operations.append(
    {
        'targetted_audiences': [id1, id2, ide3, .....]
    }
)" 
here "targetted_audiences" field is not correct and correct field name is unknown to us.

**Additional context:**

If we can put correct field name instead of "targetted_audiences" then we will be able to successfully create ad_group and target audiences. Similary we can target audience after creting ad_group.

```
import uuid
from google.ads.googleads.v14.enums.types.targeting_dimension import TargetingDimensionEnum
from google.ads.googleads.client import GoogleAdsClient
from google.ads.googleads.errors import GoogleAdsException
customer_id = "XXXXXXXXX"
campaign_id = "XXXXXXXXX"

client = GoogleAdsClient.load_from_storage(version="v15")

ad_group_service = client.get_service("AdGroupService")
campaign_service = client.get_service("CampaignService")

# Create ad group.
ad_group_operation = client.get_type("AdGroupOperation")
ad_group = ad_group_operation.create
ad_group.name = f"DemoAdGroup{uuid.uuid4()}"
ad_group.status = client.enums.AdGroupStatusEnum.ENABLED
ad_group.campaign = campaign_service.campaign_path(
    customer_id, campaign_id)
ad_group.type_ = client.enums.AdGroupTypeEnum.SEARCH_STANDARD
ad_group.cpc_bid_micros = 10000000

ad_group.targeting_setting.target_restrictions.append(
    {
        'targeting_dimension': TargetingDimensionEnum.TargetingDimension.AUDIENCE,
        'bid_only': True,  # Set to True if you only want to observe, not target,
    }
)

ad_group.targeting_setting.target_restriction_operations.append(
    {
        'targetted_audience': []
    }
)

# Add the ad group.
ad_group_response = ad_group_service.mutate_ad_groups(
    customer_id=customer_id, operations=[ad_group_operation]
)
print(f"Created ad group {ad_group_response.results[0].resource_name}.")

```

**Comment by devzer01** [comment]
Your support team has been a great resource for us in groups.google.com but the issue has reached beyond the limitation of what has been documented. Your kind assistance on this matter is greatly appreciated. Thank you

**Comment by BenRKarl** [comment]
Hi @shivam-2002 - thank you for filing this issue. Could you please paste a link to the forum post you mentioned? I'd like to follow up on it to ensure correct information is provided in the future. 

To set an Ad Group to target and audience, you will need to create a new [`AdGroupCriterion`](https://developers.google.com/google-ads/api/reference/rpc/latest/AdGroupCriterion), setting the [`audience`](https://developers.google.com/google-ads/api/reference/rpc/latest/AdGroupCriterion#audience) field equal to the resource name of the audience you want to target. 

The [`add_demographic_targeting_criteria`](https://github.com/googleads/google-ads-python/blob/main/examples/targeting/add_demographic_targeting_criteria.py) example is a pretty decent approximation of the logic you will need to implement. Let me know if you need further details.

**Comment by shivam-2002** [comment]
Hi Ben, thank you for your attention, I already have created AdGroup Criterian but I am getting some error in that which I have reported to support forun, they told that it looks like a bug.
I can't paste link forum post because conversation happend in email thread with case id: "ref:!00D1U01174p.!5004Q02ryquU:ref"

```
import argparse
import sys

from google.ads.googleads.client import GoogleAdsClient
from google.ads.googleads.errors import GoogleAdsException
from google.ads.googleads.v15.common.types.criteria import CustomAudienceInfo

import logging


def main(client, customer_id, ad_group_id="<AD-GROUP-ID>"):
    try:
        custom_audience_resource_name = "customers/<CUSTOMER-ID>/customAudiences/<CUSTOM-AUDIENCE>"

        ad_group_service = client.get_service("AdGroupService")
        ad_group_criterion_service = client.get_service(
            "AdGroupCriterionService")

        ad_group_resource_name = ad_group_service.ad_group_path(
            customer_id, ad_group_id
        )
        ad_group_criterion_operation = client.get_type(
            "AdGroupCriterionOperation"
        )
        ad_group_criterion = ad_group_criterion_operation.create
        ad_group_criterion.ad_group = ad_group_resource_name
        ad_group_criterion.custom_audience = CustomAudienceInfo(
            custom_audience=custom_audience_resource_name
        )

        ad_group_criterion_response = (
            ad_group_criterion_service.mutate_ad_group_criteria(
                customer_id=customer_id,
                operations=[
                    ad_group_criterion_operation,
                ],
            )
        )

        for result in ad_group_criterion_response.results:
            print(result.resource_name)
    except Exception as ex:
        logging.DEBUG(ex)


if __name__ == "__main__":
    googleads_client = GoogleAdsClient.load_from_storage(version="v15")

    parser = argparse.ArgumentParser(
        description=(
            "Adds demographic targeting criteria to the provided"
            " ad group, for the specified customer."
        )
    )
    # The following argument(s) should be provided to run the example.
    parser.add_argument(
        "-c",
        "--customer_id",
        type=str,
        required=True,
        help="The Google Ads customer ID.",
    )
    # parser.add_argument(
    #     "-a", "--ad_group_id", type=str, required=True, help="The ad group ID."
    # )
    args = parser.parse_args()

    try:
        main(googleads_client, args.customer_id)
    except GoogleAdsException as ex:
        print(
            f'Request with ID "{ex.request_id}" failed with status '
            f'"{ex.error.code().name}" and includes the following errors:'
        )
        for error in ex.failure.errors:
            print(f'\tError with message "{error.message}".')
            if error.location:
                for field_path_element in error.location.field_path_elements:
                    print(f"\t\tOn field: {field_path_element.field_name}")
        sys.exit(1)
```

The error 
[example.log](https://github.com/googleads/google-ads-python/files/14227462/example.log)
log file is attach to it.

> Hi @shivam-2002 - thank you for filing this issue. Could you please paste a link to the forum post you mentioned? I'd like to follow up on it to ensure correct information is provided in the future.
> 
> To set an Ad Group to target and audience, you will need to create a new [`AdGroupCriterion`](https://developers.google.com/google-ads/api/reference/rpc/latest/AdGroupCriterion), setting the [`audience`](https://developers.google.com/google-ads/api/reference/rpc/latest/AdGroupCriterion#audience) field equal to the resource name of the audience you want to target.
> 
> The [`add_demographic_targeting_criteria`](https://github.com/googleads/google-ads-python/blob/main/examples/targeting/add_demographic_targeting_criteria.py) example is a pretty decent approximation of the logic you will need to implement. Let me know if you need further details.
