### ISSUE TITLE
StatusCode.PERMISSION_DENIED

### ISSUE THREAD

**Issue by ariasgian** [googleads/google-ads-python#837]
**I am having problems uploading data to Google Ads, even though it was working fine until a month ago**
![error_megalista](https://github.com/googleads/google-ads-python/assets/51102814/c9fdb9da-1010-41ec-9921-48476a6bd546)

**Comment by BenRKarl** [comment]
Hi @ariasgian That looks like a general API issue and not a problem with this library. I recommend following the support steps on [this page](https://developers.google.com/google-ads/api/support/api-issues) to resolve the issue.
