### ISSUE TITLE
Ad Accounts Suspensions Following Campaign Pausing

### ISSUE THREAD

**Issue by nehoil** [googleads/google-ads-python#839]
Hello,

We have encountered an issue with our Google Ads accounts being suspended under the "Circumventing systems policy" violation. Our company, Lichy.io, has created around 6 ad accounts under our MCC (Manager Account) using the Google Ads API. These accounts were set up for legitimate businesses, including painters, furniture moving, and cleaning services. We've ensured full compliance with Google Ads policies, leveraging the API to automate and manage campaigns end-to-end with support from generative AI.

Despite our adherence to guidelines, 5/6 accounts were suspended a few weeks after creation shortly after pausing them. This is perplexing and concerning, as it directly impacts our ability to serve our customers and hinders our startup's growth. We have attempted to resolve this through Google Ads support, but have not received a resolution or clear understanding of the specific compliance issues.

We've used the following API methods to create and manage our campaigns, demonstrating our reliance on the Google Ads API for operations:

- GoogleAdsService.MutateCampaigns for campaign creation and management.
- CampaignService.Create to set up new campaigns.
- AdGroupService.Mutate for ad group adjustments.
- AdGroupAdService.MutateAds to manage individual ads.
- CampaignCriterionService.MutateCampaignCriteria for targeting adjustments.
- *CampaignService.PauseCampaign* to pause all active campaigns as part of our account management practices.

We're seeking clarity on what triggered the suspensions and guidance on how to rectify this situation. Our goal is to ensure our campaigns and account management practices are in full alignment with Google's policies, preventing future suspensions and ensuring a positive outcome for our customers.

Could the campaign pausing triggered an accounts suspension? 

Thank you for your attention to this matter. We appreciate any insights or guidance you can provide to help us understand and resolve these suspensions.

Best regards,
Nehoray Ilani,
Lichy.io Team

**Comment by BenRKarl** [comment]
Hi @nehoil this page is intended for issues related to the functionality of this library, to get help with account suspensions I suggest following the steps on [this support page](https://developers.google.com/google-ads/api/support/policy),
