### ISSUE TITLE
503 DNS resolution failed for keyword report example

### ISSUE THREAD

**Issue by economy** [googleads/google-ads-python#84]
I'm attempting to walk through the example for pulling a keyword report, and it looks like I'm successfully initializing the client and service.

I'm using Anaconda Python 3.7.1, have installed google-ads 1.3.1. The service is set to version 'v1' as in the provided example. 

When I run the sample query, I get to line 48:

    for row in response:
            campaign = row.campaign
            ad_group = row.ad_group
    ...

Which throws an exception: 

    Request made: ClientCustomerId: XXX-XXX-XXXX, Host: googleads.googleapis.com:443, Method: /google.ads.googleads.v1.services.GoogleAdsService/Search, RequestId: None, IsFault: True, FaultMessage: DNS resolution failed

and

    _Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "DNS resolution failed"
	debug_error_string = "{"created":"@1555542001.640383000","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2715,"referenced_errors":[{"created":"@1555541990.752433000","description":"Resolver transient failure","file":"src/core/ext/filters/client_channel/resolving_lb_policy.cc","file_line":335,"referenced_errors":[{"created":"@1555541990.752432000","description":"DNS resolution failed","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc","file_line":326,"grpc_status":14,"referenced_errors":[{"created":"@1555541990.752381000","description":"C-ares status is not ARES_SUCCESS: DNS query cancelled","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":240,"referenced_errors":[{"created":"@1555541990.752374000","description":"C-ares status is not ARES_SUCCESS: DNS query cancelled","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":240}]}]}]}]}"

**Comment by BenRKarl** [comment]
Hi @economy thanks for posting this. That's definitely an interesting error. It appears as though the request is not able to get a response from the DNS server so it's failing before it reaches the Google Ads API. I looked around on the gRPC Issue list and found a similar problem related to C# https://github.com/grpc/grpc/issues/18411. It might be better to submit an issue with them to see if that error exists for Python as well.
