### ISSUE TITLE
Adding Consent Field To OfflineUserDataJobOperation Job

### ISSUE THREAD

**Issue by masabni** [googleads/google-ads-python#845]
Whenever I try to add the consent field to the user data operation I get this error
`[ERROR] AttributeError: consent`
this is how I'm doing it in the code

        user_data_operation = client.get_type('OfflineUserDataJobOperation')

        user_data = user_data_operation.create

        user_identifier = client.get_type('UserIdentifier')

        user_identifier.hashed_email = normalize_and_hash(email)

        # add GRANTED consent for the user (2 is the enum value for GRANTED)
        user_data.consent.ad_user_data = 2
        user_data.consent.ad_personalization = 2

it looks like that doing it like `user_data.consent.ad_user_data = 2` is not the correct way, I didn't find much documentation about this anywhere except for the examples and even there it's similar to my code.
Can you please tell me what I'm doing wrong here, thanks in advance

**Comment by BenRKarl** [comment]
@masabni is this for a customer match user list? If so, then I suggest reading the documentation [here](https://developers.google.com/google-ads/api/docs/remarketing/audience-segments/customer-match/get-started#usage-flow).

**Comment by masabni** [comment]
hello @BenRKarl, it would be really great if I can get a confirmation about the consent attribute. Let me know how can I help here

**Comment by BenRKarl** [comment]
@masabni one thing to double-check is that you're using `v15` of the API or later. You can specific which API version to use when initializing a client, as is shown [here](https://github.com/googleads/google-ads-python/blob/main/examples/basic_operations/get_campaigns.py#L53).

**Comment by masabni** [comment]
@BenRKarl I see, when I tried it, it gave error 

```
[ERROR] ValueError: There was an error importing the "google.ads.googleads.v15" module. Please check that "v15" is a valid API version. Here are the current API versions supported by this library: v14, v13.
```

looks like the package is not up to date in my case, even tho I'm running those commands before deployment but still same

```
pip install -r requirements.txt -t python
pip install --upgrade google-api-python-client
pip install --upgrade google-ads
pip install --upgrade google
```
do you think I'm missing something? which package among those should have the latest version?
