### ISSUE TITLE
Get the account hierarchy under the current account

### ISSUE THREAD

**Issue by Olmer1st** [googleads/google-ads-python#85]
Hello,

How to get accounts hierarchy for root MCC?
I'm trying to implement same solution like you had in this example for old API:
https://developers.google.com/adwords/api/docs/samples/python/account-management#get-the-account-hierarchy-under-the-current-account

Could you provide some help or example?

Thanks

**Comment by BenRKarl** [comment]
@Olmer1st Thanks for the question. You can use [this example](https://github.com/googleads/google-ads-python/blob/master/examples/account_management/list_accessible_customers.py) to list all the accounts that are directly accessible to the user authenticating the request. And you can use the search method to retrieve the customer-client links for a given manager account, for example:

```
SELECT customer_client_link.client_customer FROM customer_client_link
```

**Comment by Olmer1st** [comment]
Thanks for answer.
When I use the example I'm getting always only one account back - root mcc. 

Could you prepare full example how to retrieve full tree including account names and positions of accounts in order to build tree like in old API because currently it not explained well.

Thanks

**Comment by BenRKarl** [comment]
@Olmer1st I'll add this Issue as a feature request and see if we can add a formal example for the client libraries. In the meantime are you able to get the information you need using the `customer_client` resource and not the `customer_client_link` resource?

```
SELECT customer_client.client_customer FROM customer_client
```

**Comment by Olmer1st** [comment]
Thanks, example will help to a lot of people. Currently according to google forum many developers stuck in same place like me and it prevent us to finalize migration process.
Yes, now I'm able to get part of info from customer_client, but in order to define MCC for accounts customer_client.level not enough that require to use customer_client_link. In addition, in order to get details about each account need to use get_customer (RESOURCE_EXHAUSTED exception in a minute) or search for customer.
Looks like something wrong with API, in my case it's thousand API calls.  Old API was just one call and paging.
May be I'm loosing something in my understanding?

**Comment by BenRKarl** [comment]
@Olmer1st following up here to let you know that retrieving account hierarchies is being looked at at the API level, so any changes to that functionality will be shared via the [Developer Blog](https://ads-developers.googleblog.com/) and not here. Please keep an eye on the blog for future announcements.

**Comment by Olmer1st** [comment]
Thanks for letting me know, but why you closed the issue? Do you still have plan to build an full example?

**Comment by BenRKarl** [comment]
@Olmer1st I closed this because it will be addressed at the API level not at the client library level. It will be part of an upcoming API release which will be announced on the developer blog. I'm not sure at the moment whether we'll write an example for the new feature, but when it's released if you have problems using it you can always open a new issue here.
