### ISSUE TITLE
keyword plan idea service does not give suggested bid like in old target idea service

### ISSUE THREAD

**Issue by pratiksha-cobiro** [googleads/google-ads-python#86]
the old version of target idea service was giving suggested bid for each keyword, on the other hand in the new keyword plan idea service, it only gives a field called competition which has values low, medium, high.

Is there any way by which I can get suggested bid for keywords? if not, is there any plan to introduce it again in future updates?

**Comment by pratiksha-cobiro** [comment]
I await for the answer :)

**Comment by BenRKarl** [comment]
Hi @pratiksha-cobiro thanks for the question. I'm working on getting an answer and will get back to you as soon as possible.

**Comment by BenRKarl** [comment]
Hi @pratiksha-cobiro actually I realize this questions is better suited for the API support channel and not this Issue tracker, (which is intended to handle issues with this library specifically). Would you mind bringing your question to the [API support forum](https://groups.google.com/forum/#!forum/adwords-api).
