### ISSUE TITLE
Merchant links examples were removed as obsolete. Why?

### ISSUE THREAD

**Issue by pySilver** [googleads/google-ads-python#872]
Hi!

I've just upgraded from deprecated v14 and noticed that Merchant Links are not working any more and were removed from examples directory. Is it no longer needed?

**Comment by BenRKarl** [comment]
@pySilver in the [blog post announcing v15](https://ads-developers.googleblog.com/2023/10/announcing-v15-of-google-ads-api.html) it mentions that merchant center links were migrated to product links. If you look at [`ProductLinkService`](https://developers.google.com/google-ads/api/reference/rpc/v17/ProductLinkService) you should find what you need.
