### ISSUE TITLE
Where in the package can I access programatically the query_validator function?

### ISSUE THREAD

**Issue by edpruuv** [googleads/google-ads-python#873]
Hi,

I want to use https://developers.google.com/google-ads/api/fields/v17/query_validator on my python code.
So that I can check before sending a query that the query is indeed  a valid GAQL query.

Is the function available here on the python package?

Thanks in advanced!

**Comment by BenRKarl** [comment]
Hey @edpruuv unfortunately that functionality isn't available in the library, however that is a very cool idea. For now, I think the next best option is to submit a `Search` request with [`validate_only`](https://developers.google.com/google-ads/api/reference/rpc/v17/SearchGoogleAdsRequest#validate_only) set to True.
