### ISSUE TITLE
Demand Gen Campaigns missing in ad_group_ad

### ISSUE THREAD

**Issue by jabjak** [googleads/google-ads-python#874]
**What is your question?**

It seems that the API calls do not return results for Demand Gen campaigns from ad_group_ad. From the docummentation I would expect it differently, cause the specific fields are accessible - https://developers.google.com/google-ads/api/fields/v17/ad_group_ad#ad_group_ad.ad.demand_gen_carousel_ad.business_name.

**Comment by BenRKarl** [comment]
Hi @jabjak - this looks like an API issue, and not something specific to this library. Please see these [support options](https://developers.google.com/google-ads/api/support) for help.
