### ISSUE TITLE
Script stops with no logs

### ISSUE THREAD

**Issue by gadcam** [googleads/google-ads-python#886]
**Describe the bug:** Running the default snippet stops with no logs (and thus it is very hard to understand what is going on)

**Steps to Reproduce:**
- Run the script provided in [getting started](https://developers.google.com/google-ads/api/docs/get-started/make-first-call)
- Optional : add logging with
```python
import logging
logging.basicConfig(level=logging.DEBUG, format='[%(asctime)s - %(levelname)s] %(message).5000s')
logging.getLogger('google.ads.googleads.client').setLevel(logging.DEBUG)
```

**Expected behavior:**
Either runs the query or fails with an error message.

**Workaround:**
Set env vars `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION` to `python` then I get the output.
I think there should at least be a note on hinting we could try to set this variable if we get no output.

**Client library version and API version:**
Client library version: google-ads==21.3.0
Also
- google-api-core==2.19.2
- google-auth==2.34.0
- google-auth-oauthlib==1.2.1

Google Ads API version: v17

**Request/Response Logs:**
[2024-09-10 19:08:21,292 - DEBUG] Making request: POST https://accounts.google.com/o/oauth2/token
[2024-09-10 19:08:21,299 - DEBUG] Starting new HTTPS connection (1): accounts.google.com:443
[2024-09-10 19:08:21,402 - DEBUG] https://accounts.google.com:443 "POST /o/oauth2/token HTTP/11" 200 None
 
**Anything else we should know about your project / environment:**
Windows 11

**Comment by BenRKarl** [comment]
@gadcam generally the expectation would be that logging behavior is specified through [configuration](https://developers.google.com/google-ads/api/docs/client-libs/python/configuration).
