### ISSUE TITLE
GoogleAdsService.Search

### ISSUE THREAD

**Issue by Olmer1st** [googleads/google-ads-python#89]
Hello,
how to retrieve  total_results_count and field_mask from search response?
`AttributeError: 'GRPCIterator' object has no attribute 'total_results_count'`

**Comment by wihl** [comment]
This is a known issue. We are working on a resolution which may have some minor breaking API changes to the Response object.

Thanks for the feedback!

**Comment by BenRKarl** [comment]
Closing this in favor of this more general Issue: https://github.com/googleads/google-ads-python/issues/111
