### ISSUE TITLE
SystemExit: 2 error

### ISSUE THREAD

**Issue by DmitryShvetsov** [googleads/google-ads-python#90]
Hi!
I'm trying to get keywords usind google ads API and get respond below. What can be a reason of error and how to fix it?
The code is here (from examples): https://yadi.sk/d/X8mp2bvWrqEhxA

Respond:
"runfile('C:/Users/rp/Documents/python_scripts/adsAPI/change_action_content/example.py', wdir='C:/Users/rp/Documents/python_scripts/adsAPI/change_action_content')
usage: example.py [-h] -c CUSTOMER_ID [-a AD_GROUP_ID]
example.py: error: the following arguments are required: -c/--customer_id
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

C:\Users\rp\Downloads\WinPython\python-3.6.5.amd64\lib\site-packages\IPython\core\interactiveshell.py:2918: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)"

**Comment by BenRKarl** [comment]
Hi @DmitryShvetsov! As mentioned in this issue https://github.com/googleads/google-ads-python/issues/92 when running our examples as-is you'll need to provide some information (in this case your customer ID) via the command line. This is somewhat different from the AdWords API, where `customer_id` was provided via your googlads.yaml configuration file.

Hope this helps!
