### ISSUE TITLE
Getting headers

### ISSUE THREAD

**Issue by rubberviscous** [googleads/google-ads-python#91]
Currently I'm able to extract the headers (for CSV output) from the query response using a set of procedure that goes as follows: convert message to dictionary MessageToDict(), flatten dictionary, get all keys in dictionary. It seems to work most of the time. However I noticed there are scenarios where I'm unable to get the full header, this happens when the returned rows have NULL values for some SELECT fields. It seems like the underlying protobuf message does not include a field if the value is NULL. I tried adding some custom logic to check the header on each row but that felt greasy. Is there a better way to get all the headers? Thanks in advance.

**Comment by BenRKarl** [comment]
@rubberviscous thanks for the question! For search requests I would try looking at the `field_mask` on the response object instead of the header. That will contain a list of all the fields that were selected.

**Comment by BenRKarl** [comment]
@rubberviscous I'm going to close this issue out assuming the suggestion worked for you, but please let me know if you continue having issues.

**Comment by rubberviscous** [comment]
@BenRKarl I'm a little lost on how to get the `field_mask` on the response object. Given this reference implementation here: https://github.com/googleads/google-ads-python/blob/master/examples/reporting/get_hotel_ads_performance.py#L49, how would one fetch the fields using `field_mask`?
