### ISSUE TITLE
error: the following arguments are required: -c/--customer_id

### ISSUE THREAD

**Issue by DmitryShvetsov** [googleads/google-ads-python#92]
Hello!
I run example python script (https://github.com/googleads/google-ads-python/blob/master/examples/basic_operations/get_ad_groups.py).

I use Googleads Api. 
It says me: "usage: example_get_campaigns_ads.py [-h] -c CUSTOMER_ID [-i CAMPAIGN_ID]
example_get_campaigns_ads.py: error: the following arguments are required: -c/--customer_id"

Screenshot: http://prntscr.com/nh995v

What -c/--customer_id arguments should I add and where to put it in?
How to fix the problem?

Thank you for attention!

**Comment by jramirezpr** [comment]
I also have this issue, I commented out the parser and hardcoded my customer_id as a string, but now i am getting zero results.

**Comment by BenRKarl** [comment]
Hi @DmitryShvetsov those are command line flags that you pass in when invoking the script via your terminal, so for example:

```python
python get_ad_groups.py -c 123456 -i 9876543
```

Hope that helps.

@jramirezpr try running the example again with these flags, providing both your customer ID and the campaign ID. If you're having problems with the results please open a separate issue.
