### ISSUE TITLE
Google My Business Location Extensions 

### ISSUE THREAD

**Issue by j-walker23** [googleads/google-ads-python#93]
Hello,

I'm trying to figure out how to create a GMB feed for location extensions in the new ads api.
There are no docs (that i can find) so i'm going off of the adwords api https://developers.google.com/adwords/api/docs/guides/feed-services-locations.

This adwords api says for the feed.origin to be `ADWORDS`. But that option is not listed in the new feed.origin enum at https://developers.google.com/google-ads/api/docs/fields/feed#feedorigin.

Is there any help i could find for creating GMB location extensions in the new google ads api anywhere. 
Thanks for any help.

**Comment by BenRKarl** [comment]
@j-walker23 thanks for the question! Have you tried setting the feed origin to `GOOGLE`?

**Comment by j-walker23** [comment]
@BenRKarl Thanks for the response! I did, and it seemed to get me further.

A Feed is being created, but while creating a CustomerFeed I am getting the below. Do you have any insight on what it's saying on a practical level and how i should move forward?

`google.ads.googleads.v1.errors.GoogleAdsFailure The appropriate error code isn't part of the API yet.`
`LOCATION operations CUSTOMER_FEED_ERROR_MISSING_FEEDMAPPING_FOR_PLACEHOLDER_TYPE`

**Comment by j-walker23** [comment]
Fixed it. I was using the placeholder enum type incorrectly. Because it resolves to a number i thought i could just import and use the enum straight from the package since all the enums are concrete in the package. Changed it to the `client.get_type` way and it seems to be working.

**Comment by j-walker23** [comment]
@BenRKarl Can I ask you a quick question please. I feel you, since building the literal new Google Ads API, would be authoritative on this.

I posted a question in the AdWords/Google Ads API forum asking for any documentation on using Location Extensions in the new API. And I got a response today that creating Ads with Location Extensions is not offered by the API.

It surprised me since I can use the api to create GMB sync feeds, CustomerFeeds, CampaignFeeds and AdGroupFeeds for Location Extensions.
So i hoped if you had a second you could confirm if that is true please. Thank you.

**Comment by BenRKarl** [comment]
@j-walker23 thanks for the question - do you have a link to that forum thread? This is something I'll need to double-check, but will follow up when I get more info.

**Comment by BenRKarl** [comment]
@j-walker23 Apologies for the back-and-forth. Unfortunately this question is better addressed in the Support Forum. In that thread, I suggest asking whether this feature is something that won't be supported, or if it's functionality that's just not supported _yet_.

**Comment by j-walker23** [comment]
@BenRKarl I did ask them and sadly they responded with below. No biggie, though, thanks for checking.

> Unfortunately, I could not provide any comment about future updates and releases specific to Google Ads API.
