### ISSUE TITLE
Get all RESOURCE fields for use in GoogleAdsFieldService.search_google_ads_fields

### ISSUE THREAD

**Issue by j-walker23** [googleads/google-ads-python#98]
GoogleAdsFieldService with a query `name = RESOURCE` seems to give back everything but it's fields. Is there any way to get the fields as well which can be used in the SELECT list of a `GoogleAdsService.search` programmatically?

**Comment by wihl** [comment]
Let's say you are looking for all the fields of the [AdGroup](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v2.resources#adgroup) resource. Use:
```
SELECT name, attribute_resources, data_type, category  
WHERE  name LIKE 'ad_group.%'
```

**Comment by j-walker23** [comment]
What! This has been possible all along. Could have saved so much time.
Thank you!
